### ISSUE TITLE
Dynamic import with TLA inside a plugin hangs in deno

### ISSUE THREAD

**Issue by PaulBlanche** [evanw/esbuild#3223] opened 2023-07-12 08:47 UTC
given thoses files : 
```ts
// ./main.ts
import * as esbuild from "https://deno.land/x/esbuild@v0.18.11/mod.js";

console.log("build start");
await esbuild.build({
    entryPoints: [],
    plugins: [{
        name: "test",
        setup(build) {
            build.onEnd(async () => {
                console.log("onEnd start");
                await import("./await.ts");
                console.log("onEnd done");
            });
        },
    }],
});
console.log("build done");

esbuild.stop();


// ./await.ts
console.log("await start");
await new Promise((res) => setTimeout(res, 100));
console.log("await done");
```

running  `deno run -A main.ts`  (deno 1.35.0) outputs while never terminating :
```
build start
onEnd start
await start
await done
```

I expected `esbuild` to handle TLA inside a dynamic import inside a plugin, giving this ouput while terminating : 
```
build start
onEnd start
await start
await done
onEnd done
build done
```

Given that the same code adapted for node works as expected, i'm not sure if this is an issue with `esbuild` or `deno`.

**Comment by evanw** [comment] 2023-07-13 19:35
I assume this is a problem with Deno:

```
$ deno upgrade --version 1.29.0
$ deno run -A main.ts
build start
onEnd start
await start
await done
onEnd done
build done

$ deno upgrade --version 1.30.0
$ deno run -A main.ts
build start
onEnd start
await start
await done
(hangs)
```

It looks like this is a regression in Deno between versions 1.29.0 and 1.30.0.

**Comment by evanw** [comment] 2023-07-13 19:52
I'm closing this issue since this isn't something esbuild can fix. I have filed this bug with Deno for you here: https://github.com/denoland/deno/issues/19823

**Closed by evanw** 2023-07-13 19:52 UTC
