### ISSUE TITLE
error on macOS 13 beta2

### ISSUE THREAD

**Issue by sheiy** [evanw/esbuild#2344] opened 2022-06-23 13:18 UTC
<img width="695" alt="image" src="https://user-images.githubusercontent.com/12210038/175307987-74f352b6-f8cf-4c2b-bdd9-82931403658f.png">

maybe this issues will have some help https://github.com/golang/go/issues/53372

**Comment by evanw** [comment] 2022-06-23 16:40
I suspect https://github.com/golang/go/issues/53372 is unrelated because that has to do with cgo and [esbuild explicitly disables cgo](https://github.com/evanw/esbuild/blob/8b0da1d674921c0e7354315bc3155e7aceeb23fc/Makefile#L10). In addition, that's a link-time error while this is a run-time error, which implies that linking was successful.

The error you showed looks like potentially a logic error inside esbuild instead. Is it deterministic? Can you provide example code that would allow me to reproduce the error?

**Comment by sheiy** [comment] 2022-06-24 01:54
@evanw 
Sorry I can't provide sample code; because this code is company's; this code compiles fine on macOS 12.4 but not on macOS 13 beta2

**Comment by evanw** [comment] 2022-06-24 03:17
Ah ok, makes sense. Unfortunately there's nothing I can do with this error report for now then. I'm sure it'll get fixed by later this year at the latest since it sounds like that's when macOS 13 will reach general availability.

**Comment by sheiy** [comment] 2022-06-24 06:09
yeah, I reinstalled my os

**Closed** 2022-06-24 06:09 UTC
