### ISSUE TITLE
Dose it support vue lib？

### ISSUE THREAD

**Issue by langhuihui** [evanw/esbuild#133] opened 2020-05-22 14:10 UTC
> vue-cli-service build --target lib --name plugin-webrtc
With the above command, you can compile the Vue file into Lib

**Comment by evanw** [comment] 2020-05-22 17:11
This is a duplicate of #75. Apparently you can use Vue with esbuild if you use JSX syntax. Otherwise, Vue syntax is not supported by esbuild itself. However, esbuild is being integrated into the Vue ecosystem as a library to transform TypeScript to JavaScript. See the thread for details.

**Closed by evanw** 2020-05-22 17:11 UTC
