### ISSUE TITLE
Bad mappings warning appearing when bundling

### ISSUE THREAD

**Issue by djalbat** [evanw/esbuild#2066] opened 2022-02-28 09:07 UTC
Good morning.

ESBuild has started printing warnings this morning for some of my projects. For example:

```
 lib/view/span/copied.js#sourceMappingURL:1:3512: warning: Bad "mappings" data in source map at character 663: Invalid source index value: 1
    1 │ ...QAAa,CACrC;QAAW,CACV;QAAW,CAGlC;;;;K;;;IAvGMA,UAAU,iBAAhB,QAAQ;kC;;aAAFA,UAAU,CACFC,QAAQ,EAAEC,OAAO;yC;;kCACrBD,QAAQ,CCZlB,CDYoB;cAEXE,QAAQ,GAAGD,OAAO,CAAC;;;;;YAG1BE,GAAY,EAAZA,CAAY;mBAAZA,QAAQ,CAARA,YAAY,GAAG,CAAC;gBACd,EAAE,EAAE,IAAI,...
      ╵                                                                                                                          ^
```

The transpiler is SWC. I assume that ESBuild has it right and that this is a problem with SWC but thought I would let you know.

To replicate this issue exactly, clone the following repository:

https://github.com/xomicloud/ui-elements

Then `npm install` and `npm run build-debug`.

Many thanks and kind regards,
James

**Comment by evanw** [comment] 2022-02-28 12:17
An example is here:

```json
{
  "version": 3,
  "sources": [
    "../../../src/view/span/copied.js"
  ],
  "sourcesContent": [
    "\"use strict\";\n\nimport withStyle from \"easy-with-style\";\n\nimport { Element } from \"easy\";\n\nimport { COPIED_SPAN_DELAY } from \"../../constants\";\nimport { biancaYellow, plainBlack } from \"../../colours\";\nimport { quarterSize, halfSize, smallSize, largeSize } from \"../../sizes\";\n\nclass CopiedSpan extends Element {\n  constructor(selector, timeout) {\n    super(selector);\n\n    this.timemout = timeout;\n  }\n\n  resetTimeout() {\n    if (this.timeout !== null) {\n      clearTimeout(this.timemout);\n\n      this.timeout = null;\n    }\n  }\n\n  show() {\n    super.show();\n\n    this.resetTimeout();\n\n    this.timeout = setTimeout(() => this.hide(), COPIED_SPAN_DELAY);\n  }\n\n  hide() {\n    super.hide();\n\n    this.resetTimeout();\n  }\n\n  didMount() {\n    this.hide();\n  }\n\n  willUnmount() {\n    ///\n  }\n\n  childElements() {\n    return \"Copied!\";\n  }\n\n  parentContext() {\n    const showCopiedSpan = this.show.bind(this);  ///\n\n    return ({\n      showCopiedSpan\n    });\n  }\n\n  static tagName = \"span\";\n\n  static defaultProperties = {\n    className: \"copied\"\n  };\n\n  static fromClass(Class, properties) {\n    const timeout = null,\n          copiedSpan = Element.fromClass(Class, properties, timeout);\n\n    return copiedSpan;\n  }\n}\n\nexport default withStyle(CopiedSpan)`\n\n  top: -${smallSize};\n  right: calc(${halfSize} - 4px);\n  width: auto;\n  z-index: 2;\n  width: auto;\n  filter: brightness(100%) !important;\n  border: 1px solid ${plainBlack};\n  padding: ${quarterSize};\n  display: inline-block;\n  position: absolute;\n  font-size: ${smallSize};\n  background-color: ${biancaYellow};\n  \n  ::before {\n    top: ${largeSize};\n    left: calc(${largeSize} - 3px);\n    width: 0; \n    height: 0; \n    z-index: 1;\n    content: \" \";\n    position: absolute;\n    border-top: ${halfSize} solid ${biancaYellow};\n    border-left: ${halfSize} solid transparent;\n    border-right: ${halfSize} solid transparent;\n  }\n  \n  ::after {\n    top: ${largeSize};\n    left: calc(${largeSize} - 5px);\n    width: 0; \n    height: 0; \n    content: \" \";\n    position: absolute;\n    border-top: calc(${halfSize} + 2px) solid ${plainBlack};\n    border-left: calc(${halfSize} + 2px) solid transparent;\n    border-right: calc(${halfSize} + 2px) solid transparent;\n  }\n  \n`;\n"
  ],
  "names": [
    "CopiedSpan",
    "selector",
    "timeout",
    "timemout",
    "resetTimeout",
    "clearTimeout",
    "show",
    "setTimeout",
    "hide",
    "COPIED_SPAN_DELAY",
    "didMount",
    "willUnmount",
    "childElements",
    "parentContext",
    "showCopiedSpan",
    "bind",
    "fromClass",
    "Class",
    "properties",
    "copiedSpan",
    "Element",
    "tagName",
    "defaultProperties",
    "className",
    "withStyle",
    "smallSize",
    "halfSize",
    "plainBlack",
    "quarterSize",
    "biancaYellow",
    "largeSize"
  ],
  "mappings": "AAAA,CAAY,WAAA,CAAC;;;E;wB;AAES,GAAiB,CAAjB,cAAiB;AAEf,GAAM,CAAN,KAAM;AAEI,GAAiB,CAAjB,UAAiB;AACV,GAAe,CAAf,QAAe;AACI,GAAa,CAAb,MAAa;;;;;;;;;;;;;;;;;gF;;;;;;;;sC;;;;;;iC;;;iE;;S;;;;;;;8D;sC;6D;iE;;;;wE;gE;;;;;;;;;;U;;wB;;;;;;0B;;;;;;;;;;S;;;;;;;K;;;;;;;;;;;;;M;yD;;;;;;;;;;;;;;;;;;uB;;K;;;;;wC;;;;;;;8B;;;;;;;;;2B;;;;;;;;;;;;sC;;;;;;;;;;;;U;;K;;;;;;;;qF;;;;;;;;;;;;mE;;iD;;;;;;;QAiEpC,CAE7B;QAAY,CACN;QAAW,CAKL;QAAa,CACtB;QAAc,CAGZ;QAAY,CACL;QAAe,CAG1B;QAAY,CACN;QAAY,CAMX;QAAW,CAAO;QAAe,CAChC;QAAW,CACV;QAAW,CAIpB;QAAY,CACN;QAAY,CAKN;QAAW,CAAc;QAAa,CACrC;QAAW,CACV;QAAW,CAGlC;;;;K;;;IAvGMA,UAAU,iBAAhB,QAAQ;kC;;aAAFA,UAAU,CACFC,QAAQ,EAAEC,OAAO;yC;;kCACrBD,QAAQ,CCZlB,CDYoB;cAEXE,QAAQ,GAAGD,OAAO,CAAC;;;;;YAG1BE,GAAY,EAAZA,CAAY;mBAAZA,QAAQ,CAARA,YAAY,GAAG,CAAC;gBACd,EAAE,EAAE,IAAI,CAACF,OAAO,KAAK,IAAI,EAAE,CAAC;oBAC1BG,YAAY,CAAC,IAAI,CAACF,QAAQ,CAAC,CAAC;oBAE5B,IAAI,CAACD,OAAO,GAAG,IAAI,CAAC;gBACtB,CAAC;YACH,CAAC;;;YAEDI,GAAI,EAAJA,CAAI;mBAAJA,QAAQ,CAARA,IAAI,GAAG,CAAC;;qCAfJN,UAAU,aAgBNM,CAAI,OAAV,IAAK,YC1BT,CD0BiB;gBAEb,IAAI,CAACF,YAAY,EAAE,CAAC;gBAEpB,IAAI,CAACF,OAAO,GAAGK,UAAU,CAAC,QAAQ;oBAAF,MAAM,OAADC,IAAI;mBAAIC,UAAiB,mBAAC,CAAC;YAClE,CAAC;;;YAEDD,GAAI,EAAJA,CAAI;mBAAJA,QAAQ,CAARA,IAAI,GAAG,CAAC;qCAvBJR,UAAU,aAwBNQ,CAAI,OAAV,IAAK,YClCT,CDkCiB;gBAEb,IAAI,CAACJ,YAAY,EAAE,CAAC;YACtB,CAAC;;;YAEDM,GAAQ,EAARA,CAAQ;mBAARA,QAAQ,CAARA,QAAQ,GAAG,CAAC;gBACV,IAAI,CAACF,IAAI,EAAE,CAAC;YACd,CAAC;;;YAEDG,GAAW,EAAXA,CAAW;mBAAXA,QAAQ,CAARA,WAAW,GAAG,CAAC;YACb,EAAG,AAAH,CAAG;YACL,CAAC;;;YAEDC,GAAa,EAAbA,CAAa;mBAAbA,QAAQ,CAARA,aAAa,GAAG,CAAC;gBACf,MAAM,CAAC,CAAS;YAClB,CAAC;;;YAEDC,GAAa,EAAbA,CAAa;mBAAbA,QAAQ,CAARA,aAAa,GAAG,CAAC;gBACf,GAAK,CAACC,cAAc,GAAG,IAAI,CAACR,IAAI,CAACS,IAAI,CAAC,IAAI,GAAI,EAAG,AAAH,CAAG;gBAEjD,MAAM,CAAE,CAAC;oBACPD,cAAc,EAAdA,cAAc;gBAChB,CAAC;YACH,CAAC;;;;YAQME,GAAS,EAATA,CAAS;mBAAhB,QAAQ,CAADA,SAAS,CAACC,KAAK,EAAEC,UAAU,EAAE,CAAC;gBACnC,GAAK,CAAChB,OAAO,GAAG,IAAI,EACdiB,UAAU,GAAGC,KAAO,SAACJ,SAAS,CAACC,KAAK,EAAEC,UAAU,EAAEhB,OAAO;gBAE/D,MAAM,CAACiB,UAAU;YACnB,CAAC;;M;;mBA5DsBC,KAAO;gBAA1BpB,UAAU,EAiDPqB,CAAO,UAAG,CAAM,M;gBAjDnBrB,UAAU,EAmDPsB,CAAiB,oBAAG,CAAC;IAC1BC,SAAS,EAAE,CAAQ;AACrB,CAAC,C;mBAUYC,cAAS,UAACxB,UAAU,qBAEzByB,MAAS,YACHC,MAAQ,WAKFC,QAAU,aACnBC,MAAW,cAGTH,MAAS,YACFI,QAAY,eAGvBC,MAAS,YACHA,MAAS,YAMRJ,MAAQ,WAAUG,QAAY,eAC7BH,MAAQ,WACPA,MAAQ,WAIjBI,MAAS,YACHA,MAAS,YAKHJ,MAAQ,WAAiBC,QAAU,aAClCD,MAAQ,WACPA,MAAQ;0B"
}
```

This source map is indeed broken. If you attempt to iterate over it using Mozilla's [`source-map`](https://www.npmjs.com/package/source-map) library (the most widely-used source map parser), you get a similar error:

```
Uncaught Error: No element indexed by 1
    at ArraySet.at (./node_modules/source-map/lib/array-set.js:88:11)
    at Array.<anonymous> (./node_modules/source-map/lib/source-map-consumer.js:374:42)
    at mapping_callback (./node_modules/source-map/lib/wasm.js:64:52)
    at wasm://wasm/0002f8d6:wasm-function[30]:0x3cac
    at ./node_modules/source-map/lib/source-map-consumer.js:387:30
    at Object.withMappingCallback (./node_modules/source-map/lib/wasm.js:95:11)
    at BasicSourceMapConsumer.eachMapping (./node_modules/source-map/lib/source-map-consumer.js:371:16)
```

So it's junk data, which is why there's a warning. If you don't want to see warnings about problems with your build you can use `--log-level=error` to hide them. Closing this issue as by design.

**Closed by evanw** 2022-02-28 12:17 UTC

**Comment by djalbat** [comment] 2022-02-28 12:55
Many thanks for confirming. I will like to this from the SWC issue.
