### ISSUE TITLE
Unexpected default import behavior (and inconsistent with `tsx`)

### ISSUE THREAD

**Issue by michaelbridge** [evanw/esbuild#3356] opened 2023-08-29 11:41 UTC
For certain libraries (i.e., `@searchkit/api` and `@graphile/pg-aggregates`), the default import is not exposed as expected, and the behavior is inconsistent with `tsx` in development. [Please review the gist here](https://esbuild.github.io/try/#YgAwLjE5LjIALS1idW5kbGUgLS1wbGF0Zm9ybT1ub2RlIC0tdGFyZ2V0PW5vZGUxNiAtLXBhY2thZ2VzPWV4dGVybmFsAGUAZW50cnkuanMALy8gbnBtIGkgQHNlYXJjaGtpdC9hcGkgQGdyYXBoaWxlL3BnLWFnZ3JlZ2F0ZXMgLS1zYXZlCgppbXBvcnQgU2VhcmNoa2l0IGZyb20gJ0BzZWFyY2hraXQvYXBpJwppbXBvcnQgUGdBZ2dyZWdhdGVzUGx1Z2luIGZyb20gJ0BncmFwaGlsZS9wZy1hZ2dyZWdhdGVzJwoKLy8gRGVmYXVsdCBpbXBvcnQgZXhwZWN0ZWQsIGJ1dCBpbnN0ZWFkIGF2YWlsYWJsZSB2aWEgLmRlZmF1bHQKY29uc29sZS5sb2coU2VhcmNraXRbJ2RlZmF1bHQnXSkgCmNvbnNvbGUubG9nKFBnQWdncmVnYXRlc1BsdWdpblsnZGVmYXVsdCddKQo).

ESBuild options (v0.19.2):
```
esbuild ./src/index.ts --bundle --platform=node --target=node16 --packages=external --sourcemap --outfile=dist/index.cjs
```

TSX options (v3.12.7):
```
tsx watch ./src/index.ts
```

Expected behavior/TSX behavior:
```
import Searchkit from '@searchkit/api'
const client = Searchkit()
```

Actual ESBuild behavior:
```
import Searchkit from '@searchkit/api'
const client = Searchkit['default']()
```

**Comment by evanw** [comment] 2023-09-04 11:30
Read this: https://esbuild.github.io/content-types/#default-interop

If you compile in Babel mode (e.g. with the `.ts` extension and without `type: module`), then a default import will give you the value of the export called `default`:

```console
$ cat entry.ts
import Searchkit from '@searchkit/api'
import PgAggregatesPlugin from '@graphile/pg-aggregates'
console.log(Searchkit)
console.log(PgAggregatesPlugin)

$ esbuild entry.ts --bundle --platform=node --packages=external | node
[Function: createClient]
undefined

$ node -e 'console.log(require("@searchkit/api").default); console.log(require("@graphile/pg-aggregates").default)'
[Function: createClient]
undefined
```

If you compile in Node mode (e.g. with the `.mts` extension or with `type: module`), then a default import will give you the value of `module.exports`:

```console
$ cat entry.mts
import Searchkit from '@searchkit/api'
import PgAggregatesPlugin from '@graphile/pg-aggregates'
console.log(Searchkit)
console.log(PgAggregatesPlugin)

$ esbuild entry.mts --bundle --platform=node --packages=external | node
{
  default: [Getter],
  ESTransporter: [Getter],
  MatchFilter: [Getter],
  TermFilter: [Getter]
}
{
  PgAggregatesPreset: {
    plugins: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ]
  }
}

$ node -e 'console.log(require("@searchkit/api")); console.log(require("@graphile/pg-aggregates"))'
{
  default: [Getter],
  ESTransporter: [Getter],
  MatchFilter: [Getter],
  TermFilter: [Getter]
}
{
  PgAggregatesPreset: {
    plugins: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ]
  }
}
```

It's up to you which behavior you want to use. This is not a bug with esbuild. Matching the behavior of `tsx` is also not a goal of esbuild. I'm closing this issue as esbuild appears to be working as intended, and this behavior is already described in the documentation.

**Closed by evanw** 2023-09-04 11:30 UTC
