### ISSUE TITLE
multiple entry points: file loader artifacts not obeying to outbase rule

### ISSUE THREAD

**Issue by toxeus** [evanw/esbuild#2406] opened 2022-07-22 07:49 UTC
When using esbuild with multiple entry points it's possible to set `outbase` such that the bundle for each entry point ends up in its specific subfolder derived from the paths used in the project's source directory. Docs: https://esbuild.github.io/api/#outbase

Surprisingly, the file loader artifacts don't follow this subfolder convention but are output into `outdir`. I would have expected the artifacts to end up in a subfolder according to `outbase`; matching the behavior of the bundle output directory.

**Comment by evanw** [comment] 2022-07-22 13:29
Are you perhaps missing `[dir]` from [`assetNames`](https://esbuild.github.io/api/#asset-names)? The default value for `assetNames` is `./[name]-[hash]` which doesn't contain `[dir]`.

**Comment by toxeus** [comment] 2022-07-25 20:29
Thanks for the fast reply @evanw. I didn't know about `[dir]` nor about `assetNames`. I looked at the docs and it's not exactly what I was looking for.

`[dir]` mirrors the asset paths used in the source repository. I'm looking for a mechanism that arranges the assets per entrypoint. I can give a contrived but illustrative example:
```sh
find . -type f
src/app1/index.tsx
src/app2/index.tsx
src/shared/logo.png
esbuild --bundle --loader:.png=file --outdir=public src/app1/index.tsx src/app2/index.tsx
```
Default behavior (as you explained above):
```sh
find ./public -type f
public/app1/index.js
public/app2/index.js
public/logo.png
```
using `[dir]`:
```sh
find ./public -type f
public/app1/index.js
public/app2/index.js
public/shared/logo.png
```
what I'd like to achieve:
```sh
find ./public -type f
public/app1/index.js
public/app1/logo.png
public/app2/index.js
public/app2/logo.png
```

**Comment by evanw** [comment] 2022-07-25 22:26
There’s no setting that will put the same asset in two different locations in a single build. Instead, you can get that to happen by building multiple times, once per entry point.

**Comment by toxeus** [comment] 2022-07-26 06:38
You're describing exactly my current setup. Because I have many entrypoints the instrumenting code became quite a bit. I was hoping to delegate this to esbuild once I found out about `outbase` but got stuck with the assets. My hope was that I could use a simple
```sh
esbuild --bundle --loader:.png=file --outdir=public src/*/index.tsx
```
and delegate the rest to the shell's pathname expansion.

**Comment by evanw** [comment] 2022-07-26 11:46
That won’t work because `outbase` just controls the reference directory that’s used to derive `[dir]` from. It’s not a way to build multiple times with one build command. 

Closing this issue because esbuild is working as intended here.

**Closed by evanw** 2022-07-26 11:46 UTC

**Comment by toxeus** [comment] 2022-07-27 07:49
Alright. Thanks!
