### ISSUE TITLE
Imported modules are undefined (tree shaking bug?)

### ISSUE THREAD

**Issue by GiancarlosIO** [evanw/esbuild#3038] opened 2023-04-04 21:22 UTC
Hi there!
I was migrating a React app to esbuild and found an weird error when trying to import components from a workspace/local library.

I'm getting the error:
````
Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
````

After several minutes of debugging, I found It's because some of the react imported components are undefined even when they are defined/exist in the library

````ts
import {
  CoursePreviewProvider, // this is undefined 😢 
  ProductsContainer, // this is NOT undefined 🤔 
  SavedCoursesProvider, // this is undefined 😢 
} from '@luxus/web';
````

The weird thing is that is that IF I import all modules using `* as bla` it works.

````ts
import * as bla from '@luxus/web'; // bla contains the CoursePreviewProvider which is not undefined 🤔 
````

I have tried to create a reproduction repo but I can't reproduce the same bug/error in this new repo 😢 
Here is the repo where I was trying to reproduce the error, it includes my esbuild config in: `apps/my-app/scripts/build.mjs` and also include the configuration used to compile the library from where the modules are undefined.
https://github.com/GiancarlosIO/esbuild-bug-undefined-modules

Is there any options that I can enable in order to debug this behavior? 😞 

Esbuild: v0.17.15
pnpm: v7.18
Nodejs: v16.19.1

**Comment by evanw** [comment] 2023-04-04 23:03
There's no automatic way to debug this built in to esbuild, but you could potentially step through it with a debugger (or equivalently by adding log statements in various places). I'm marking this as `unactionable` until a way to reproduce this issue is provided.

**Comment by evanw** [comment] 2023-04-22 19:06
I'm closing this issue because it has been unactionable for a while and no additional information was provided.

**Closed by evanw** 2023-04-22 19:06 UTC
Labels: unactionable
