### ISSUE TITLE
Tree shaking doesn't remove unused imports

### ISSUE THREAD

**Issue by egoist** [evanw/esbuild#1873] opened 2021-12-20 16:03 UTC
`package.json`:

```json
{
  "dependencies": {
    "esbuild": "^0.14.6"
  },
  "sideEffects": false
}
```

`index.js`:

```js
export { sum } from "./sum"
```

`sum.js`:

```js
import fs from "fs"

const c = "c"
export const bar = () => fs.read() + c

export const sum = () => {}
```

Run:

```bash
esbuild index.js --outfile=out.js --bundle --platform=node --format=esm 
```

Output:

```js
// sum.js
import fs from "fs";
var sum = () => {
};
export {
  sum
};

```

**Comment by evanw** [comment] 2021-12-21 02:47
I think this is a duplicate of #705 and #1173. Closing as a duplicate.

**Closed by evanw** 2021-12-21 02:47 UTC
