### ISSUE TITLE
Difference in execution of plugins between esbuild.serve and esbuild.build using same configuration

### ISSUE THREAD

**Issue by bobbyrenwick** [evanw/esbuild#948] opened 2021-03-10 15:17 UTC
Using 0.9.0, I have an issue where `esbuild.serve` throws errors about not having a loader for file extensions that I have a plugin for. `esbuild.build` works as expected.

The error looks like:
```
 > assets/js/stats/StatsApp.tsx:11:34: error: No loader is configured for ".graphql" files: assets/js/stats/queries.graphql
    11 │ ...rt { MyQuery } from "./queries.graphql";
       ╵
```

I have a config file `esbuild.config.js` that looks like this:

```tsx
const yarnPlugin = require("@yarnpkg/esbuild-plugin-pnp");
const graphql = require("./esbuild.plugin-graphql");
const fixReactDates = require("./esbuild.plugin-fix-react-dates");

module.exports.config = {
    entryPoints: ["assets/js/index.tsx"],
    bundle: true,
    outdir: "webpack_static/dist",
    plugins: [graphql.plugin(), fixReactDates.plugin(), yarnPlugin.pnpPlugin()],
    define: {
        "process.env.NODE_ENV": '"production"',
        "import.meta.env.NODE_ENV": '"production"',
        global: "window", // This is for react-dates
    },
    loader: {
        ".woff": "file",
        ".svg": "file",
        ".png": "file",
    },
    publicPath: "/s/dist/",
    // React will still complain that it's in production
    // mode but the Dead Code Elimination hasn't been done because
    // esbuild doesn't do that at the moment
    minify: true,
};
```

I have a `esbuild.build.js` that looks like:

```tsx
const fs = require("fs");
const esbuild = require("esbuild");
const esbuildConfig = require("./esbuild.config.js");

fs.rm(esbuildConfig.config.outdir, { recursive: true, force: true }, () => {
    esbuild.build(esbuildConfig.config).catch(() => {
        process.exit(1);
    });
});

```

and a `esbuild.dev.js` that looks like:

```tsx
const esbuild = require("esbuild");
const esbuildConfig = require("./esbuild.config.js");

esbuild
    .serve(
        {
            port: 9000,
        },
        esbuildConfig.config
    )
    .then(server => {
        server.stop();
    });

```

As you can see, there's no difference in the config between the two but `build` handles the graphql files using the plugin, and `serve` doesn't. I'm using my own [graphql-loader plugin](https://github.com/luckycatfactory/esbuild-graphql-loader/issues/10#issuecomment-795078359) that I pasted into an issue on the one listed on esbuild's site.

Running `yarn node esbuild.dev.js` actually quits without any output but running the same things in `node` manually gives the error posted at the top.

**Comment by zaydek** [comment] 2021-03-10 19:41
@bobbyrenwick Can you provide a reproducible repo? Sometimes Evan / maintainers can grok a mistake from user code, but I think more often than not having a reproducible repo is preferred.

**Comment by bobbyrenwick** [comment] 2021-03-11 07:56
@zaydek I can make one over the weekend

**Comment by evanw** [comment] 2021-03-28 22:59
Please provide a way to reproduce this. Otherwise this issue will be closed as it's currently unactionable.

**Comment by evanw** [comment] 2021-03-29 21:18
Closing due to lack of a reply. I'm happy to investigate this in the future if a way for me to reproduce the issue is added.

**Closed by evanw** 2021-03-29 21:18 UTC
Labels: unactionable
