### ISSUE TITLE
Target node14 still polyfills stuff

### ISSUE THREAD

**Issue by mfbx9da4** [evanw/esbuild#1583] opened 2021-09-08 16:21 UTC
```
// app.ts
const a = { a: 1 }
const b = { ...a }
```

```
// out.js
var __defProp = Object.defineProperty;
var __getOwnPropSymbols = Object.getOwnPropertySymbols;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __propIsEnum = Object.prototype.propertyIsEnumerable;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __spreadValues = (a2, b2) => {
  for (var prop in b2 || (b2 = {}))
    if (__hasOwnProp.call(b2, prop))
      __defNormalProp(a2, prop, b2[prop]);
  if (__getOwnPropSymbols)
    for (var prop of __getOwnPropSymbols(b2)) {
      if (__propIsEnum.call(b2, prop))
        __defNormalProp(a2, prop, b2[prop]);
    }
  return a2;
};

// app.ts
var a = { a: 1 };
var b = __spreadValues({}, a);
```

```
npx esbuild app.ts --bundle --platform=node --target=node14.6 > out.js && node out.js
```

Node 14.6 supports spread, why does esbuild still polyfill?

**Comment by evanw** [comment] 2021-09-08 17:04
This syntax is transformed when targeting V8-based runtimes because it’s faster than V8’s implementation and people requested that esbuild generate the higher-performance version. There is more context here: https://github.com/evanw/esbuild/issues/951. 

Closing as a duplicate of https://github.com/evanw/esbuild/issues/1365.

**Closed by evanw** 2021-09-08 17:04 UTC
