### ISSUE TITLE
The package "util" wasn't found on the file system

### ISSUE THREAD

**Issue by cvlmtg** [evanw/esbuild#1996] opened 2022-02-07 10:16 UTC
Hi, I upgraded from esbuild 0.13.15 to 0.14.19 and now I get this error:

```
✘ [ERROR] Could not resolve "util"

    node_modules/sinon/lib/sinon/util/core/format.js:3:22:
      3 │ var inspect = require("util").inspect;
        ╵                       ~~~~~~

  The package "util" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
```

I have this in my project's package.json:

```
"browser": {
  "events": "events",
  "path": "path-browserify",
  "stream": "stream-browserify",
  "util": "node-util"
},
```

so AFAIK that should avoid the error. setting `platform` to "node" as suggested by the error is wrong imho, because the code I'm bundling will be run under puppeteer. In any case if I try I get a warning about the module `"source-map-support"` and the tests fail.

what am I doing wrong? Thanks in advance!

**Comment by evanw** [comment] 2022-02-07 13:21
The `browser` field wasn't designed by me. I have tried to make it behave in esbuild the same way it does in other tools. It appears to be intended to allow package authors to enable their packages to work in the browser. I don't believe it's meant for package consumers. So if the authors of `sinon` want to enable the file `sinon/lib/sinon/util/core/format.js` to work in the browser, then they could add a browser-specific override for that file to their `browser` map.

I'm not sure about how that file is being pulled in within your code but as a consumer, you could also potentially just avoid depending on the `sinon/lib/sinon/util/core/format.js` file to get bundling to work for the browser. You could remove references to it completely or you could create two versions of your own code, one that uses it and one that doesn't, and then use a `browser` map in your own package to pick between the two versions depending on whether you are targeting node or the browser.

**Comment by evanw** [comment] 2022-02-07 14:49
Could you post a code sample demonstrating the issue? I've been keeping list of tests that I use for how `browser` works in various tools: https://github.com/evanw/package-json-browser-tests. I try to make sure to have esbuild cover cases that are handled by at least one of the other tools in the list. If that's the case for your code, then I can add it as a test case and change esbuild to support it. Otherwise, esbuild is working as intended.

**Comment by cvlmtg** [comment] 2022-02-07 15:22
@evanw I tried but the sample is working 🤔 I need some more time to pinpoint what is missing and/or different from the real app...

**Comment by cvlmtg** [comment] 2022-02-10 08:51
@evanw sorry, didn't have time to work on that yet, but... the good news is that the problem has disappeared. I suppose that's due to esbuild 0.14.21. thanks!

**Comment by evanw** [comment] 2022-02-10 13:39
Glad to hear that it has been fixed. I agree that it’s almost certainly due to esbuild version 0.14.21 since that fixed a bug in this area. Closing this issue as fixed.

**Closed by evanw** 2022-02-10 13:39 UTC

**Comment by cvlmtg** [comment] 2022-02-11 15:45
@evanw for some reason it is happening again 🤔 however I've not updated any dependency now, nor I have changed something in my package.json, so I really have no idea what's happening... next week I'll see if I can find some time to do another app that triggers the problem

```
     Error: Build failed with 3 errors:
node_modules/@sinonjs/fake-timers/src/fake-timers-src.js:154:53: ERROR: Could not resolve "util"
node_modules/nise/lib/fake-server/log.js:2:22: ERROR: Could not resolve "util"
node_modules/sinon/lib/sinon/util/core/format.js:3:22: ERROR: Could not resolve "util"
      at failureErrorWithLog (node_modules/esbuild/lib/main.js:1601:15)
      at /Users/matteo/dev/player-esercizi/node_modules/esbuild/lib/main.js:1247:28
      at runOnEndCallbacks (node_modules/esbuild/lib/main.js:1160:65)
      at buildResponseToResult (node_modules/esbuild/lib/main.js:1245:7)
      at /Users/matteo/dev/player-esercizi/node_modules/esbuild/lib/main.js:1354:14
      at /Users/matteo/dev/player-esercizi/node_modules/esbuild/lib/main.js:664:9
      at handleIncomingPacket (node_modules/esbuild/lib/main.js:761:9)
      at Socket.readFromStdout (node_modules/esbuild/lib/main.js:631:7)
      at addChunk (internal/streams/readable.js:290:12)
      at readableAddChunk (internal/streams/readable.js:265:9)
      at Socket.Readable.push (internal/streams/readable.js:204:10)
      at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by jelenv** [comment] 2024-06-13 09:18
I encountered this or a similar issue when using Angular 17, @microsoft/signalr@8.0.0 and esbuild. This issue seems to be connected to it: #3629 (more info is also here: angular/angular-cli#27175 and here: dotnet/aspnetcore#52082
