### ISSUE TITLE
Escape hatch for opinions set via platform option

### ISSUE THREAD

**Issue by ggoodman** [evanw/esbuild#640] opened 2021-01-04 13:58 UTC
While spiking on some experiments, I observed a few behaviours that I believe are unintended side-effects of the simplifying assumptions from the `platform` option:

**With `platform: 'node'`**:

- I can't seem to get `esbuild` to generate ESM imports for node core libraries in `format: 'esm'`. This seems to be true even when such imports are remapped to `node:fs`-style specifiers supported in `>14.13.1` (https://nodejs.org/docs/latest-v14.x/api/esm.html#esm_node_imports). Instead these imports seem to get converted to `require` calls.
- I can't seem to get `esbuild` to preserve dynamic `import()` expressions within generated code without resorting to a hack [1].

**With `platform: 'browser'`**:

- I can't seem to convince `esbuild`'s resolver to ignore the `browser` field of `package.json` even when I set custom `mainFields` to `['module', 'main']`. 

Notes:

1: Hack to 'preserve' dynamic import:

```js
  const importFn = new Function('spec', 'return import(spec);');
  const { default: App } = await importFn(appPath);
```

**Comment by evanw** [comment] 2021-01-04 22:05
> I can't seem to get `esbuild` to generate ESM imports for node core libraries in `format: 'esm'`. Instead these imports seem to get converted to require calls.

Is the problem that they are originally `require()` calls and esbuild is just passing them through untransformed? Or are they originally ESM imports and esbuild is transforming them to `require()` calls?

> I can't seem to get `esbuild` to preserve dynamic `import()` expressions within generated code without resorting to a hack

This seems to work for me: `echo 'import(dynamic)' | esbuild --bundle --format=esm`. Are you just trying to get rid of the warning? Warnings are just to notify you about something, they don't stop build. The build should still succeed and produce a valid bundle.

**Comment by ggoodman** [comment] 2021-01-09 00:14
Hi @evanw, you can see the behaviour I'm talking about with the following test:

```sh
echo 'import("fs")' | ./node_modules/.bin/esbuild --platform=node --bundle
```
Produces:
```js
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __markAsModule = (target) => __defProp(target, "__esModule", {value: true});
var __exportStar = (target, module2, desc) => {
  __markAsModule(target);
  if (module2 && typeof module2 === "object" || typeof module2 === "function") {
    for (let key of __getOwnPropNames(module2))
      if (!__hasOwnProp.call(target, key) && key !== "default")
        __defProp(target, key, {get: () => module2[key], enumerable: !(desc = __getOwnPropDesc(module2, key)) || desc.enumerable});
  }
  return target;
};
var __toModule = (module2) => {
  if (module2 && module2.__esModule)
    return module2;
  return __exportStar(__defProp(module2 != null ? __create(__getProtoOf(module2)) : {}, "default", {value: module2, enumerable: true}), module2);
};

// <stdin>
Promise.resolve().then(() => __toModule(require("fs")));
```

Note that last line which appears to special-case requires of node built-in modules. In node's ESM world, this is not allowed from with an ES Module. Instead, the should be `import('fs')` or even `import('node:fs')` but `esbuild` seems to prevent me from doing that directly.

**Comment by ggoodman** [comment] 2021-01-09 00:15
I've also played around with using `require('module').createRequire` to create a require function that I inject in a `banner` with some success. It felt more like working against the system than working with it though.

**Comment by evanw** [comment] 2021-01-28 23:04
I'm going to close this since there isn't code to reproduce the issue.

Note that you can now use `--platform=neutral` to disable all [platform-specific defaults](https://esbuild.github.io/api/#platform), and then build up your own config from scratch. That could be worth a try if you're still encountering this problem.

Happy to reopen if you're still dealing with this issue and the new neutral platform setting doesn't help.

**Closed by evanw** 2021-01-28 23:04 UTC
