### ISSUE TITLE
define not respected when it's value is imported/constant

### ISSUE THREAD

**Issue by znewsham** [evanw/esbuild#2724] opened 2022-12-07 21:37 UTC
Consider the following:

```
const X = require('x');

if (X.isServer) {
 require('server-only');
}
```

when running:
```
esbuild.build({
 define: {
   'X.isServer': 'false'
 }
})
```

The specific usecase is: some code I'm trying to bundle (part of a library I don't control) uses `X.isServer` to differentiate between client and server code - it then imports a module that doesn't exist on the client, esbuild tries to resolve that module and I'd expect it NOT to.

I'm aware I can escape from this on a case-by-case by using `external` - but are there any plans to support the above usecase?

Interestingly both `X.isServer = true;...` and `X = {...}` work as I'd expect (e.g., the defined value overrules) - the issue happens specifically when `let`/`var`/`const` or `import` are used.

**Comment by evanw** [comment] 2022-12-07 22:12
This is not what the define feature does. It’s only meant for replacing references to global variables. Replacing local variables is not nearly as robust and is not something I’m planning to build into esbuild. 

If you want to do this, you’ll have to do this yourself. One way to do this is to write a plugin that edits the file at build time before esbuild compiles it: https://esbuild.github.io/plugins/#on-load. You could also consider asking the package author to make their package bundler-friendly. 

Closing this issue as working as intended.

**Closed by evanw** 2022-12-07 22:12 UTC
