### ISSUE TITLE
esbuild includes tslib multiple times

### ISSUE THREAD

**Issue by kyeotic** [evanw/esbuild#1586] opened 2021-09-09 21:24 UTC
The purpose of [tslib](https://github.com/microsoft/tslib) is to eliminate the duplication of "helper" functions for transpiled code. When building a typescript project whose dependencies use tslib the entire tslib library is included for every reference.

I am using this config ([see here for reproduction](https://github.com/Nike-Inc/dynamo-arc/commit/7336c1ea9173afdb5ed0097aa7a61698da5e6351))

```
require('esbuild')
  .build({
    entryPoints: ['src/main.ts'],
    bundle: true,
    outfile: 'lib/main.js',
    platform: 'node',
    format: 'cjs',
    target: 'es2019',
  })
  .catch(() => process.exit(1))
```

The entire tslib library is included 23 times. Its not even pulling the one matching the target (2018), its pulling the es5 version with the very large __generator/__awaiter helpers. The result is a bundle with very large duplicated sections of code.

**Comment by evanw** [comment] 2021-09-10 04:44
It looks like on the file system, each package under the `node_modules/@aws-sdk` directory is getting its own nested `node_modules/tslib` directory file inside it (so `node_modules/@aws-sdk/client-dynamodb/node_modules/tslib` and `node_modules/@aws-sdk/util-dynamodb/node_modules/tslib` and so on). This means that when you run the code in node `tslib` will be loaded many times.

So esbuild bundling `tslib` multiple times is "correct" because that's what's supposed to happen given the code on the file system. In fact it would be incorrect for esbuild to merge all `tslib` copies to a single copy because that's not semantically the same (e.g. each function object is supposed to have its own object identity, which merging would destroy). See also https://github.com/evanw/esbuild/issues/1038#issuecomment-805263902 for someone asking about this same issue in the past.

The underlying problem is that npm is creating many copies of `tslib` on the file system. From what I understand, this happens when there are conflicting versions. One of the versions gets installed at the top level `node_modules/tslib` location and then conflicting versions get installed in nested locations such as `node_modules/@aws-sdk/client-dynamodb/node_modules/tslib`. Your project has at least two versions of `tslib` active: `tslib@1.14.1` (required by `@aws-crypto/ie11-detection` among others) and `tslib@2.3.1` (required by `@aws-sdk/middleware-logger` among others).

So you could either try to fix this at install time by somehow getting the installer to not put many copies of `tslib` all over the place, or you could fix this with a [custom esbuild plugin](https://esbuild.github.io/plugins/#resolve-callbacks) that redirects different copies of `tslib` to the same copy. But esbuild cannot do this automatically as it would potentially change the semantics of the code.

**Comment by kyeotic** [comment] 2021-09-10 17:06
@evanw Rollup does not produce the duplicated tslib ([reproduction](https://github.com/Nike-Inc/dynamo-arc/tree/cc0fc09b1ffbca0533690292d9aebb57ba3628b7)). I would call that behavior "correct", regardless of the underlying filesystem.

**Comment by hyrious** [comment] 2021-09-12 01:20
It turns out that @rollup/plugin-typescript did dedupe tslib in its [custom resolving code](https://github.com/rollup/plugins/blob/53fb18c0c2852598200c547a0b1d745d15b5b487/packages/typescript/src/index.ts#L92-L95).
If you'd like to make it happen in esbuild, you may need to write a plugin to handle `onResolve`.

**Comment by evanw** [comment] 2021-09-12 20:13
I just verified that when you run that code in node, it loads and evaluates the following copies of tslib:

```
node_modules/@aws-sdk/client-dynamodb/node_modules/tslib/tslib.js
node_modules/@aws-sdk/smithy-client/node_modules/tslib/tslib.js
node_modules/@aws-sdk/middleware-stack/node_modules/tslib/tslib.js
node_modules/@aws-sdk/middleware-serde/node_modules/tslib/tslib.js
node_modules/@aws-sdk/client-sts/node_modules/tslib/tslib.js
node_modules/@aws-sdk/middleware-signing/node_modules/tslib/tslib.js
node_modules/@aws-sdk/property-provider/node_modules/tslib/tslib.js
node_modules/@aws-sdk/signature-v4/node_modules/tslib/tslib.js
node_modules/@aws-sdk/config-resolver/node_modules/tslib/tslib.js
node_modules/@aws-sdk/credential-provider-imds/node_modules/tslib/tslib.js
node_modules/@aws-sdk/node-config-provider/node_modules/tslib/tslib.js
node_modules/@aws-sdk/client-sso/node_modules/tslib/tslib.js
node_modules/@aws-sdk/middleware-retry/node_modules/tslib/tslib.js
node_modules/@aws-sdk/middleware-content-length/node_modules/tslib/tslib.js
node_modules/@aws-sdk/middleware-host-header/node_modules/tslib/tslib.js
node_modules/@aws-sdk/middleware-logger/node_modules/tslib/tslib.js
node_modules/@aws-sdk/middleware-user-agent/node_modules/tslib/tslib.js
node_modules/@aws-sdk/credential-provider-web-identity/node_modules/tslib/tslib.js
node_modules/@aws-sdk/middleware-endpoint-discovery/node_modules/tslib/tslib.js
node_modules/@aws-sdk/endpoint-cache/node_modules/tslib/tslib.js
node_modules/@aws-sdk/util-waiter/node_modules/tslib/tslib.js
node_modules/@aws-sdk/lib-dynamodb/node_modules/tslib/tslib.js
node_modules/@aws-sdk/util-dynamodb/node_modules/tslib/tslib.js
```

So esbuild's interpretation of the module graph on the file system is accurate (i.e. just like node). You are welcome to modify esbuild's module resolution logic with a custom plugin if you wish. Documentation is here: https://esbuild.github.io/plugins/#resolve-callbacks. I suggest considering only collapsing tslib copies with the same `package.json` version as different versions may be incompatible and collapsing them all into a single copy may break things.

Closing this since esbuild is working as intended.

**Closed by evanw** 2021-09-12 20:13 UTC
