### ISSUE TITLE
local image cannot display after bundle

### ISSUE THREAD

**Issue by mebest100** [evanw/esbuild#3433] opened 2023-10-08 06:10 UTC
Local image cannot display on the page  after bundle but picture file output there

img quote code :
```
   <Carousel {...settings}>
                <div>
                  <img src={require("@/images/carousel_1.jpg").default} />
                </div>
                <div>
                  <img src={require("@/images/carousel_2.jpg").default} />
                </div>
                <div>
                  <img src={require("@/images/carousel_3.jpg").default} />
                </div>
                <div>
                  <img src={require("@/images/carousel_4.jpg").default} />
                </div>
              </Carousel>
```
DevServerConfig.js
```
const esbuild = require("esbuild");
const path = require("path");
const { lessLoader } = require("esbuild-plugin-less");

const serverPort = 7001;

(async () => {
  const config = {
    entryPoints: ["./src/root.js"], 
    bundle: true, 
    outdir: "./public/build", 
    minify: false, 
    loader: {
      ".js": "jsx",
      ".css": "css", 
      ".png": "file",
      ".jpg": "file",
      ".jpeg": "file", 
      ".gif": "file", 
      ".svg": "file", 
    },
    alias: {      
      "@": path.resolve(__dirname, "./src"),
    },
    plugins: [lessLoader()],
  };

  
  const context = await esbuild.context(config);
  let { port } = await context.serve({
    servedir: "public/build", 
  });

  const express = require("express")
  const app = express();
  const {
    createProxyMiddleware,   
  } = require("http-proxy-middleware");
  const history = require("connect-history-api-fallback");
 

  app.use(
    "/api",
    createProxyMiddleware({
      target: "https://way.jd.com/jisuapi/get", 
      changeOrigin: true,
      pathRewrite: {
        "^/api": "", 
      },
    })
  );


app.use('/', createProxyMiddleware({
  target: `http://127.0.0.1:${port}`, 
  changeOrigin: true,
}));

app.use(history());
app.listen(serverPort, () => {
  console.log(`Server is running on port ${serverPort}`);
});

})();

```

My react code run well with webpack, but with problem with esbuild. Anything should be changed for esbuild config or for my code?

**Comment by evanw** [comment] 2023-10-11 05:51
Sorry but it's not going to be possible for me to reproduce your issue (and therefore see whether it's a problem with esbuild or not) without a complete code example that actually runs. Please provide a way to reproduce your issue.

You should also be able to debug this for yourself. The URLs that esbuild's `file` loader returns should be visible in the network tab of your browser's developer tools. You can look at them and figure out what's going on from there.

**Comment by evanw** [comment] 2023-10-17 01:16
Closing this issue because the issue reporting instructions were not followed (there is no way to reproduce the issue).

**Closed by evanw** 2023-10-17 01:16 UTC
