### ISSUE TITLE
The packages used in the project, there are.bin How to package Settings

### ISSUE THREAD

**Issue by soeasyjx** [evanw/esbuild#3503] opened 2023-11-23 02:37 UTC
#### problem

I used the update-notifier@5 library in my nodejs project, and after packaging it, I got an error when running it

A shell program named is-ci exists in the update-notifier library.bin directory

#### Errors are as follows

```bash
node:internal/modules/cjs/loader:1078
  throw err;
  ^

Error: Cannot find module 'is-ci'
Require stack:
```

#### environment
- esbuild:0.19.5
- node:v18.14.1

#### Package management
pnpm

**Comment by evanw** [comment] 2023-11-23 02:44
I'm confused. Why are you posting about that here? Perhaps you are looking for these repos instead:

* https://github.com/yeoman/update-notifier
* https://github.com/watson/is-ci

If not, you need to follow the issue reporting instructions and provide a way to reproduce the issue (and describe what esbuild is doing wrong). I'm closing this issue because you ignored the issue reporting instructions, and this also doesn't sound like it's related to esbuild at all.

**Closed by evanw** 2023-11-23 02:44 UTC

**Comment by soeasyjx** [comment] 2023-11-23 05:03
I used esbuild to package the nodejs project above
