### ISSUE TITLE
`loader: 'tsx'` + `jsx: 'preserve'` doesn't work

### ISSUE THREAD

**Issue by hipstersmoothie** [evanw/esbuild#2229] opened 2022-05-06 05:56 UTC
It seem like preserve is only implement for `jsx`. When I try to use it with `tsx` I get this error

```
 error: Invalid option in transform() call: "jsx"
```

**Comment by hyrious** [comment] 2022-05-06 09:41
I didn't reproduce your error, here's what I did:

```js
> esbuild.transformSync('<div />', { jsx: 'preserve', loader: 'tsx' })
{ warnings: [], code: '<div />;\n', map: '' }
```

**Comment by evanw** [comment] 2022-05-07 17:44
Marking as `unactionable` because there isn't enough information here to reproduce the problem.

**Comment by evanw** [comment] 2022-06-15 20:43
Closing due to lack of a reply.

**Closed by evanw** 2022-06-15 20:43 UTC
Labels: unactionable
