### ISSUE TITLE
What code base to choose for a new project?

### ISSUE THREAD

**Issue by vdegenne** [evanw/esbuild#1960] opened 2022-01-25 17:37 UTC
Hello,

I am new to `esbuild`, previously using `rollup` I try to get a grasp of this new build tool.
I usually use `rollup` for my web applications but this time I am making a small npm module and I plan to release it with both commonjs and esm distribution files.

What is the recommended way? Should I use typescript, es-modules or commonjs as the base language in my project?

(sorry for opening an issue for this question but I couldn't find any social place to ask the devs)

Thanks in advance

**Comment by evanw** [comment] 2022-01-25 19:30
> What is the recommended way?

I have no recommendation. Feel free to write code however you'd like to.

> typescript, es-modules or commonjs

The decision is TypeScript vs. JavaScript, and independently ESM vs. CommonJS. One is about language and the other is about module format. ESM and CommonJS are not languages.

**Comment by vdegenne** [comment] 2022-01-25 20:40
@evanw What I meant is "is it easier to configure esbuild if I am using ECMAScript modules or CommonJS.
I tried writing my module using ECMAScript and I typed

```bash
esbuild input.js --platform=node --outfile=output.js
```

But the ouput still use the ECMAScript import syntax. I have to use `--bundle` to force `esbuild` to translate my code to CommonJS. Technically I am not needed to bundle anything, this is just one file to convert.

Maybe I am not using the right tool, I just needed an easy program to translate one module to another and I thought `esbuild` was the one. Maybe you would recommend another program instead if you confirm that I am using `esbuild` for the wrong purpose.
I will try to use `esbuild` for my next web project though, it looks awesome.

Thanks!

**Comment by evanw** [comment] 2022-01-25 21:20
> I have to use `--bundle` to force `esbuild` to translate my code to CommonJS.

That's just a side effect of `--bundle` because bundling implies some output format, so esbuild picks one for you if you don't specify one. The `--format=` flag is the actual way to set the output format though: https://esbuild.github.io/api/#format.

I guess the choice of module format depends on what type of API you want. If you want to enable people to `import { something } from` your module in the ESM output variant then you should author in ESM and convert to CommonJS, since CommonJS-authored modules only have a default export when converted to ESM (so you'd have to do `import something from` instead). But if you want people to `import something from` your module then you may want to author in CommonJS and convert to ESM instead. The reason is that the ESM `export default` works inconsistently between tools after it's been converted to CommonJS (specifically node does it one way and everyone else does it another way).

> I plan to release it with both commonjs and esm distribution files

One consideration regarding this approach is that doing this can result in duplicate copies of your code being loaded. That may be ok if you know for sure that people will only use one or the other. But otherwise it can result in inefficiencies in the best case and subtle bugs in the worst case. This is by design and is part of node's module format specification: https://nodejs.org/api/packages.html#dual-package-hazard. One recommended workaround is to author in CommonJS and then provide an ESM shim that imports the CommonJS code and then re-exports it using an ESM API. Keep in mind that this may limit how well tree shaking works with your package, however. Read that link for more details about the dual package hazard.

**Comment by evanw** [comment] 2022-01-27 14:57
Closing this because the question was answered and this issue is not a problem with esbuild.

**Closed by evanw** 2022-01-27 14:57 UTC

**Comment by vdegenne** [comment] 2022-01-29 15:19
@evanw Thanks

Yes that is the reason why I needed a transpiler, to write one version of my code in the language I feel comfortable with, but yet providing my package in two modules of choice. I finally chose to write my library using Typescript only which does wonderful for transpiling both in ES and CommonJS modules and generating typing files.

I think `esbuild` will do great for bundling my next web project. Thanks a lot for taking your time to explain also! ⭐
