### ISSUE TITLE
Define non-JSON values in config for module usage with bundlers

### ISSUE THREAD

**Issue by andrewcourtice** [evanw/esbuild#1050] opened 2021-03-25 00:35 UTC
Hi

Firstly, thank you for esbuild - it's great!

I've come across an issue which is more than likely my own misunderstanding of the configuration but here goes. I am bundling a series of TypeScript files to be published as a library. As a result I have some code which looks like this:

```typescript
if (__IS_DEV__ && values.has(name)) {
    // if body
}
```

What I am trying to achieve is that during compilation the `__IS_DEV__` global is replaced with `process.env.NODE_ENV !== "production"` so that when the consumer of the library is running the lib through their bundler their bundle process transforms the prod statement accordingly.

I have attempted this with my esbuild config: 

```typescript
{
    define: {
        '__IS__DEV__': format === 'iife' ? false : 'process.env.NODE_ENV !== "production"'
    }
}
```

When I run the build esbuild logs this to the console:
```console
error: Invalid define value (must be valid JSON syntax or a single identifier): process.env.NODE_ENV !== 'production'
```

Is there a way to achieve this behaviour using `define` or `inject`?

Thanks 👍

**Comment by evanw** [comment] 2021-03-25 02:58
The define feature is for constants. The inject feature is the way to inject arbitrary code. Documentation for the inject feature is here: https://esbuild.github.io/api/#inject. You should be able to inject a file containing this code to accomplish this:

```js
export var __IS__DEV__ = process.env.NODE_ENV !== "production"
```

**Comment by andrewcourtice** [comment] 2021-03-25 03:38
@evanw Thanks for getting back to me.

I attempted to use inject like so:
```javascript
// injection.js
 export const __IS_DEV__ = process.env.NODE_ENV !== 'production';
```

However, esbuild evaluates the injection before putting it in the output, so the output just has the literal value:
```javascript
// ../packages/build/src/injections/dev.js
var __IS_DEV__ = false;
```

I also attempted to use a function but that turned out the same way:
```javascript
// injection.js
 export const __IS_DEV__ = () => process.env.NODE_ENV !== 'production';
```
And the output:
```javascript
// ../packages/build/src/injections/dev.js
var __IS_DEV__ = () => false;
```

Is there any way to tell esbuild to not evaluate the injected code before injecting it?

Thanks again for getting back to me so quickly 👍

**Comment by evanw** [comment] 2021-03-25 04:07
I'm guessing you also defined `process.env.NODE_ENV` at the same time? If you want `process.env.NODE_ENV` to be a run-time value instead of a build-time value, you should remove it from the define list. If that's not the case then it could be good to see your full build API call to be able to reproduce what you're doing.

**Comment by andrewcourtice** [comment] 2021-03-25 04:26
Ahhh yep - that was the culprit.

Thanks again for helping out.

**Comment by evanw** [comment] 2021-03-26 08:20
Closing this as it seems to be resolved.

**Closed by evanw** 2021-03-26 08:20 UTC

**Comment by andrewcourtice** [comment] 2021-03-26 12:15
@evanw great 👍 Here's the outcome I ended up with if you are curious: https://github.com/andrewcourtice/harlem/blob/main/packages/build/src/index.js
