### ISSUE TITLE
NPM install code 1 error esbuild

### ISSUE THREAD

**Issue by ktsandven** [evanw/esbuild#2783] opened 2022-12-30 12:29 UTC
I am receiving this error when running 'npm install' after npm create vite@latest

I've run into this problem with versions 10, 14,  16, and 18 of node

#npm ERR! code 1
npm ERR! path /Users/kylesandven/Desktop/react/hacker-stories/node_modules/esbuild
npm ERR! command failed
npm ERR! command sh -c -- node install.js
npm ERR! node:internal/errors:857
npm ERR!   const err = new Error(message);
npm ERR!               ^
npm ERR! 
npm ERR! Error: Command failed: /Users/kylesandven/Desktop/react/hacker-stories/node_modules/esbuild/bin/esbuild --version
npm ERR! dyld: Symbol not found: _SecTrustEvaluateWithError
npm ERR!   Referenced from: /Users/kylesandven/Desktop/react/hacker-stories/node_modules/esbuild/bin/esbuild
npm ERR!   Expected in: flat namespace
npm ERR! 
npm ERR! 
npm ERR!     at checkExecSyncError (node:child_process:861:11)
npm ERR!     at Object.execFileSync (node:child_process:896:15)
npm ERR!     at validateBinaryVersion (/Users/kylesandven/Desktop/react/hacker-stories/node_modules/esbuild/install.js:90:32)
npm ERR!     at /Users/kylesandven/Desktop/react/hacker-stories/node_modules/esbuild/install.js:243:5 {
npm ERR!   status: null,
npm ERR!   signal: 'SIGABRT',
npm ERR!   output: [
npm ERR!     null,
npm ERR!     Buffer(0) [Uint8Array] [],
npm ERR!     Buffer(182) [Uint8Array] [
npm ERR!       100, 121, 108, 100,  58,  32,  83, 121, 109,  98, 111, 108,
npm ERR!        32, 110, 111, 116,  32, 102, 111, 117, 110, 100,  58,  32,
npm ERR!        95,  83, 101,  99,  84, 114, 117, 115, 116,  69, 118,  97,
npm ERR!       108, 117,  97, 116, 101,  87, 105, 116, 104,  69, 114, 114,
npm ERR!       111, 114,  10,  32,  32,  82, 101, 102, 101, 114, 101, 110,
npm ERR!        99, 101, 100,  32, 102, 114, 111, 109,  58,  32,  47,  85,
npm ERR!       115, 101, 114, 115,  47, 107, 121, 108, 101, 115,  97, 110,
npm ERR!       100, 118, 101, 110,  47,  68, 101, 115, 107, 116, 111, 112,
npm ERR!        47, 114, 101,  97,
npm ERR!       ... 82 more items
npm ERR!     ]
npm ERR!   ],
npm ERR!   pid: 44802,
npm ERR!   stdout: Buffer(0) [Uint8Array] [],
npm ERR!   stderr: Buffer(182) [Uint8Array] [
npm ERR!     100, 121, 108, 100,  58,  32,  83, 121, 109,  98, 111, 108,
npm ERR!      32, 110, 111, 116,  32, 102, 111, 117, 110, 100,  58,  32,
npm ERR!      95,  83, 101,  99,  84, 114, 117, 115, 116,  69, 118,  97,
npm ERR!     108, 117,  97, 116, 101,  87, 105, 116, 104,  69, 114, 114,
npm ERR!     111, 114,  10,  32,  32,  82, 101, 102, 101, 114, 101, 110,
npm ERR!      99, 101, 100,  32, 102, 114, 111, 109,  58,  32,  47,  85,
npm ERR!     115, 101, 114, 115,  47, 107, 121, 108, 101, 115,  97, 110,
npm ERR!     100, 118, 101, 110,  47,  68, 101, 115, 107, 116, 111, 112,
npm ERR!      47, 114, 101,  97,
npm ERR!     ... 82 more items
npm ERR!   ]
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kylesandven/.npm/_logs/2022-12-30T17_18_48_823Z-debug-0.log

**Comment by evanw** [comment] 2022-12-30 17:25
Duplicate of #2183. You are running an unsupported version of macOS that's too old to run esbuild. You can see that thread for possible workarounds.

Closing as this is not something that esbuild can fix.

**Closed by evanw** 2022-12-30 17:25 UTC
