### ISSUE TITLE
Import statements of externals are not merged

### ISSUE THREAD

**Issue by heyheyhello** [evanw/esbuild#1218] opened 2021-04-28 08:45 UTC
Is there a reason why a bundle has a separate import statement for every file that uses the exact same external? If I have 4 files that do `import { x } from "myexternal";` I end up with a bundle that has (only imports shown for brevity):

```js
// src/a.ts
import {x as x3} from "myexternal";
// src/b.ts
import {x as x2} from "myexternal";
// src/c.ts
import {x as x1} from "myexternal";
// src/d.ts
import {x} from "myexternal";
```

Is this about side effects? I tried marking all uses of `x` as `/* @__PURE__ */` but no change. I also tried an external defined in tsconfig.json's `path` field. I tried `--minify` too. Here's a minimal repro: https://github.com/heyheyhello/esbuild-merge-externals

Is there a way to just make this into:

```js
import {x} from "myexternal";
```

I want all references to `x` in the entire codebase to be a single import statement since I'm passing this to an acorn AST parser after esbuild is done.

Thank you! 🌺

**Comment by evanw** [comment] 2021-04-28 08:49
The reason is that I'm working on a rewrite of the linker to address this and a lot of other issues but the rewrite hasn't landed yet. Closing as a duplicate of #475 since this has already been filed.

**Closed by evanw** 2021-04-28 08:49 UTC

**Comment by heyheyhello** [comment] 2021-04-28 08:56
Interesting, ok thanks. I'll try to use the threeShim that #475 suggests.
