### ISSUE TITLE
`assert` module import is transformed incorrectly

### ISSUE THREAD

**Issue by floydspace** [evanw/esbuild#141] opened 2020-05-24 23:42 UTC
I do `assert` module import like this in typescript:
```typescript
import * as assert from 'assert';
...
assert(serviceUrl?.length, `Cannot initialize service ${serviceName}`);
```
and I'm getting error in runtime `"TypeError: assert5 is not a function"`

Following the stack trace, I see that it was transformed like:
```javascript
const assert5 = __toModule(require("assert"));
...
assert5(serviceUrl == null ? void 0 : serviceUrl.length, `Cannot initialize service ${serviceName}`);
```
but the assert5 function invokation is supposed to be transformed to `assert5.default` the same way like I would import it using default import:
```typescript
import assert from 'assert';
```
So `import * as assert from 'assert';` is not transformed correctly. I see that this kind of import is covered by tests on `fs` module example, but apparently the case that default export is a function is not covered.

**Comment by evanw** [comment] 2020-05-25 02:45
ES6 namespace imports are objects, not functions. The behavior of esbuild described above matches what happens in node itself, so I believe that esbuild's behavior is correct.

## Namespace import

Create a file called `example.mjs` with this code:

```js
import * as assert from 'assert'
assert(false)
```

Run with `node --experimental-modules example.mjs`:

```
(node:11440) ExperimentalWarning: The ESM module loader is experimental.
example.mjs:2
assert(false)
^

TypeError: assert is not a function
    at example.mjs:2:1
    at ModuleJob.run (internal/modules/esm/module_job.js:110:37)
    at async Loader.import (internal/modules/esm/loader.js:176:24)
```

## Default import

Create a file called `example.mjs` with this code:

```js
import assert from 'assert'
assert(false)
```

Run with `node --experimental-modules example.mjs`:

```
(node:11442) ExperimentalWarning: The ESM module loader is experimental.
internal/modules/run_main.js:57
    internalBinding('errors').triggerUncaughtException(
                              ^

AssertionError [ERR_ASSERTION]: false == true
    at example.mjs:2:1
    at ModuleJob.run (internal/modules/esm/module_job.js:110:37)
    at async Loader.import (internal/modules/esm/loader.js:176:24) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
```

**Comment by evanw** [comment] 2020-05-25 20:42
Just saw you gave a 👍. Closing as "working as intended".

**Closed by evanw** 2020-05-25 20:42 UTC

**Comment by floydspace** [comment] 2020-05-25 21:21
no prob, thank you.
