### ISSUE TITLE
[css-minifier] do not escape invisible characters

### ISSUE THREAD

**Issue by yisibl** [evanw/esbuild#2124] opened 2022-03-24 03:27 UTC
We usually do some special hacking with invisible characters, which will become unreadable after escaping and hard to read the CSS code when debugging.

For escaped characters, it is safest to convert only case and compress the length of Unicode characters. See also: https://mathiasbynens.be/notes/css-escapes

For example: 

- `\000A` => `\a`
- `\0020` => `\20`
-  `\9` => `\9`

## Input

The following example is from: https://lea.verou.me/2012/02/flexible-multiline-definition-lists-with-2-lines-of-css/

```css
:not(#\9) .foo {
  font-family: \000A;
}

dd:after {
  content: "\A" "\0009" "Hello" "\3A";
  white-space: pre;
}
```

## Output

```css
:not(#\	) .foo{font-family:\a}dd:after{content:"\a" "	" "Hello" "\:";white-space:pre}
```

## Expected

```
:not(#\9) .foo{font-family:\a}dd:after{content:"\a" "\9" "Hello" "\3a";white-space:pre}
```

**Comment by evanw** [comment] 2022-03-24 13:58
Enabling minification means asking for esbuild to produce the smallest valid output. The tab character is one byte while `\9` is two bytes, so `\9` is not the correct minification of the tab character. It looks to me like esbuild is working as intended.

It would only be a bug if esbuild's minifier produces a rendering difference in the browser when compared to the unminified code. If you have an example of such a rendering difference, then please provide it. Otherwise I'm going to close this issue as "working as intended."

> will become unreadable after escaping and hard to read the CSS code when debugging

Making code unreadable is a well-known side effect of minification. Minified code is for computers, not for humans. If you want to debug minified code you should be using source maps.

**Comment by evanw** [comment] 2022-03-27 01:51
I'm closing this because I believe this to be by design, as described above.

**Closed by evanw** 2022-03-27 01:51 UTC
