### ISSUE TITLE
esbuild --bundle hangs on follow-redirects

### ISSUE THREAD

**Issue by ryantm** [evanw/esbuild#3283] opened 2023-08-03 14:55 UTC
I'm not sure if this is a problem with esbuild or follow-redirects, but with
```
 esbuild index.ts --log-level=verbose --bundle --platform=node
```
with index.ts
```
require("follow-redirects")
```
it hangs indefinitely.

If I comment out from the debug.js file
```
      /* eslint global-require: off */
      //debug = require("debug")("follow-redirects");
```
it stops hanging.

```
$ esbuild --version
0.15.14
```

Couldn't include the other library but:
https://esbuild.github.io/try/#YgAwLjE4LjE3AC0tYnVuZGxlIC0tcGxhdGZvcm09bm9kZQBlAGVudHJ5LmpzAHJlcXVpcmUoImZvbGxvdy1yZWRpcmVjdHMiKQ

https://github.com/follow-redirects/follow-redirects/issues/229

**Comment by evanw** [comment] 2023-08-04 21:23
I'm marking this issue as `unactionable` because I cannot reproduce it. Here's what I tried:

```
npm init -y && npm i esbuild@0.15.14 follow-redirects@1.15.2 && echo 'require("follow-redirects")' > index.ts && npx esbuild index.ts --log-level=verbose --bundle --platform=node
```

I get a valid bundle printed to stdout when I run that command. Please provide more information about how to reproduce the hang.

**Comment by evanw** [comment] 2023-08-07 20:12
I’m closing this issue because additional information was not provided. We can reopen this later if sufficient information is added.

**Closed by evanw** 2023-08-07 20:12 UTC
Labels: unactionable

**Comment by ryantm** [comment] 2023-08-07 21:25
I've confirmed that your script still causes a hang in one of my environments and is also okay on my laptop. The difference is on the place that it hangs I have a /nix/store directory that contains tens of thousands of directories.

NODE_PATH is set to `/nix/store/dj805sw07vvpbxx39c8g67x8qddg0ikw-nodejs-18.12.1/lib/node_modules` so that explains why that directory is searched, but not why it has to stat the directories above it.

If I set NODE_PATH to empty, it builds fine.

Here's relevant part of the strace:

```
11977 openat(AT_FDCWD, "/home/runner/esbuild-hang/node_modules/debug", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
11977 openat(AT_FDCWD, "/nix/store/dj805sw07vvpbxx39c8g67x8qddg0ikw-nodejs-18.12.1/lib/node_modules", O_RDONLY|O_CLOEXEC) = 3
11977 epoll_ctl(4, EPOLL_CTL_ADD, 3, {events=EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, data={u32=454984024, u64=139900424716632}}) = -1 EPERM (Operation not permitted)
11977 getdents64(3, 0xc0001ee000 /* 4 entries */, 8192) = 104
11977 getdents64(3, 0xc0001ee000 /* 0 entries */, 8192) = 0
11977 close(3)                          = 0
11989 <... nanosleep resumed>NULL)      = 0
11977 openat(AT_FDCWD, "/nix", O_RDONLY|O_CLOEXEC <unfinished ...>
11989 nanosleep({tv_sec=0, tv_nsec=10000000},  <unfinished ...>
11977 <... openat resumed>)             = 3
11977 epoll_ctl(4, EPOLL_CTL_ADD, 3, {events=EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, data={u32=454984024, u64=139900424716632}}) = -1 EPERM (Operation not permitted)
11977 getdents64(3, 0xc0001ee000 /* 4 entries */, 8192) = 104
11977 getdents64(3, 0xc0001ee000 /* 0 entries */, 8192) = 0
11977 close(3)                          = 0
11977 newfstatat(AT_FDCWD, "/nix", {st_mode=S_IFDIR|0777, st_size=0, ...}, AT_SYMLINK_NOFOLLOW) = 0
11977 openat(AT_FDCWD, "/nix/store", O_RDONLY|O_CLOEXEC) = 3
11977 epoll_ctl(4, EPOLL_CTL_ADD, 3, {events=EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, data={u32=454984024, u64=139900424716632}}) = -1 EPERM (Operation not permitted)
11977 getdents64(3,  <unfinished ...>
11989 <... nanosleep resumed>NULL)      = 0
11989 epoll_pwait(4, [], 128, 0, NULL, 0) = 0
11989 futex(0xc000072548, FUTEX_WAKE_PRIVATE, 1) = 1
```

**Comment by evanw** [comment] 2023-08-07 22:08
Ah, I see. Part of what esbuild's resolver does is to scan parent directories for certain configuration files (e.g. `package.json` and `tsconfig.json`) because they can affect their subtree. So this issue isn't that esbuild is hanging, but that you're running esbuild within a parent directory that has an enormous number of files. I recommend not doing that.
