### ISSUE TITLE
esbuild tries to resolve wrong css file name in any node_module folder with an upper case .tsx-component

### ISSUE THREAD

**Issue by jonasem** [evanw/esbuild#3341] opened 2023-08-25 11:33 UTC
After upgrading esbuild 0.17 -> 0.19 we experienced a weird behavior where esbuild will try to resolve .css-files for components in node_modules even though they are not imported, just merely by beeing on the disk.

We recreated this in a tiny project only installing react@18 and esbuild@0.19 and adding a folder in node_modules like this:

![image](https://github.com/evanw/esbuild/assets/1006193/187f95e3-b7c1-4cd4-829e-1e26d8b23797)

The error output is:

`Could not read from file: /home/jonas/tmp/esbuild-bug/node_modules/foo/bar/A.css`

Note that it looks for a big-letter A.css, while we have a small one, and the kicker is, it's not ever imported anywhere. 

We tested this multiple times, just making a lower-Pascal-case css file matching an upper case .tsx file triggers this error.

**Comment by evanw** [comment] 2023-08-25 13:00
Please provide a way to reproduce the issue. You have not provided enough information here. Marking this issue as `unactionable` for now since I cannot do anything without a way to reproduce the issue.

**Comment by jonasem** [comment] 2023-08-25 14:26
Sure, you can try this repo I made to show the issue https://github.com/jonasem/esbuild-component-css-bug

**Comment by hyrious** [comment] 2023-08-25 14:59
You can enable `logLevel: 'verbose'` to see what actually happens in detail, then you will find this log:

```
⬥ [VERBOSE] Resolving import "./bar/AComponent" in directory "/node_modules/foo" of type "import-statement"
...
    Checking for file "AComponent"
    Checking for file "AComponent.jsx"
    Checking for file "AComponent.js"
    Checking for file "AComponent.css"
    Found file "AComponent.css"
```

So here are 2 things:

- when resolving extension-less imports, esbuild searches for `.css` files, this may be wrong
- esbuild's resolver is case-insensitive, this is ok. however it failed to work well on case-sensitive fs like on linux

**Comment by jonasem** [comment] 2023-08-25 19:32
Thank you for the insight into how to debug this issue. So I didn't expect this behavior, but it make sense when I see the error. Renaming the file to uppercase gave an error during runtime which also makes sense with the given verbose log.I hope I don't have to import typescript files by giving the full extension though, esbuils didn't do that before in this case.

**Comment by hyrious** [comment] 2023-08-25 23:48
The resolver correctly works back at version 0.17.19 [repl](https://hyrious.me/esbuild-repl/?version=0.17.19&b=e%00entry.ts%00import+foo+from+%27foo%27%0Aconsole.log%28foo%29&b=%00node_modules%2Ffoo%2Findex.ts%00import+AComponent+from+%22.%2Fbar%2FAComponent%22%3B%0Aexport+default+AComponent%3B&b=%00node_modules%2Ffoo%2Fbar%2FAComponent.tsx%00import+React+from+%27react%27%0Aexport+default+%28%29+%3D%3E+%3C%3E%3C%2F%3E&b=%00node_modules%2Ffoo%2Fbar%2FaComponent.css%00&o=--bundle+--log-level%3Dverbose+--external%3Areact+--outdir%3Ddist). So I guess this is a bug introduced in 0.18.

**Comment by jonasem** [comment] 2023-08-28 08:47
Don't really know what more to make of this now. I wrote some tests in `bundler_ts_test.go` to confirm my thinking.

I only got a failing test on this, and no solution. But I suspect a `.ts` file in `node_modules` importing an implicit extension should favor `.ts` over `.css`. 

@evanw Is there anything I can do to help along with this issue?

**Comment by vprus** [comment] 2024-01-23 19:54
Hi, 
I might be missing something, but what's preventing this issue from getting fixed - if there was a PR, even? I've just run into it in a project that has index.tsx + index.css in a number of directories, and esbuild picks CSS one, and fails.

**Closed** 2024-01-26 06:37 UTC
Labels: unactionable
