### ISSUE TITLE
import.meta is empty

### ISSUE THREAD

**Issue by davidmz** [evanw/esbuild#2249] opened 2022-05-13 09:18 UTC
I'm trying to use the [gifsicle](https://www.npmjs.com/package/gifsicle) package in one of my projects, and have an import.meta.url issue. Here is a simple repo that reproduces the problem: https://github.com/davidmz/gifsicle-esbuild-test

Try to compile code with the `npm run build` command and then run it with `npm run run`. You will see the `ERR_INVALID_URL` error. [This line](https://github.com/imagemin/gifsicle-bin/blob/v7.0.0/lib/index.js#L6) of gifsicle code uses the import.meta.url:
```
const pkg = JSON.parse(fs.readFileSync(new URL('../package.json', import.meta.url)));
```
and esbuild compiled it to the:
```
var import_meta = {};
var pkg = JSON.parse(import_node_fs.default.readFileSync(new URL("../package.json", import_meta.url)));
```
What do I (or, maybe, the gifsicle authors) wrong?

**Comment by hyrious** [comment] 2022-05-13 10:03
You have to make the code work:

```js
fs.readFileSync(new URL('../package.json', import.meta.url))
```

In 2 ways,

- Don't bundle that library. You can add `--external:gifsicle` to your build command so that this code will not change and it will work if your node runtime supports import.meta.
- Modify this code to be bundle-able. You can write a plugin to replace this line with what it expects (the contents of the package.json).

_Why is `import.meta.url` not bundle-able?_ Because this is a **runtime feature**, it only exists in ESM context. So esbuild will add `var import_meta = {}` in non-ESM formats (like CJS/IIFE) to make it not a syntax error. In which case not all users want this result. However doing [polyfill](https://github.com/egoist/tsup/blob/dev/assets/cjs_shims.js) about this thing is not esbuild's duty.

**Comment by evanw** [comment] 2022-05-15 15:22
Thanks for the comment. I agree that making `gifsicle` external makes the most sense here, as it's not easy to bundle. Gifsicle also appears to invoke a native binary executable so bundling it also doesn't make sense for that reason. Even if you were to bundle it somehow, you would still need to keep the `node_modules` file around anyway since I assume `gifsicle` wouldn't work without the binary executable.

Closing as "working as intended."

**Closed by evanw** 2022-05-15 15:22 UTC

**Comment by davidmz** [comment] 2022-05-16 11:19
Thank you so much for the detailed explanations!

**Comment by douglasg14b** [comment] 2024-11-18 17:56
We should be able to bundle this when it's used in an isomorphic manner, this breaks bundling if any dependency includes isomorphic CJS/ESM compatible code of this type.
