### ISSUE TITLE
Cloudflare breaks the minimized code for Float's

### ISSUE THREAD

**Issue by OverLord561** [evanw/esbuild#3766] opened 2024-05-14 12:44 UTC
### Problem with minification

Hi!
I have a code like this and the problem is with (0.0) minimization
`(0.0).toLocaleString('en-US', { style: 'currency', currency: 'USD' }).replace('0.00', '');`
it will be minified to 
`0 .toLocaleString('en-US', { style: 'currency', currency: 'USD' }).replace('0.00', '');`

**There is the whitespace after 0 before .toLocaleString**

Later Cf-Bgj: minify feature of Cloudflare will remove whitespace before toLocaleString
`0.toLocaleString('en-US', { style: 'currency', currency: 'USD' }).replace('0.00', '');`

which cause 
**Uncaught SyntaxError: Invalid or unexpected token**

### Expected behavior

Default behaviour like in Terser when number is wrapped into brackets
`(0).toLocaleString('en-US', { style: 'currency', currency: 'USD' }).replace('0.00', '');`

### Minimal reproduction URL

https://stackblitz.com/edit/vitejs-vite-tha46h?file=currency.js

### Version

Chrome Version 124.0.6367.119 (Official Build) (64-bit)

### Node.js version

20.11

### Package manager

pnpm

### Operating system

Linux

### The explanation
https://stackoverflow.com/questions/9380077/why-cant-i-access-a-property-of-an-integer-with-a-single-dot

**Comment by lazarljubenovic** [comment] 2024-05-14 12:59
Shouldn't this be reported to the minifier that removes the space?

**Comment by evanw** [comment] 2024-05-14 13:50
I’m closing this as this is not a bug with esbuild. This is a bug with Cloudflare. 

Also FYI I found [this](https://developers.cloudflare.com/speed/optimization/content/auto-minify/):

> **Deprecation notice**
>
> Auto Minify is deprecated and will be removed on 2024-08-05. After this date, Auto Minify will no longer be available via the Cloudflare dashboard, API, or Terraform.
>
> We recommend that you minify at the origin during the build phase. Minification is included in most modern web development frameworks.

I’m not sure if this is the same feature since I don’t use Cloudflare myself. But if it is, it sounds like you shouldn’t even be using it. You should just turn it off to fix this problem as it’s going to be removed soon anyway.

**Closed by evanw** 2024-05-14 13:50 UTC

**Comment by OverLord561** [comment] 2024-05-14 15:06
Thank you guys!
