### ISSUE TITLE
Webpack 5 watch mode SIGBUS exit when running esbuild

### ISSUE THREAD

**Issue by marco2216** [evanw/esbuild#1734] opened 2021-11-01 14:39 UTC
After upgrading to webpack 5 (5.61.0), when running webpack in watch mode, if I run esbuild anywhere (even in another folder), it crashes the webpack process with a SIGBUS message:

```
error Command failed with signal "SIGBUS".
```

I did try to create a minimal example, but it seems to only happen when webpack is watching a large amount of code. We have multiple entry points in our app, and it only crashes on some of them, if I disable all other entry points. I managed to reproduced with only one plugin, babel to compile typescript. Without this plugin the error does not occur, but of course webpack cannot compile anything either. 

It can be reproduced on multiple machines (Mac OS Big Sur, 11.6). Tested with esbuild 0.8.11 and 0.13.12.

Any ideas, any more information I can give?

**Comment by evanw** [comment] 2021-11-02 02:51
Can you provide a code sample that reproduces the issue? I'm not sure what to do with this issue report otherwise, sorry.

**Comment by marco2216** [comment] 2021-11-04 21:19
Hi, sorry for the delay. I haven't been able to create a project that reproduces the issue yet. But I have narrowed it down further. With just one entry point, the issue seems to occur when the bundle size (or maybe number of required files) gets over some limit. But it doesn't crash 100% of the time.
My testing has led to a case where I can import one file, and it will not crash when running esbuild. But if I import another file as well, it will crash (not always on first attempt, but it will eventually crash if I keep running esbuild a few times). But it will not crash if I import either of the two alone. So that leads me to believe it has something to do with the size/amount of files required, which might make sense if it's a memory issue.

**Comment by chentselee** [comment] 2021-11-24 06:08
I am running into this issue with Vite and i agree with @marco2216 that it seems to have something to do with limit of some sort (file sizes/number of files)

**Comment by evanw** [comment] 2022-01-06 17:38
I'm going to close this since there isn't anything actionable here, and the underlying problem is with Webpack anyway.

**Closed by evanw** 2022-01-06 17:38 UTC
Labels: unactionable

**Comment by aoarashi1988** [comment] 2022-12-02 11:21
any update here ?
