### ISSUE TITLE
esbuild bundle 3 times the size of the equivalent webpack bundle

### ISSUE THREAD

**Issue by kimsagro1** [evanw/esbuild#958] opened 2021-03-12 06:32 UTC
Given the following  `index.js` file

```js
import { DynamoDBDocument } from '@aws-sdk/lib-dynamodb'
console.log(DynamoDBDocument)
```

Bundling with esbuild produces an output of size `394.4 KB`
```
> npx esbuild index.js --bundle --minify --platform=node --target=node14 --outfile=dist.js
dist.js  394.4kb
```

The equivalent webpack bundle produces an output of size `134 KB`
```
> npx webpack --mode=production --target=node ./index.js
asset main.js 134 KiB [emitted] [minimized] (name: main) 1 related asset
orphan modules 1.59 MiB [orphan] 246 modules
built modules 904 KiB [built]
  modules by path ./node_modules/uuid/ 5.03 KiB
    modules by path ./node_modules/uuid/*.js 4.03 KiB
      ./node_modules/uuid/index.js 120 bytes [built] [code generated]
      ./node_modules/uuid/v1.js 3.25 KiB [built] [code generated]
      ./node_modules/uuid/v4.js 680 bytes [built] [code generated]
    modules by path ./node_modules/uuid/lib/*.js 1020 bytes
      ./node_modules/uuid/lib/rng.js 246 bytes [built] [code generated]
      ./node_modules/uuid/lib/bytesToUuid.js 775 bytes [built] [code generated]
  ./src/index.js + 51 modules 899 KiB [built] [code generated]
  external "crypto" 42 bytes [built] [code generated]
webpack 5.24.4 compiled successfully in 5181 ms
```

`package.json` dependency versions
```js
"dependencies": {
  "@aws-sdk/lib-dynamodb": "^3.8.1",
  "esbuild": "^0.9.0",
  "webpack": "^5.24.4",
  "webpack-cli": "^4.5.0"
}
```

I'm wondering what is accounting for such a large different in size.

**Comment by evanw** [comment] 2021-03-12 06:54
It looks like the difference is mostly due to Webpack defaulting to selecting the `module` field in `package.json` vs. esbuild defaulting to selecting the `main` field in `package.json`. The `module` field improves tree shaking (dead code removal) vs. the `main` field. I did this because given a choice about which file to import for a given package, esbuild tries to prioritize getting a working bundle instead of getting the smallest bundle. Some package authors unfortunately use the `module` field incorrectly and put browser-specific code in there, so esbuild defaults to the `main` field with `--platform=node` for maximum compatibility. But if you know your packages have valid `module` fields, you can tell esbuild to prefer `module` over `main` by passing `--main-fields=module,main`. More detail is here: https://esbuild.github.io/api/#main-fields.

**Comment by kzc** [comment] 2021-03-12 15:05
*very* off topic... webpack emits its size units using [IEC nomenclature](https://en.wikipedia.org/wiki/Byte#Multiple-byte_units) for kibibyte (KiB):
```
> npx webpack --mode=production --target=node ./index.js
asset main.js 134 KiB [emitted] [minimized] (name: main) 1 related asset
```
and esbuild uses "kb":
```
$ esbuild index.js --bundle --minify --platform=node --main-fields=module,main --target=node14 --outfile=dist.js

  dist.js  146.7kb
```
Even though I suspected that an old school hacker would likely use a power of 2 nomenclature, I had to use `ls -l` to verify that `kb` in this case meant 1024 bytes - as opposed to 1000. Just to throw another nomenclature into the mix, the Unix command line shells use the `K` suffix to denote 1024 bytes with `ls -lh`.

While Metric uses kB for 1000 bytes, and JEDEC using KB for 1024 bytes, MB and GB are ambiguously claimed by the two systems to mean different sizes. Which is why I suppose webpack elected to use the unambiguous although somewhat annoying IEC nomenclature.

**Comment by evanw** [comment] 2021-03-12 20:29
Yeah that whole thing is a mess. Kilobyte will always mean 1024 to me. I just can't bring myself to say kibibyte. Looks like Parcel also uses KB for 1024 bytes.

**Comment by kimsagro1** [comment] 2021-03-12 21:06
Thanks for your response @evanw, that makes sense. Feel free to close out this issue if you like.

**Comment by evanw** [comment] 2021-03-12 21:15
Sure thing. Thanks for getting back. Closing as by design.

**Closed by evanw** 2021-03-12 21:15 UTC
