### ISSUE TITLE
Top-level return cannot be used inside an ECMAScript module

### ISSUE THREAD

**Issue by elantion** [evanw/esbuild#1814] opened 2021-11-30 11:28 UTC
I am facing this error: Top-level return cannot be used inside an ECMAScript module.
And have another warning: This file is considered an ECMAScript module because of the "import" keyword here.
If the typescript file without 'import' keyword, it can be build without any error.
Have I miss config something?

My typescript file may look like this:
```typescript
import { add } from 'helper';
return add(1, 1);
```

config:
```
        entryPoints: [scriptPath],
        bundle: true,
        outfile: targetFilePath,
        nodePaths: nodePaths,
        format: 'cjs',
        platform: 'node',
        tsconfig: tsconfig
```

tsconfig:
```json
{
    "compilerOptions": {
        "target": "es6",
        "module": "CommonJS",
        "noImplicitAny": true,
        "lib": ["es6", "es2016", "es2017", "dom"],
        "moduleResolution": "node"
    }
}
```

**Comment by evanw** [comment] 2021-11-30 13:21
Your code is invalid because it contains a syntax error. This is not a bug with esbuild. You should fix your syntax error.

Closing this issue as invalid.

**Closed by evanw** 2021-11-30 13:21 UTC

**Comment by elantion** [comment] 2021-12-01 01:37
For some reasons. I need to return outside of a function, that is expected. I already use `@ts-ignore`, but it seem not working.

**Comment by evanw** [comment] 2021-12-01 06:07
That's not valid syntax, so there's no option to enable it.

You can still do this with the `footer` feature: https://esbuild.github.io/api/#footer. That lets you add an arbitrary string to the end of your code. The syntax of the footer string is not validated so you can use it for whatever you want. For example, you could do `--format=iife --global-name=xyz "--footer:js=return xyz;"` to return the exports object of the entry point, or you could do `--format=iife --global-name=xyz "--footer:js=return xyz.default;"` to return the `default` export of the entry point (if you want to return a non-object). You could of course also manipulate the output of esbuild yourself even without the `footer` feature. That feature isn't necessary; it only exists for convenience.

**Comment by elantion** [comment] 2021-12-03 06:45
Thanks your solution. But it it not suitable for me, my code use `return` not always at the end of the file. And if I maniplulate the output will do too much work to worthy. So, I fall back to version 0.11.5, it seem working great till now.

Top level returns may very common in real worl. For example, cloud service script, bash script, enterprise middleware and so on. You can check these conversations:
https://github.com/babel/babel/pull/3503
https://github.com/inspect-js/node-deep-equal/issues/78

Hoping esbuild can support this feature in somedays. Cheers mate.

**Comment by evanw** [comment] 2021-12-03 06:58
https://github.com/inspect-js/node-deep-equal/issues/78 is about CommonJS modules, not ES modules. See specifically https://github.com/inspect-js/node-deep-equal/issues/78#issuecomment-566366886. Top-level return in CommonJS modules is valid, is supported by esbuild, and works fine. But top-level return in ES modules is not valid, and so does not work in esbuild. It also doesn't work in node or in any browser. If you still want to use top-level return in esbuild, you can put it inside a CommonJS module, in which case it will work. But that means you'll have to use `require()` instead of `import`.
