### ISSUE TITLE
Sourcemap paths being appended when composing sourcemaps

### ISSUE THREAD

**Issue by rprend** [evanw/esbuild#3553] opened 2023-12-18 02:29 UTC
Setup: esbuild.build() using stdin specifying the `resolveDir` and `contents`. 

The resolved dir is `root/lib`, and all of the files in that directory are .js files with `sourceMappingURL` comments at the bottom (and corresponding `.map` files at the same path. The input to esbuild is the output of gulp compilation. The input files to gulp are in `root/src`. When bundling these lib files with esbuild, the outputted stdin.js.map composes the bundled sourcemap with the existing sourcemaps, getting the correct line and column numbers for the original source in `root/src`. However the `source` pathname is appended rather than replaced by the original source path.

So for example if i check the sourcemap for the line `console.log('foo')` in the bundle, I get the correct row/column for `console.log('foo')` in `root/src/path/to/file.ts`. However, the `.source` field in that mapping looks like `root/lib/path/to/path/to/file.ts`. this is a nonexistent file. We have the `root/lib/path/to/file.js` compiled gulp output, and the `root/src/path/to/file.ts` original source output. Every mapping is constructed like this-- it seems to be "lib dir, plus folder names duplicated, plus the correct original source file".

Is there any known issue of sourcemap compositions messing up the source path? The mappings themselves are correctly composed to the original line/column; this seems a bug in the equivalent process for the source path.

**Comment by evanw** [comment] 2023-12-18 18:20
You didn't provide a way to reproduce the issue. The instructions you deleted when making this issue said this:

> When reporting a bug or requesting a feature, please do the following:
>
> * Provide a way to reproduce the issue. The best way to do this is to demonstrate the issue on the playground (https://esbuild.github.io/try/) and paste the URL here. A link to a minimal code sample with instructions for how to reproduce the issue may also work. Issues without a way to reproduce them may be closed.

**Comment by evanw** [comment] 2024-01-04 18:04
I'm closing this issue because a way to reproduce the issue was not provided.

**Closed by evanw** 2024-01-04 18:04 UTC
Labels: unactionable
