### ISSUE TITLE
CentOS installation failed. I don't know what the problem is

### ISSUE THREAD

**Issue by Likunone** [evanw/esbuild#1005] opened 2021-03-19 03:59 UTC
```
> esbuild@0.9.3 postinstall /The path/node_modules/esbuild
> node install.js

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '/The path/node_modules/esbuild/install.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! esbuild@0.9.3 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the esbuild@0.9.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by evanw** [comment] 2021-03-19 04:06
Unfortunately I'm not sure what the problem is either, sorry. I have never used CentOS and don't have an install available. I also have never seen that particular installation error.

It could potentially be useful in the future for you to list the versions of node and npm that you are using (`node --version` and `npm --version`) in case someone else also has this problem in the future and a pattern emerges.

**Comment by Likunone** [comment] 2021-03-19 04:10
node v12.16.1
npm v6.13.4

**Comment by Likunone** [comment] 2021-03-19 04:12
> Unfortunately I'm not sure what the problem is either, sorry. I have never used CentOS and don't have an install available. I also have never seen that particular installation error.
> 
> It could potentially be useful in the future for you to list the versions of node and npm that you are using (`node --version` and `npm --version`) in case someone else also has this problem in the future and a pattern emerges.

node v14.15.0
npm v6.14.8

**Comment by Likunone** [comment] 2021-03-19 04:13
![image](https://user-images.githubusercontent.com/15193414/111730468-75f9f500-88ac-11eb-927f-8db0e9234a0a.png)

**Comment by antimatter15** [comment] 2021-03-19 05:37
This looks like a permission error, you could probably run `npm i -g esbuild` with sudo, or try to install esbuild without the `-g` flag.

**Comment by Zuckjet** [comment] 2021-03-19 05:46
As **antimatter15**  pointed, it's not relevant with esbuild. If you still want to install esbuild globally without sudo permission, see [npm  docs](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally)

**Comment by Likunone** [comment] 2021-03-19 06:03
@antimatter15 @Zuckjet 
Sorry I updated the screenshot

**Comment by evanw** [comment] 2021-03-19 06:45
I can't think of anything actionable to do from this information. The `install.js` file is part of the `esbuild` package so if it's not there, it seems to me like that means something is wrong with npm on your machine instead of with the `esbuild` package.

**Comment by Zuckjet** [comment] 2021-03-19 06:47
@Likunone Can't reproduce your problem. First check you are on the root path of your project(current folder has a package.json), then  you can try this steps:
`rm -rf node_modules package-lock.json && npm install && npm start`
If still not working, can you try to create your project in a different folder, such as `cd ~ && create your projcet && cd project folder && npm i`

**Comment by Likunone** [comment] 2021-03-19 07:30
Thank you. After upgrading NPM, it will be OK

**Closed** 2021-03-19 07:30 UTC
