### ISSUE TITLE
Question error [ERROR] Two output files share the same path but have different contents

### ISSUE THREAD

**Issue by ips219** [evanw/esbuild#3763] opened 2024-05-12 19:38 UTC
I am trying to upgrade to Angular 17 with Native Federation which is using esbuild, and I'm having an issue building the application with esbuild.

Attached the console.log with the "**[ERROR] Two output files share the same path but have different contents**" error
[error.txt](https://github.com/evanw/esbuild/files/15287404/error.txt)

` 
VRB!      at failureErrorWithLog (C:\data\repositorios\AUBAY\aubay-gestion\aubay-gestion-web\mfe-aubay-gestion\node_modules\.pnpm\esbuild@0.19.12\node_modules\esbuild\lib\main.js:1651:15)    
 VRB!      at C:\data\repositorios\AUBAY\aubay-gestion\aubay-gestion-web\mfe-aubay-gestion\node_modules\.pnpm\esbuild@0.19.12\node_modules\esbuild\lib\main.js:1059:25
 VRB!      at C:\data\repositorios\AUBAY\aubay-gestion\aubay-gestion-web\mfe-aubay-gestion\node_modules\.pnpm\esbuild@0.19.12\node_modules\esbuild\lib\main.js:1527:9
 VRB!      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
`

According to the exception thrown, it seems that there is some kind of issue with fullcalendar library.
![image](https://github.com/evanw/esbuild/assets/3368591/e35f116b-21bc-4e4b-9757-e66908196330)

May anybody clarify me if the exception means a compatibility issue of fullcalendar modules with esbuild or address me how can I debug this issue?

Thanks and Best regards.

**Comment by evanw** [comment] 2024-05-12 19:45
Some thoughts:

* Angular adds a lot of custom tooling around esbuild, so this is probably a better question for Angular instead of esbuild
* You didn't follow the issue reporting instructions (there is no way to reproduce your issue) so I can't help you

Marking this report as `unactionable` because the issue reporting instructions weren't followed.

**Comment by ips219** [comment] 2024-05-13 06:32
Thank you for your support Evan, I'll do as you said.

I thought that given the specific of the error that it may be the expected behaviour for some incompatible conditions.

BR

**Comment by evanw** [comment] 2024-06-08 03:05
Closing this issue as it has been `unactionable` without a follow-up reply.

**Closed by evanw** 2024-06-08 03:05 UTC
Labels: unactionable
