### ISSUE TITLE
Transforming const to the configured target environment ("es5") is not 

### ISSUE THREAD

**Issue by 3400442579** [evanw/esbuild#1380] opened 2021-06-17 08:28 UTC
"esbuild Scripts/pages/compress.js --bundle --format=esm --outfile=wwwroot/pages/compress.js --target=es5"

 "esbuild": "0.12.9"

node_modules/sweetalert2/dist/sweetalert2.js:11:2: error: Transforming const to the configured target environment ("es5") is not 
supported yet
    11 │   const DismissReason = Object.freeze({
       ╵   ~~~~~

**Comment by evanw** [comment] 2021-06-17 08:36
The error message is correct. Transforming `const` to ES5 is not supported yet. Closing as a duplicate of #297.

**Closed by evanw** 2021-06-17 08:36 UTC
