### ISSUE TITLE
Handling of `browser` field in package.json

### ISSUE THREAD

**Issue by yongjun21** [evanw/esbuild#1124] opened 2021-04-07 14:55 UTC
When a module specified false in package.json `browser` field, according to [spec](https://github.com/defunctzombie/package-browser-field-spec#ignore-a-module), an empty object should be substituted.

Say
```js
// package.json
{
  "browser": {
    "./path/to/some_module.js": false
  }
}
```

```js
// some_comsumer.js

import * as node from './some_module'
```

The name `node` should be assigned an empty object. However the name `node` turned out to be undefined. As the name is subsequently re-exported, this cause a `Uncaught SyntaxError: local binding for export 'node' not found` error to be thrown.

Here is a simple repro: https://github.com/yongjun21/vite-bug-repro

This issue is first raised as a Vite issue: https://github.com/vitejs/vite/issues/2870. However, I believe the bug is likely to be on esbuild side.

**Comment by evanw** [comment] 2021-04-09 08:12
Thanks for the report.

Note to self: it looks like the way to reproduce this without all of the Vite code in the way is this:

```
$ esbuild --bundle vue @loaders.gl/core @loaders.gl/images --outdir=out --define:process.env.NODE_ENV=\"production\" --tree-shaking=ignore-annotations --format=esm --splitting --out-extension:.js=.mjs

$ node node out/\@loaders.gl/core/dist/esm/index.mjs
out/chunk-LMUDM5RF.mjs:1795
  node3 as node,
  ^^^^^^^^^^^^^

SyntaxError: Export 'node3' is not defined in module
```

**Comment by evanw** [comment] 2021-04-10 22:45
It looks like this problem has already been fixed. The repro uses esbuild version 0.9.7 but esbuild is now on version 0.11.7. This problem first stops happening in version 0.10.1, so that's likely when it was fixed. I'm going to close this issue since there is nothing to fix. You need to update esbuild to fix this issue.

**Closed by evanw** 2021-04-10 22:45 UTC
