### ISSUE TITLE
JSX automatic transform imports 'react' with `createElement`

### ISSUE THREAD

**Issue by rdzar** [evanw/esbuild#3696] opened 2024-03-13 21:01 UTC
**The problem**
ESBuild suddenly includes the following code:
```js
import { createElement } from "react";
```

while using `--jsx=automatic`, assuming JSX output.

**The reason**
It seems using a custom spread **with a key**, causes it to break and use old 'createElement' logic.
```jsx
<div {...customProps} key={field.field}>
```

If you replace this with
```jsx
<div key={field.field}>
```

it will work, but, well, I kinda need the spread ;) The demo is simplified.

**Playground**
https://esbuild.github.io/try/#YgAwLjIwLjEAdGVzdC5qc3ggLS1qc3g9YXV0b21hdGljAAB0ZXN0LmpzeABleHBvcnQgZGVmYXVsdCBmdW5jdGlvbiBUZXN0Q29tcG9uZW50IChwcm9wcykgewogIGZ1bmN0aW9uIGVhY2hGaWVsZCAoZmllbGQpIHsKICAgIGNvbnN0IGN1c3RvbVByb3BzID0gewogICAgICAnZmllbGQtZGF0YSc6IGZpZWxkLmZpZWxkCiAgICB9OwogICAgcmV0dXJuICgKICAgICAgPGRpdiB7Li4uY3VzdG9tUHJvcHN9IGtleT17ZmllbGQuZmllbGR9PgogICAgICAgIDxsYWJlbD57ZmllbGQuZmllbGR9PC9sYWJlbD4KICAgICAgPC9kaXY+CiAgICApOwogIH0KCiAgcmV0dXJuICgKICAgIDxkaXY+CiAgICAgIHtwcm9wcy5maWVsZHMubWFwKGVhY2hGaWVsZCl9CiAgICA8L2Rpdj4KICApCn0

**What I expected**
I expected the build to return all `jsx/jsxs` elements.

I think this is a bug, but I'm not totally sure. As the docs say:

> esbuild's [JSX](https://esbuild.github.io/api/#jsx) transform to automatic, which generates import statements for you

But am I wrong, assuming JSX build, should produce JSX/JSXS calls?

**Comment by evanw** [comment] 2024-03-13 21:19
This is not a bug. You have chosen to use the new React-specific JSX transform instead of the original general-purpose JSX transform, and it has a bunch of React-specific stuff in it including this weird edge case that you discovered. [TypeScript](https://www.typescriptlang.org/play?target=99&jsx=4#code/KYDwDg9gTgLgBAE2AMwIYFcA29noHYDGMAlhHnACrADOMAwhALaR7B7wAUYUEY1AlHADeAKDhxchEmTjBUBABYAxYsEwI4HZKvWDR48QTK04BdLSYAFHnzgBeYWIPiA5NrUIAtAlQxULgC4JHQQAOnd1J3EAXwBuKLgoYBh0KHIOBPEAHgRiADdhUKKzC0ZrXmpouABrYABPOyEIsObogD5MgyzMVAAjNTamkPCQ6KyAeh7+zA7nbPHcvNmDfniYkScklLTNBJz85echbgqRj2pQxlQwDjlFFQ9+aL2Fg6d+EWigA) and [Babel](https://babel.dev/repl#?browsers=chrome%20110&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=KYDwDg9gTgLgBAE2AMwIYFcA29noHYDGMAlhHnACrADOMAwhALaR7B7wAUYUEY1AlHADeAKDhxchEmTjBUBABYAxYsEwI4HZKvWDR48QTK04BdLSYAFHnzgBeYWIPiA5NrUIAtAlQxULgC4JHQQAOnd1J3EAXwBuKLgoYBh0KHIOBPEAHgRiADdhUKKzC0ZrXmpouABrYABPOyEIsObogD5MgyzMVAAjNTamkPCQ6KyAeh7-zA7nbPHcvNmDfniYkScklLTNBJz85echbgqRj2pQxlQwDjlFFQ9-aL2Fg6d-EWigA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-3%2Ctypescript&prettier=false&targets=&version=7.24.0&externalPlugins=%40babel%2Fplugin-syntax-explicit-resource-management%407.20.0&assumptions=%7B%7D) also do the exact same thing as esbuild here, so esbuild is correct.

React's [blog post about their new transform](https://legacy.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html) contains a note about this edge case:

> If you’re a library author and you are implementing the `/jsx-runtime` entry point for your library, keep in mind that [there is a case](https://github.com/facebook/react/issues/20031#issuecomment-710346866) in which even the new transform has to fall back to `createElement` for backwards compatibility. In that case, it will auto-import `createElement` directly from the _root_ entry point specified by `importSource`.

This edge case is also mentioned in [esbuild's documentation about the JSX automatic transform](https://esbuild.github.io/api/#jsx-import-source):

> The `createElement` import is used regardless of the JSX dev mode when an element has a prop spread followed by a `key` prop, which looks like this:
>
> ```jsx
> return <div {...props} key={key} />
> ```

I'm closing this issue because this behavior is intentional, and is already called out in esbuild's documentation. I agree that it's weird and unfortunate but the React team designed their JSX transform so they get to decide how it works.

**Closed by evanw** 2024-03-13 21:19 UTC
