### ISSUE TITLE
stdin not supports onLoad && onResolve plugin

### ISSUE THREAD

**Issue by hardfist** [evanw/esbuild#720] opened 2021-01-28 03:24 UTC
It seems that stdin contents isn't handled by onLoad && onResolve plugin, and it seems doesn't support namespace too

**Comment by zaydek** [comment] 2021-01-28 03:45
@hardfist I’d recommend putting together some reproducible code snippets -- whatever you tried -- to share.

**Comment by hardfist** [comment] 2021-01-28 06:17
build.js
```js
 const result = await build({
    // entryPoints: [path.join(__dirname, 'src/index.js')],  // resolve and load plugin are called
    stdin: { // resolve and load plugin are not called
      contents: 'export default 42',
      loader: 'js',
      resolveDir: '',
      sourcefile: 'test.js',
    },
    bundle: true,
    format: 'esm',
    splitting: true,
    outdir: 'dist',
    write: false,
    plugins: [
      {
        name: 'esbuild',
        setup(build) {
          build.onResolve({ filter: /.*/ }, (args) => {
            console.log('load args:', args);
          });
          build.onLoad({ filter: /.*/ }, (args) => {
            console.log('resolve args2:', args);
          });
        },
      },
    ],
  });
```
src/index.js
``` title=src/index.js
export default 42
```

**Comment by evanw** [comment] 2021-01-28 09:40
If I'm understanding your issue correctly, this is by design. The stdin API is a convenience API and has limited features. If you need the behavior I think you're asking for, you should be able to implement it yourself:

```js
const result = await build({
  entryPoints: ['<stdin>'],
  bundle: true,
  format: 'esm',
  splitting: true,
  outdir: 'dist',
  write: false,
  plugins: [
    {
      name: 'esbuild',
      setup(build) {
        build.onResolve({ filter: /^<stdin>$/ }, (args) => {
          return { path: 'test.js', namespace: 'stdin' };
        });
        build.onLoad({ filter: /.*/, namespace: 'stdin' }, (args) => {
          return { contents: 'export default 42', loader: 'js' };
        });
      },
    },
  ],
});
```

**Comment by hardfist** [comment] 2021-01-29 04:09
> If I'm understanding your issue correctly, this is by design. The stdin API is a convenience API and has limited features. If you need the behavior I think you're asking for, you should be able to implement it yourself:
> 
> ```js
> const result = await build({
>   entryPoints: ['<stdin>'],
>   bundle: true,
>   format: 'esm',
>   splitting: true,
>   outdir: 'dist',
>   write: false,
>   plugins: [
>     {
>       name: 'esbuild',
>       setup(build) {
>         build.onResolve({ filter: /^<stdin>$/ }, (args) => {
>           return { path: 'test.js', namespace: 'stdin' };
>         });
>         build.onLoad({ filter: /.*/, namespace: 'stdin' }, (args) => {
>           return { contents: 'export default 42', loader: 'js' };
>         });
>       },
>     },
>   ],
> });
> ```

yes, It works , but kind of awkard, If it's by design, then I think it's ok。

**Comment by evanw** [comment] 2021-05-14 02:47
Closing since this is by design, and there is a workaround.

**Closed by evanw** 2021-05-14 02:47 UTC
