### ISSUE TITLE
define doesn't like values with two dots

### ISSUE THREAD

**Issue by fedgrant** [evanw/esbuild#1855] opened 2021-12-14 21:49 UTC
As part of my build script I pull in my package.json and bump in the version number into my bundled code through the define property. It looks like define doesn't like when the version has two `.` in it.

```
{ "version": "1.1" } // works
{ "version": "1.1.1" } // doesn't work
```

sample from the build script
```
const pj = JSON.parse(fs.readFileSync('./package.json'))

esbuild
  .build({
    ...
    define: {
      PLAYER_VERSION: pj.version,
    },
  })
  .catch(() => process.exit(1))
  ```

Am I doing something wrong?

**Comment by fedgrant** [comment] 2021-12-14 21:55
If I were to guess, I'd say the lexer thinks that the version is a number because of the first period and thinks the second period is incorrect. But I haven't been able to track down where that is happening.

**Comment by maisano** [comment] 2021-12-14 22:05
esbuild will treat the value here as an identifier. If you want to inline the version as a string, you'll need to cast it as such, e.g. ```js
define: {
  PLAYER_VERSION: JSON.stringify(pj.version),
}
```

**Comment by hyrious** [comment] 2021-12-14 22:07
The value of define should be a valid js expression wrapped in string, in which case you should write: `{ VERSION: '"1.1.1"' }`.

**Comment by evanw** [comment] 2021-12-14 23:29
Yes, that's correct. The value of a define is a string containing JSON. So `PLAYER_VERSION: '1.1'` is a number and `PLAYER_VERSION: '"1.1"'` is a string. This is in the docs: https://esbuild.github.io/api/#define. Closing as working as intended.

**Closed by evanw** 2021-12-14 23:29 UTC

**Comment by fedgrant** [comment] 2021-12-15 02:22
Thank you.
