### ISSUE TITLE
Which stream does esbuild write to?

### ISSUE THREAD

**Issue by mrgrain** [evanw/esbuild#2466] opened 2022-08-13 18:54 UTC
This is mostly a question of understanding. I'm developing a library that integrates with esbuild. I came across this when I was attempting to unit test that invalid code will result in some error output. Basically there seems to be no way to capture esbuild's messages at the moment.

I'm really just curious **if that's expected, what's the background to it and if there's any known way to capture the output.**
As I mentioned above, this would purely be QoL, nothing else.

Here's a minimal reproduction, highlighting that `process.stderr` is not used.
```js
process.stderr.end();
const esbuild = require('esbuild');

try {
    esbuild.transformSync('let : d ===== 1', {
        logLevel: 'warning'
    });
} catch (_) {
}
```

**What did I expect to happen?**
An error `Error [ERR_STREAM_WRITE_AFTER_END]: write after end` would be thrown, as when I would do:
```js
process.stderr.end();
console.error('throw');
```
Note that the same applies to `process.stdout`, but as mentioned elsewhere esbuild should write messages to STDERR.

**What does happen?**
esbuild still happily prints the output. Piping on the shell DOES work.
```
➜   node esbuild.js
✘ [ERROR] Unexpected "=="

    <stdin>:1:11:
      1 │ let : d ===== 1
        ╵            ~~
```

**Comment by evanw** [comment] 2022-08-13 19:25
Logging is written to stderr. But it's written to Unix file descriptor 2 in the child process, not specifically to `process.stderr`, which is probably why this isn't working the way you want it to. This sounds like expected behavior to me.

**Comment by evanw** [comment] 2022-08-13 21:54
I'm closing this because the question has been answered, and this is not the way that the API is intended to be used. If you want to print the log messages you should use the [`formatMessages`](https://github.com/evanw/esbuild/blob/e6fa7393054316d0acd233c4325691b21ec60815/lib/shared/types.ts#L504-L512) API instead.

**Closed by evanw** 2022-08-13 21:54 UTC
