### ISSUE TITLE
middle-router: require is undefined for eventemitter3

### ISSUE THREAD

**Issue by jimsimon** [evanw/esbuild#894] opened 2021-02-27 06:02 UTC
Hello, I'm trying to use the following import:
```typescript
import * as Router from 'middle-router';
```
But at runtime I get the following error:
![image](https://user-images.githubusercontent.com/156367/109377090-038e8a00-7897-11eb-9c4f-b5af00a03501.png)
![image](https://user-images.githubusercontent.com/156367/109377153-74ce3d00-7897-11eb-90c5-d4fdcf1c595b.png)

Any idea why require would be undefined here?

Here's my tsconfig.json for reference in case it matters:
```json
{
  "compilerOptions": {
    "declaration": true,
    "noImplicitAny": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "allowJs": true,
    "esModuleInterop": true,
    "target": "ES2020",
    "sourceMap": true,
    "baseUrl": "./",
    "module": "ES2020",
    "moduleResolution": "Node",
  }
}
```

**Comment by evanw** [comment] 2021-02-27 07:37
Is this problem related to esbuild? You haven't provided any information that indicates whether you are using esbuild or how you are using it.

**Comment by jimsimon** [comment] 2021-02-27 07:55
Sorry for not being clear, I'm using esbuild via https://modern-web.dev/guides/dev-server/getting-started/.

**Comment by evanw** [comment] 2021-02-27 08:17
Ah ok, thanks for the info. This problem is not related to esbuild then. According to [their documentation](https://modern-web.dev/docs/dev-server/plugins/esbuild/#single-file-transforms), esbuild is only used for TSX/JSX/JSON-to-JS but otherwise doesn't have any effect on your code.

The problem is that you are trying to use code that calls `require()` in the browser, and that doesn't work because `require` is a node-specific API that doesn't exist in the browser. Looks like there is documentation about how to use CommonJS modules with this software here: https://modern-web.dev/guides/going-buildless/es-modules/#commonjs-modules. If you are having additional problems you should ask for help from them.

Closing this issue since this problem is not related to esbuild.

**Closed by evanw** 2021-02-27 08:17 UTC

**Comment by jimsimon** [comment] 2021-02-27 08:21
Ah I saw the docs for esbuild say it supports CommonJS, is that only for output?

**Comment by evanw** [comment] 2021-02-27 08:42
It’s for bundling (esbuild is primarily a bundler) but the tool you’re using isn’t using esbuild’s bundling feature.

**Comment by jimsimon** [comment] 2021-02-27 08:43
Ah okay, thanks for the clarification!
