### ISSUE TITLE
Source maps issue (Chrome +102 - Esbuild - PIXI.js V6)

### ISSUE THREAD

**Issue by oskfan** [evanw/esbuild#2295] opened 2022-06-03 08:16 UTC
Hi!

When building a project using PIXI.js V6 with esbuild + sourcemaps and running with dev tools in Chrome +102:
There seems to be some mismatch or mapping error when using esbuild with sourcemaps (linked or inline gives same issue) where the sourcemap is parsed incorrectly by Chrome/Chromium running any version at 102 or higher. 
Stack traces are off and break points are mismatching with actual source-code.
Earlier Chrome versions (-101) interpret it just fine, and other browsers like Firefox and Edge also parse it fine.

I've shared a minimum reproducible repo with you @evanw called **esbuild-pixijsv6-issue** (clone from https://github.com/GuillaumeDesforges/pixijs-typescript-starter but upgraded PIXI and a few other modules) in case you want to take a look. 
As a comparison, building using webpack creates a working sourcemap for any browser.

Also, great work on esbuild. We dropped our jaws seeing the difference in performance when testing it for our projects. Stellar work!

Regards,

**Comment by vforsh** [comment] 2022-06-03 12:09
Our team experience the very same problem with a very similar setup (PIXI.js V6 with esbuild + sourcemaps)

Can confirm all that @oskfan has mentioned.

> As a comparison, building using webpack creates a working sourcemap for any browser.
> Earlier Chrome versions (-101) interpret it just fine, and other browsers like Firefox and Edge also parse it fine.

**Comment by smival** [comment] 2022-06-03 12:24
same issue

**Comment by evanw** [comment] 2022-06-03 16:20
This is clearly a regression in Chrome so I'm going to let the Chrome team investigate this instead of spending the time to investigate this myself. Here's the relevant Chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1329997. You can follow that bug for updates.

**Comment by evanw** [comment] 2022-06-04 22:32
Closing this because this is not a problem with esbuild.

**Closed by evanw** 2022-06-04 22:32 UTC

**Comment by oskfan** [comment] 2022-06-07 06:45
@evanw Thanks! Makes sense since they probably have a whole team dedicated for that. 
Regards,

**Comment by Pyrolistical** [comment] 2022-08-26 03:12
Looks like it will be included in Chrome 105 which has a public release Aug 30
