### ISSUE TITLE
Esbuild not able to minify properly due to `\n` character

### ISSUE THREAD

**Issue by pffigueiredo** [evanw/esbuild#3018] opened 2023-03-24 17:20 UTC
**What is the current behavior?**

Right now, when trying to rely on `esbuild` to minify some code with CSS-in-JS sort of syntax that has `\n` characters within, it seems to break the minification process and result in a non-minified version of the file :grimacing: 

**What is the expected behavior?**

Expected the file to actually be minified correctly like with `Terser` that leaves the `\n` character intact or even if replacing it with a "line-break", it shouldn't result in a non-minified version of the file.

**Example**

[Repo with a reproducible example](https://github.com/pffigueiredo/esbuild-bug-minify)

INPUT :point_down: 
![image](https://user-images.githubusercontent.com/24414890/227596093-02dde5f1-e082-48a7-bfd4-97631de74139.png)

OUTPUT :point_down: 
![image](https://user-images.githubusercontent.com/24414890/227595750-0e90c51d-f0f2-4eb5-9ad6-a0f1b2fca07c.png)

**Comment by evanw** [comment] 2023-03-24 18:04
You have asked esbuild to minify your code. Minification means to make your code smaller. The character sequence `\n` is two bytes while a newline character is one byte. So esbuild is just doing what you told it to do, and this is not a bug. Closing as invalid.

**Closed by evanw** 2023-03-24 18:04 UTC

**Comment by pffigueiredo** [comment] 2023-03-24 18:10
Hey @evanw I don't think you read the full disclosure, I understand and I actually did read `esbuild` docs on that particularity, the thing is, when it finds `\n` in that place, it's breaking the whole minifcation process.

The files aren't actually getting minified after that point (you can see that looking at the screenshot) and so, the file will be much larger and NOT minified.

It's not really about the `\n`, it's just some bug that happens in this specific scenario :+1:

**Comment by evanw** [comment] 2023-03-24 18:17
This code is 29 bytes long:

```js
var baseStyles = "a\nb\nc\n";
```

This code is 26 bytes long:

```js
var baseStyles = `a
b
c
`;
```

Therefore the second code is a minified version of the first code. To minify code doesn't mean "to put on one line". It instead means "to use as few bytes as possible".

**Comment by evanw** [comment] 2023-03-24 19:00
I added a FAQ entry about this because it's a somewhat-frequently asked question: https://esbuild.github.io/faq/#minified-newlines

**Comment by pffigueiredo** [comment] 2023-03-24 19:05
Well, you are totally right on this (as expected), I stripped down everything but the `CSS` and the file is indeed smaller in the `esbuild` minified version!

However, there is something weird that's causing a file to be 12MB instead of 2MB when minified with `esbuild` vs `Terser`. I'll try to narrow it down and if I can, create another issue.

Sorry about this one and thanks for the good work :muscle:

**Comment by pffigueiredo** [comment] 2023-03-24 20:04
After narrowing down the problem a little further, I noticed that the problem is in fact related to tree-shaking when using `esbuild` as a `webpack` loader. 

Found this [issue](https://github.com/esbuild-kit/esbuild-loader/issues/178), which basically says that nothing can be done in this regard :cry:
