### ISSUE TITLE
splitting issue: only export `default` at `dynamic import` interop with `umd`

### ISSUE THREAD

**Issue by underfin** [evanw/esbuild#1847] opened 2021-12-13 17:12 UTC
### Expected

I expected the consistent behavior for dynamic import interop with `umd` either splitting is enable or disable.

### Actual

On splitting is enable, only export `default` at `dynamic import` interop with `umd`.

### Reproduction

https://github.com/underfin/esbuild-tree-shaking

#### step to Reproduct

``` shell
// disable splitting
npm run build:normal 
// invoke code. it will log "{ default: { a: 1, b: 1 }, a: [Getter], b: [Getter] }"
node output/output-normal.js

// enable splitting
npm run splitting && npm run build:splitting
// invoke code. it will log "{ default: [Getter] }"
// it should also direct export `a` and `b`
node output/output-splitting.js
```

**Comment by evanw** [comment] 2021-12-13 20:51
The problem is that `a` and `b` are run-time exports and the ESM output format doesn't support run-time exports. When you do `--format=esm` in the middle step, the run-time exports are stripped away. This is not a problem with esbuild. This is a fundamental limitation of the ESM format itself.

**Comment by underfin** [comment] 2021-12-14 03:41
Yeah, i get it. Can it be fixed with esbuild support spliiting for iife? It will not generate esm in the middle step. Hope get some advice, thanks a lot :)

**Comment by evanw** [comment] 2021-12-14 04:04
Yes, this issue should be fixed once esbuild supports splitting for iife. The tracking issue for that is #16.

**Closed** 2021-12-14 07:39 UTC
