### ISSUE TITLE
Support tsconfigRaw in build

### ISSUE THREAD

**Issue by hardfist** [evanw/esbuild#943] opened 2021-03-10 10:13 UTC
since esbuild only follows a subset of typescript config, it may help to list the supported typescript compiler options like what @babel/plugin-transform-typescript does,  https://babeljs.io/docs/en/babel-plugin-transform-typescript#typescript-compiler-options,
and it seems that `tsconfigRaw` only supports in transform, why not supports it in build ?

**Comment by evanw** [comment] 2021-03-10 10:51
I think this is a duplicate of #923. I'm keeping that issue open until I document the supported `tsconfig.json` options.

**Comment by hardfist** [comment] 2021-03-10 11:37
will you support rawtsconfig in build？

**Comment by hardfist** [comment] 2021-11-18 08:35
@evanw  we want to fully control what user set in tsconfig.json(like what babel does when babelrc set to false https://babeljs.io/docs/en/options#babelrc), are you going to support this feature?

**Comment by evanw** [comment] 2021-11-18 14:25
Ah set of supported `tsconfig.json` features has been documented for a while now: https://esbuild.github.io/content-types/#tsconfig-json. Sorry I didn’t update this issue. 

For the build API, you can use the `tsconfig` option instead of `tsconfigRaw` option and write the content to a file.

**Comment by hardfist** [comment] 2021-11-18 14:36
Why not `build` also supports `tsconfigRaw`, pass an file path to build may be a problem for browser environment  which lacks fs support

**Comment by djgrant** [comment] 2023-01-25 15:37
@hardfist I would also like this feature but resolving baseUrl/paths needs a filesystem. During the resolution stage, esbuild is interacting with the filesystem to determine how import paths should be resolved.

For example, given a path mapping `paths: { "~/*": ["src/*", "src/generated/*"] }`, there is no way to determine whether to use the first path or the fallback path to construct the resolved path without inspecting the file system.

@evanw Looking through the issues there seems to be interest for resolving virtual modules by people using the WASM version of esbuild. It's fairly painful re-implementing and maintaining tsconfig baseUrl/path resolution and ESM/CJS module resolution from scratch within plugins. Is there any possibility of piggy-backing on esbuild's built-in resolution mechanics? 

I suspect the answer is no, but, for example, could some callbacks be provided to proxy interactions with the filesystem? Eg:

```
{
  fileExists(lookupPath: string): boolean
  getFile(resolvedPath: string): string | Promise<string>
}
```

**Closed** 2023-06-05 06:20 UTC
Labels: tsconfig
