### ISSUE TITLE
Recharts library won't build using esbuild

### ISSUE THREAD

**Issue by treet** [evanw/esbuild#1289] opened 2021-05-15 14:47 UTC
I can't get a project using the recharts library (https://recharts.org) to build using esbuild, it works fine with webpack (react-scripts). It builds fine esbuild, but gives me an error in the browser: "react-dom.production.min.js:216 TypeError: Cannot read property 'parse' of undefined".

Here's how to reproduce:

```
git clone https://github.com/treet/esbuild-recharts.git
cd esbuild-recharts
npm install
npm run build
npm start
chrome http://127.0.01:8000/
```
Open the developer console and the error should be there. I think I've narrowed it down to some kind of problem with postcss-value-parser, which is a dependency of recharts, but the library builds fine in isolation, see the postcss-value-parser branch in the same repo (https://github.com/treet/esbuild-recharts/tree/postcss-value-parser)/

I'm at a loss how to debug this. Am I missing some kind of parameter to esbuild?

**Comment by evanw** [comment] 2021-05-15 18:15
Closing as a duplicate of #1202, which is the underlying issue.

The package `reduce-css-calc` contains code like this:

```js
if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
  exports.parser = parser;
}
```

The `require` function isn't defined in the browser, so this code causes the library to not export anything. This bug will be fixed at some point in a future version of esbuild, but for now you can work around this by doing something like `window.require = function() {}` before loading this library.

**Closed by evanw** 2021-05-15 18:15 UTC

**Comment by treet** [comment] 2021-05-15 20:43
Thanks!

For anyone else finding this issue, this works:


Create a file named **esbuild-require-workaround.js**:
```js
window.require = function() {};
```
Inject it when running esbuild:

esbuild index.jsx --bundle --minify --sourcemap --outfile=public/app.js **--inject:./esbuild-require-workaround.js**
