### ISSUE TITLE
0.14.2 and tsc 4.5.2

### ISSUE THREAD

**Issue by SnarkBoojum** [evanw/esbuild#1844] opened 2021-12-10 13:15 UTC
There's something a bit amiss with a newer typescript:
```
npm/node.ts:365:18 - error TS2345: Argument of type 'string | Buffer' is not assignable to parameter of type 'Uint8Array'.
  Type 'string' is not assignable to type 'Uint8Array'.

365   readFromStdout(stdout);
```

**Comment by evanw** [comment] 2021-12-11 19:23
I just updated to TypeScript 4.5.2 and everything is fine: https://github.com/evanw/esbuild/runs/4494274492.

**Comment by evanw** [comment] 2021-12-14 18:55
Closing because I believe this to be a non-issue. Feel free to provide more information about how to reproduce this if you believe otherwise.

**Closed by evanw** 2021-12-14 18:55 UTC
