### ISSUE TITLE
Expect json file comilped to es6 module.

### ISSUE THREAD

**Issue by underfin** [evanw/esbuild#262] opened 2020-07-16 08:51 UTC
### Feature Request
Expect json file support comilped to es6 module.

### Current behavior
The json file will compiled to common js module even passed `target: 2020` options
``` json
{
  "hello": "this is json"
}
```
``` js
module.exports = {
  hello: "this is json"
};
```

### Other Feature
It is great if it can support named export.

**Comment by evanw** [comment] 2020-07-16 19:13
It will be compiled into an ES6 module if imported using an ES6 import. Can you say more about your use case? How are you compiling this? Through the API? Through the command line? With what options?

**Comment by underfin** [comment] 2020-07-17 02:45
Sorry for not provider more info at first.
 I want to compile json to es6 modules. The use case is here https://github.com/vitejs/vite/blob/master/src/node/server/serverPluginJson.ts#L11 and use `(await startService()).transform`  api to do this.The options is `{loader: 'json',target: 'es2020'}`

**Comment by evanw** [comment] 2020-07-19 10:54
It looks like this is a duplicate of #109. This would be possible if you could pass the `format` option when transforming.

**Closed by evanw** 2020-07-19 10:54 UTC
