### ISSUE TITLE
Broken RegExp

### ISSUE THREAD

**Issue by strangerintheq** [evanw/esbuild#315] opened 2020-08-04 12:06 UTC
just found

following source code 

```
var hebrew = "\u05D0-\u05EA";
var arabic = "\u0600-\u06FF\u0750-\u077F\u08A0-\u08FF";
var rtlChars = new RegExp("[" + hebrew + arabic + "]");
```

result code:

```
  var hebrew = "א-ת";
  var arabic = "؀-ۿݐ-ݿࢠ-ࣿ";
  var rtlChars = new RegExp("[" + hebrew + arabic + "]");
```

exception in Chrome:

**Uncaught SyntaxError: Invalid regular expression: /[×-×ªØ€-Û¿Ý-Ý¿à¢ -à£¿]/: Range out of order in character class**

code:
https://github.com/CesiumGS/cesium/blob/e74fa2322817af02308b3689f2f93d61e4e7def3/Source/Scene/Label.js#L1461

**Comment by evanw** [comment] 2020-08-04 18:03
Closing as a duplicate of #70.

This happens because you are serving your HTML page as ASCII instead of as UTF-8. A quick fix for this is to add `<meta charset="utf-8">` to your HTML page. Does that work for you?

**Closed by evanw** 2020-08-04 18:03 UTC

**Comment by strangerintheq** [comment] 2020-08-04 18:42
thank you a lot
