### ISSUE TITLE
Cannot use esbuild in a GitHub action

### ISSUE THREAD

**Issue by mattiaz9** [evanw/esbuild#2591] opened 2022-10-04 08:39 UTC
In my local environment everything works just fine, but in a GitHub action it seems esbuild isn't installed correctly.
I get this error: `Cannot find package 'esbuild' imported from /home/runner/work/etherna-api-js/etherna-api-js/bundle.mjs`.

I'm not sure if I'm doing something wrong or it's a bug.

**Comment by evanw** [comment] 2022-10-04 12:58
This issue doesn’t have enough information for me to do anything with it. Marking as `unactionable`.

**Comment by mattiaz9** [comment] 2022-10-04 13:37
@evanw if it could help this is the bundler file: https://github.com/Etherna/etherna-api-js/blob/main/bundle.mjs
and this is the workflow: https://github.com/Etherna/etherna-api-js/blob/main/.github/workflows/main.yml

This is instead the error:
<img width="1009" alt="Screenshot 2022-10-04 at 15 35 20" src="https://user-images.githubusercontent.com/9766700/193833597-7ecbae4d-fbdd-443b-9c7f-b0bbaedd3e81.png">

**Comment by evanw** [comment] 2022-10-04 13:41
`ERR_MODULE_NOT_FOUND` comes from node, not esbuild. You will have to debug this for yourself to discover what the root cause is. Then if it turns out that this problem has something to do with the esbuild package itself instead of just with your environment, it could be something actionable to report here.

**Comment by evanw** [comment] 2022-10-14 13:42
Closing because this is unactionable.

**Closed by evanw** 2022-10-14 13:42 UTC
Labels: unactionable
