### ISSUE TITLE
yarn install broken from esbuild 0.13.4 onwards for yarn 1.22

### ISSUE THREAD

**Issue by martin-jarvis-vg** [evanw/esbuild#3279] opened 2023-08-02 10:02 UTC
We're getting an error when running `yarn install` on a package.json that referenced `esbuild`:

```
error /home/coder/backstage/node_modules/esbuild-loader/node_modules/esbuild: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /home/coder/backstage/node_modules/esbuild-loader/node_modules/esbuild
Output:
node:internal/errors:857
  const err = new Error(message);
              ^

Error: Command failed: /usr/bin/node /home/coder/backstage/node_modules/esbuild-loader/node_modules/esbuild/bin/esbuild --version
/home/coder/backstage/node_modules/esbuild-loader/node_modules/esbuild/bin/esbuild:1
ELF
^

SyntaxError: Invalid or unexpected token
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1084:15)
    at Module._compile (node:internal/modules/cjs/loader:1119:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47

    at checkExecSyncError (node:child_process:861:11)
    at Object.execFileSync (node:child_process:896:15)
    at validateBinaryVersion (/home/coder/backstage/node_modules/esbuild-loader/node_modules/esbuild/install.js:96:28)
    at /home/coder/backstage/node_modules/esbuild-loader/node_modules/esbuild/install.js:281:5 {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(660) [Uint8Array] [
       47, 104, 111, 109, 101,  47,  99, 111, 100, 101, 114,  47,
       98,  97,  99, 107, 115, 116,  97, 103, 101,  47, 110, 111,
      100, 101,  95, 109, 111, 100, 117, 108, 101, 115,  47, 101,
      115,  98, 117, 105, 108, 100,  45, 108, 111,  97, 100, 101,
      114,  47, 110, 111, 100, 101,  95, 109, 111, 100, 117, 108,
      101, 115,  47, 101, 115,  98, 117, 105, 108, 100,  47,  98,
      105, 110,  47, 101, 115,  98, 117, 105, 108, 100,  58,  49,
       10, 127,  69,  76,  70,   2,   1,   1,  10,  94,  10,  10,
       83, 121, 110, 116,
      ... 560 more items
    ]
  ],
  pid: 27822,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(660) [Uint8Array] [
     47, 104, 111, 109, 101,  47,  99, 111, 100, 101, 114,  47,
     98,  97,  99, 107, 115, 116,  97, 103, 101,  47, 110, 111,
    100, 101,  95, 109, 111, 100, 117, 108, 101, 115,  47, 101,
    115,  98, 117, 105, 108, 100,  45, 108, 111,  97, 100, 101,
    114,  47, 110, 111, 100, 101,  95, 109, 111, 100, 117, 108,
    101, 115,  47, 101, 115,  98, 117, 105, 108, 100,  47,  98,
    105, 110,  47, 101, 115,  98, 117, 105, 108, 100,  58,  49,
     10, 127,  69,  76,  70,   2,   1,   1,  10,  94,  10,  10,
     83, 121, 110, 116,
    ... 560 more items
  ]
```

The project is using: 
yarn: v1.22.19
node: v16.18.1

It looks like the `esbuild` binary is attempting it execute the binary as a JS file.  By investigating the script change from 0.13.3 -> 0.13.4 it looks like the install script is treating all yarn operations as if it were v2 or above - in 0.13.3 there was a check for this that has since been removed.

0.13.3:
```js
function isYarn2OrAbove() {
  const { npm_config_user_agent } = process.env;
  if (npm_config_user_agent) {
    const match = npm_config_user_agent.match(/yarn\/(\d+)/);
    if (match && match[1]) {
      return parseInt(match[1], 10) >= 2;
    }
  }
  return false;
}
```

has been changed to:
0.13.4:
```js
function isYarn() {
  const { npm_config_user_agent } = process.env;
  if (npm_config_user_agent) {
    return /\byarn\//.test(npm_config_user_agent);
  }
  return false;
}
```

**Comment by evanw** [comment] 2023-08-03 03:42
Please provide instructions for how to reproduce this. Here's what I tried:

```
$ yarn init -y
yarn init v1.22.19
warning The yes flag has been set. This will automatically answer yes to all questions, which may have security implications.
success Saved package.json
Done in 0.04s.

$ yarn add esbuild
yarn add v1.22.19
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 2 new dependencies.
info Direct dependencies
└─ esbuild@0.18.17
info All dependencies
├─ @esbuild/linux-x64@0.18.17
└─ esbuild@0.18.17
Done in 5.40s.

$ ./node_modules/.bin/esbuild --version
0.18.17
```

It seems to work fine as far as I can tell. I'm adding the `unactionable` label because there's nothing I can do with your report.

**Comment by martin-jarvis-vg** [comment] 2023-08-03 08:45
My minimum case package.json is:

```
{
    "name": "yarnesbuildtest",
    "version": "1.0.0",
    "devDependencies": {
        "esbuild": "0.18.17"
    },
    "main": "index.js",
    "license": "MIT"
}
```

`yarn install` gives:

```
yarn install v1.22.19
warning package.json: No license field
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
warning yarnesbuildtest@1.0.0: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error /home/coder/esbuild-test/node_modules/esbuild: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /home/coder/esbuild-test/node_modules/esbuild
Output:
node:internal/errors:857
  const err = new Error(message);
              ^

Error: Command failed: /usr/bin/node /home/coder/esbuild-test/node_modules/esbuild/bin/esbuild --version
/home/coder/esbuild-test/node_modules/esbuild/bin/esbuild:1
ELF
^

SyntaxError: Invalid or unexpected token
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1084:15)
    at Module._compile (node:internal/modules/cjs/loader:1119:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47

    at checkExecSyncError (node:child_process:861:11)
    at Object.execFileSync (node:child_process:896:15)
    at validateBinaryVersion (/home/coder/esbuild-test/node_modules/esbuild/install.js:98:28)
    at /home/coder/esbuild-test/node_modules/esbuild/install.js:283:5 {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(635) [Uint8Array] [
       47, 104, 111, 109, 101,  47,  99, 111, 100, 101, 114,  47,
      101, 115,  98, 117, 105, 108, 100,  45, 116, 101, 115, 116,
       47, 110, 111, 100, 101,  95, 109, 111, 100, 117, 108, 101,
      115,  47, 101, 115,  98, 117, 105, 108, 100,  47,  98, 105,
      110,  47, 101, 115,  98, 117, 105, 108, 100,  58,  49,  10,
      127,  69,  76,  70,   2,   1,   1,  10,  94,  10,  10,  83,
      121, 110, 116,  97, 120,  69, 114, 114, 111, 114,  58,  32,
       73, 110, 118,  97, 108, 105, 100,  32, 111, 114,  32, 117,
      110, 101, 120, 112,
      ... 535 more items
    ]
  ],
  pid: 7992,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(635) [Uint8Array] [
     47, 104, 111, 109, 101,  47,  99, 111, 100, 101, 114,  47,
    101, 115,  98, 117, 105, 108, 100,  45, 116, 101, 115, 116,
     47, 110, 111, 100, 101,  95, 109, 111, 100, 117, 108, 101,
    115,  47, 101, 115,  98, 117, 105, 108, 100,  47,  98, 105,
    110,  47, 101, 115,  98, 117, 105, 108, 100,  58,  49,  10,
    127,  69,  76,  70,   2,   1,   1,  10,  94,  10,  10,  83,
    121, 110, 116,  97, 120,  69, 114, 114, 111, 114,  58,  32,
     73, 110, 118,  97, 108, 105, 100,  32, 111, 114,  32, 117,
    110, 101, 120, 112,
    ... 535 more items
  ]
}
```
Starting from nothing:
```
[coder@bazaar ~/esbuild-test (master)] $ yarn init -y
yarn init v1.22.19
warning The yes flag has been set. This will automatically answer yes to all questions, which may have security implications.
success Saved package.json
Done in 0.04s.
[coder@bazaar ~/esbuild-test (master)] $ yarn add esbuild
yarn add v1.22.19
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error /home/coder/esbuild-test/node_modules/esbuild: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /home/coder/esbuild-test/node_modules/esbuild
Output:
node:internal/errors:857
  const err = new Error(message);
              ^

Error: Command failed: /usr/bin/node /home/coder/esbuild-test/node_modules/esbuild/bin/esbuild --version
/home/coder/esbuild-test/node_modules/esbuild/bin/esbuild:1
ELF
^

SyntaxError: Invalid or unexpected token
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1084:15)
    at Module._compile (node:internal/modules/cjs/loader:1119:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47

    at checkExecSyncError (node:child_process:861:11)
    at Object.execFileSync (node:child_process:896:15)
    at validateBinaryVersion (/home/coder/esbuild-test/node_modules/esbuild/install.js:98:28)
    at /home/coder/esbuild-test/node_modules/esbuild/install.js:283:5 {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(635) [Uint8Array] [
       47, 104, 111, 109, 101,  47,  99, 111, 100, 101, 114,  47,
      101, 115,  98, 117, 105, 108, 100,  45, 116, 101, 115, 116,
       47, 110, 111, 100, 101,  95, 109, 111, 100, 117, 108, 101,
      115,  47, 101, 115,  98, 117, 105, 108, 100,  47,  98, 105,
      110,  47, 101, 115,  98, 117, 105, 108, 100,  58,  49,  10,
      127,  69,  76,  70,   2,   1,   1,  10,  94,  10,  10,  83,
      121, 110, 116,  97, 120,  69, 114, 114, 111, 114,  58,  32,
       73, 110, 118,  97, 108, 105, 100,  32, 111, 114,  32, 117,
      110, 101, 120, 112,
      ... 535 more items
    ]
  ],
  pid: 8929,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(635) [Uint8Array] [
     47, 104, 111, 109, 101,  47,  99, 111, 100, 101, 114,  47,
    101, 115,  98, 117, 105, 108, 100,  45, 116, 101, 115, 116,
     47, 110, 111, 100, 101,  95, 109, 111, 100, 117, 108, 101,
    115,  47, 101, 115,  98, 117, 105, 108, 100,  47,  98, 105,
    110,  47, 101, 115,  98, 117, 105, 108, 100,  58,  49,  10,
    127,  69,  76,  70,   2,   1,   1,  10,  94,  10,  10,  83,
    121, 110, 116,  97, 120,  69, 114, 114, 111, 114,  58,  32,
     73, 110, 118,  97, 108, 105, 100,  32, 111, 114,  32, 117,
    110, 101, 120, 112,
    ... 535 more items
  ]
}
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
[coder@bazaar ~/esbuild-test (master)] $ node --version
v16.18.1
```

Maybe it's Node v16 related?

**Comment by hyrious** [comment] 2023-08-03 08:51
I didn't reproduce your error:

```console
$ node -v
v16.18.1

$ yarn
yarn install v1.22.19
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
✨  Done in 18.85s.

$ npx esbuild --version
0.18.17
```

For more details, I'm running these commands on macOS 13.5 and the node was installed by [`fnm use 16.18.1`](https://github.com/Schniz/fnm).

**Comment by martin-jarvis-vg** [comment] 2023-08-03 09:02
Hmmm, I'm running on a centos 7 based Coder environment.

From my minimum case `package.json` from above:
```
[coder@bazaar ~/esbuild-test (master)] $ yarn
yarn install v1.22.19
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error /home/coder/esbuild-test/node_modules/esbuild: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /home/coder/esbuild-test/node_modules/esbuild
Output:
node:internal/errors:857
  const err = new Error(message);
              ^

Error: Command failed: /usr/bin/node /home/coder/esbuild-test/node_modules/esbuild/bin/esbuild --version
/home/coder/esbuild-test/node_modules/esbuild/bin/esbuild:1
ELF
^

SyntaxError: Invalid or unexpected token
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1084:15)
    at Module._compile (node:internal/modules/cjs/loader:1119:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47

    at checkExecSyncError (node:child_process:861:11)
    at Object.execFileSync (node:child_process:896:15)
    at validateBinaryVersion (/home/coder/esbuild-test/node_modules/esbuild/install.js:98:28)
    at /home/coder/esbuild-test/node_modules/esbuild/install.js:283:5 {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(635) [Uint8Array] [
       47, 104, 111, 109, 101,  47,  99, 111, 100, 101, 114,  47,
      101, 115,  98, 117, 105, 108, 100,  45, 116, 101, 115, 116,
       47, 110, 111, 100, 101,  95, 109, 111, 100, 117, 108, 101,
      115,  47, 101, 115,  98, 117, 105, 108, 100,  47,  98, 105,
      110,  47, 101, 115,  98, 117, 105, 108, 100,  58,  49,  10,
      127,  69,  76,  70,   2,   1,   1,  10,  94,  10,  10,  83,
      121, 110, 116,  97, 120,  69, 114, 114, 111, 114,  58,  32,
       73, 110, 118,  97, 108, 105, 100,  32, 111, 114,  32, 117,
      110, 101, 120, 112,
      ... 535 more items
    ]
  ],
  pid: 11795,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(635) [Uint8Array] [
     47, 104, 111, 109, 101,  47,  99, 111, 100, 101, 114,  47,
    101, 115,  98, 117, 105, 108, 100,  45, 116, 101, 115, 116,
     47, 110, 111, 100, 101,  95, 109, 111, 100, 117, 108, 101,
    115,  47, 101, 115,  98, 117, 105, 108, 100,  47,  98, 105,
    110,  47, 101, 115,  98, 117, 105, 108, 100,  58,  49,  10,
    127,  69,  76,  70,   2,   1,   1,  10,  94,  10,  10,  83,
    121, 110, 116,  97, 120,  69, 114, 114, 111, 114,  58,  32,
     73, 110, 118,  97, 108, 105, 100,  32, 111, 114,  32, 117,
    110, 101, 120, 112,
    ... 535 more items
  ]
}
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[coder@bazaar ~/esbuild-test (master)] $ npx esbuild --version
0.18.17
```

I'm happy to take suggestions on what else the problem could be - or additional tests I can perform to help narrow this down.

**Comment by evanw** [comment] 2023-08-06 19:38
I'm closing this issue for two reasons:

1. The issue can't be reproduced given the reproduction instructions. This could mean that it's a problem with your machine (e.g. with how you installed node) instead of a problem with esbuild. In any case it's impossible to proceed with this issue if it can't be reproduced.

2. The fact that `npm_config_user_agent` doesn't appear to contain `yarn/` means that this could be a problem with Yarn, not with esbuild. That would be a bug to file against the Yarn project instead (or potentially with centos, as described below).

It's hypothetically possible that `npm_config_user_agent` contains `yarn/` but doesn't match the regular expression `\byarn/` with the `\b` word boundary, which was introduced in esbuild version 0.13.4. However, Yarn always generates a string starting with `yarn/` according to [Yarn's source code](https://github.com/yarnpkg/berry/blob/d85702c61e3b19715c728fa9d2ecec68dcbf39b2/packages/yarnpkg-core/sources/scriptUtils.ts#L189-L194). So this would presumably only happen if you installed Yarn using a centos-specific installation method and they deliberately messed with Yarn's source code (which would not be unsurprising, as this has happened to esbuild). For example if `npm_config_user_agent` somehow started with `centosyarn/` or something. You could potentially check the contents of `npm_config_user_agent` on your machine as it appears from a package installation script being run by the `yarn add` command to see if this is what's happening for you.

**Closed by evanw** 2023-08-06 19:38 UTC
Labels: unactionable

**Comment by martin-jarvis-vg** [comment] 2023-08-07 09:07
That's unfortunate.

For reference, my yarn user agent is:
```
[coder@backstage ~/backstage] $ yarn config get user-agent
yarn/1.22.19 npm/? node/v16.18.1 linux x64
```

Also as I mentioned in the original ticket the logic did work in esbuild 0.13.3 which used a more specific check for yarn v2 or above.  If the user agent didn't match the regex, the issue wouldn't occur as the esbuild binary would be invoked directly, not via node.

I'll see if I can track down any other potential cause for this.

**Comment by evanw** [comment] 2023-08-07 12:53
We can reopen this issue if you can provide a way to reproduce it. Unfortunately I need a reproduction to be able to validate that a fix is correct and to add test coverage to prevent a regression.

FWIW esbuild's CI [runs a `yarn install`](https://github.com/evanw/esbuild/blob/0e5b5fb295260c3169de2cb7c8c3ca8334a3c89e/.github/workflows/e2e.yml#L40-L43) on esbuild every 6 hours to make sure it's working correctly. I have added a test for Yarn "classic" (currently version 1.22.19) and it also completes successfully in CI. So something must be different about your computer.

**Comment by martin-jarvis-vg** [comment] 2023-08-07 12:59
Understood, I've gone through what I can and can't see anything that would cause it.   I'll feedback if I figure it out, but I think my workaround  for the moment is to pin the esbuild version to 0.13.3.

**Comment by JSMike** [comment] 2023-09-11 17:32
FYI, I posted on stackoverflow: https://stackoverflow.com/a/77083238/6074747

Not specific to yarn, but same error message type. I've run into this issue on monorepos when multiple versions of esbuild are required by different dependencies.

I'll try to do a repro of this and open a separate issue, but wanted to reference since it's the same error message.
