### ISSUE TITLE
Error: The following dependencies are imported but could not be resolved: main.css

### ISSUE THREAD

**Issue by vaynevayne** [evanw/esbuild#3805] opened 2024-06-17 02:10 UTC
I use vite, but I'm not sure if this is a problem with esbuild,Even if not, I hope the author can give me some direction to solve the problem.
```jsx
yarn run dev

Error: The following dependencies are imported but could not be resolved:

  main.css (imported by /Users/xiaofan_yu/cs/react-school-system/src/index.tsx)

Are they installed?
    at file:///Users/xx/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:51104:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///Users/xx/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:50609:26
```

```jsx
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react-swc'
import path from 'node:path'
import cdn from 'vite-plugin-cdn-import'
import {fileURLToPath} from 'url'
const filename = fileURLToPath(import.meta.url)
const _dirname = path.dirname(filename)

// https://vitejs.dev/config/
export default defineConfig({
  esbuild: {
    loader: 'jsx',
  },
  optimizeDeps:{
    esbuildOptions:{
      loader: {
        '.js': 'jsx', // For old projects, jsx is written in the .js of the project.
After adding this configuration, the problem occurred
      },
    }
   
  },
  plugins: [
    react(),
    cdn({
      modules: [
        {
          name: 'polyfill',
          var: 'Polyfill',
          path: 'http://polyfill.alicdn.com/v3/polyfill.min.js',
        },
        {
          name: 'react',
          var: 'React',
          path: `...,
        },
        {
          name: 'react-dom',
          var: 'ReactDOM',
          path: `...`,
        },
      ],
    }),
  ],
  resolve: {
    alias: [{ find: '@', replacement: path.resolve(_dirname, 'src') }],
  },
  build: {
    outDir: 'build',
    rollupOptions: {
      external: ['react', 'react-dom'],
      output: {
        manualChunks: {
          lodash: ['lodash'],
        },
      },
    },
  },
})

```

**Comment by evanw** [comment] 2024-06-17 02:20
> I use vite, but I'm not sure if this is a problem with esbuild

I'm not sure either. It looks like you posted some code that uses Vite, not esbuild. The Vite repository is here: https://github.com/vitejs/vite. You may be able to find help with your problem by asking the Vite team. I don't use Vite myself, I'm not familiar with it, and I'm definitely the wrong person to ask questions about how to use Vite.

I'm closing this issue as it's irrelevant to esbuild. If you have a reproduction for an issue that involves using esbuild instead of Vite, then feel free to post it here and we can discuss it.

**Closed by evanw** 2024-06-17 02:20 UTC

**Comment by hyrious** [comment] 2024-06-17 02:59
First of all, since you're using Vite and the error message [comes from Vite](https://github.com/vitejs/vite/blob/b4b4acfb23654ea109630fcf90a974877355e9c4/packages/vite/src/node/optimizer/index.ts#L405), you should prefer raising the issue at the Vite repository instead of here.

Secondly, your issue seems that you have written:

```js
import "main.css" // Not "./main.css"
```

Paths without leading `.` or `/` are considered an npm module's name, like `"vue"`. What happens is that Vite cannot find a module named "main.css". You probably want to write `"./main.css"` instead.

**Comment by vaynevayne** [comment] 2024-06-18 02:02
Thank you. I felt dizzy yesterday, but I reacted this morning, but thank you very much
