### ISSUE TITLE
drop:['console'] got error : text: 'Invalid option in build() call: "drop"',

### ISSUE THREAD

**Issue by tonyload** [evanw/esbuild#3071] opened 2023-04-19 02:04 UTC
i set drop in build like this:

```js
build({
  outfile: `dist/${outputName}.esm.js`,
  format: 'esm',
  minify: true,
    drop: ['console'],
});
```

but i got error below:

```
detail: Error: Invalid option in build() call: "drop"
```

from the https://esbuild.github.io/api/#drop.  why ?

**Comment by hyrious** [comment] 2023-04-20 07:48
I don't see this error. The `drop` option was added since [0.14.10](https://github.com/evanw/esbuild/blob/main/CHANGELOG-2021.md#01410). Can you check your esbuild version (`npm why esbuild`) or provide a reproduction?

**Comment by evanw** [comment] 2023-04-22 18:45
I'm marking this issue as `unactionable` because it cannot be reproduced with the information given.

**Comment by evanw** [comment] 2023-05-12 19:28
I'm closing this issue because it's been unactionable for a while with no follow-up reply.

**Closed by evanw** 2023-05-12 19:28 UTC
Labels: unactionable
