### ISSUE TITLE
Esbuild best practice for bundling React apps with deps triggering multiple React instances??

### ISSUE THREAD

**Issue by cameronelliott** [evanw/esbuild#3419] opened 2023-10-03 05:44 UTC
I am using esbuild 0.19.3

What is happening:
In a simple React project that imports a library, which imports React:
**React is getting imported twice as per this --analyze=verbose output**
```
c@macmini ~/D/r/w/e/whep-viewer (main)> npx esbuild --bundle --outdir=www/js  src/index.tsx --analyze=verbose --servedir=www src/index.tsx --platform=browser

 > Local:   http://127.0.0.1:8000/
 > Network: http://192.168.86.135:8000/
 > Network: http://192.168.86.134:8000/


  www/js/index.js ──────────────────────────────────────────────────── 1.2mb ─ 100.0%
   ├ node_modules/react-dom/cjs/react-dom.development.js ─────────── 926.6kb ── 77.6%
   │  └ node_modules/react-dom/index.js
   │     └ node_modules/react-dom/client.js
   │        └ src/index.tsx
   ├ ../../node_modules/react/cjs/react.development.js ────────────── 78.9kb ─── 6.6%
   │  └ ../../node_modules/react/index.js
   │     └ ../../dist/WhepViewer.js
   │        └ ../../dist/index.js
   │           └ src/index.tsx
   ├ node_modules/react/cjs/react.development.js ──────────────────── 78.9kb ─── 6.6%
   │  └ node_modules/react/index.js
   │     └ node_modules/react/cjs/react-jsx-runtime.development.js
   │        └ node_modules/react/jsx-runtime.js
   │           └ src/index.tsx
```

**Modern React with hooks simply cannot work correctly when multiple instances are created**

[link explaining WHY you can't have multiple instances of React in an App](https://react.dev/warnings/invalid-hook-call-warning#duplicate-react:~:text=If%20these%20react%20imports%20resolve%20to%20two%20different%20exports%20objects%2C%20you%20will%20see%20this%20warning.%20This%20may%20happen%20if%20you%20accidentally%20end%20up%20with%20two%20copies%20of%20the%20react%20package.)

I simply want to ask what is the recommended way to resolve this with `esbuild` ?? (which I think is the bees-knees).

I made some progress using `--external:react --external:react-dom`, as it's clear React and React-dom don't even get bundled in this case. I got stuck with `Uncaught Error: Dynamic require of "react-dom/client" is not supported` error in the browser, but I think I might be over looking a flag to use Esm6 imports.

But before proceeding down that road, I want to make sure from your perspective, @evanw 
that this is the best way to go. (using external rather than bundling React with some sort of de-duplication)

**What do you recommend as a method and mechanism to stop multiple-imports of React into applications which import libraries that import React (yet as PeerDependencies) so that esbuild can be used in this situation for bundling React apps that import libs that import React?**

My sample project:
https://github.com/cameronelliott/whip-whep-webrtc-react/commit/b872e15156c0cb738375bb682d6a7ea7427744fc

PS
I also noticed others in issue #475 struggling with multiple instances of React:
https://github.com/evanw/esbuild/issues/475#issuecomment-863277639
https://github.com/evanw/esbuild/issues/475#issuecomment-873415053
https://github.com/evanw/esbuild/issues/475#issuecomment-907563901
https://github.com/evanw/esbuild/issues/475#issuecomment-910175236
https://github.com/evanw/esbuild/issues/475#issuecomment-946760991
https://github.com/evanw/esbuild/issues/475#issuecomment-985957709
https://github.com/evanw/esbuild/issues/475#issuecomment-990149748
https://github.com/evanw/esbuild/issues/475#issuecomment-1034918835
https://github.com/evanw/esbuild/issues/475#issuecomment-1140867169

PPS
You made a comment about how duplicate instances should not impact correctness,
but it absolutely does in the case of React!
https://github.com/evanw/esbuild/issues/475#issuecomment-1156911260

**Comment by cameronelliott** [comment] 2023-10-03 05:53
It's worth noting how multiple users of Webpack resolved this multiple-instance vs single-instance of React problem:
In Webpack, this config code is how some users resolve the problem:
```
// In webpack.config.js

  resolve: {
    alias: {
      react: path.resolve('node_modules/react'),
    },
  },
```
Which apparently causes React to only be output a single time in the bundle, rather than being output twice or more with multiple paths like `node_modules/react`, and then `foolib/node_modules/react` ... etc

https://stackoverflow.com/a/42411974/86375

**Comment by hyrious** [comment] 2023-10-03 06:04
It's not always the bad case when you have multiple instances of React (which is rarely seen but the use case still exists).

Since you mentioned the `alias` feature in webpack, esbuild [also has one](https://esbuild.github.io/api/#alias). You just have to use `--alias:react=react` so that all importing to `react` will be resolved to the one in the root directory of your project.

**Comment by cameronelliott** [comment] 2023-10-03 06:17
@hyrious Thank you, thank you, thank you for taking a minute to point out that option! That seems to be a great way to get past the multiple instances issue. ❤️

**Comment by evanw** [comment] 2023-10-17 03:35
I'm closing this issue because esbuild is working as intended here.

**Closed by evanw** 2023-10-17 03:35 UTC
