### ISSUE TITLE
module detection in browsers

### ISSUE THREAD

**Issue by riquito** [evanw/esbuild#1224] opened 2021-04-28 23:18 UTC
Some of my (third party) dependencies check whether `typeof module` is undefined or not to detect if the library is loaded in NodeJS or a browser.

The following vanilla code code output `module undefined` in a browser and `module detected` in NodeJS.

```
function main() {
  if (typeof module === 'undefined') {
      console.log('module undefined')
  } else {
      console.log('module detected')
     // attempt to `require` something or run other Node specific logic
  }
}

main()
```

If I bundle it then `module` is never undefined, and those libraries start executing the wrong logic when running in a browser

`esbuild test.js --bundle`

```
(() => {
  var __commonJS = (cb, mod) => () => (mod || cb((mod = {exports: {}}).exports, mod), mod.exports);

  // test.js
  var require_test = __commonJS((exports, module) => {
    function main() {
      if (typeof module === "undefined") {
        console.log("module undefined");
      } else {
        console.log("module detected");
      }
    }
    main();
  });
  require_test();
})();
```

It looks common enough in my dependencies that I may be missing the obvious.

The most common usages I see are
`typeof module === 'object' && module.exports`
`typeof module !== 'undefined' && module.exports`

**Comment by evanw** [comment] 2021-04-28 23:31
Bundlers like esbuild that support CommonJS will provide a `module` object for each file. This is necessary to allow for example assignment to `module.exports` so that importing modules can access that module’s exports. So `typeof module` will deliberately always be `"object"` by design in esbuild (unless you reassign something else to `module` of course).

You should use another way of detecting whether you are running in a browser or not. Maybe `typeof window`? It probably depends on your requirements and what other libraries you use since some libraries are pretty invasive and can add properties to the global object.

**Comment by riquito** [comment] 2021-04-29 01:05
Thanks Evan, I wasn't sure about whether there was some way in CommonJS to support this case while not providing module as `module`, but I guess it's not the case.
The dependencies are third parties, not in my control, so I suppose CommonJS is out of the question. Feel free to close this issue

**Comment by evanw** [comment] 2021-04-29 02:56
Yes, I'm going to close this since it's working as expected. FWIW Webpack, Parcel, and Rollup appear to all do this as well.

**Closed by evanw** 2021-04-29 02:56 UTC
