### ISSUE TITLE
feature detection scrip

### ISSUE THREAD

**Issue by jimmywarting** [evanw/esbuild#3147] opened 2023-06-07 01:05 UTC
i found that instead of using target you could then instead use something like: `esbuild app.js --supported:bigint=false`

I'm compiling things in browser using WASM. and i would like to use feature detection and only build something for the current browser that is being used, not by any other specific browser. and not by using esnext as it's by default

So i found that you keep a list of them here:
```
JavaScript:

arbitrary-module-namespace-names
array-spread
arrow
async-await
async-generator
bigint
class-field
class-private-accessor
class-private-brand-check
class-private-field
class-private-method
class-private-static-accessor
class-private-static-field
class-private-static-method
class-static-blocks
class-static-field
class
const-and-let
default-argument
destructuring
dynamic-import
exponent-operator
export-star-as
for-await
for-of
generator
hashbang
import-assertions
import-meta
inline-script
logical-assignment
nested-rest-binding
new-target
node-colon-prefix-import
node-colon-prefix-require
nullish-coalescing
object-accessors
object-extensions
object-rest-spread
optional-catch-binding
optional-chain
regexp-dot-all-flag
regexp-lookbehind-assertions
regexp-match-indices
regexp-named-capture-groups
regexp-sticky-and-unicode-flags
regexp-unicode-property-escapes
rest-argument
template-literal
top-level-await
typeof-exotic-object-is-object
unicode-escapes

CSS:

hex-rgba
inline-style
inset-property
modern-rgb-hsl
nesting
rebecca-purple
```
I'm just wondering if you do have any such feature detection script that could find out what's supported on the current browser esbuild is being executed on.

**Comment by evanw** [comment] 2023-06-07 01:09
> I'm just wondering if you do have any such feature detection script that could find out what's supported on the current browser esbuild is being executed on.

This information already ships with esbuild. Just set esbuild’s `target` to the current browser version.

**Comment by evanw** [comment] 2023-06-08 16:50
I'm closing this issue because this is a question, and not a bug with esbuild.

> I'm just wondering if you do have any such feature detection script that could find out what's supported on the current browser esbuild is being executed on.

No, I don't. The feature detection code comes from this project: https://github.com/kangax/compat-table. You could extract the feature detection code from that project if you are interested.

**Closed by evanw** 2023-06-08 16:50 UTC
