### ISSUE TITLE
Duplicated identifier with external modules

### ISSUE THREAD

**Issue by ArrayZoneYour** [evanw/esbuild#526] opened 2020-11-13 07:41 UTC
Input:

`index.ts`
```ts
export { default as A } from './A'
export { default as B } from './B'
```

`A.tsx`
```tsx
import React from 'external'
export default () => {
  return <></>
}
```

`B.tsx`
```tsx
import React from 'external'
export default () => {
  return <></>
}
```

Build Script
`build.js`
```js
const esbuild = require('esbuild')
esbuild.build({
  entryPoints: ['./index.ts'],
  bundle: true,
  external: ['external'],
  outfile: 'out.js',
})
```

`out.js`
```js
// ...
  // A.tsx
  const external = __toModule(require("external"));
  var A_default = () => {
    return /* @__PURE__ */ external.default.createElement(external.default.Fragment, null);
  };

  // B.tsx
  const external2 = __toModule(require("external"));   // duplicated require !
  var B_default = () => {
    return /* @__PURE__ */ external2.default.createElement(external2.default.Fragment, null);
  };
// ...

```

Related: #405

**Comment by evanw** [comment] 2020-11-25 10:34
Thanks for reporting this. Closing as a duplicate of #475.

**Closed by evanw** 2020-11-25 10:34 UTC
