### ISSUE TITLE
Source map not correct when using `minifySyntax` to eliminate dead code branches - the branch code remains in the sourcemap

### ISSUE THREAD

**Issue by krymel** [evanw/esbuild#2794] opened 2023-01-05 12:09 UTC
Hi,

I've found that when using:

```ts
build({
    bundle: true,
    minifySyntax: true,
    sourceMap: 'linked', // any value that isn't false
    define: {
        "isServer": JSON.stringify(false),
    }
})
```

...and having code with top-level `isServer` code branching such as:

```ts
if (isServer) {
    console.log('SSR')
} else {
    console.log('CSR')
}
```

...the code branch will be removed and the only code that remains will be: `console.log('CSR')` -> this is **correct**.

However, the resulting sourcemap file will still have the original code prior to the AST transform -> this seems **incorrect**.

This might be an edge usecase, as most people won't run such aggressive optimization in development mode.

I do it, because I need to check code size results of my static site builder and I was puzzled by this behaviour. Debugging it, I only looked at the sourcemapped code in the beginning and was wondering "why esbuild is not doing dead code elimination correctly" ---only when I checked the source to sourcemap difference I realized that it works, but the sourcemap is way off.

esbuld version `0.16.14`

Impressions:

<img width="678" alt="Bildschirmfoto 2023-01-05 um 13 05 06" src="https://user-images.githubusercontent.com/87694/210776609-78f63649-48a3-4b86-a2db-c675d90a86af.png">

<img width="726" alt="Bildschirmfoto 2023-01-05 um 13 04 50" src="https://user-images.githubusercontent.com/87694/210776634-a1d61c33-f990-4ff1-b946-f49c31224ffb.png">

Do you want me to provide a reproduction example?

**Comment by evanw** [comment] 2023-01-05 15:16
I’m confused. The whole reason source maps exist is to map from the final code back to the original code. So this is exactly what is supposed to happen. If you only care about the final code and don’t want to see the original code, then you don’t need source maps.

**Comment by evanw** [comment] 2023-01-06 17:05
I’m closing this issue as it’s working as intended.

**Closed by evanw** 2023-01-06 17:05 UTC

**Comment by krymel** [comment] 2023-01-10 19:35
@evanw I agree that it's confusing. What I mean is: The original codebase is written in TypeScript. It is transpiled to JavaScript, but when you activate `minifySyntax`, one branch of an if/else will be wiped out from your original code.

But the sourcemap seems to have been generated *before* the AST minification happened. Therefore the resulting source map does not cover the AST transform that has happened to the code while being processed by esbuild. 

Therefore, a sourcemap generated when `minifySyntax` is enabled will just miss and be broken. Now, arguably, sourcemaps are meant to show the original code (TypeScript). But `minifySyntax` alters the code, but only the transpile target code (JavaScript), not the input code at TypeScript level. The SourceMap now believes that there is a branch, but there is none anymore. You get optimized code that is not debuggbalesing sourcemaps  anymore. If esbuild would reflect that change at TypeScript level before generating the sourcemap, everything would be in sync and the statement "The SourceMap should reflect the original code" would still be true, because `minifySyntax` arguably changes the original code to a new, altered reality. One could argue that SourceMaps should reflect the "original" original code, no matter what tools do to it, but then the combination of features will lead to broken SourceMaps and non-debuggable code as it does right now.

**Comment by evanw** [comment] 2023-01-10 20:16
> Now, arguably, sourcemaps are meant to show the original code (TypeScript).

Yes. This is what source maps are supposed to do.

> The SourceMap now believes that there is a branch, but there is none anymore. You get optimized code that is not debuggbale using sourcemaps anymore.

The code should still be debuggable. If it's not then it's a problem with your debugger, not with esbuild.

[Here is the source map in your original example.](https://evanw.github.io/source-map-visualization/#MzM1AGNvbnNvbGUubG9nKCJDU1IiKTsKLy8jIHNvdXJjZU1hcHBpbmdVUkw9ZGF0YTphcHBsaWNhdGlvbi9qc29uO2Jhc2U2NCxld29nSUNKMlpYSnphVzl1SWpvZ015d0tJQ0FpYzI5MWNtTmxjeUk2SUZzaVlYQndMblJ6SWwwc0NpQWdJbk52ZFhKalpYTkRiMjUwWlc1MElqb2dXeUpwWmlBb2FYTlRaWEoyWlhJcElIdGNiaUFnWTI5dWMyOXNaUzVzYjJjb0oxTlRVaWNwWEc1OUlHVnNjMlVnZTF4dUlDQmpiMjV6YjJ4bExteHZaeWduUTFOU0p5bGNibjFjYmlKZExBb2dJQ0p0WVhCd2FXNW5jeUk2SUNKQlFVZEZMRkZCUVZFc1NVRkJTU3hMUVVGTE95SXNDaUFnSW01aGJXVnpJam9nVzEwS2ZRbz0KMTk3AHsKICAidmVyc2lvbiI6IDMsCiAgInNvdXJjZXMiOiBbImFwcC50cyJdLAogICJzb3VyY2VzQ29udGVudCI6IFsiaWYgKGlzU2VydmVyKSB7XG4gIGNvbnNvbGUubG9nKCdTU1InKVxufSBlbHNlIHtcbiAgY29uc29sZS5sb2coJ0NTUicpXG59XG4iXSwKICAibWFwcGluZ3MiOiAiQUFHRSxRQUFRLElBQUksS0FBSzsiLAogICJuYW1lcyI6IFtdCn0K) That's what it's supposed to look like. And here's what you get when you see it in Chrome Developer Tools:

<img src="https://user-images.githubusercontent.com/406394/211652228-2819eaba-8dc4-4eca-9e2d-590928a09125.jpg" height="207">

Notice how line 4 is darker than the other ones. That's Chrome telling you which parts of the original source code are still present in the final bundle. You can use that information when debugging to know what parts of the code you can interact with. Chrome will let you put a breakpoint on line 4 but not on other lines, since they are not in the bundle. That's how debugging JavaScript with source maps is supposed to work.

**Comment by krymel** [comment] 2023-01-10 21:29
First of all, thank you for your lengthy explanation. `esbuild` is an amazing piece of software and I really love it. Thank you for your support! Maybe it's just my configuration that is off -- or a bug in the debugger, as you said. 

When`minifySyntax` is enabled, the lines that are supposed to be clickable (as you explained so well) are not all clickable to set a breakpoint. I'm also using Chrome btw. -- also, they tend to pick the wrong line. However, the debugger behaves correctly again, when I disable the option. I reproduced and tested with many build options and different combinations and it all works well until `minifySyntax` is activated. 

But my codebase is a whole reimplementation of Next.js so it is quite large and complex, also the build chain has its complexity... I wrote 8 esbuild plugins to customize so that the userland code can import all kinds of data formats, but I'll take some time to isolate all the input parameters and create a small, dependency free reproduction example with the static input/output that makes this behaviour visible so that it's easier to get some evidence.

**Comment by evanw** [comment] 2023-01-10 21:45
https://evanw.github.io/source-map-visualization/ should be able to visualize large source maps. Even without doing any work to isolate a reproduction you should be able to drop your production output files and source maps into that visualizer and check to see if anything is off around the areas you're describing. If the source mappings aren't correct then it's a bug with esbuild or the configuration, and can be fixed. But if the source mappings are correct and the debugger is being buggy, then it's a problem with the debugger, not with esbuild or with your configuration.

**Comment by krymel** [comment] 2023-01-10 23:54
Okay, cool, thank you. Nice debugging tool for sourcemaps.

So, I uploaded both builds as gists so you can easily download the zips of both.
The issue can per perfectly reproduced there. The only thing I did between them was switching `minifySyntax` from `true` to `false`.

This one is fine  (minifySyntax disabled)::
code, sourcemap: https://gist.github.com/krymel/58a846922745029f3e5abf279d656bed

<img width="1470" alt="Bildschirmfoto 2023-01-11 um 00 49 34" src="https://user-images.githubusercontent.com/87694/211686397-79091e32-68ac-48a0-9ae4-10aa9039eddd.png">

And here we have a problem (minifySyntax enabled):
code, sourcemap:  https://gist.github.com/krymel/eed7505635f2b2726fba605d5f5f0ec9

<img width="1289" alt="Bildschirmfoto 2023-01-11 um 00 45 37" src="https://user-images.githubusercontent.com/87694/211686500-f09ff517-98bd-43c2-999e-eca5167019b8.png">

The file in the selection dropdown is:
<img width="869" alt="Bildschirmfoto 2023-01-11 um 00 51 07" src="https://user-images.githubusercontent.com/87694/211686584-7396e390-77f0-4255-8de7-71f8c557834b.png">
