### ISSUE TITLE
esbuild runtime code leaks globals

### ISSUE THREAD

**Issue by shirotech** [evanw/esbuild#3275] opened 2023-07-28 02:57 UTC
When esbuild minify the source code, it renames some of the runtime code variables.

For example when this breaks:

```js
var __defProp = Object.defineProperty
// more
```

becomes

```js
var $=Object.defineProperty;var F=(r,u,o)=>u in r?$(r,u,{enumerable:!0,configurable:!0,writable:!0,value:o}):r[u]=o;var j=(r,u,o)=>(F(r,typeof u!="symbol"?u+"":u,o),o);
```

When this is loaded in the browser, the `$` is assigned globally in the `window` context and hence overrides any library that is in conflict, in this case, it could be jQuery using $.

**Comment by hyrious** [comment] 2023-07-28 03:35
I guess you're using the wrong format or wrong tag (`<script>` or `<script type=module>`). If you want an IIFE then you should set `--format=iife` then all variables will be scoped in a closure. If your runtime supports ESM then you can load it in `<script type=module>` then all variables will not be leaked.

**Comment by shirotech** [comment] 2023-07-28 04:18
> I guess you're using the wrong format or wrong tag (`<script>` or `<script type=module>`). If you want an IIFE then you should set `--format=iife` then all variables will be scoped in a closure. If your runtime supports ESM then you can load it in `<script type=module>` then all variables will not be leaked.

We're using System.js for the build on top, not an option to use module or iife. Any possible solution? Thank you.

**Comment by hyrious** [comment] 2023-07-28 04:56
You can run rollup against an ESM bundle of esbuild with {output.format: 'system'} to do so.

**Comment by shirotech** [comment] 2023-07-28 05:34
> You can run rollup against an ESM bundle of esbuild with {output.format: 'system'} to do so.
> 
> ```
> esbuild --bundle --format=esm source.js --outfile=bundle.js
> rollup bundle.js -f system -o bundle.system.js
> ```

Yes but vite seems to run rollup internally first before running esbuild.

**Comment by hyrious** [comment] 2023-07-28 05:46
Yes but I don't know if Vite supports SystemJS in the first place. I mean it just passes through rollup options and maybe some options does not meet its assumptions on modern web developments. So users have to find out their own path to do what they want in against the _easy_ path provided by Vite.

Anyway it seems not a fault of esbuild.

**Comment by evanw** [comment] 2023-07-28 11:51
I’m closing this issue because esbuild is working as intended here. Please read the documentation: https://esbuild.github.io/api/#format. If you are running the output in the global scope, use `--format=iife`. If you are running the output as a CommonJS module, use `--format=cjs`. If you are running the output as an ES module, use `--format=esm`. SystemJS is not a supported output format.

**Closed by evanw** 2023-07-28 11:51 UTC

**Comment by matths** [comment] 2024-04-16 15:27
@evanw, I think this still exists and is an esbuild problem.

So when compiling a Svelte component as Custom element in IIFE mode and minified, Vite is using esbuild under the hood.
And I think, esbuild is then adding helpers outside the IIFE:

```
var __defProp =
var __defNormalProp =
var __publicField =
```

And esbuild is also minifying these, and so it can happen, that there are global variables that the coder did not intend there to be. And this leads to errors when conflicting with other javascript that has variables of the same name in the global namespace.

I described this problem in a Vite discussion https://github.com/vitejs/vite/discussions/15489 before, but it might be better placed here, maybe.

This is really a tough problem when using the Vite/Esbuild toolchain for code that runs side by side with legacy code and when having conflicts in the global namespace!

There was a pull request trying to fix this inside Vite, but this works only if esbuild minify option is set to false, otherwise the replacement isn't working as intended. (https://github.com/vitejs/vite/pull/11882)
But it should work for code minified by esbuild.

Any help would be much appreciated!

**Comment by matths** [comment] 2024-04-16 17:46
I try to reproduce with the esbuild cli tool, but can't, yet.

My test.js
```javascript
class MyClass {
  static [Math.random()] = "random";
}
const instance = new MyClass();
console.log(MyClass[Math.random()]);
```

bundled with `npx esbuild --bundle --format=iife --target=es2020,edge88,firefox78,chrome87,safari14 --outfile=bundle.js test.js` leads to this:

```javascript
(() => {
  var __defProp = Object.defineProperty;
  var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
  var __publicField = (obj, key, value) => {
    __defNormalProp(obj, typeof key !== "symbol" ? key + "" : key, value);
    return value;
  };

  // test.js
  var _a;
  var MyClass = class {
  };
  _a = Math.random();
  __publicField(MyClass, _a, "random");
  var instance = new MyClass();
  console.log(MyClass[Math.random()]);
})();
```

So here the helpers are inside the IIFE, but when it is about my Svelte custom elements and bundling using Vite, these helpers are outside of IIFE scope and when minified pollute the global namespace or conflict with other global vars. I can't see the difference in Vite. Any ideas?

**Comment by matths** [comment] 2024-04-17 06:13
Now I can reproduce it!

test.js
```javascript
(function () {
  class MyClass {
    static [Math.random()] = "random";
  }
  const instance = new MyClass();
  console.log(MyClass[Math.random()]);
})();
```

esbuild command: `npx esbuild --target=es2020,edge88,firefox78,chrome87,safari14 --platform=browser --loader:.js=js  --supported:dynamic-import=true --supported:import-meta=true --outfile=bundle.js test.js`

(notice: there is no --build or --format=iife set)

I could also use it code-wise like Vite is probably using it:

```javascript
const { build } = require("esbuild");

build({
  entryPoints: ["test.js"],
  // bundle: true,
  // format: "iife",
  format: undefined,
  target: ["es2020", "edge88", "firefox78", "chrome87", "safari14"],
  loader: { ".js": "js" },
  outfile: "bundle.js",
  logLevel: "info",
}).catch(() => process.exit(1));
```

and the resulting bundle looks like this:

```javascript
var __defProp = Object.defineProperty;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __publicField = (obj, key, value) => {
  __defNormalProp(obj, typeof key !== "symbol" ? key + "" : key, value);
  return value;
};
(function() {
  var _a;
  class MyClass {
  }
  _a = Math.random();
  __publicField(MyClass, _a, "random");
  const instance = new MyClass();
  console.log(MyClass[Math.random()]);
})();
```


So I stumbled across this comment in Vite: https://github.com/vitejs/vite/blob/5d5508311f9856de69babd72dc4de0e7c21c7ae8/packages/vite/src/node/plugins/esbuild.ts#L281-L290

And I just don't know if I should blame esbuild or Vite or both and where to go from here.
