### ISSUE TITLE
esbuild detects esm package `p-timeout` as cjs

### ISSUE THREAD

**Issue by jsinglamms** [evanw/esbuild#3240] opened 2023-07-17 13:35 UTC
Hello,

We are working with esbuild, to do a workarround as our current environment doesn't support ESM packages, and we found that when we transpile `p-timeout` and `p-wait-for` to cjs modules, the `p-wait-for` is importing the `p-timeout` as common js, but it's not common js yet (when the transpilation of `p-wait-for` is done, `p-timeout` is not changed yet).

After some investigations, we found that if we patch-package the `p-timeout` & `p-wait-for` to remove the default export of p-timeout, the import is done correctly, and is not used anymore the __toEsm wrapper. 

This are the lines we modified in this packages:
https://github.com/sindresorhus/p-wait-for/blob/main/index.js#L1C8-L1C16
https://github.com/sindresorhus/p-timeout/blob/main/index.js#L38C4-L38C21
https://github.com/sindresorhus/p-timeout/blob/main/index.d.ts#L144-L148

The esbuild configuration that we do is the following:
```ts
await build({
   entryPoints: filteredEntryPoints,
   outdir: dir,
   allowOverwrite: true,
   bundle: false,
   minify: false,
   sourcemap: false,
   logLevel: 'info',
   platform: 'node',
   format: 'cjs',
   target: 'node16',
});
```

**Comment by evanw** [comment] 2023-07-17 21:05
You haven't provided enough information here to reproduce the issue, so I'm marking this issue as `unactionable`. Please provide the input to esbuild, the problematic output, enough information to let me produce the problematic output from the input, and a description of why the output is problematic. I don't know what "the import is done correctly" means, for example.

**Comment by evanw** [comment] 2023-07-22 00:29
I'm closing this issue because no reproduction was provided. If a sufficient reproduction is provided later, we can reopen this issue then.

**Closed by evanw** 2023-07-22 00:29 UTC
Labels: unactionable
