### ISSUE TITLE
Tsconfig `extends` resolution

### ISSUE THREAD

**Issue by arcanis** [evanw/esbuild#3213] opened 2023-07-04 21:49 UTC
There's a little bug in the `extends` resolution. According to the [documentation](https://www.typescriptlang.org/tsconfig/extends.html):

> The value of `extends` is a string which contains a path to another configuration file to inherit from. **The path may use Node.js style resolution.**

In my case, I have the following:

- A `package.json` with `"name": "my-pkg"`
- A `tsconfig.json` with `"extends": "my-pkg/tsconfig.focus.json"`
- **I don't have** `tsconfig.focus.json`
- However, I have a `tsconfig.focus.json.json` file (note the double `.json`)

In these circumstances, TS properly resolves the `extends` configuration to load whatever is inside `tsconfig.focus.json.json`, but Esbuild reports an error (many errors).

*(Note that, due to what's probably a bug in TS, this only works if `extends` uses a bare identifier; if it's a relative path, TS won't use the Node.js resolution and will instead add a `.json` path **if it's not already there**; it thus fails to load `tsconfig.focus.json.json`)*

In case you're curious why the hell I'd hit such a situation, I have a tool to my disposal that can generate a temporary tsconfig.json that covers only specific sets of files (using a restricted `include`). We don't want this temporary file to ever be committed (so it should be in the gitignore), but we also don't want TS to crash if it doesn't find it (which is usually the case, since it's in the gitignore). The `.json.json` is a fairly ugly but functional way of achieving those two goals.

**Comment by evanw** [comment] 2023-07-20 12:39
I can't reproduce this. [Here's what I tried.](https://esbuild.github.io/try/#YgAwLjE4LjE0AC0tYnVuZGxlIC0tanN4LXNpZGUtZWZmZWN0cwBlAGVudHJ5LnRzeABmdW5jdGlvbiB3b3JrcygpIHsKICBjb25zb2xlLmxvZygnc3VjY2VzcycpCn0KPGRpdi8+AAB0c2NvbmZpZy5qc29uAHsKICAiZXh0ZW5kcyI6ICJteS1wa2cvdHNjb25maWcuZm9jdXMuanNvbiIKfQAAbm9kZV9tb2R1bGVzL215LXBrZy9wYWNrYWdlLmpzb24AewogICJuYW1lIjogIm15LXBrZyIKfQAAbm9kZV9tb2R1bGVzL215LXBrZy90c2NvbmZpZy5mb2N1cy5qc29uLmpzb24AewogICJjb21waWxlck9wdGlvbnMiOiB7CiAgICAianN4IjogInJlYWN0IiwKICAgICJqc3hGYWN0b3J5IjogIndvcmtzIgogIH0KfQ) It seems to work fine.

**Comment by evanw** [comment] 2023-08-04 21:17
I'm closing this because it has been `unactionable` for a while without any additional information being added. We can reopen this later if more information is provided.

**Closed by evanw** 2023-08-04 21:17 UTC
Labels: unactionable, tsconfig
