### ISSUE TITLE
[ERROR] No matching export in "node_modules/react-native-screens/src/index.native.tsx" for import "isSearchBarAvailableForCurrentPlatform"

### ISSUE THREAD

**Issue by ko-devHong** [evanw/esbuild#3401] opened 2023-09-22 07:36 UTC
I tried to solve React-native with esbuild. But esbuild sent out an error while compiling. I thought it was a custom library problem at first, but when I searched it, it appeared to be an esbuild problem itself. How am I right to solve this problem here?

- package.json
```json
{
 ...
 "react-native-screens": "^3.19.0",
 "@react-navigation/bottom-tabs": "^6.3.1",
 "@react-navigation/elements": "^1.3.13",
 "@react-navigation/material-top-tabs": "^6.2.2",
 "@react-navigation/native": "^6.1.2",
 "@react-navigation/native-stack": "^6.9.8",
 "react-native": "0.71.1",
 "react-native-esbuild": "^0.6.0",
 "esbuild": "^0.19.3"
}
```

## How to reproduce it

-  react-native.config.js
```js
const { commands } = require('react-native-esbuild');

module.exports = {
  commands,
};
```

- package.json
```json
"scripts": {
    "ios" : "react-native run-ios --no-packager"
    "start": "react-native esbuild-start",
}
```

- shell
```bash
 yarn ios
 yarn start
```

<img width="1971" alt="스크린샷 2023-09-22 오후 4 35 19" src="https://github.com/evanw/esbuild/assets/45538347/07efaea2-eaf0-4f18-99e6-ccaefa6a2672">

<img width="614" alt="스크린샷 2023-09-22 오후 4 35 44" src="https://github.com/evanw/esbuild/assets/45538347/6074e072-6202-473c-bedb-ef459e6ca01f">

<img width="987" alt="스크린샷 2023-09-22 오후 4 35 58" src="https://github.com/evanw/esbuild/assets/45538347/a792663f-5317-4643-9416-45684fc75c01">

**Comment by evanw** [comment] 2023-09-22 15:02
You did not follow the issue reporting instructions. This issue does not provide enough information for me to reproduce the problem, so I can’t say for sure why this happens. Marking this issue as `unactionable` until the instructions are followed.

**Comment by ko-devHong** [comment] 2023-09-25 01:28
@evanw  I have revised my question.

**Comment by evanw** [comment] 2023-09-25 02:28
Your instructions don't work for me:

```
@evanw ➜ /workspaces/codespaces-blank/temp $ yarn ios
yarn run v1.22.19
warning package.json: No license field
$ react-native run-ios --no-packager
error iOS project folder not found. Are you sure this is a React Native project?.
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
```

I know nothing about React Native, sorry.

**Comment by ko-devHong** [comment] 2023-09-25 02:53
@evanw  Well, then can you just look at it from a code point of view?? As far as I know, if I write using "export decare" like a snapshot from the beginning, an error occurs when compiling in exbuild. But I didn't write this code myself, and it's happening with another library code I installed. What are some ways to solve this?

**Comment by evanw** [comment] 2023-09-25 03:07
Well first of all looking at the `.d.ts` file should be irrelevant because that shouldn't ever be loaded by esbuild in the first place (since [esbuild doesn't have a type checker](https://esbuild.github.io/content-types/#no-type-system)). The missing export is in the file `src/index.native.tsx` so I'm not sure why you're looking for the export in the file `lib/typescript/index.d.ts` instead. That's a completely different file.

Anyway, the `package.json` for that package contains this:

```json
  "main": "lib/commonjs/index",
  "module": "lib/module/index",
  "react-native": "src/index",
```

When configured normally, esbuild would load from either `main` or `module` which would be the TypeScript compiler's output (the TypeScript compiled into JavaScript). However, the error appears to be because esbuild appears to have been configured to load the `react-native` entry point instead. This points to a TypeScript file instead of a JavaScript file. Loading a TypeScript file from inside `node_modules` is generally a bad idea. It's a workflow that the TypeScript team recommends against. It's not even well-defined what should happen when you do this because the `tsconfig.json` files (which could indicate important information about the source code that affects its run-time behavior) may be missing and/or removed from the context of the original project and therefore uninterpretable. You haven't provided enough information to say who or what is configuring esbuild to take the `react-native` path, if that is intentional or a mistake, and if so which other project to report the mistake to.

**Comment by evanw** [comment] 2023-10-17 04:49
I'm closing this issue because it's been `unactionable` for a while without a resolution.

**Closed by evanw** 2023-10-17 04:49 UTC
Labels: unactionable

**Comment by wtbrave-pix** [comment] 2024-12-16 02:19
> @evanw I have revised my question.

how did you do it?

**Comment by wtbrave** [comment] 2024-12-16 02:25
> @evanw I have revised my question.

how did you do it ?
