### ISSUE TITLE
"Top-level await is not available in the configured target environment"

### ISSUE THREAD

**Issue by o-t-w** [evanw/esbuild#1096] opened 2021-04-01 09:15 UTC
I thought that ESBuild was meant to be able to transpile code so it works in older browsers? Or is the point of `target` just to show me errors telling me I can't use certain features?

My output format is ES modules, in which I thought top level await is meant to be able to work?

```
require('esbuild').build({
  entryPoints: ['./src/new-js/international.js', './src/new-js/homepage.js'],
  bundle: true,
  minify: true,
  format: 'esm',
  outdir: 'build/js/new-js',
  target: ['chrome75', 'firefox70', 'safari11'],
}).catch(() => process.exit(1));
```

**Comment by evanw** [comment] 2021-04-01 10:45
Some language features can be transpiled but others can't be. Top-level await can't really be transpiled because there's no equivalent older syntax. Up until the introduction of top-level await, all ESM module evaluation was synchronous. There was no way to insert an asynchronous step at the top-level.

**Comment by bisubus** [comment] 2021-04-01 15:06
@evanw This requires a bundler to be aware of top-level awaits, but I don't see fundamental problems with this. Webpack supports this, doesn't it? I guess an equivalent is that every module export is wrapped with async IIFE.

**Comment by evanw** [comment] 2021-04-03 04:08
Webpack doesn't even support the ESM output format at all I think (open issue: https://github.com/webpack/webpack/issues/2933) so it's not equivalent. I'm planning to add support for top-level await to the IIFE output format for esbuild, in which case this should work.

**Comment by evanw** [comment] 2021-04-10 04:36
Closing this as a duplicate of #253, which is the general open issue for top-level await support. I'm using that issue to represent adding top-level await support to the IIFE format.

**Closed by evanw** 2021-04-10 04:36 UTC
