### ISSUE TITLE
Decorators stage3

### ISSUE THREAD

**Issue by reganpony** [evanw/esbuild#3462] opened 2023-10-23 10:45 UTC
TypeScript5.0 Already supported. Decorators stage3 [href](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html)

[tc39/proposal-decorators](https://github.com/tc39/proposal-decorators#2-calling-decorators)

```ts
type Decorator = (value: Input, context: {
  kind: string;
  name: string | symbol;
  access: {
    get?(): unknown;
    set?(value: unknown): void;
  };
  private?: boolean;
  static?: boolean;
  addInitializer?(initializer: () => void): void;
}) => Output | void;

```

> esbuild Why not generate Decorators  code?

**Comment by reganpony** [comment] 2023-10-23 10:48
https://esbuild.github.io/try/#dAAwLjE5LjMALS1sb2FkZXI9dHMAdHlwZSBUYXJnZXQ8VGhpcz4gPSAodGhpczogVGhpcywgLi4uYXJnczogYW55W10pID0+IHZvaWQ7CgpmdW5jdGlvbiBsaXN0ZW4oZXZlbnQ6IHN0cmluZykgewogICAgcmV0dXJuIGZ1bmN0aW9uIDxUaGlzPih0YXJnZXQ6IFRhcmdldDxUaGlzPiwgY3R4OiBDbGFzc01ldGhvZERlY29yYXRvckNvbnRleHQ8VGhpcywgVGFyZ2V0PFRoaXM+PikgewogICAgICAgIGN0eC5hZGRJbml0aWFsaXplcihmdW5jdGlvbiAoKSB7CiAgICAgICAgICAgIHRoaXNbY3R4Lm5hbWVdID0gdGhpc1tjdHgubmFtZV0uYmluZCh0aGlzKTsKICAgICAgICB9KQogICAgfQp9CgoKCmNsYXNzIEhlbGxvCnsKICAgIEBsaXN0ZW4oJ2V2ZW50JykKICAgIHB1YmxpYyBydW4oKSB7CiAgICAgICAgCiAgICB9Cn0

**Comment by evanw** [comment] 2023-11-18 19:15
Closing as a duplicate of #104.

**Closed by evanw** 2023-11-18 19:15 UTC
