### ISSUE TITLE
Modules resolved by plugins are never tree-shakeable

### ISSUE THREAD

**Issue by chriscasola** [evanw/esbuild#1314] opened 2021-05-25 21:40 UTC
See PR #1313 

Pasting the description for reference:

@agaynor and I have been working on a non-public esbuild plugin that resolves vue modules. We're running into an issue where any module that matches the onResolve hook for a plugin becomes exempt from all tree shaking, even if it is in a package with `sideEffects: false`.

The unit test in this PR named `TestPackageJsonSideEffectsFalsePluginResolver` demonstrates the issue. It is failing because the `cmp1.js` file is not being tree-shaken.

From what we can tell, only the built-in resolver can mark modules as not having side effects which happens [here](https://github.com/evanw/esbuild/blob/master/internal/resolver/resolver.go#L483).

Is there any way to make it possible for plugins to indicate in the resolve result that the same "has side effects" logic should be applied to the resolved path?

**Comment by evanw** [comment] 2021-05-26 00:30
This hasn't been implemented yet. Closing this issue as a duplicate of #1009.

**Closed by evanw** 2021-05-26 00:30 UTC
