### ISSUE TITLE
Esbuild version update increases the package size of project 

### ISSUE THREAD

**Issue by sunilnalumachucb** [evanw/esbuild#3451] opened 2023-10-16 16:53 UTC
I am using esbuild in our node serverless project, The node version we use is 18 and serverless 3.42. I observed recently after updating the esbuild to latest version i see the  package size increased. 

I tested with couple of esbuild versions and the package size increases for each esbuild version increase.
esbuild -  0.19.4 i see package size is 14mb
esbuild -  0.16.17 i see package size is 7.5mb
esbuild -  0.15.18 i see package size is 4.5mb
esbuild -  0.15.8 i see package size is 4.5mb

current esbuild config we have in our serverless file:
  esbuild:
    bundle: true
    minify: true
    exclude: []
    target: "node18"
    platform: "node"
    concurrency: 10
    sourcemap: true

May i know the reason, why the package size increasing with higher version of esbuild because of this aws lambda using more memory and response time is very high. I am expecting if we increase the esbuild version the performance needs to increase and package size need to come less compare to previous version of esbuild.

**Comment by evanw** [comment] 2023-10-16 17:40
I don't know the reason. I can try to look into it at some point. From what I understand, a significant part of the binary executable size of Go executables is debugging metadata that unfortunately can't be removed because it's also used by the Go GC somehow. So the difference could potentially mostly be explained by something as boring as different Go compiler versions being used to compile different versions of esbuild.

You should know that size of the binary on the file system is not something that esbuild considers important or has ever optimized for. For example, if esbuild did care about size on the file system then it wouldn't be written in Go in the first place, and would also use something like [UPX](https://upx.github.io/) to make the file size smaller. Using UPX comes with a performance cost at startup, which goes against esbuild's performance goals, so it's not something esbuild will use.

If you care a lot about the size of the executable, then esbuild may not be the right tool for you. For example, tools written in JavaScript instead of native code are likely to have a much smaller size on the file system. In any case, you are welcome to use an older version of esbuild if you prefer that version over newer versions.

**Comment by evanw** [comment] 2023-10-16 22:26
After reading this again, it's possible that you could be talking about something other than esbuild's package size (also because esbuild's latest binary size is 9mb, not 14mb). In that case, you didn't follow the issue reporting instructions and didn't provide a way to reproduce your issue. So I'm going to label this issue as `unactionable`. It will be closed soon if the issue reporting instructions are still not followed.

**Comment by AlexJeffcott** [comment] 2023-11-03 09:57
@sunilnalumachucb 
Did you compare this with esbuild 0.19.3?

**Comment by evanw** [comment] 2023-11-06 17:16
I'm closing this due to lack of a follow-up reply.

**Closed by evanw** 2023-11-06 17:16 UTC
Labels: unactionable

**Comment by AlexJeffcott** [comment] 2023-11-07 12:00
Apologies for the late reply. I wanted to speak to some colleagues to see what they thought, too.

I think that you are right that this behaviour is, in fact, correct.

Two questions, though:

1. if one wanted to use the raw syntax, what would be the best way to do that?
2. if this is the correct behaviour, the warning does seem a little alarming, maybe that could be changed?
