### ISSUE TITLE
[Feature Request]: code splitting with commonjs

### ISSUE THREAD

**Issue by DylanPiercey** [evanw/esbuild#1341] opened 2021-06-02 04:09 UTC
I'm playing around with using esbuild for bundling library code with a setup like the following:

```js
import { build } from "esbuild";

await build({
  external: [...], // Make node_modules external
  bundle: true,
  format: "esm",
  splitting: true,
  platform: "node",
  entryPoints: [
    "src/entry-a.ts",
    "src/entry-b.ts"
  ],
});
```

The problem is many libraries I work on require exposing multiple "entry point" files to the user. Think stuff like:

```js
import a from "some-module/entry-a";
import b from "some-module/entry-b";
```

With the `esm` output it seems I can easily achieve this with the code splitting automatically deduping common code between the entries.

Currently though it's not possible to use `format: "cjs"` with `splitting` enabled. It would be great if this was possible because then it would allow me to use esbuild for these modules which require backward compat via providing cjs and esm builds.

If I run `esbuild` again on the output from the `esm` build with `format: "cjs"` it basically does what I want, however it re-inlines all of the runtime stuff again which isn't ideal.

**Comment by evanw** [comment] 2021-06-02 20:51
This happens because the code splitting feature is not finished yet. Closing as a duplicate of #16.

**Closed by evanw** 2021-06-02 20:51 UTC
