### ISSUE TITLE
[BUG] "typeof window" can not be the define key.

### ISSUE THREAD

**Issue by Amour1688** [evanw/esbuild#1954] opened 2022-01-24 13:02 UTC
* esbuild

![image](https://user-images.githubusercontent.com/31695475/150787352-07f870ea-26e4-48d8-9be2-c63fd280488a.png)

* webpack

![image](https://user-images.githubusercontent.com/31695475/150787426-1c7226d4-d47b-4f95-a13c-7ff028134924.png)

**Comment by upupming** [comment] 2022-01-24 15:43
@Amour1688 I think we should use `--define:window=undefined` directly instead of `--define:"typeof window"=undefined`:

Input:

```js
if (typeof window === 'undefined') {
  console.log('sss')
} else {
  console.log('ttt')
}

```

` esbuild test.js --define:window=undefined` Output:

```js
if (true) {
  console.log("sss");
} else {
  console.log("ttt");
}
```

`esbuild test.js --define:window=\"object\"` Output:

```js
if (false) {
  console.log("sss");
} else {
  console.log("ttt");
}
```

**Comment by evanw** [comment] 2022-01-24 17:00
This is not a bug. The define feature is only for replacing certain kinds of expressions. It's not a general-purpose code replacement mechanism. Changing just `typeof window` without changing `window` sounds potentially unsafe since it means code will have an inconsistent view of what the `window` variable is. You are welcome to define `process.browser` or some other thing instead.

**Comment by evanw** [comment] 2022-01-27 15:12
Closing this issue because this is not a bug, and I don't think this feature request should be implemented because it leads to logical inconsistencies in the code that could introduce bugs and/or be confusing.

**Closed by evanw** 2022-01-27 15:12 UTC
