### ISSUE TITLE
panic when use esbuild-wasm to build large asm.js files

### ISSUE THREAD

**Issue by hardfist** [evanw/esbuild#1271] opened 2021-05-11 01:56 UTC
when i build an large asm.js files(70M+) using esbuild-wasm(esbuild works fine), it panics
* node: 16.1.0
* MacBook Pro (13-inch, M1, 2020) | macOS Big Sur
```sh
panic: runtime error: slice bounds out of range [:-4294967295]

goroutine 9536 [running]:
github.com/evanw/esbuild/internal/js_printer.(*printer).printNonNegativeFloat(0x85951648, 0x41e0000000000000)
        /Users/evan/dev/esbuild/internal/js_printer/js_printer.go:2257 +0x114
github.com/evanw/esbuild/internal/js_printer.(*printer).printExpr(0x85951648, 0x68b, 0xf3948, 0x38e75328, 0x3, 0x0)
        /Users/evan/dev/esbuild/internal/js_printer/js_printer.go:1916 +0x653
github.com/evanw/esbuild/internal/js_printer.(*printer).printExpr(0x85951648, 0x67d, 0xf3808, 0x38da0320, 0x3, 0x0)
        /Users/evan/dev/esbuild/internal/js_printer/js_printer.go:1635 +0x896
github.com/evanw/esbuild/internal/js_printer.(*printer).printExpr(0x85951648, 0x675, 0xf3728, 0x38e7e780, 0x0, 0x8)
        /Users/evan/dev/esbuild/internal/js_printer/js_printer.go:2114 +0x34c
github.com/evanw/esbuild/internal/js_printer.(*printer).printStmt(0x85951648, 0x675, 0xf3ce8, 0x38da7e40)
        /Users/evan/dev/esbuild/internal/js_printer/js_printer.go:3028 +0xb8f
github.com/evanw/esbuild/internal/js_printer.(*printer).printBlock(0x85951648, 0x65e, 0x2ea82498, 0x1, 0x1)
        /Users/evan/dev/esbuild/internal/js_printer/js_printer.go:2368 +0x21
github.com/evanw/esbuild/internal/js_printer.(*printer).printIf(0x85951648, 0x38e7e7c0)
        /Users/evan/dev/esbuild/internal/js_printer/js_printer.go:2417 +0x145
github.com/evanw/esbuild/internal/js_printer.(*printer).printStmt(0x85951648, 0x64c, 0xf3d88, 0x38e7e7c0)
        /Users/evan/dev/esbuild/internal/js_printer/js_printer.go:2705 +0x554
github.com/evanw/esbuild/internal/js_printer.(*printer).printBlock(0x85951648, 0x5eb, 0x38c7ebd0, 0x6, 0x6)
        /Users/evan/dev/esbuild/internal/js_printer/js_printer.go:2368 +0x21
github.com/evanw/esbuild/internal/js_printer.(*printer).printIf(0x85951648, 0x38e7e900)
        /Users/evan/dev/esbuild/internal/js_printer/js_printer.go:2460 +0x68
github.com/evanw/esbuild/internal/js_printer.(*printer).printStmt(0x85951648, 0x593, 0xf3d88, 0x38e7e900)
        /Users/evan/dev/esbuild/internal/js_printer/js_printer.go:2705 +0x554
github.com/evanw/esbuild/internal/js_printer.(*printer).printBlock(0x85951648, 0x44e, 0x38c7eb40, 0x6, 0x6)
        /Users/evan/dev/esbuild/internal/js_printer/js_printer.go:2368 +0x21
github.com/evanw/esbuild/internal/js_printer.(*printer).printIf(0x85951648, 0x38e7e940)
        /Users/evan/dev/esbuild/internal/js_printer/js_printer.go:2460 +0x68
github.com/evanw/esbuild/internal/js_printer.(*printer).printIf(0x85951648, 0x38e7e980)
        /Users/evan/dev/esbuild/internal/js_printer/js_printer.go:2463 +0xa0
github.com/evanw/esbuild/internal/js_printer.(*printer).printStmt(0x85951648, 0x31a, 0xf3d88, 0x38e7e980)
        /Users/evan/dev/esbuild/internal/js_printer/js_printer.go:2705 +0x554
github.com/evanw/esbuild/internal/js_printer.(*printer).printBlock(0x85951648, 0x2e6, 0x38d7faa0, 0x2, 0x2)
        /Users/evan/dev/esbuild/internal/js_printer/js_printer.go:2368 +0x21
github.com/evanw/esbuild/internal/js_printer.(*printer).printBody(0x85951648, 0x2e6, 0xf3b08, 0x38d21cf8)
        /Users/evan/dev/esbuild/internal/js_printer/js_printer.go:2350 +0xe
github.com/evanw/esbuild/internal/js_printer.(*printer).printStmt(0x85951648, 0x2a6, 0xf3d08, 0x38d7f1a0)
        /Users/evan/dev/esbuild/internal/js_printer/js_printer.go:2839 +0xcf8
github.com/evanw/esbuild/internal/js_printer.(*printer).printBlock(0x85951648, 0x20b, 0x1f215080, 0x8, 0x8)
        /Users/evan/dev/esbuild/internal/js_printer/js_printer.go:2368 +0x21
github.com/evanw/esbuild/internal/js_printer.(*printer).printFn(0x85951648, 0x38e74690, 0x200, 0x38e7e040, 0x1, 0x1, 0x20b, 0x1f215080, 0x8, 0x8, ...)
        /Users/evan/dev/esbuild/internal/js_printer/js_printer.go:992 +0xa
github.com/evanw/esbuild/internal/js_printer.(*printer).printStmt(0x85951648, 0x1f1, 0xf3d68, 0x1a5e07e0)
        /Users/evan/dev/esbuild/internal/js_printer/js_printer.go:2526 +0xa43
github.com/evanw/esbuild/internal/js_printer.(*printer).printBlock(0x85951648, 0x11a, 0x38c37200, 0xb, 0xb)
        /Users/evan/dev/esbuild/internal/js_printer/js_printer.go:2368 +0x21
github.com/evanw/esbuild/internal/js_printer.(*printer).printFn(0x85951648, 0x0, 0x110, 0x38c2df00, 0x1, 0x1, 0x11a, 0x38c37200, 0xb, 0xb, ...)
        /Users/evan/dev/esbuild/internal/js_printer/js_printer.go:992 +0xa
github.com/evanw/esbuild/internal/js_printer.(*printer).printExpr(0x85951648, 0x107, 0xf37c8, 0x1a5e1980, 0x1, 0x0)
        /Users/evan/dev/esbuild/internal/js_printer/js_printer.go:1694 +0x975
github.com/evanw/esbuild/internal/js_printer.(*printer).printExpr(0x85951648, 0x1, 0xf3768, 0x38e7ff80, 0x0, 0x8)
        /Users/evan/dev/esbuild/internal/js_printer/js_printer.go:1502 +0x108
github.com/evanw/esbuild/internal/js_printer.(*printer).printStmt(0x85951648, 0x0, 0xf3ce8, 0x2ea80700)
        /Users/evan/dev/esbuild/internal/js_printer/js_printer.go:3028 +0xb8f
github.com/evanw/esbuild/internal/js_printer.(*printer).printBlock(0x85951648, 0x0, 0x23444030, 0x2, 0x2)
        /Users/evan/dev/esbuild/internal/js_printer/js_printer.go:2368 +0x21
github.com/evanw/esbuild/internal/js_printer.(*printer).printExpr(0x85951648, 0x0, 0xf36c8, 0x1fab6c00, 0x1, 0x0)
        /Users/evan/dev/esbuild/internal/js_printer/js_printer.go:1670 +0x6c6
github.com/evanw/esbuild/internal/js_printer.(*printer).printExpr(0x85951648, 0x0, 0xf3768, 0x1fab6dc0, 0x1, 0x0)
        /Users/evan/dev/esbuild/internal/js_printer/js_printer.go:1502 +0x108
github.com/evanw/esbuild/internal/js_printer.(*printer).printDecls(0x85951648, 0x8dbdf, 0x3, 0x14ad20a0, 0x1, 0x1, 0x0)
        /Users/evan/dev/esbuild/internal/js_printer/js_printer.go:2342 +0x32
github.com/evanw/esbuild/internal/js_printer.(*printer).printDeclStmt(0x85951648, 0x0, 0x8dbdf, 0x3, 0x14ad20a0, 0x1, 0x1)
        /Users/evan/dev/esbuild/internal/js_printer/js_printer.go:2305 +0x1f
github.com/evanw/esbuild/internal/js_printer.(*printer).printStmt(0x46b648, 0x0, 0xf3e08, 0x14ad2080)
        /Users/evan/dev/esbuild/internal/js_printer/js_printer.go:2700 +0x53b
github.com/evanw/esbuild/internal/js_printer.Print(0x88, 0x0, 0x101010000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/evan/dev/esbuild/internal/js_printer/js_printer.go:3140 +0xd
github.com/evanw/esbuild/internal/bundler.(*linkerContext).generateCodeForFileInChunkJS(0x4d416b40, 0xf3f48, 0x232ef80, 0x36778900, 0x94, 0x500000004, 0x209e3bc7, 0x1, 0x1, 0x40723780, ...)
        /Users/evan/dev/esbuild/internal/bundler/linker.go:3744 +0x71
created by github.com/evanw/esbuild/internal/bundler.(*linkerContext).generateChunkJS
        /Users/evan/dev/esbuild/internal/bundler/linker.go:4266 +0x37f
/Users/yj/lynx/lepus-pack/node_modules/.pnpm/esbuild-wasm@0.11.5/node_modules/esbuild-wasm/lib/main.js:1098
        return callback(new Error(error), null);
                        ^

Error: The service was stopped
    at /Users/yj/lynx/lepus-pack/node_modules/.pnpm/esbuild-wasm@0.11.5/node_modules/esbuild-wasm/lib/main.js:1098:25
    at /Users/yj/lynx/lepus-pack/node_modules/.pnpm/esbuild-wasm@0.11.5/node_modules/esbuild-wasm/lib/main.js:597:9
    at Socket.afterClose (/Users/yj/lynx/lepus-pack/node_modules/.pnpm/esbuild-wasm@0.11.5/node_modules/esbuild-wasm/lib/main.js:575:7)
    at Socket.emit (node:events:377:35)
    at endReadableNT (node:internal/streams/readable:1312:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by kzc** [comment] 2021-05-11 13:46
There's likely a floating point value that triggers a bug in the Go wasm runtime. This patch would print the problematic value:

```patch
--- a/internal/js_printer/js_printer.go
+++ b/internal/js_printer/js_printer.go
@@ -2267,2 +2267,5 @@ func (p *printer) printNonNegativeFloat(absValue float64) {
 		if e := bytes.LastIndexByte(result, 'e'); e != -1 {
+			if dot < -1 {
+				panic(fmt.Sprintf("Internal error: printNonNegativeFloat(%f)", absValue))
+			}
 			integer := result[:dot]
```

If the problem is indeed in the wasm runtime, here's a possible workaround:

```patch
--- a/internal/js_printer/js_printer.go
+++ b/internal/js_printer/js_printer.go
@@ -2195,2 +2195,11 @@ func parseSmallInt(bytes []byte) int {
 
+func indexBytePortable(s []byte, c byte) int {
+       for i, b := range s {
+               if b == c {
+                       return i
+               }
+       }
+       return -1
+}
+
 func (p *printer) printNonNegativeFloat(absValue float64) {
@@ -2236,3 +2245,3 @@ func (p *printer) printNonNegativeFloat(absValue float64) {
 
-       dot := bytes.IndexByte(result, '.')
+       dot := indexBytePortable(result, '.')
 
```

**Comment by evanw** [comment] 2021-05-11 17:10
It would definitely be interesting to know what the floating-point value is here. Printing `math.Float64bits(absValue)` would be more accurate since it should show the actual bit pattern.

The value being shown as `-42949672951` seems strange because that doesn't fit in a 32-bit number and `int` should be 32-bit in WebAssembly. So it's possible that there's something strange about the way it's printed and it's actually a different value.

It's also potentially possible that this is the result of a memory issue if it's running out of memory (since you mentioned that it's a huge file). Getting the bit pattern present when this happens should help to determine whether this is the case or not because if it's that specific number, it should reproduce even on a small-sized file.

By the way esbuild isn't designed to minify asm.js code, so it may not do what you want even when we do get it to work. For example, I believe esbuild strips the `"use asm"` pragma and may also apply some transformations that disrupt asm.js type annotations. This is not intentional but just a result of asm.js having additional semantics outside of JavaScript. This may result in your code failing to validate as asm.js which may cause your code to run more slowly as the JS VM may do extra work when it tries and fails to compile it as asm.js before falling back to regular JS. If you want to minify asm.js code I recommend using emscripten directly to do that instead.

**Comment by evanw** [comment] 2021-05-11 19:21
Interesting! Thanks for investigating. I didn't realize the arguments were present in the stack trace. That's pretty cool. But I agree that it now sounds like that's not the issue.

**Comment by kzc** [comment] 2021-05-11 19:45
Those echo statements above run fine on darwin/amd64 locally, but they really ought to be run on the same version of node+arch in the top post to verify.

**Comment by hardfist** [comment] 2021-05-14 00:46
do i need to provide info to investigate @evanw

**Comment by evanw** [comment] 2021-05-14 00:51
Yes. I marked it as unactionable because there's nothing I can do with this without more information. One way to move forward would be if you could provide a way for me to reproduce the issue myself. If that's not an option, another way to move forward could potentially be to attempt to debug the issue on your end, either on your own or as a back-and-forth here. Interesting things to know for debugging would be a) the bit pattern of the floating-point value in question and b) the value of the `result` and `dot` local variables in that spot (version `v0.11.5` of esbuild on line 2257 of `js_printer.go`).

**Comment by hardfist** [comment] 2021-05-14 01:51
ok，i will try to make an mimal example

**Comment by evanw** [comment] 2021-09-21 23:23
Closing due to lack of a response.

**Closed by evanw** 2021-09-21 23:23 UTC
Labels: unactionable
