### ISSUE TITLE
resolveExtensions with jsx and npm package

### ISSUE THREAD

**Issue by joelmoss** [evanw/esbuild#2778] opened 2022-12-28 16:13 UTC
I have an NPM package that exports jsx files directly, and esbuild is then configured to compile these on demand. I have a file at `mypackage/some/component/index.jsx`. I want to be able to import this `import Component from 'mypackage/some/component`.

According to https://esbuild.github.io/api/#resolve-extensions, files with jsx extensions should resolve automatically. However this does not seem to be working for me. It works everywhere else. Just not when importing an NPM (bare) module.

Am I missing something, or should this work?

thx

**Comment by evanw** [comment] 2022-12-28 16:26
It depends. 

If you are in node compatibility mode (so a `.mjs` extension or `type: module` in `package.json`) then the extension is required. This is to match node’s behavior, since esbuild implements node’s path resolution algorithm. 

If the package uses `exports` in `package.json`, that could also prevent this from working. The way that feature works is that import paths not present in the exports map are not allowed to be imported.

**Comment by joelmoss** [comment] 2022-12-28 16:32
Yeah so after a little digging, it seems it's my use of the `exports` field is the problem.

```json
"name": "mypackage",
"exports": {
    "./some/*": "./app/components/some/*",
}
```

`./app/components/some/component` contains an `index.jsx` file.

`import Component from 'mypackage/some/component` fails to resolve, but `import Component from 'mypackage/some/component/index.jsx` works great (I have `files` field also defined to enable this).

**Comment by joelmoss** [comment] 2022-12-28 16:36
Add this 

```json
"exports": {
    "./components/lib/button": "./app/components/hue/lib/button/index.jsx",
```

**Comment by evanw** [comment] 2022-12-28 23:05
I just took a look. It looks like esbuild's current error message should already be sufficient to tell you what's wrong here:

```
✘ [ERROR] Could not resolve "mypackage/some/component"

    src/index.js:1:22:
      1 │ import Component from 'mypackage/some/component'
        ╵                       ~~~~~~~~~~~~~~~~~~~~~~~~~~

  The module "./app/components/some/component" was not found on the file system:

    src/node_modules/mypackage/package.json:4:16:
      4 │     "./some/*": "./app/components/some/*"
        ╵                 ~~~~~~~~~~~~~~~~~~~~~~~~~

  Import from "mypackage/some/component.jsx" to get the file
  "src/node_modules/mypackage/app/components/some/component.jsx":

    src/index.js:1:47:
      1 │ import Component from 'mypackage/some/component'
        │                                                ^
        ╵                                                .jsx

  You can mark the path "mypackage/some/component" as external to exclude it from the bundle, which
  will remove this error.
```

So I think there aren't any changes needed to esbuild here, and I'm going to close this issue since esbuild is working as intended.

FWIW if you want to continue to use wildcards in `exports` but have the `.jsx` suffix be added automatically, you could try something like this:

```json
"name": "mypackage",
"exports": {
    "./some/*": "./app/components/some/*.jsx"
}
```

And if you want import paths to work either with or without the `.jsx` suffix, I believe you can do something like this:

```json
"name": "mypackage",
"exports": {
    "./some/*": "./app/components/some/*.jsx",
    "./some/*.jsx": "./app/components/some/*.jsx"
}
```

**Closed by evanw** 2022-12-28 23:05 UTC
