### ISSUE TITLE
Thoughts on allowing for invocation of intermediate build steps?

### ISSUE THREAD

**Issue by Aghassi** [evanw/esbuild#1118] opened 2021-04-07 00:17 UTC
Hello @evanw !

Thank you, first off, for all the work you have put into this tool. It shows a lot of promise, and I'm really excited to use it. One of the pitfalls that other bundlers out there is that they try to do too many things and don't allow for intermediate artifacts or management by build tools. While there are advancements in this area, like Webpack 5, me and my team are using Bazel (https://bazel.build/) to build our source code. This means we actually want to have individual, granular, reproducible, hermetic steps (which are deterministic in nature) exposed to us so that we can create a build graph out of them and gain cache hits on repeated work.

Do you think it would be possible to have parts of the build in ESBuild be called/invoked individually such that we can benefit from incrementality and caching under Bazel? Go is definitely faster than JS, but the same rules at scale apply with sufficiently large code bases and code splitting etc.

**Comment by evanw** [comment] 2021-04-07 07:37
> parts of the build

What does this mean? If you mean transforming input files before esbuild sees them, that can be done with esbuild's current plugin API: https://esbuild.github.io/plugins/#load-callbacks. If you mean some of esbuild's intermediate steps, then I'm not sure I understand because esbuild doesn't have an internal step where it generates intermediate files that are then re-consumed for further processing.

The phases of work are roughly 1) parse all of the files, 2) run tree shaking and code splitting, and 3) generate the output files. Phases 2 and 3 have to be redone if phase 1 is changed. All of this generally completes in a second or two on large code bases, so it doesn't seem worth it to try to memoize fine-grained computations inside esbuild and then save/restore them over the network.

If bundling with esbuild is slow, it's almost certainly caused by plugins, and slow plugins can be written to be memoized and to save/restore their state independent of esbuild. Doing this is somewhat complicated, but such is the nature of cache invalidation. Here's some information about how to do this: https://esbuild.github.io/plugins/#caching-your-plugin.

**Comment by evanw** [comment] 2021-04-07 08:30
There's another discussion about this here in case that's helpful: #817.

**Comment by Aghassi** [comment] 2021-04-08 04:05
Great thanks so much for that insight. Sorry I wasn't clear, your explenation makes sense. As long as ESBuild remains a small fast bundler with minimal steps then I guess there's no need for intermediate output etc. So for now I'll plan to use ESBuild as a linker like you stated in the other thread, but will most likely avoid leaning on the plugin system too much. Honestly, that's what makes other bundlers even slower. 

I guess, to your point in the other thread, does it even make sense to have things like Babel transpiling in front of ESBuild? I assume in some cases it does, but we have a TS codebase that also has some babel plugins (which means for us Babel handles everything). I know ESBuild can handle TS transpiling too, so I've been trying to understand which is the "preferred" way given the way we are looking to organize code that's incremental.

You could imagine that on a large codebase, transpiling folders is a very rare thing since not all JS code needs transpiling on every go around since it doesn't change frequently. I assume under ESBuild this is negligible because of how fast Go is, but would like to get some confirmation that my assumptions are right 😅 . Overall, it seems to me preprocess of JS and CSS stuff should happen before ESbuild like you said, then ESBuild handles bundle creation. Any post processing can happen after the fact (like image compression or additional bundle compression like brotli).

The only area we are still hazy on is how to do a dev server with esbuild. Other bundlers like to watch the file system and do things when files change. However, under Bazel we intend to use iBazel (https://github.com/bazelbuild/bazel-watcher). iBazel is in charge of invoking Bazel, which will write the files to disk, and then attempt to send a signal to the running process to refresh. Under other bundlers, multiple writes to disk cause multiple rebuilds and can cause weird issues with reloading and getting the latest build. In addition, most other bundlers don't let you tell them when to rebuild because they are watching the disk. It's quite frustrating.

Thanks for the prompt response too! I really appreciate it.

**Comment by evanw** [comment] 2021-04-09 10:35
> I assume under ESBuild this is negligible because of how fast Go is, but would like to get some confirmation that my assumptions are right 😅 .

It's negligible, but it's mainly because parsing and transpiling in esbuild are the same thing, not because esbuild is written in Go. The parser transpiles as it goes so there's no real additional cost to transpiling if you have to parse the file anyway.

> attempt to send a signal to the running process to refresh

There is an incremental build API in esbuild that you can use to make builds somewhat faster: https://esbuild.github.io/api/#incremental. This is intended for watch-like scenarios where you are re-running the same build API call with the same options but just different file contents. It's an in-memory caching layer in front of phase 1 that avoids re-parsing and re-transpiling files that haven't changed. Phases 2 and 3 are currently still always redone, although I'd like to eventually short-circuit more things in phases 2 and 3 as well to make it even faster in the future.

**Comment by evanw** [comment] 2021-04-10 12:08
I'm going to close this issue because it's not an issue with esbuild, and the question has been answered.

**Closed by evanw** 2021-04-10 12:08 UTC
