### ISSUE TITLE
esBuild is killing already defined fields

### ISSUE THREAD

**Issue by eco747** [evanw/esbuild#2284] opened 2022-05-30 16:26 UTC
__publicField implementation do not care of already defined fields.

With something like that:

```ts
class Base {
    constructor( els: object ) {
        for( let f in els ) {
            this[f] = els[f];
        }
    }
}

class Derived extends Base {
    public id;
    constructor( els ) {
        super( els );
    }
}

let test = new Derived( { id: 1 } );

console.log( test.id ); // should display 1, but display undefined
```

the generated code looks like that:

```js
var Base = class {
  constructor(els) {
    for (let f in els) {
      this[f] = els[f];
    }
  }
};
__name(Base, "Base");
var Derived = class extends Base {
  constructor(els) {
    super(els); //<<<<< here id is defined in the instance
    __publicField(this, "id"); // <<<<<<<< here it is killed
  }
};
__name(Derived, "Derived");
```

**Comment by eco747** [comment] 2022-05-30 17:08
here is the (pseudo) code for __defNormalProp called by __publicField

```js
    var __defNormalProp = (obj, key, value) => {
    if( key in obj ) {
        __defProp(obj, key, { 
           enumerable: true, 
           configurable: true, 
           writable: true,
           value   // <<<<<<<< should not be there if value===undefined because it will overrides the initial value with undefined
       })
    }
    else {
        obj[key] = value;
     } 
}
```

should be

```js
    var __defNormalProp = (obj, key, value) => {
    if( key in obj ) {
        let props = { 
           enumerable: true, 
           configurable: true, 
           writable: true,
       }
      
       if( value!==undefined ) {
           props.value = value;
       }

        __defProp(obj, key, props );
    }
    else {
        obj[key] = value;
     } 
}
```

**Comment by evanw** [comment] 2022-05-30 18:24
> `// should display 1, but display undefined`

This is the difference between "assign" semantics (i.e. legacy TypeScript) and "define" semantics (i.e. JavaScript and modern TypeScript). It looks like you're looking for legacy TypeScript semantics (which esbuild does by default) but you have configured esbuild to use JavaScript semantics instead (which is why `__publicField` is present). You can see for yourself that `undefined` is the correct result following JavaScript semantics by running the following JavaScript code in node:

```js
class Base {
  constructor(els) {
    for (let f in els) {
      this[f] = els[f];
    }
  }
}

class Derived extends Base {
  id;
  constructor(els) {
    super(els);
  }
}

let test = new Derived({ id: 1 });

console.log(test.id); // should display 1, but display undefined
```

This will print `undefined`.

To use legacy TypeScript semantics instead of JavaScript semantics, you need to set `useDefineForClassFields: false` in `tsconfig.json`: https://www.typescriptlang.org/tsconfig#useDefineForClassFields. Another workaround is to use `declare public id;` instead of `public id;` which turns the field from a JavaScript field with the value `undefined` into a pure type annotation for TypeScript that is completely removed when the TypeScript is compiled into JavaScript.

Closing this issue as esbuild appears to be working as intended here.

**Closed by evanw** 2022-05-30 18:24 UTC

**Comment by eco747** [comment] 2022-05-31 07:31
Thanks for your explanation, 
It is also solved by setting *target* to something less than esnext & es2022 or >

but 


it's not a long-term solution, may be we will need esnext or es2023 sooner or later.

If you look at the __defNormalProp implementation, the code first check if the value is already present in the class, then if present mark it as public, then set the value. 

for me the *intent* of __publicField(this, <field name> ) call without value is clear, just ensure the value in the class is public, not to set the value to undefined.

it will not change anything for existing code when initial value is not present, just not reset value if present.
