### ISSUE TITLE
TS Class field regression

### ISSUE THREAD

**Issue by privatenumber** [evanw/esbuild#3385] opened 2023-09-14 06:45 UTC
## Input code
```ts
interface A {
  n: number;
}

class B {
  constructor(public readonly a: A) {
  }

  public readonly n = this.a.n;
}

const b = new B({ n: 1 });
console.log(b);
```

## TypeScript as baseline
https://www.typescriptlang.org/play?target=99#code/JYOwLgpgTgZghgYwgAgILIN4ChnJALjwFcBbAI2gG4sBfLLBAGzgGcXkAhTHZBAexAswUIgjB8oACgAORMo2AJkUCHAAmAxgE9kcQqgCU3XHR6z5i5ao0hteZAF5kYABbAWAOjgeQ1U-0EwZDJHPAgAd05JDDxCAEZkGgNqAJY+RggPRj4Ac0kyZKwgA

### Compiled
```js
"use strict";
class B {
    constructor(a) {
        this.a = a;
        this.n = this.a.n;
    }
}
const b = new B({ n: 1 });
console.log(b);
```

## Working in v0.17.19
https://esbuild.github.io/try/#dAAwLjE3LjE5AC0tbG9hZGVyPXRzIC0tdGFyZ2V0PW5vZGUxMgBpbnRlcmZhY2UgQSB7CiAgbjogbnVtYmVyOwp9CgpjbGFzcyBCIHsKICBjb25zdHJ1Y3RvcihwdWJsaWMgcmVhZG9ubHkgYTogQSkgewogIH0KCiAgcHVibGljIHJlYWRvbmx5IG4gPSB0aGlzLmEubjsKfQoKY29uc3QgYiA9IG5ldyBCKHsgbjogMSB9KTsKY29uc29sZS5sb2coYik7

### Compiled
```js
class B {
  constructor(a) {
    this.a = a;
    this.n = this.a.n;
  }
}
const b = new B({ n: 1 });
console.log(b);
```

## Not working in v0.18.0+
https://esbuild.github.io/try/#dAAwLjE4LjAALS1sb2FkZXI9dHMgLS10YXJnZXQ9bm9kZTEyAGludGVyZmFjZSBBIHsKICBuOiBudW1iZXI7Cn0KCmNsYXNzIEIgewogIGNvbnN0cnVjdG9yKHB1YmxpYyByZWFkb25seSBhOiBBKSB7CiAgfQoKICBwdWJsaWMgcmVhZG9ubHkgbiA9IHRoaXMuYS5uOwp9Cgpjb25zdCBiID0gbmV3IEIoeyBuOiAxIH0pOwpjb25zb2xlLmxvZyhiKTs

### Compiled
```js
class B {
  constructor(a) {
    this.a = a;
  }
  n = this.a.n;
}
const b = new B({ n: 1 });
console.log(b);
```

### Error
```
$ node a.js
/a.js:5
	n = this.a.n;
	           ^

TypeError: Cannot read properties of undefined (reading 'n')
    at <instance_members_initializer> (/a.js:5:13)
    at new B (/a.js:2:13)
    at Object.<anonymous> (/a.js:7:13)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47

Node.js v18.7.0
```

## Related issue
https://github.com/esbuild-kit/tsx/issues/280

**Comment by evanw** [comment] 2023-09-14 22:36
TypeScript can also match esbuild's behavior: https://www.typescriptlang.org/play?useDefineForClassFields=true&target=99#code/JYOwLgpgTgZghgYwgAgILIN4ChnJALjwFcBbAI2gG4sBfLLBAGzgGcXkAhTHZBAexAswUIgjB8oACgAORMo2AJkUCHAAmAxgE9kcQqgCU3XHR6z5i5ao0hteZAF5kYABbAWAOjgeQ1U-0EwZDJHPAgAd05JDDxCAEZkGgNqAJY+RggPRj4Ac0kyZKwgA

And esbuild can also match TypeScript's behavior: https://esbuild.github.io/try/#dAAwLjE4LjAALS1sb2FkZXI9dHMgLS10YXJnZXQ9bm9kZTEyICctLXRzY29uZmlnLXJhdz17ImNvbXBpbGVyT3B0aW9ucyI6eyJ1c2VEZWZpbmVGb3JDbGFzc0ZpZWxkcyI6ZmFsc2V9fScAaW50ZXJmYWNlIEEgewogIG46IG51bWJlcjsKfQoKY2xhc3MgQiB7CiAgY29uc3RydWN0b3IocHVibGljIHJlYWRvbmx5IGE6IEEpIHsKICB9CgogIHB1YmxpYyByZWFkb25seSBuID0gdGhpcy5hLm47Cn0KCmNvbnN0IGIgPSBuZXcgQih7IG46IDEgfSk7CmNvbnNvbGUubG9nKGIpOw

The difference is caused by the [`useDefineForClassFields`](https://www.typescriptlang.org/tsconfig#useDefineForClassFields) setting in `tsconfig.json`. If you read the [release notes for v0.18.0](https://github.com/evanw/esbuild/releases/v0.18.0) you can see that esbuild's default behavior changed regarding `useDefineForClassFields`. You can read the release notes for all the details.

In any case, if you actually try to build the code in https://github.com/esbuild-kit/tsx/issues/280 with that `main.ts` file, that `tsconfig.json` file (with `"noEmit": true` removed), and that version of TypeScript, `tsc` will generate the following output:

```js
"use strict";
class B {
    a;
    constructor(a) {
        this.a = a;
    }
    n = this.a.n;
}
const b = new B({ n: 1 });
console.log(b);
```

Which is exactly the same as what esbuild generates. Furthermore if you update from TypeScript 5.1 to TypeScript 5.2, that person's code actually generates an error at build time:

```
main.ts:9:28 - error TS2729: Property 'a' is used before its initialization.

9   public readonly n = this.a.n;
                             ~

  main.ts:6:15
    6   constructor(public readonly a: A) {
                    ~~~~~~~~~~~~~~~~~~~~
    'a' is declared here.
```

That person's code is broken. I'm closing this issue because esbuild is working as intended here. I do not consider this to be a regression.

If that user wants legacy TypeScript class field behavior, then they should set `useDefineForClassFields: false` in their `tsconfig.json` file to explicitly opt-into the legacy class field behavior.

**Closed by evanw** 2023-09-14 22:36 UTC

**Comment by magic-akari** [comment] 2023-09-15 03:35
FYI: TypeScript behaviors may vary inconsistently across different targets.
With the target <= es2021 , you will get the expected results.

check it: https://www.typescriptlang.org/play?useDefineForClassFields=true&target=8&ssl=2&ssc=13&pln=2&pc=19#code/PTAEAEFcGcFMBFYDMCWA7WAxA9gJwMIA2AhtNJirIQCbQBcoALrpLAFAgSPG4DmsjBrGgAmAAwiAjG3SNYuJMQDGsUAEFQAbzahQaBmkgBbAEbyA3GwC+bNkpJlQAIS07QS7GmjNISxngAKAAdIE0IUJVBcWGJqT0IAT1BiBjUASlddGzcQsIiomLi0RL1QAF4mAAsUaAA6Ylq0S2yPL0ZQE3K9WAB3ZwDNPQZJUCs0y1bobEJYWsJsXgCTcbYgA

related issue: https://github.com/swc-project/swc/pull/7055#issuecomment-1464897834

**Comment by evanw** [comment] 2023-09-15 04:43
Yes. This inconsistency is also replicated by esbuild (as described in the release notes linked above). IMO it’s still clearest to set `useDefineForClassFields` explicitly instead of relying on this extremely confusing behavior of TypeScript’s `target` setting.

**Comment by privatenumber** [comment] 2023-09-15 06:41
Should've seen this in the release notes. Sorry for not looking into this deeper.
As always, thank you for taking the time to carefully explain!
