### ISSUE TITLE
Imports order using code splitting

### ISSUE THREAD

**Issue by elv1n** [evanw/esbuild#417] opened 2020-09-28 12:13 UTC
The example I'm providing is not actually accurate in how modules should be imported but I think it could point on a defect that can cause issues.

Let's say we have the next structure

```
// index.ts
import { Import1 } from './components'
import { Import2 } from './base'


export const getChunk = () => import('./chunk')
export {
    Import1,
    Import2,
}

// chunk.ts
import { Import1 } from './components'
import { Import2 } from './base'

export const Ui = {
    Import1,
    Import2,
}
```

In the output bundled chunk, the second import declared first

```
// base/index.ts
const Import2 = 22;

// /components/index.ts
const Import1 = 1;

export {
  Import2,
  Import1
};
```

In all other cases, like leaving imports only in chunk or in the entry file imports will be ordered as declared.
After renaming directories order changed

**Comment by evanw** [comment] 2020-09-28 21:07
Closing as a duplicate of #399. This issue arose from a misunderstanding of mine about the ordering constraints of ES6 import statements. I believe it only happens when code splitting is enabled. Fixing this means coming up with a new algorithm instead of simply fixing a bug, so it's not something I can quickly release a patch for unfortunately.

**Closed by evanw** 2020-09-28 21:07 UTC
