### ISSUE TITLE
Error: Command failed: /Users/~/n/node_modules/esbuild/bin/esbuild --version

### ISSUE THREAD

**Issue by 617qqq** [evanw/esbuild#2586] opened 2022-10-01 17:45 UTC
when i try to run 'npm install esbuild',  (node : 16.0.0; npm 6.14.17)
node:child_process:707
    err = new Error(msg);
          ^

Error: Command failed: /Users/liuyq/other/code/vue/babyRecord/n/node_modules/esbuild/bin/esbuild --version
dyld: Symbol not found: _SecTrustEvaluateWithError
  Referenced from: /Users/liuyq/other/code/vue/babyRecord/n/node_modules/esbuild/bin/esbuild
  Expected in: flat namespace

    at checkExecSyncError (node:child_process:707:11)
    at Object.execFileSync (node:child_process:726:15)
    at validateBinaryVersion (/Users/liuyq/other/code/vue/babyRecord/n/node_modules/esbuild/install.js:90:32)
    at /Users/liuyq/other/code/vue/babyRecord/n/node_modules/esbuild/install.js:243:5 {
  status: null,
  signal: 'SIGABRT',
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(175) [Uint8Array] [
      100, 121, 108, 100,  58,  32,  83, 121, 109,  98, 111, 108,
       32, 110, 111, 116,  32, 102, 111, 117, 110, 100,  58,  32,
       95,  83, 101,  99,  84, 114, 117, 115, 116,  69, 118,  97,
      108, 117,  97, 116, 101,  87, 105, 116, 104,  69, 114, 114,
      111, 114,  10,  32,  32,  82, 101, 102, 101, 114, 101, 110,
       99, 101, 100,  32, 102, 114, 111, 109,  58,  32,  47,  85,
      115, 101, 114, 115,  47, 108, 105, 117, 121, 113,  47, 111,
      116, 104, 101, 114,  47,  99, 111, 100, 101,  47, 118, 117,
      101,  47,  98,  97,
      ... 75 more items
    ]
  ],
  pid: 3729,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(175) [Uint8Array] [
    100, 121, 108, 100,  58,  32,  83, 121, 109,  98, 111, 108,
     32, 110, 111, 116,  32, 102, 111, 117, 110, 100,  58,  32,
     95,  83, 101,  99,  84, 114, 117, 115, 116,  69, 118,  97,
    108, 117,  97, 116, 101,  87, 105, 116, 104,  69, 114, 114,
    111, 114,  10,  32,  32,  82, 101, 102, 101, 114, 101, 110,
     99, 101, 100,  32, 102, 114, 111, 109,  58,  32,  47,  85,
    115, 101, 114, 115,  47, 108, 105, 117, 121, 113,  47, 111,
    116, 104, 101, 114,  47,  99, 111, 100, 101,  47, 118, 117,
    101,  47,  98,  97,
    ... 75 more items
  ]
}
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/android-arm@0.15.10 (node_modules/esbuild/node_modules/@esbuild/android-arm):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/android-arm@0.15.10: wanted {"os":"android","arch":"arm"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/linux-loong64@0.15.10 (node_modules/esbuild/node_modules/@esbuild/linux-loong64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/linux-loong64@0.15.10: wanted {"os":"linux","arch":"loong64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-android-64@0.15.10 (node_modules/esbuild/node_modules/esbuild-android-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-android-64@0.15.10: wanted {"os":"android","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-darwin-arm64@0.15.10 (node_modules/esbuild/node_modules/esbuild-darwin-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-darwin-arm64@0.15.10: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-android-arm64@0.15.10 (node_modules/esbuild/node_modules/esbuild-android-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-android-arm64@0.15.10: wanted {"os":"android","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-freebsd-64@0.15.10 (node_modules/esbuild/node_modules/esbuild-freebsd-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-freebsd-64@0.15.10: wanted {"os":"freebsd","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-freebsd-arm64@0.15.10 (node_modules/esbuild/node_modules/esbuild-freebsd-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-freebsd-arm64@0.15.10: wanted {"os":"freebsd","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-32@0.15.10 (node_modules/esbuild/node_modules/esbuild-linux-32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-32@0.15.10: wanted {"os":"linux","arch":"ia32"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-64@0.15.10 (node_modules/esbuild/node_modules/esbuild-linux-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-64@0.15.10: wanted {"os":"linux","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-arm64@0.15.10 (node_modules/esbuild/node_modules/esbuild-linux-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-arm64@0.15.10: wanted {"os":"linux","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-arm@0.15.10 (node_modules/esbuild/node_modules/esbuild-linux-arm):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-arm@0.15.10: wanted {"os":"linux","arch":"arm"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-mips64le@0.15.10 (node_modules/esbuild/node_modules/esbuild-linux-mips64le):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-mips64le@0.15.10: wanted {"os":"linux","arch":"mips64el"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-ppc64le@0.15.10 (node_modules/esbuild/node_modules/esbuild-linux-ppc64le):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-ppc64le@0.15.10: wanted {"os":"linux","arch":"ppc64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-riscv64@0.15.10 (node_modules/esbuild/node_modules/esbuild-linux-riscv64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-riscv64@0.15.10: wanted {"os":"linux","arch":"riscv64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-s390x@0.15.10 (node_modules/esbuild/node_modules/esbuild-linux-s390x):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-s390x@0.15.10: wanted {"os":"linux","arch":"s390x"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-netbsd-64@0.15.10 (node_modules/esbuild/node_modules/esbuild-netbsd-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-netbsd-64@0.15.10: wanted {"os":"netbsd","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-openbsd-64@0.15.10 (node_modules/esbuild/node_modules/esbuild-openbsd-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-openbsd-64@0.15.10: wanted {"os":"openbsd","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-windows-32@0.15.10 (node_modules/esbuild/node_modules/esbuild-windows-32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-windows-32@0.15.10: wanted {"os":"win32","arch":"ia32"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-sunos-64@0.15.10 (node_modules/esbuild/node_modules/esbuild-sunos-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-sunos-64@0.15.10: wanted {"os":"sunos","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-windows-arm64@0.15.10 (node_modules/esbuild/node_modules/esbuild-windows-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-windows-arm64@0.15.10: wanted {"os":"win32","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-windows-64@0.15.10 (node_modules/esbuild/node_modules/esbuild-windows-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-windows-64@0.15.10: wanted {"os":"win32","arch":"x64"} (current: {"os":"darwin","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! esbuild@0.15.10 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the esbuild@0.15.10 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/liuyq/.npm/_logs/2022-10-01T17_40_03_782Z-debug.log

**Comment by evanw** [comment] 2022-10-01 17:47
Duplicate of #2183. You are running an unsupported version of macOS that's too old to run esbuild. You can see that thread for possible workarounds.

Closing as this is not something that esbuild can fix.

**Closed by evanw** 2022-10-01 17:47 UTC

**Comment by gitxiaobao** [comment] 2022-11-04 08:30
macOS 旧版本为何不支持
