### ISSUE TITLE
Sourcemap for original source isn't included for type-only cjs exports under pnp

### ISSUE THREAD

**Issue by ASDFGerte** [evanw/esbuild#2767] opened 2022-12-22 12:42 UTC
For files exporting types only, under yarn pnp, bundling cjs input (here coming from TS), the original ".ts" file isn't included in the sourcemap, but only the ".js" file. This does not impact functionality at all, but leads to e.g. chrome showing annoying errors, as it sees the ".js" file with sourcemap annotation, but cannot find the related ".js.map" file, as it doesn't understand zip archives in paths, nor would the file be always available.

As an example (here the setup is more complex, the cjs module is in a package):
```
Could not read source map for file:///[...]/.yarn/cache/[...].js: ENOENT: no such file or directory, open '[...]\.yarn\cache\[...].js.map'
```

I am not sure, whether there is a configuration I can choose to fix the problem on my end. I assume a full switch to esm would solve the problem (tree-shaking would probably remove the file altogether), but did not test it, plus this isn't always feasible.

---

"src" will be compiled by tsc to "bin", which in turn is bundled by esbuild:

```
📁
├─📁 src
│ ├─📄 index.ts
│ └─📄 types.ts
├─📁 bin
└─📁 public
```

```ts
// index.ts
export * from './types.js';
// types.ts
export type T = never;
```

The resulting input to esbuild then has an "index.js" where the import is to an empty js module, and due to being cjs not tree-shaken:

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const tslib_1 = require("tslib");
tslib_1.__exportStar(require("./types.js"), exports);
//# sourceMappingURL=index.js.map
```

And "types.js.map" links to the related ts file, but has no mappings:

```
{"version":3,"file":"types.js","sourceRoot":"","sources":["../src/types.ts"],"names":[],"mappings":""}
```

Bundling results in a "bundle.js.map" that only has the related js file (entry for "tslib" removed):

```
"sources": ["../bin/types.js", "../src/index.ts"]
```

---

Notes:
 - Adding an exported value to "types.ts" fixes the problem.
 - Due to a debugger never being in a type-only file, this only produces annoying errors in the console on startup. Apart from that, everything works.
 - Should the `export *` be explicitly marked as `type`? Yes, but that's blocked by [TS #37238](https://www.github.com/microsoft/TypeScript/issues/37238).
 - I once tried changing to a setup with all the type-only exports in `.d.ts` files, but reverted due to various annoying technicalities.

---

esbuild 0.16.10
chrome Version 108.0.5359.125 (Official Build) (64-bit)

**Comment by evanw** [comment] 2022-12-23 18:12
> And "types.js.map" links to the related ts file, but has no mappings:

I think this is the underlying problem. Mappings are what associates a part of the output file with an input file. Without any mappings, there is no link from the output file back to an input file, and it could be incorrect for esbuild to make assumptions like this. So this is a bug with TypeScript, not with esbuild.

I suppose I could have esbuild assume that if there are no mappings but there is a single source file, then there should be a mapping from the start of the output file to the start of the input file. That should be sufficient to fix this broken source map and get the intended behavior.

**Comment by evanw** [comment] 2022-12-23 18:40
Actually, I'm not sure I should do this. It doesn't seem correct to make this assumption. The code in the output file might be totally unrelated to the input file. For example, you could imagine a tool that bundles together two files, file A which doesn't have an input source map but results in generated code, and file B which has an input source map but does not result in generated code. Then the resulting generated code could consist entirely of file A but the generated source map `sources` array could only have file B. So esbuild automatically generating a mapping from the start of the output to the start of the only source file could be incorrect.

I'm going to close this issue because I think esbuild is actually working correctly here. I think this bug should be fixed on TypeScript's side.

**Closed by evanw** 2022-12-23 18:40 UTC
