### ISSUE TITLE
Wrong import order.

### ISSUE THREAD

**Issue by houd1ni** [evanw/esbuild#3012] opened 2023-03-22 08:07 UTC
Hi! There's a weird issue in my project: a dependency file goes far after its' import. There are bundle pieces:

It is a usage of ORM class that in source was imported above this line in the same this file:
![image](https://user-images.githubusercontent.com/7501201/226837882-eb5fa31d-4df2-4559-85cc-217263f18db9.png)

And this was that ORM class object construction and export:
![image](https://user-images.githubusercontent.com/7501201/226837913-05dda6a4-cec4-4685-8034-70c5f0fa589d.png)

Therefore, `.use` of the first one is called on undefined: var is hoisted but still unassigned.

There are no loop dependencies if pick exported variables separately, but there's one, if place modules by copy-paste as files.
Removing the last, all interprets well.
The change suggested in this issue does not change output at all: https://github.com/evanw/esbuild/issues/1582
The dependencies are like this, with fully isolated exports in the case:
```javascript
// utils.js
import { proxyVar } from './proxy'
export const util1 = proxyVar+1

// db.js
import { util1 } from './utils'
export const orm = new ORM({ utils: [util1] })

// proxy.js
import { orm } from '../../../db'
orm.use(...)
export const proxyVar = 5   // 5 is just for example.
```

Why esbuild simply merging files ?
Is there a way to make it think more like rollup for example ? At least, it seems to support tree-shaking of unused exports, hence should be able to order that exports in a sane way.
Thanks!

**Comment by evanw** [comment] 2023-03-22 14:49
Please provide a self-contained way to reproduce the issue.

**Comment by houd1ni** [comment] 2023-03-25 00:05
okay, sure. I'll take some time to extract that code to readable case.

**Comment by evanw** [comment] 2023-04-04 13:34
I'm closing this due to lack of a follow-up reply. We can reopen this if more info is provided.

**Closed by evanw** 2023-04-04 13:34 UTC
Labels: unactionable
