### ISSUE TITLE
Can't bundle @prisma/client

### ISSUE THREAD

**Issue by kensukesaito** [evanw/esbuild#1181] opened 2021-04-23 01:11 UTC
# Description

Can't bundle @prisma/client.

```
$ npx esbuild --bundle --format=cjs --outdir=dist --platform=node src/index.ts

 > node_modules/@prisma/client/runtime/index.js:24152:23: error: Could not resolve "_http_common" (mark it as external to exclude it from the bundle, or surround it with try/catch to handle the failure at run-time)
    24152 │   var common = require("_http_common");
          ╵                        ~~~~~~~~~~~~~~
```

# Reproduction

```json
// package.json
{
  "name": "test",
  "scripts": {
    "build": "esbuild --bundle --format=cjs --outdir=dist --platform=node src/index.ts"
  },
  "dependencies": {
    "@prisma/client": "^2.21.2"
  },
  "devDependencies": {
    "esbuild": "^0.11.12",
    "prisma": "^2.21.2"
  }
}
```

```prisma
// schema.prisma
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "rhel-openssl-1.0.x"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Book {
  id          String        @id @default(dbgenerated("uuid_generate_v4()")) @db.Uuid
  title       String?
  author      String?
  description String?
  price       Int?
}
```

```typescript
// src/index.ts
import * as Prisma from '@prisma/client'

const prisma = new Prisma.PrismaClient()
```

```
// ✅ Before `prisma generate`, can bundle successfully.
$ npm run build                         

> test@1.0.0 build
> esbuild --bundle --format=cjs --outdir=dist --platform=node src/index.ts

  dist/index.js  2.0kb

⚡ Done in 2ms
```

```
$ npx prisma generate                   
Prisma schema loaded from schema.prisma

✔ Generated Prisma Client (2.21.2) to ./node_modules/@prisma/client in 152ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
```

```
// ❌ After `prisma generate`, can't bundle.
$ npm run build

> test@1.0.0 build
> esbuild --bundle --format=cjs --outdir=dist --platform=node src/index.ts

 > node_modules/@prisma/client/runtime/index.js:24152:23: error: Could not resolve "_http_common" (mark it as external to exclude it from the bundle, or surround it with try/catch to handle the failure at run-time)
    24152 │   var common = require("_http_common");
          ╵                        ~~~~~~~~~~~~~~

1 error
```

Does anyone have any idea?

Source code
https://codesandbox.io/s/upbeat-https-bgy4c

**Comment by evanw** [comment] 2021-04-23 02:44
I assume this is a bug with that library. The package `_http_common` doesn't exist anywhere on the file system with these reproduction instructions.

I googled it for you and this is the bug: https://github.com/prisma/prisma/issues/6564. There is also some context here: https://github.com/prisma/prisma/pull/6463#pullrequestreview-633524299. It looks like this package is maybe supposed to be external. In that case you can pass `--external:_http_common` to esbuild to allow this package to be bundled.

I'm closing this issue as it's not a problem with esbuild.

**Closed by evanw** 2021-04-23 02:44 UTC

**Comment by prescience-data** [comment] 2021-04-26 09:54
fwiw, `http_common` cannot be external if you have any reliance on node `http` module.
However, it is definitely a Prisma issue, rather than an esbuild issue.

**Comment by matthewmueller** [comment] 2021-06-02 13:34
I actually think this is a bundler issue for the unfortunate reason that Node developers use private APIs. In this example, https://github.com/nodejs/undici is using this private API.

To see this in action:
```
node -e "console.log(require('_http_common'))"
```

I feel like in the same way that when you specify `platform: "node"` it doesn't complain about `require('http')`, some of the private require-able APIs should be treated the same way.
