### ISSUE TITLE
How to work with core-js ? 

### ISSUE THREAD

**Issue by vaynevayne** [evanw/esbuild#3803] opened 2024-06-15 14:16 UTC
I know ESBUILD doesn't add any polyfill, but I was wondering how to configure useage injection for core-js in an esbuild project? For example, I use Vite

**Comment by evanw** [comment] 2024-06-15 14:39
Sorry, I don't know anything about core-js. I did a web search for you and found [this](https://vitejs.dev/guide/build#browser-compatibility):

> Note that by default, Vite only handles syntax transforms and **does not cover polyfills**. You can check out [Polyfill.io](https://polyfill.io/) which is a service that automatically generates polyfill bundles based on the user's browser UserAgent string.

You could consider asking Vite and/or core-js for additional information if needed.

**Comment by vaynevayne** [comment] 2024-06-15 18:10
Are You Ai?

**Comment by evanw** [comment] 2024-06-15 18:11
What? No. In any case, I'm closing this issue as this isn't a bug with esbuild.

**Closed by evanw** 2024-06-15 18:11 UTC

**Comment by vaynevayne** [comment] 2024-06-15 18:17
Well, it's not an esbuild issue, so can I just ask a technical question? How Do I use core-js in Vite + esbuild projects?
```jsx
// main.js
import "core-js";

[].at(-1)
```

This is invalid. It looks like core-js is being treeshaking
@evanw

**Comment by evanw** [comment] 2024-06-15 18:36
It doesn't look like esbuild tree-shakes this. Running `echo 'import "core-js"; [].at(-1)' | esbuild --bundle` gives 900kb of output for me. If you have a case where esbuild's bundler is tree-shaking something incorrectly, then you'd need to provide specific reproduction instructions for me to be able to fix the bug with esbuild.

Note that this is the esbuild repo, not the Vite repo. It's possible that Vite's bundler is doing something different that what esbuild's bundler does. As far as I know Vite uses Rollup for bundling, not esbuild, and also layers a lot of custom stuff on top. If you have a Vite-specific question then you should ask on the Vite repo instead: https://github.com/vitejs/vite.

**Comment by zloirock** [comment] 2024-06-15 19:12
> It doesn't look like esbuild tree-shakes this. Running `echo 'import "core-js"; [].at(-1)' | esbuild --bundle` gives 900kb of output for me.

Polyfills optimization / injection requires some specific logic like it's implemented in [SWC](https://swc.rs/docs/configuration/supported-browsers#corejs) or [Babel](https://babeljs.io/docs/babel-preset-env). Since `esbuild` also transforms new syntax features, it could be good to have the same for the standard library features (polyfills optimization / injection) to avoid extra tooling in the development stack.

In case if you are interested in implementing this, I can open an issue and consult about it.

**Comment by mctrafik** [comment] 2025-08-08 21:12
For core-js stuff, I think it's possible to build an esbuild plugin that inject the polyfills as a JS banner. It's not ideal, but I think that would work.
