### ISSUE TITLE
[Bug?] Code splitting not emitting the entry point

### ISSUE THREAD

**Issue by BobobUnicorn** [evanw/esbuild#898] opened 2021-02-27 21:10 UTC
I'm sorry that I don't have a repro, because I'm not even sure why it's happening. The code base is private.

When I enable code splitting, the entrypoint file is not generated.

If there are any tips as to how to debug this, I would love to hear it!

**Comment by heyheyhello** [comment] 2021-02-28 07:21
Can you provide more information please? The esbuild script, or command invocation to start. 

Was this working before codesplitting? Is enabling/disabling that feature in isolation really enough to recreate the issue on your end?

**Comment by BobobUnicorn** [comment] 2021-02-28 19:08
Yes, setting `splitting: true` is the only difference.

The config object is:
```
{
  "entryPoints": [
    "bazel-out/k8-fastbuild/bin/src/ng/main.localdev.mjs"
  ],
  "bundle": true,
  "outdir": "bazel-out/k8-fastbuild/bin/src/ng/localdevbundle",
  "platform": "browser",
  "loader": {},
  "define": {
    "process.env.NODE_ENV": "\"development\"",
    "process.env.NODE_DEBUG": "\"\"",
    "global": "window",
    "process.platform": "\"browser\""
  },
  "target": "esnext",
  "logLevel": "error",
  "tsconfig": "tsconfig.json",
  "external": [
    "firebase-admin",
    "domain"
  ],
  "color": true,
  "sourcemap": true,
  "format": "esm"
}
```

**Comment by heyheyhello** [comment] 2021-02-28 19:43
How are you handling errors in the build script? Maybe you have a `.catch()` which is silently hiding errors. The entire build script and package.json invocation would be helpful, I assume you're running this with node/npm?

**Comment by BobobUnicorn** [comment] 2021-02-28 20:55
No, it's in bazel. There are no errors emitted. There is one warning:
```
{
  "warnings": [
    {
      "location": {
        "column": 7,
        "file": "../../../../../../../../../[redacted]/node_modules/mathjs/es/core/create.js",
        "length": 22,
        "line": 3,
        "lineText": "import './../utils/polyfills';",
        "namespace": ""
      },
      "notes": [
        {
          "location": {
            "column": 2,
            "file": "../../../../../../../../../[redacted]/node_modules/mathjs/package.json",
            "length": 13,
            "line": 136,
            "lineText": "  \"sideEffects\": false",
            "namespace": ""
          },
          "text": "\"sideEffects\" is false in the enclosing \"package.json\" file"
        }
      ],
      "text": "Ignoring this import because \"../../../../../../../../../[redacted]/node_modules/mathjs/es/utils/polyfills.js\" was marked as having no side effects"
    }
  ]
}
```

Some chunks are emitted, but there's no entrypoint.

```
 cassc@cassc-MINIPC-PN50 ~/[redacted]  $ ls bazel-bin/src/ng/localdevbundle/**
bazel-bin/src/ng/localdevbundle/chunk.3P6XRYPA.js.map*
bazel-bin/src/ng/localdevbundle/chunk.4RMQ724H.js*
bazel-bin/src/ng/localdevbundle/chunk.BLMKQZNR.js.map*
bazel-bin/src/ng/localdevbundle/chunk.MTRAL5PF.js*
bazel-bin/src/ng/localdevbundle/chunk.Q7IVXFGJ.js*
bazel-bin/src/ng/localdevbundle/chunk.U7E2XJI5.js.map*
bazel-bin/src/ng/localdevbundle/[redacted]/node_modules/firebase/auth/dist/index.esm.js*
bazel-bin/src/ng/localdevbundle/[redacted]/node_modules/firebase/auth/dist/index.esm.js.map*
bazel-bin/src/ng/localdevbundle/[redacted]/node_modules/firebase/functions/dist/index.esm.js*
bazel-bin/src/ng/localdevbundle/[redacted]/node_modules/firebase/functions/dist/index.esm.js.map*

bazel-bin/src/ng/localdevbundle/[redacted]:
node_modules/

bazel-bin/src/ng/localdevbundle/[redacted]/node_modules:
firebase/

bazel-bin/src/ng/localdevbundle/[redacted]/node_modules/firebase:
auth/  functions/

bazel-bin/src/ng/localdevbundle/[redacted]/node_modules/firebase/auth:
dist/

bazel-bin/src/ng/localdevbundle/[redacted]/node_modules/firebase/auth/dist:
index.esm.js*  index.esm.js.map*

bazel-bin/src/ng/localdevbundle/[redacted]/node_modules/firebase/functions:
dist/

bazel-bin/src/ng/localdevbundle/[redacted]/node_modules/firebase/functions/dist:
index.esm.js*  index.esm.js.map*
```

This is the output with code splitting disabled:
```
 cassc@cassc-MINIPC-PN50 ~/[redacted]  $ ls bazel-bin/src/ng/localdevbundle/**
bazel-bin/src/ng/localdevbundle/main.localdev.css*
bazel-bin/src/ng/localdevbundle/main.localdev.js*
bazel-bin/src/ng/localdevbundle/main.localdev.js.map*
```

**Comment by evanw** [comment] 2021-03-01 09:02
Sorry to hear that this is happening. I might not be able to help too much without a way to reproduce this.

Some ideas for how to debug this further:

* Does this happen when you run esbuild directly without using bazel? Perhaps the problem is bazel and not esbuild?

* There is an option called [metafile](https://esbuild.github.io/api/#metafile) that generates a JSON file describing all inputs and outputs in the bundling operation. In particular, output files corresponding to the entry point should have an `entryPoint` property that links back to the entry point. Does that file contain any information that might help explain what's happening?

**Comment by BobobUnicorn** [comment] 2021-03-04 00:12
The metafile helped! It looks like the entrypoints were being output in a totally different directory. I wonder if it's something to do with how bazel sets up the working environment; it does make use of a lot of symlinks.

**Comment by evanw** [comment] 2021-03-04 20:33
Glad you were able to get more information. I'm going to close this issue in this case because it sounds like a bug with your Bazel integration instead of with esbuild itself.

**Closed by evanw** 2021-03-04 20:33 UTC
