### ISSUE TITLE
instanceof not working in v 0.19.1

### ISSUE THREAD

**Issue by sebastianwessel** [evanw/esbuild#3379] opened 2023-09-12 18:04 UTC
I'm using custom errors for my lib (typescript).

```ts
export class HandledError extends Error {
  constructor(
    public errorCode: StatusCode,
    message?: string,
    public data?: unknown,
    public traceId?: TraceId,
  ) {
    /* Calling the constructor of the parent class (Error) and passing the message. */
    super(message || getErrorMessageForCode(errorCode))
    Error.captureStackTrace(this, this.constructor)

    Object.setPrototypeOf(this, HandledError.prototype)
    this.name = this.constructor.name
  }
 }
 ```
 
This fails;
 
 ```ts
 import { HandledError } from 'lib'
 
 if (err instanceof HandledError) {
    // the if-clause becomes never true
 }
 ```
 
The build script looks like this:

```js
esbuild
  .build({
    entryPoints: ['./src/index.ts'],
    outfile: './lib/cjs/index.cjs',
    bundle: true,
    format: 'cjs',
    splitting: false,
    platform: 'node',
    sourcemap: false,
    target: 'node18',
    minify: true,
    packages: 'external',
    keepNames: true,
  })
  .catch(() => process.exit(1))
```

It worked like a charm with ^0.18.11 and earlier.

I also tried to disable `minify` and added `keepNames` without any luck.

Any ideas if this is an issue in esbuild or if I'm doing something wrong?

**Comment by evanw** [comment] 2023-09-12 18:54
Sorry but you did not provide a way to reproduce the issue, so I can't help you. Please provide a way to reproduce the issue.

Did you by any chance see [these instructions](https://github.com/evanw/esbuild/blob/cc74cd0f50bc58b768b24685e2440316266e2fac/.github/ISSUE_TEMPLATE/new-issue.md?plain=1#L15) when you created an issue?

> * Provide a way to reproduce the issue. The best way to do this is to demonstrate the issue on the playground (https://esbuild.github.io/try/) and paste the URL here. A link to a minimal code sample with instructions for how to reproduce the issue may also work. Issues without a way to reproduce them may be closed.

The reason I'm asking this because I'm trying to provide instructions for people so that they create useful issues that I can do something with. But almost no one seems to be following the instructions, so I'm wondering if something about how the instructions are written is confusing, or perhaps GitHub isn't actually showing the instructions to people at all when they create a new issue. Your feedback on the new issue flow could potentially be helpful for me.

**Comment by lukeed** [comment] 2023-09-12 19:09
I was curious so I [started a REPL](https://esbuild.github.io/try/#YgAwLjE5LjIAewogIGJ1bmRsZTogdHJ1ZSwKICBmb3JtYXQ6ICdjanMnLAogIHNwbGl0dGluZzogZmFsc2UsCiAgcGxhdGZvcm06ICdub2RlJywKICBzb3VyY2VtYXA6IGZhbHNlLAogIHRhcmdldDogJ25vZGUxOCcsCiAgbWluaWZ5OiB0cnVlLAogIHBhY2thZ2VzOiAnZXh0ZXJuYWwnLAogIGtlZXBOYW1lczogdHJ1ZSwKfQBlAGVudHJ5LmpzAGltcG9ydCB7IEhhbmRsZWRFcnJvciwgb3RoZXIgfSBmcm9tICcuL2xpYicKCmxldCBlcnIgPSBuZXcgSGFuZGxlZEVycm9yKDQwNCwgJ05vdCBGb3VuZCcpOwpjb25zb2xlLmxvZyhlcnIsIGVyciBpbnN0YW5jZW9mIEhhbmRsZWRFcnJvcik7Cgpjb25zb2xlLmxvZygnb3RoZXInLCBvdGhlcigpIGluc3RhbmNlb2YgSGFuZGxlZEVycm9yKTsAAGxpYi50cwBleHBvcnQgY2xhc3MgSGFuZGxlZEVycm9yIGV4dGVuZHMgRXJyb3IgewogIGNvbnN0cnVjdG9yKAogICAgcHVibGljIGVycm9yQ29kZTogU3RhdHVzQ29kZSwKICAgIG1lc3NhZ2U/OiBzdHJpbmcsCiAgICBwdWJsaWMgZGF0YT86IHVua25vd24sCiAgICBwdWJsaWMgdHJhY2VJZD86IFRyYWNlSWQsCiAgKSB7CiAgICAvKiBDYWxsaW5nIHRoZSBjb25zdHJ1Y3RvciBvZiB0aGUgcGFyZW50IGNsYXNzIChFcnJvcikgYW5kIHBhc3NpbmcgdGhlIG1lc3NhZ2UuICovCiAgICBzdXBlcihtZXNzYWdlIHx8IGdldEVycm9yTWVzc2FnZUZvckNvZGUoZXJyb3JDb2RlKSkKICAgIEVycm9yLmNhcHR1cmVTdGFja1RyYWNlKHRoaXMsIHRoaXMuY29uc3RydWN0b3IpCgogICAgT2JqZWN0LnNldFByb3RvdHlwZU9mKHRoaXMsIEhhbmRsZWRFcnJvci5wcm90b3R5cGUpCiAgICB0aGlzLm5hbWUgPSB0aGlzLmNvbnN0cnVjdG9yLm5hbWUKICB9CiB9CgpleHBvcnQgZnVuY3Rpb24gb3RoZXIoKSB7CiAgcmV0dXJuIG5ldyBIYW5kbGVkRXJyb3IoNTAwLCAiT29wcyIpCn0) from the information provided here.

I wasn't able to reproduce this issue, but at least you can use this REPL as a starting point @sebastianwessel

**Comment by sebastianwessel** [comment] 2023-09-12 19:35
Got it a bit more detailed - [see example](https://esbuild.github.io/try/#YgAwLjE5LjIAaW5kZXgudHMgLS1vdXRkaXI9b3V0IC0tYnVuZGxlIC0tZm9ybWF0PWNqcyAtLXNwbGl0dGluZz1mYWxzZSAtLXBsYXRmb3JtPW5vZGUgLS1zb3VyY2VtYXA9ZmFsc2UgLS10YXJnZXQ9bm9kZTE4IC0tbWluaWZ5AGUAZXJyb3IudHMAZXhwb3J0IGNsYXNzIEhhbmRsZWRFcnJvciBleHRlbmRzIEVycm9yIHsKICBjb25zdHJ1Y3RvcigKICAgIHB1YmxpYyBlcnJvckNvZGU6IHN0cmluZywKICAgIG1lc3NhZ2U/OiBzdHJpbmcsCiAgICBwdWJsaWMgZGF0YT86IHVua25vd24sCiAgICBwdWJsaWMgdHJhY2VJZD86IHN0cmluZywKICApIHsKICAgIHN1cGVyKG1lc3NhZ2UgfHwgJ21zZycpCiAgICBFcnJvci5jYXB0dXJlU3RhY2tUcmFjZSh0aGlzLCB0aGlzLmNvbnN0cnVjdG9yKQoKICAgIE9iamVjdC5zZXRQcm90b3R5cGVPZih0aGlzLCBIYW5kbGVkRXJyb3IucHJvdG90eXBlKQogICAgdGhpcy5uYW1lID0gdGhpcy5jb25zdHJ1Y3Rvci5uYW1lCiAgfQogfQoKZXhwb3J0IGNsYXNzIHRlc3QgewogIGZuKCl7CiAgICB0aHJvdyBuZXcgSGFuZGxlZEVycm9yKCcxMDAnLCd0ZXN0IG1zZycpCiAgfQp9CgAAaW5kZXgudHMAaW1wb3J0IHtIYW5kbGVkRXJyb3IsIHRlc3R9IGZyb20gJy4vZXJyb3IudHMnCgp0cnl7CiAgY29uc3QgdCA9IG5ldyB0ZXN0KCkKICB0ZXN0LmZuKCkKfWNhdGNoKGUpIHsKICBpZihlIGluc3RhbmNlb2YgSGFuZGxlZEVycm9yKSB7CiAgICBjb25zb2xlLmxvZygnd29ya3MnKQogIH1lbHNlewogICBjb25zb2xlLmxvZygnZmFpbHMnKQogIH0KfQo)

The issue seems to be, when the custom error is thrown from a function of another class instance.
As far as I can see, it works as expected, when the function is a simple exported function.
Hope that helps a bit more to reproduce.

error.ts
```ts
export class HandledError extends Error {
  constructor(
    public errorCode: string,
    message?: string,
    public data?: unknown,
    public traceId?: string,
  ) {
    super(message || 'msg')
    Error.captureStackTrace(this, this.constructor)

    Object.setPrototypeOf(this, HandledError.prototype)
    this.name = this.constructor.name
  }
 }

export class test {
  fn(){
    throw new HandledError('100','test msg')
  }
}
```

index.ts
```ts
import {HandledError, test} from './error.ts'

try{
  const t = new test()
  test.fn()
}catch(e) {
  if(e instanceof HandledError) {
    console.log('works')
  }else{
   console.log('fails')
  }
}
```

build options:
```
index.ts --outdir=out --bundle --format=cjs --splitting=false --platform=node --sourcemap=false --target=node18 --minify
```

**Comment by evanw** [comment] 2023-09-12 19:41
That code throws `TypeError: test.fn is not a function`, which it isn't. Replacing `test` with `t` makes it work. I'm closing this issue as invalid. You have a bug in your code.

**Closed by evanw** 2023-09-12 19:41 UTC

**Comment by sebastianwessel** [comment] 2023-09-12 20:35
I've prepared a small repo where it is definitely reproducible.

See: [https://github.com/sebastianwessel/temp](https://github.com/sebastianwessel/temp)

Sorry for the poor information in the beginning.
Tbh: I was hoping that someone else also had this issue or had some "hey you only need to"-answer.

Can you have a look again into it @evanw or @lukeed ?

**Comment by evanw** [comment] 2023-09-12 21:01
If you look at `app/lib/cjs/index.cjs` you will find multiple bundled copies of the file that declares `class HandledError`. Each class object has its own identity in JavaScript. This is not a problem with esbuild. You need to structure your build system operations such that each file is only bundled once. 

The simplest solution is to bundle everything together at once using a single esbuild command instead of trying to bundle each file individually and then bundle those bundles together.

**Comment by sebastianwessel** [comment] 2023-09-12 21:35
I see the duplicates of the HandledError and I understand the issue with the copies.

But I really don't understand why this happens.
I mean, these are 3 individual packages, where B relies on A, C relies on A & B and the app on A, B & C.
They shouldn't be bundled together at all.

Regarding the documentation:

> You can exclude all of your dependencies from the bundle by setting [packages](https://esbuild.github.io/api/#packages) to external
> `esbuild app.jsx --bundle --platform=node --packages=external`

My expectation is/was, that the output looks like this:

- A is a own package
- B is a own package which imports/requires needed deps from package A without including A in the bundle of B
- C is a own package which imports/requires needed deps from packages A & B without including A or B in the bundle of C
- The App imports/requires needed deps from packages A, B & C bundle, but does not bundle them into the build of the app

**Comment by evanw** [comment] 2023-09-12 23:12
The "packages" concept that the `--packages` flag refers to is packages that live in `node_modules`. Specifically, node generally [treats paths that don't start with `/`, `../`, or `./` as package paths](https://nodejs.org/api/modules.html#loading-from-node_modules-folders) that reside in `node_modules` folders. When you import from `../a` you are using a relative path, not a package path:

```js
import { HandledError } from "../a";
```

Relative paths are not affected by the `--packages` flag because they are not package paths. So they are included in the bundle when you do this.

**Comment by sebastianwessel** [comment] 2023-09-13 09:12
Don't know how to say thank you 🤷‍♂️

After some deep digging, I finally found the issue nestled deep within the heart of the base tsconfig.js file:

```json
"compilerOptions": {
  [....]
  "paths": {
      "@purista/*": [
        "./packages/*"
      ]
    },
    [....]
}
```

A worng `paths` setting in `tsconfig.json` from the very, very early days, directs esbuild to the source files of the imported stuff, which is correctly seen as "hey I can also bundle it".
Looks like that in version `0.9.x` this setting is higher prioritized than the hint `import { x } from 'package'` or maybe was ignored before 🤷‍♂️.

After removing this unecessarly setting from the base config (which is used on all packaged 🤫), it works as expected.

I don't know how to express my appreciation for your hard work and your assistance in finally resolving the "Problem in front of computer"-issue 🙏
