### ISSUE TITLE
dynamically Importing a missing, optional module, causes esbuild to raise an error

### ISSUE THREAD

**Issue by znewsham** [evanw/esbuild#3216] opened 2023-07-06 17:13 UTC
A shared package I'm maintaining (internal to an org, but shared across multiple services) has optional dependencies - which modify the behaviour of the package - they do this by exposing a global, so the load order is critical (I'm aware this is bad practice, but hard to unwind). When these packages get dynamically imported, the load order isn't enforced (this is "correct"). 

A "fix" for this is to have a dummy function - interestingly, this ensures that load order is obeyed. 

```
function neverCalled() {
import('optionalDependency');
}
```
However, in the case of services which *do not* have that package present, obviously we don't need a catch in this case since the functionality is never called

```
async function someFunction() {
await import("whateverModule");
}
✘ [ERROR] Could not resolve "optionalDependency"

    node_modules/sharedPackage/lib/index.js:16:9:
      16 │   import('optionalDependency');
         ╵          ~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "optionalDependency as external to exclude it from the bundle, which will remove this error. You can also add ".catch()" here to handle this failure at run-time instead of bundle-time.
```

I have a few questions:
1. Should this be a warning, vs an error
2. Does the presence of the error indicate that some other portion of the build has not started (e.g., early exit)
3. Why does the presence of the dynamic import in a function that is never called resolve this problem? I assume it's something to do with the chunking logic.
4. if the package exists, but is never explicitly loaded (e.g., the package is present but the service never excplicitly imports it, and `neverCalled` is, as the name suggests never called, will the code in `optionalDependency` run? This sounds like it should be an obvious "no" - but from looking at the built code, it's not clear.

**Comment by hyrious** [comment] 2023-07-10 07:11
1. I don't think so. Since a bundler should do bundle everything you're asking it to bundle. If the behavior alters just because of someone running `rm -r node_modules/optionalDependency`, then

**Comment by evanw** [comment] 2023-07-10 13:00
1: I think so, yes. Bundling crawls the import graph and anything that isn't explicitly marked as "do not bundle" is an error if it cannot be bundled.

2-4: I don't understand what "some other portion of the build has not started" or "something to do with the chunking logic" or "looking at the built code" means without context, sorry. Providing a self-contained example may help (code + build instructions, ideally on https://esbuild.github.io/try/).

If you want to get rid of the error on the code side instead of marking `optionalDependency` as external, you can use one of a few different patterns that esbuild uses as a heuristic for "import errors are probably handled" (see a [live demo here](https://esbuild.github.io/try/#YgAwLjE4LjExAC0tYnVuZGxlAGUAZW50cnkuanMAYXN5bmMgZnVuY3Rpb24gbmV2ZXJDYWxsZWQxKCkgewogIHRyeSB7CiAgICBhd2FpdCBpbXBvcnQoJ29wdGlvbmFsRGVwZW5kZW5jeTEnKTsKICB9IGNhdGNoIHsKICB9Cn0KCmZ1bmN0aW9uIG5ldmVyQ2FsbGVkMigpIHsKICBpbXBvcnQoJ29wdGlvbmFsRGVwZW5kZW5jeTInKS5jYXRjaCgoKSA9PiB7fSk7Cn0KCmZ1bmN0aW9uIG5ldmVyQ2FsbGVkMygpIHsKICBpbXBvcnQoJ29wdGlvbmFsRGVwZW5kZW5jeTMnKS50aGVuKCgpID0+IHt9LCAoKSA9PiB7fSk7Cn0)):

```js
async function neverCalled1() {
  try {
    await import('optionalDependency1');
  } catch {
  }
}

function neverCalled2() {
  import('optionalDependency2').catch(() => {});
}

function neverCalled3() {
  import('optionalDependency3').then(() => {}, () => {});
}
```

**Comment by znewsham** [comment] 2023-07-10 18:04
oh interesting - so esbuild detects that it is caught? Ahh, I knew to catch the error if it was called, but I didn't know that esbuild would know about it!

**Comment by evanw** [comment] 2023-07-13 12:05
I’m closing this issue as I consider it to be working as intended. You can resolve this issue as described above.

**Closed by evanw** 2023-07-13 12:05 UTC

**Comment by znewsham** [comment] 2023-08-04 14:20
Sorry for the delay here - I just tried this, and it doesn't appear to be working, I have:

```
function neverCalled() {
  import('packagename').catch(() => {});
}
```

and I get:
```
✘ [ERROR] Could not resolve "packagename" [plugin add-js-extension]

    main.js:5:9:
      5 │   import('packagename').catch(() => {});
        ╵          ~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "packagename" as external to exclude it from the bundle, which will remove this error. You can also add ".catch()" here to handle this failure at run-time instead of bundle-time.

**Comment by evanw** [comment] 2023-08-04 14:23
It looks like that error is being reported by a plugin called `add-js-extension`, not by esbuild itself.

**Comment by znewsham** [comment] 2023-08-04 14:24
Oh, interesting - I assumed this was just being passed through from esbuild

**Comment by znewsham** [comment] 2023-08-04 14:42
Oh, I think I see - instead of catching - I should get the result and replace the errors object with a warnings object:

```
const res = await build.resolve(`@${scope}/${packageName}`, { kind, ...args });
// TODO: check for real errors :rofl: 
res.warnings = res.errors
res.errors = []
```

I don't think the plugin has the information necessary to know that it's got a try/catch though? I guess esbuild will report that if it doesn't?
