### ISSUE TITLE
A way for libraries to tell esbuild to treat an import as external without errors or warnings

### ISSUE THREAD

**Issue by btakita** [evanw/esbuild#3601] opened 2024-01-17 18:42 UTC
I'm maintaining several isomorphic libraries. Some of these libraries dynamically `import('node:fs/promises')`, among others, when run on a server while handling browser environments differently.

esbuild will throw an error if `import('node:fs/promises')` is directly used in the code. To mitigate, `'node:fs/promises'` can be assigned to a variable. However, this causes verbose warning spam from esbuild, making it difficult to see legitimate warnings.

Is there a way for a library to tell esbuild that I really want to treat this import as an external without the warning or error?

I suppose, users of the library could add `node:*` to the externals list on the browser builds...but that is an extra configuration. Adding `node:*` to externals also masks real issues of importing `'node:'` modules, leaving the user unprotected from runtime errors of this type. This protection is useful especially for large apps.

**Comment by evanw** [comment] 2024-01-17 22:10
> To mitigate, `'node:fs/promises'` can be assigned to a variable. However, this causes verbose warning spam from esbuild, making it difficult to see legitimate warnings.

I cannot reproduce this, sorry. Doing this [does not emit any warnings](https://esbuild.github.io/try/#YgAwLjE5LjExAC0tYnVuZGxlAGUAZW50cnkuanMAY29uc3QgeCA9ICdub2RlOmZzL3Byb21pc2VzJwppbXBvcnQoeCk). You can get a warning to appear if you [explicitly change the log level](https://esbuild.github.io/try/#YgAwLjE5LjExAC0tYnVuZGxlIC0tbG9nLW92ZXJyaWRlOnVuc3VwcG9ydGVkLWR5bmFtaWMtaW1wb3J0PXdhcm5pbmcAZQBlbnRyeS5qcwBjb25zdCB4ID0gJ25vZGU6ZnMvcHJvbWlzZXMnCmltcG9ydCh4KQ) of this hidden log message to warning, but that's not the default behavior.

Please follow the [issue reporting instructions](https://raw.githubusercontent.com/evanw/esbuild/main/.github/ISSUE_TEMPLATE/new-issue.md) that you deleted when you posted this issue. I will repost them here for you:

> When reporting a bug or requesting a feature, please do the following:
>
> * Provide a way to reproduce the issue. The best way to do this is to demonstrate the issue on the playground (https://esbuild.github.io/try/) and paste the URL here. A link to a minimal code sample with instructions for how to reproduce the issue may also work. Issues without a way to reproduce them may be closed.

I'm marking this issue as `unactionable` for now because I cannot do anything with it.

**Comment by evanw** [comment] 2024-01-27 05:19
Closing this issue due to lack of a follow-up reply.

**Closed by evanw** 2024-01-27 05:19 UTC
Labels: unactionable

**Comment by btakita** [comment] 2024-01-27 20:23
Apologies for the late reply. I was thinking through exactly what I'm looking for. Here is the repro using log-level=debug.

https://esbuild.github.io/try/#YgAwLjE5LjExAC0tYnVuZGxlIC0tbG9nLWxldmVsPWRlYnVnAGUAZW50cnkuanMAY29uc3QgeCA9ICdub2RlOmZzL3Byb21pc2VzJwppbXBvcnQoeCk

Ideally, I'd like any import 'node:*' to be treated as an external for the browser platform...but doing a standard import would cause an error in the browser.
https://esbuild.github.io/try/#YgAwLjE5LjExAHsKICBidW5kbGU6IHRydWUsCiAgbG9nTGV2ZWw6ICdkZWJ1ZycsCiAgcGxhdGZvcm06ICdicm93c2VyJywKICBleHRlcm5hbDogWydub2RlOionXSwKfQBlAGVudHJ5LmpzAGltcG9ydCB7IHJlYWRGaWxlIH0gZnJvbSAnbm9kZTpmcy9wcm9taXNlcycKcHJvY2Vzcz8ucmVsZWFzZT8ubmFtZSA/IHJlYWRGaWxlKCcvZm9vL2JhcicpIDogdW5kZWZpbmVk

**Comment by btakita** [comment] 2024-01-27 20:30
Actually the generated code throws an error in the browser.

![browser-import-error](https://github.com/evanw/esbuild/assets/3664/48093234-56a7-4f5a-aa41-8affa06e5149)

**Comment by btakita** [comment] 2024-01-27 20:34
Inlining the import does work...but it's considerably bigger in bundle size

https://esbuild.github.io/try/#YgAwLjE5LjExAHsKICBidW5kbGU6IHRydWUsCiAgbG9nTGV2ZWw6ICdkZWJ1ZycsCiAgcGxhdGZvcm06ICdicm93c2VyJywKICBleHRlcm5hbDogWydub2RlOionXSwKfQBlAGVudHJ5LmpzAGdsb2JhbFRoaXMucHJvY2Vzcz8ucmVsZWFzZT8ubmFtZSA/IGltcG9ydCgnbm9kZTpmcy9wcm9taXNlcycpLnRoZW4obW9kPT5tb2QucmVhZEZpbGUoJy9mb28vYmFyJykpIDogdW5kZWZpbmVk

**Comment by btakita** [comment] 2024-01-27 20:59
Here is a repro of the error without `externals: [node:*]`.

https://esbuild.github.io/try/#YgAwLjE5LjExAHsKICBidW5kbGU6IHRydWUsCiAgbG9nTGV2ZWw6ICdkZWJ1ZycsCiAgdGFyZ2V0OiAnZXMyMDIyJywKICBwbGF0Zm9ybTogJ2Jyb3dzZXInCn0AZQBlbnRyeS5qcwBnbG9iYWxUaGlzLnByb2Nlc3M/LnJlbGVhc2U/Lm5hbWUgPyBpbXBvcnQoJ25vZGU6ZnMvcHJvbWlzZXMnKS50aGVuKG1vZD0+bW9kLnJlYWRGaWxlKCcvZm9vL2JhcicpKSA6IHVuZGVmaW5lZA

**Comment by evanw** [comment] 2024-01-27 21:30
> Dynamic imports in the source does work with `['node:*']` added to externals.

That seems like the right way to do this to me.

> The bundle size is considerably bigger than a static import.

This appears to be a tree-shaking bug with esbuild. The additional code is never called, so it either doesn't need to be emitted or it needs to be called.

> It would be great for a library to tell esbuild that a `node:*` import is to be treated an an external or for esbuild to automatically treat `node:*` imports as external. I'm not sure why anyone would want to bundle `node:*` imports...Perhaps I'm missing the reason?

It's an error to use a node library when bundling for the browser because it won't work in a browser. You can add additional configuration to esbuild to tell it to ignore these imports, but I don't think having esbuild silently generate a potentially broken bundle by default is the right approach.
