### ISSUE TITLE
Command build failed, ensure yarn is installed and `yarn build` runs without errors

### ISSUE THREAD

**Issue by Konstrukteur** [evanw/esbuild#3004] opened 2023-03-18 12:05 UTC
I am trying to deploy an app and get errors during the bundling step in production.

```
Tasks: TOP => deploy:assets:precompile
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing on host 92.205.63.233: rake exit status: 1
rake stdout: ➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0013: │ @esbuild/linux-x64@npm:0.17.8 can't be found in the cache and will 
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0007: │ esbuild@npm:0.17.8 must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 0s 491ms
➤ YN0000: Done in 0s 614ms
▲ [WARNING] Use "app/javascript/components/home.jsx" instead of "app/javascript/components/Home.jsx" to avoid issues with case-sensitive file systems [different-path-case]

    app/javascript/routes/index.jsx:3:17:
      3 │ import Home from "../components/Home";
        ╵                  ~~~~~~~~~~~~~~~~~~~~

▲ [WARNING] Use "app/javascript/components/resources.jsx" instead of "app/javascript/components/Resources.jsx" to avoid issues with case-sensitive file systems [different-path-case]

    app/javascript/routes/index.jsx:4:22:
      4 │ import Resources from "../components/Resources";
        ╵                       ~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not read from file: /home/amazingUser/apps/amazingApp/releases/20230318114732/app/javascript/components/Home.jsx

    app/javascript/routes/index.jsx:3:17:
      3 │ import Home from "../components/Home";
        ╵                  ~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not read from file: /home/amazingUser/apps/amazingApp/releases/20230318114732/app/javascript/components/Resources.jsx

    app/javascript/routes/index.jsx:4:22:
      4 │ import Resources from "../components/Resources";
        ╵                       ~~~~~~~~~~~~~~~~~~~~~~~~~

2 warnings and 2 errors
node:child_process:924
    throw err;
    ^

Error: Command failed: /home/amazingUser/apps/amazingApp/releases/20230318114732/node_modules/@esbuild/linux-x64/bin/esbuild app/javascript/application.js --bundle --sourcemap --outdir=app/assets/builds --public-path=assets
    at checkExecSyncError (node:child_process:885:11)
    at Object.execFileSync (node:child_process:921:15)
    at Object.<anonymous> (/home/amazingUser/apps/amazingApp/releases/20230318114732/node_modules/esbuild/bin/esbuild:220:28)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 31768,
  stdout: null,
  stderr: null
}

Node.js v19.6.1
rake aborted!
jsbundling-rails: Command build failed, ensure yarn is installed and `yarn build` runs without errors
/home/amazingUser/apps/amazingApp/shared/bundle/ruby/3.2.0/gems/jsbundling-rails-1.1.1/lib/tasks/jsbundling/build.rake:5:in `block (2 levels) in <main>'
/home/amazingUser/apps/amazingApp/shared/bundle/ruby/3.2.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/home/amazingUser/.rvm/rubies/ruby-3.2.1/bin/ruby_executable_hooks:22:in `eval'
/home/amazingUser/.rvm/rubies/ruby-3.2.1/bin/ruby_executable_hooks:22:in `<main>'
Tasks: TOP => assets:precompile => javascript:build
(See full trace by running task with --trace)
rake stderr: Nothing written
```

I am running the following stack:

- Rails 7 App
- React 18.2.0
- jsbundling 2.11.5
- esbuild 0.17.8
- node v19.8.1
- yarn 3.5.0

I condition I have is that the bundling process requires inconsistent naming pattern. I need to habe 4 components with lower case filenames and 4 have to o can have capital case syntax.

There is no apparent pattern I can make out. I already updated node and yarn. I need to have the app.jsx, home.jsx and resources.jsx lower case, while Topic.jsx, Type.jsx, ResourceTile can or have to have capital letters. I wanted to follow the canonical syntax in React with this app, where all non core components are written in capital letters.

I would expect the bundling to work, since the production system is case sensitive. On a MERN stack I am able to have capitalised component file names. In case the bundling would require lower case, I would expect it to require lower case for all component files.

**Comment by evanw** [comment] 2023-03-18 14:54
> I wanted to follow the canonical syntax in React with this app, where all non core components are written in capital letters.

I think this is the problem. You are expecting case-insensitivity on a case-sensitive file system. I checked what other tools do here and none of the other comparable JavaScript tools in the ecosystem do what you are asking for either:

* esbuild

    ```
    ▲ [WARNING] Use "jsx/home.jsx" instead of "jsx/Home.jsx" to avoid issues with case-sensitive file systems [different-path-case]

        jsx/index.jsx:1:17:
          1 │ import Home from "./Home";
            ╵                  ~~~~~~~~

    ▲ [WARNING] Use "jsx/resources.jsx" instead of "jsx/Resources.jsx" to avoid issues with case-sensitive file systems [different-path-case]

        jsx/index.jsx:2:22:
          2 │ import Resources from "./Resources";
            ╵                       ~~~~~~~~~~~~~

    ✘ [ERROR] Could not read from file: ./jsx/Resources.jsx

        jsx/index.jsx:2:22:
          2 │ import Resources from "./Resources";
            ╵                       ~~~~~~~~~~~~~

    ✘ [ERROR] Could not read from file: ./jsx/Home.jsx

        jsx/index.jsx:1:17:
          1 │ import Home from "./Home";
            ╵                  ~~~~~~~~
    ```

* webpack

    ```
    ERROR in ./jsx/index.jsx 1:0-26
    Module not found: Error: Can't resolve './Home' in './jsx'
    resolve './Home' in './jsx'
      using description file: ./package.json (relative path: ./jsx)
        Field 'browser' doesn't contain a valid alias configuration
        using description file: ./package.json (relative path: ./jsx/Home)
          no extension
            Field 'browser' doesn't contain a valid alias configuration
            ./jsx/Home doesn't exist
          .jsx
            Field 'browser' doesn't contain a valid alias configuration
            ./jsx/Home.jsx doesn't exist
          .js
            Field 'browser' doesn't contain a valid alias configuration
            ./jsx/Home.js doesn't exist
          as directory
            ./jsx/Home doesn't exist

    ERROR in ./jsx/index.jsx 2:0-36
    Module not found: Error: Can't resolve './Resources' in './jsx'
    resolve './Resources' in './jsx'
      using description file: ./package.json (relative path: ./jsx)
        Field 'browser' doesn't contain a valid alias configuration
        using description file: ./package.json (relative path: ./jsx/Resources)
          no extension
            Field 'browser' doesn't contain a valid alias configuration
            ./jsx/Resources doesn't exist
          .jsx
            Field 'browser' doesn't contain a valid alias configuration
            ./jsx/Resources.jsx doesn't exist
          .js
            Field 'browser' doesn't contain a valid alias configuration
            ./jsx/Resources.js doesn't exist
          as directory
            ./jsx/Resources doesn't exist
    ```

* rollup

    ```
    jsx/index.jsx → stdout...
    [!] RollupError: Could not resolve "./Home" from "jsx/index.jsx"
    jsx/index.jsx
        at error (./node_modules/rollup/dist/shared/rollup.js:271:30)
        at ModuleLoader.handleInvalidResolvedId (./node_modules/rollup/dist/shared/rollup.js:24275:24)
        at ./node_modules/rollup/dist/shared/rollup.js:24237:26
    ```

* parcel

    ```
    @parcel/core: Failed to resolve './Home' from './jsx/index.jsx'

      ./jsx/index.jsx:1:18
      > 1 | import Home from "./Home";
      >   |                  ^^^^^^^^
        2 | import Resources from "./Resources";
        3 | 

    @parcel/resolver-default: Cannot load file './Home' in './jsx'.
    💡 Did you mean './home'?
    ```

* tsc

    ```
    tsx/index.tsx:1:18 - error TS2307: Cannot find module './Home' or its corresponding type declarations.

    1 import Home from "./Home";
                      ~~~~~~~~

    tsx/index.tsx:2:23 - error TS2307: Cannot find module './Resources' or its corresponding type declarations.

    2 import Resources from "./Resources";
                            ~~~~~~~~~~~~~
    ```

So I think you should not expect this to work. I recommend following esbuild's suggestion of importing your code using the correct case to get your code to work on case-sensitive file systems. I don't consider esbuild's behavior here to be a bug with esbuild.

**Comment by Konstrukteur** [comment] 2023-03-18 15:07
Thank you very much for your extensive research! Sorry for the confusion and all the code. I expected an import statement such as:

import App from './App';
to work with a filename 'App.jsx'

currently I have

- import App from "./app";filename app.jsx
- import Home from "../components/home";
- import Resources from "../components/resources";
- import ResourcePage from "../components/ResourcePage";
- import ResourceTile from "./ResourceTile";
- import Topic from "./Topic";

**Comment by Konstrukteur** [comment] 2023-03-18 15:55
Conversely, when I try to use only lower case I get:

**Comment by hyrious** [comment] 2023-03-18 16:05
It seems your file paths differ on development/production environments. Let me guess if you're using git, make sure to use `git mv` to rename the file or you will not be able to update the file path on remote server correctly.

**Comment by Konstrukteur** [comment] 2023-03-18 16:13
> It seems your file paths differ on development/production environments. Let me guess if you're using git, make sure to use `git mv` to rename the file or you will not be able to update the file path on remote server correctly.

This is put on my test todo list.

I usually:
rename file
`git add -A`
`git commit -m .....`
etc.

With `git add -A` git 'adds, modifies, and removes index entries to match the working tree.' I will try your suggestion.

**Comment by evanw** [comment] 2023-03-24 18:36
I'm closing this issue because it sounds like esbuild is working correctly here (including already warning you about the problem). I don't think it should be esbuild's job to try to emulate a case-insensitive file system atop a case-sensitive file system, especially as no other comparable tool does that either.

**Closed by evanw** 2023-03-24 18:36 UTC

**Comment by Konstrukteur** [comment] 2023-03-24 19:55
> I'm closing this issue because it sounds like esbuild is working correctly here (including already warning you about the problem). I don't think it should be esbuild's job to try to emulate a case-insensitive file system atop a case-sensitive file system, especially as no other comparable tool does that either.

Sorry, but there is a misunderstanding or I completely miss something here. I expect esbuild to find App.js under App.js. I am not trying to find App.js under app.js. On a case-sensitive system it should be resolved (since App.js === App.js)  as well as on a case-insenstive system (case doesn't care).

I try to `import Home from "./Home"` (as Home.js) and the bundling forces me to do `import Home from "./home"` (as home.js). In other cases it requires capital letters.

**Comment by evanw** [comment] 2023-03-24 19:57
If you believe you have found a bug with esbuild, then please provide a self-contained way to independently reproduce the issue (code + instructions).

**Comment by Konstrukteur** [comment] 2023-03-24 20:03
> If you believe you have found a bug with esbuild, then please provide a self-contained way to independently reproduce the issue (code + instructions).

After working for a week on the problem, I tend to exclude esbuild for now and consider it correct to close the issue, but the description of the assumption you are incorrect to my limited understanding, that is all. With Esbundling, Yarn, Esbuild, React in the chain troubleshooting is quite a challenge to be honest. Thanks for the replies and the great work! Very much appreciated!
