### ISSUE TITLE
Sourcemap move alle sources in a subfolder with the package-name.

### ISSUE THREAD

**Issue by deleonio** [evanw/esbuild#1176] opened 2021-04-22 10:00 UTC
```json
// package.json
{
  "name": "my-app",
  ...
}
```

Workspace-Path: ~/workspace/my-app/
Sourcemap-Path: ~/workspace/my-app/**my-app**/...

**Why is the package name used in the source map in the file path?**

**Comment by evanw** [comment] 2021-04-22 19:43
Sorry, I don’t understand what you’re saying. One thing that could help is to provide a way for me to reproduce the issue.

**Comment by BenICE** [comment] 2021-04-28 10:05
The workspace & source map path are not matching each other leading to trouble debugging in VS Code. You should be able to reproduce it with a basic setup.

So what we have right now:
My workspace is under path: _~/workspace/mygitrepoapp/_
For example the path for a file looks like: _~/workspace/mygitrepoapp/src/main.ts_
If I now start a debugging session in Visual Studio Code with the Chrome Debugger Extension (standard launch.json), it cannot set the breakpoints.

As Visual Studio Code assumes the code to be in _~/workspace/mygitrepoapp/examplename/src/main.ts_

If I understand correctly it happens because e.g. Chrome has the following source map structure:
![grafik](https://user-images.githubusercontent.com/5716833/116386147-cbb1ad80-a819-11eb-8923-e33cc6e62189.png)
The red circle is for me the problem…as VSC thinks it should look into this folder.


If you need any additional information, let me know. Currently debugging from VSC is a real pain in the ass.

**Comment by deleonio** [comment] 2021-05-05 10:27
Hi @evanw,
can you watch this again, please?

**Comment by evanw** [comment] 2021-05-06 01:53
I might be able to do something with this issue if you provide steps that allow me to reproduce the issue myself. Otherwise this issue doesn't have enough information.

Also: I'm not familiar with how VSCode's source map integration works, but I wonder if [esbuild's `sourceRoot` setting](https://esbuild.github.io/api/#source-root) could help.

**Comment by BenICE** [comment] 2021-05-10 10:27
I reworked the standard source mapping properties from VSCode.

`"sourceMapPathOverrides": {
        "webpack://?:*/?:*/*": "${webRoot}/*"
      }`

So it now ignores -> _"webpack://@scope/nameOfApp/"_ and only starts to match afterwards.

The standard of VSCode just ignores _"webpack://something/"_
I guess you can close; workaround is present...still not sure who is at "fault" here

**Comment by evanw** [comment] 2021-05-14 02:15
> You should be able to reproduce it with a basic setup.

I'm unable to reproduce this. Here's what I tried:

1. Install `react`, `react-dom`, and `esbuild`
2. Create a file called `app.tsx` that looks like this:

    ```jsx
    import * as React from 'react'
    import * as ReactDOM from 'react-dom'
    let Greet = () => <h1>Hello, world!</h1>
    ReactDOM.render(<Greet />, document.getElementById('it'))
    ```

3. Create a file called `index.html` that looks like this:

    ```html
    <div id="it"></div>
    <script src="dist/out.js"></script>
    ```

4. Run `esbuild --bundle app.jsx --sourcemap --outfile=dist/out.js`
5. Open VSCode and create a `launch.json` for Chrome (click the debug sidebar button, then click "create a launch.json file", then select Chrome)
6. Serve the directory locally with `esbuild --servedir=. --serve=127.0.0.1:8080`
7. Hit the debug button in VSCode to open Chrome
8. Open Chrome Developer Tools, go to the Sources tab, and click on `app.jsx`
9. Add a breakpoint on line 3 (has the JSX `<h1>...</h1>` on it)
10. Reload

When I do that, VSCode automatically comes to the foreground with the debugger paused on line 3.

I'm going to close this issue because it's unactionable (there's no information about how to reproduce the issue). I'm happy to reopen this issue if sufficient information about how to reproduce this issue can be provided.

**Closed by evanw** 2021-05-14 02:15 UTC
Labels: unactionable
