### ISSUE TITLE
How to merge 2 of duplicated module

### ISSUE THREAD

**Issue by tanglokinteractive** [evanw/esbuild#2093] opened 2022-03-09 01:13 UTC
im import 2 module like this

```
import * as THREE from 'three';
import * as ThreeDD from 'threedd';
```

and in threedd module has import three module (external)

when i builded. it have 2 of "three" modules
![Screen Shot 2565-03-09 at 08 09 43](https://user-images.githubusercontent.com/86215152/157352748-79b15f9a-fbe2-4388-b278-20553a40a051.png)

i make sure in threedd module.js not have "three"
![Screen Shot 2565-03-09 at 08 11 31](https://user-images.githubusercontent.com/86215152/157352930-475007f9-6cde-47e7-8b69-3848351afc05.png)

how i can build only 1 of them?

// ======

i change to 
```

const THREE = require('three')
```
also duplicated
![Screen Shot 2565-03-09 at 08 27 02](https://user-images.githubusercontent.com/86215152/157354490-dea77ad3-9373-4f14-bb8c-a4743d43eb08.png)

**Comment by hyrious** [comment] 2022-03-09 01:28
This often due to `threedd` depends on different version of `three`, thus the package manager (npm, pnpm, etc.) installed two versions of `three`, and a bundler like esbuild doesn't know whether a module is duplicate unless you only have one copy of the module in your file system.

So if you're the author of `threedd`, you have these choices:

- use the same version range as the user side.
- put `three` in `peerDependencies` instead of `dependencies`.

If you're the user of these libraries, you can write an esbuild [plugin](https://esbuild.github.io/plugins) to resolve `three` to the same file:

```js
var DedupThreePlugin = {
  name: 'dedup-three',
  setup({ onResolve }) {
    var three = require.resolve('three').replace(/three\.cjs$/, 'three.module.js')
    onResolve({ filter: /^three$/ }, () => ({ path: three }))
  }
}
```

**Comment by tanglokinteractive** [comment] 2022-03-09 02:03
> This often due to `threedd` depends on different version of `three`, thus the package manager (npm, pnpm, etc.) installed two versions of `three`, and a bundler like esbuild doesn't know whether a module is duplicate unless you only have one copy of the module in your file system.
> 
> So if you're the author of `threedd`, you have these choices:
> 
> * use the same version range as the user side.
> * put `three` in `peerDependencies` instead of `dependencies`.
> 
> If you're the user of these libraries, you can write an esbuild [plugin](https://esbuild.github.io/plugins) to resolve `three` to the same file:
> 
> ```js
> var DedupThreePlugin = {
>   name: 'dedup-three',
>   setup({ onResolve }) {
>     var three = require.resolve('three').replace(/three\.cjs$/, 'three.module.js')
>     onResolve({ filter: /^three$/ }, () => ({ path: three }))
>   }
> }
> ```

thanks for your help
```
THREE DD :  138
THREE :  138
```
i check version it all same

i try peerDependencies it not work when build

![Screen Shot 2565-03-09 at 08 58 06](https://user-images.githubusercontent.com/86215152/157357726-2d9b4f35-c0fd-4a30-85d3-5260f94a1db6.png)
![Screen Shot 2565-03-09 at 08 58 19](https://user-images.githubusercontent.com/86215152/157357747-9c30964d-7e95-4de3-98e7-894cec34024d.png)

but "DedupThreePlugin" its work

![Screen Shot 2565-03-09 at 09 02 59](https://user-images.githubusercontent.com/86215152/157358005-d042a3db-99a0-45f1-8373-844d06a788a6.png)

**Comment by hyrious** [comment] 2022-03-09 02:13
I see, so your `threedd` is in another folder which has different node_modules than your working side, i.e.

```
threedd/
  node_modules/
    three/       <- one
work/
  node_modules/
    three/       <- two
    threedd/ -> ../../threedd/
```

In this situation that's impossible to merge the two `three` in the same one unless using mono-repo.

FYI, the bundler has a simple resolution algorithm that basically equals to node.js'. When it see `import 'three'` in threedd's files, it just searches three in the same folder of that file.

**Comment by evanw** [comment] 2022-03-13 17:34
The behavior of esbuild here is by design. Node's path resolution algorithm has a very exact specification: https://nodejs.org/api/modules.html#all-together. Merging these two automatically would be incorrect because it could change the run-time behavior in observable ways. If you want to use a custom path resolution algorithm, then a plugin is the right way to do this.

Closing this issue as "by design."

**Closed by evanw** 2022-03-13 17:34 UTC
