### ISSUE TITLE
esbuild would apply ext names twice if it is already given in the entry point config

### ISSUE THREAD

**Issue by yw662** [evanw/esbuild#3059] opened 2023-04-14 00:54 UTC
If the config is like
```ts
{
// ...
entryPoints: [ {in: 'index.ts', out: 'index.js'} ]
// or entryPoints: { 'index.js': 'index.ts' }
}
```

It will end up as `index.js.js`.
Should it be just `index.js` if it already says `index.js` ?

**Comment by evanw** [comment] 2023-04-14 02:01
No, that's not how it works. The [`entryPoints`](https://esbuild.github.io/api/#entry-points) field specifies the base name and the extension comes from the [`outExtension`](https://esbuild.github.io/api/#out-extension) setting.

**Comment by evanw** [comment] 2023-04-16 19:00
I'm closing this issue because esbuild is working as intended.

**Closed by evanw** 2023-04-16 19:00 UTC
