### ISSUE TITLE
Initialization is not working with ref

### ISSUE THREAD

**Issue by alenvlahovljak** [evanw/esbuild#971] opened 2021-03-13 21:55 UTC
What happens with the newest version (0.9.2), I cannot save the initialization into the ref. It works fine with `0.8.56`

**Comment by evanw** [comment] 2021-03-13 23:00
I have no idea what you are saying. What is ref?

**Comment by alenvlahovljak** [comment] 2021-03-13 23:03
Oh sorry, I mean I cannot save after I initialize it with `.initilalize()`. It's undefined when I try to save it into a variable.

**Comment by evanw** [comment] 2021-03-13 23:16
Ah, I see. In the old version, `.startService()` returned a promise that resolved to a service object. But in the new version, `.initialize()` returns a promise that resolves to undefined. This is an intentional design change. There is no more service object. Instead, you just call `transform` and `build` on esbuild's API object itself. This change should be reflected in the latest documentation: https://esbuild.github.io/api/#running-in-the-browser:

```js
let esbuild = require('esbuild-wasm')

esbuild.initialize({
  wasmURL: './node_modules/esbuild-wasm/esbuild.wasm',
}).then(() => {
  esbuild.transform(code, options).then(result => { ... })
  esbuild.build(options).then(result => { ... })
})
```

**Comment by evanw** [comment] 2021-03-14 03:18
Closing as by design.

**Closed by evanw** 2021-03-14 03:18 UTC

**Comment by Mehrdad4819** [comment] 2023-09-11 08:55
You cant also save it into a variable like this:

`  const startService = async () => {
    const service = await esbuild.initialize({
      wasmURL: '/esbuild.wasm',
// you can put esbuild.wasm file in your public file or address it directly to: './node_modules/esbuild-wasm/esbuild.wasm'
    });

    ref.current = esbuild
}
    
  useEffect(() => {
    startService();
  }, []);

  const onClick = async () => {
    if (!ref.current) {
      return;
    }

    const result = await ref.current.transform( yourCode, {
      loader: 'jsx',
      target: 'es2015',
    });

    console.log(result);

  };
`
