### ISSUE TITLE
external doesn't work with typescript's paths nor package's import

### ISSUE THREAD

**Issue by eng-dibo** [evanw/esbuild#2803] opened 2023-01-07 13:29 UTC
I want to exclude the file `./src/config.ts` from bundling and I have the following configurations:

package.json
```
{
  "type: "module",
   "imports": {
    "#*": "./src/*"
  }
```

tsconfig.json:
```
{
  compilerOptions: {
     "paths": {
      "#*": ["./src/*"]
     }
}
```

esbuild.js
```
  external: [
    './config','#config','./src/config'
  ],
```

and this is my code:

src/index.ts
```
import {example} from "#config";

example()
```

but this is compiled into:

dist/index.mjs
```
// src/config.ts
function example() {
}

// src/index.ts
example();
```

but I want to keep it as a static import.

also, changing it into a dynamic import doesn't help
```
import('#config').then(m=>m.example())
```

using a variable instead of a literal string causes TS error, as it doesn't import the types for the exported functions
```
import(`${'#config'}`).then(m=>m.example())
```

this causes the error
```
untyped function calls may not accept type arguments
```

I cannot use `import from './config'` and must use `#config`
also, I don't want to split everything so I don't want to use the `--splitting` option

I want to force a specific static or dynamic module to be split, even if it is an analyzable import
reference: https://esbuild.github.io/api/#non-analyzable-imports

**Comment by evanw** [comment] 2023-01-07 15:51
When I try that I get this:

```js
// src/index.ts
import { example } from "#config";
example();
```

because the external `#config` matches the import path. So I can't reproduce your issue. It appears to be working fine for me. You'll have to provide a working demonstration of the issue.

**Comment by eng-dibo** [comment] 2023-01-08 19:26
ok, let me publish my minimal reproduction and get back to you @evanw

**Comment by eng-dibo** [comment] 2023-01-08 19:43
here is my [minimal reproduction](https://github.com/eng-dibo/esbuild-getter)

**key points:**
- in esbuld I added different varies of `#config`
- in index.ts I need to `import from "#config"` by various methods, using static and dynamic imports
- after the building is finished I replace 'dist/config.mjs` with another one that implements the exact same functions but with different logging. the function that logs the new value (that is appends '=====' after it) guaranteed to be works as expcted

in index.ts you will find a comment above each import how does it actually work.

**Comment by eng-dibo** [comment] 2023-01-08 19:52
I got it, it seems that there is an issue when using plugins, some plugins may be able to change the behaviour of the core of esbuild to an unexpected behaviour which is must not does.

when commenting out this plugin `TsconfigPathsPlugin({ tsconfig: "./tsconfig.json" })` it works as expected

**Comment by evanw** [comment] 2023-01-08 22:12
Glad you figured it out. I'm closing this issue then because this problem is caused by a plugin.

**Closed by evanw** 2023-01-08 22:12 UTC

**Comment by eng-dibo** [comment] 2023-01-11 07:08
the plugin just replaces the alias with the real path which is also included in `external` array, and should be matched normally by esbuild.

**Comment by evanw** [comment] 2023-01-12 05:26
When a plugin intercepts a path and returns a substitution, it's overriding esbuild's normal behavior by default. It has to manually call `resolve()` if it wants esbuild's normal behavior to run.

**Comment by eng-dibo** [comment] 2023-01-17 22:14
thank you for your nice guidance @evanw.
I carefully read the docs about Plugins and I have a suggestion
instead of creating a plugin from scratch or even modifying the code base of an existing one we can reuse the existing plugin and control how it works without the need that the plugin provide options to do that

the idea is to control what lifecycle hooksare  run inside the plugin, we can prevent some hooks from running even if they provided by the plugin.

by this way we can use the existing plugin to return the path without resolving it, and add another plugin to the next plugins list to handle the path resolving

```
 plugins: [
  [TsconfigPathsPlugin({ tsconfig: "./tsconfig.json" }), {
    runHooks: ['onLoad', 'setup'],
   // or ignore hooks (overrides runHooks option)
  ignoreHooks: ['onLoad']
 ],

resolvePaths()
]
```

the registered plugin here is an array, and the second element of that array controls how the plugin works and control which hooks are run, and handled by esbuild, not by the plugin

also, we need to pass the path retreived by any plugin to the next plugin if it doesn't provide the content, i.e if it didn't resolve it.

or we can pass the result of each plugin to the next one (something like intercepts do)

**Comment by evanw** [comment] 2023-01-17 22:20
Thanks for the suggestions. Yes, this is a clear shortcoming with the existing plugin API in that many other people have asked to be able to do this as well. I'm planning to address this (specifically the desire for chaining separate plugins together). I haven't done the API design yet but I assume it's going to mean a breaking change to the plugin API, so I'm also going to need to figure out a migration plan for older plugins.

**Comment by eng-dibo** [comment] 2023-01-17 22:43
wow! really awesome
