### ISSUE TITLE
Minimizer renames "console.assert"

### ISSUE THREAD

**Issue by ronag** [evanw/esbuild#1129] opened 2021-04-09 11:24 UTC
A `console.assert` is for some reason converted into `t.assert`.

Refs: https://github.com/video-dev/hls.js/issues/3749

0.11.6

**Comment by evanw** [comment] 2021-04-09 11:32
Do you have a way for me to reproduce this? I noticed "Steps to reproduce" was not filled out on that issue.

**Comment by ronag** [comment] 2021-04-09 11:36
> Do you have a way for me to reproduce this? I noticed "Steps to reproduce" was not filled out on that issue.

Sorry not at the moment.

**Comment by ronag** [comment] 2021-04-09 11:37
We're using esbuild in webpack to minimize:

```

    minimizer: [
      new ESBuildMinifyPlugin({
        target: 'chrome61',
      }),
    ],
```

**Comment by evanw** [comment] 2021-04-10 04:34
I'm closing this since if there isn't a way to reproduce this, there isn't anything I can do with this bug report. I'm happy to reopen this issue if you have a way to reproduce the issue.

**Closed by evanw** 2021-04-10 04:34 UTC
Labels: unactionable

**Comment by ronag** [comment] 2021-04-10 21:16
terser has same problem.

**Comment by evanw** [comment] 2021-04-10 22:38
If terser has the same problem then it's likely an issue with the code, not with the minifier. I assume that means there is a variable called `console` somewhere in the file before minification. Then since it's a variable local to the file, it's being renamed to `t`.
