### ISSUE TITLE
Esbuild omits non initialized class properties

### ISSUE THREAD

**Issue by lukasholzer** [evanw/esbuild#2195] opened 2022-04-20 12:45 UTC
ESbuild drops uninizialized class properties like:

```typescript
export class Base {
  static create<I extends typeof Base>(this: I): InstanceType<I> {
    const configInstance: any = new this();

    return configInstance as InstanceType<I>;
  }

  get _keys(): string[] {
    return Object.keys(this).filter((key) => !key.startsWith('_'));
  }
}

export class TestInstance extends Base {
  someProp?: boolean;
}

export const config = TestInstance.create();

// run with: node --no-warnings --loader ts-node/esm ./test.ts
// should print ['someProp']
console.log(config._keys);
```

See this reproducible example: [Playground](https://esbuild.egoist.sh/#W1siaW5kZXgudHMiLHsiY29udGVudCI6ImV4cG9ydCBjbGFzcyBCYXNlIHtcbiAgc3RhdGljIGNyZWF0ZTxJIGV4dGVuZHMgdHlwZW9mIEJhc2U+KHRoaXM6IEkpOiBJbnN0YW5jZVR5cGU8ST4ge1xuICAgIGNvbnN0IGNvbmZpZ0luc3RhbmNlOiBhbnkgPSBuZXcgdGhpcygpO1xuXG4gICAgcmV0dXJuIGNvbmZpZ0luc3RhbmNlIGFzIEluc3RhbmNlVHlwZTxJPjtcbiAgfVxuXG4gIGdldCBfa2V5cygpOiBzdHJpbmdbXSB7XG4gICAgcmV0dXJuIE9iamVjdC5rZXlzKHRoaXMpLmZpbHRlcigoa2V5KSA9PiAha2V5LnN0YXJ0c1dpdGgoJ18nKSk7XG4gIH1cbn1cblxuZXhwb3J0IGNsYXNzIFRlc3RJbnN0YW5jZSBleHRlbmRzIEJhc2Uge1xuICBzb21lUHJvcD86IGJvb2xlYW47XG59XG5cbmV4cG9ydCBjb25zdCBjb25maWcgPSBUZXN0SW5zdGFuY2UuY3JlYXRlKCk7XG5cbi8vIHJ1biB3aXRoOiBub2RlIC0tbm8td2FybmluZ3MgLS1sb2FkZXIgdHMtbm9kZS9lc20gLi90ZXN0LnRzXG4vLyBzaG91bGQgcHJpbnQgWydzb21lUHJvcCddXG5jb25zb2xlLmxvZyhjb25maWcuX2tleXMpOyJ9XSxbImVzYnVpbGQuY29uZmlnLmpzb24iLHsiY29udGVudCI6IntcbiAgXCJmb3JtYXRcIjogXCJlc21cIixcbiAgXCJjZG5VcmxcIjogXCJodHRwczovL2Nkbi5za3lwYWNrLmRldlwiXG59In1dXQ==)

This causes upstream issues in vite and vitest https://github.com/vitest-dev/vitest/issues/1167

**Comment by hyrious** [comment] 2022-04-20 12:58
This is by design, it is aligned with typescript's behavior when [`useDefineForClassFields`](https://www.typescriptlang.org/tsconfig#useDefineForClassFields) in the tsconfig is off. You can either turn on this option or set `target` to `es2022` or higher to keep these optional fields. Or you can manully give it an initial value (`= undefined`).

**Comment by evanw** [comment] 2022-04-20 13:21
Yes, this is not a bug. This is how TypeScript behaves so esbuild behaves this way too. Compare [`useDefineForClassFields=false`](https://www.typescriptlang.org/play?&useDefineForClassFields=false#code/KYDwDg9gTgLgBAYwDYEMDOa4CF3DgbwCg440YUYBLBRKYC4AHgEk5QZgA7AE0xgE8wwCADNsuAHwAKGAAtKaAFxxmASmXNOZFJwTAAKoKbMJBYiUQQt8BFZGUA5pu27gynfzgBeOJ2AB3ODkFKVUAbkJzEjoYAFcoTktOeydrHT04dBU010MhFgkIkgBfSJIHYHgAfQBrYH40UOUyKEpOBwBtAF0zCzgY+MSAeQAjACtgBBgAOjqGmXk0VWn7JA4oKSk51W9TAEI56e1YNAB1SjkpAHIqq9Vw81LSwlBIWERUDDh9YDJnclcbBAHB4mBwaDwRBIaAgAFtgAAFKAQMAAfmUIwgECQ9E4EWer2gNisZCSKW831+MH+6WA0wQdAYoQihAA9Kz+rFEv4LrJlJwINw8ABaYUC4X+FAJNoOTCipAQFBCqBBNBiwXAVm-WFwaasjhkaYwNBsjloWQQWJIbhwMCtTjwDpXGHwpEoq5dQi2LTYukKhxSb0paa1epLCJAA) with [`useDefineForClassFields=true`](https://www.typescriptlang.org/play?useDefineForClassFields=true#code/KYDwDg9gTgLgBAYwDYEMDOa4CF3DgbwCg440YUYBLBRKYC4AHgEk5QZgA7AE0xgE8wwCADNsuAHwAKGAAtKaAFxxmASmXNOZFJwTAAKoKbMJBYiUQQt8BFZGUA5pu27gynfzgBeOJ2AB3ODkFKVUAbkJzEjoYAFcoTktOeydrHT04dBU010MhFgkIkgBfSJIHYHgAfQBrYH40UOUyKEpOBwBtAF0zCzgY+MSAeQAjACtgBBgAOjqGmXk0VWn7JA4oKSk51W9TAEI56e1YNAB1SjkpAHIqq9Vw81LSwlBIWERUDDh9YDJnclcbBAHB4mBwaDwRBIaAgAFtgAAFKAQMAAfmUIwgECQ9E4EWer2gNisZCSKW831+MH+6WA0wQdAYoQihAA9Kz+rFEv4LrJlJwINw8ABaYUC4X+FAJNoOTCipAQFBCqBBNBiwXAVm-WFwaasjhkaYwNBsjloWQQWJIbhwMCtTjwDpXGHwpEoq5dQi2LTYukKhxSb0paa1epLCJAA).

I believe the background is that the TypeScript team messed up when they released a transpiler for ES6 classes while they were still being standardized, and the eventual standardized behavior ended up being different than how TypeScript works. The TypeScript team then decided to keep the broken behavior as the default for backward compatibility and require you to opt-in to get the correct behavior via `useDefineForClassFields`.

I'm guessing Vite would have to fix this on their end by letting you configure `useDefineForClassFields: true` unless they already have the ability for you to specify your own `tsconfig.json` file, in which case you can fix this yourself (I know nothing about Vite).

Closing this issue as "by design" because this behavior is a deliberate decision by the TypeScript team.

**Closed by evanw** 2022-04-20 13:21 UTC
