### ISSUE TITLE
[CSS] external wildcard doesn't work with url query params

### ISSUE THREAD

**Issue by peteroid** [evanw/esbuild#1822] opened 2021-12-02 14:49 UTC
For example, if the esbuild config looks like this:
```
...
      external: [
        '*.png',
      ],
...
```

It will throw error for the css like `url(img/logo.png?abc)`.

To handle this, I have to put the query string in the external to ignore the files:
```
...
      external: [
        '*.png',
        '*.png?abc',
      ],
...
```

**Comment by evanw** [comment] 2021-12-03 04:45
The current behavior seems more flexible to me. This way you can mark `*.png` and/or `*.png?abc` as external independently. If `*.png` also meant `*.png?*` then you couldn't mark `*.png` as external without also marking `*.png?abc` as external, which you may not want to do.

The built-in behavior isn't fully general-purpose. If you have complex needs, you can either use multiple external markers like you suggested or use an on-resolve plugin which can contain whatever filtering logic you need: https://esbuild.github.io/plugins/#resolve-callbacks.

**Comment by evanw** [comment] 2022-01-22 07:17
Closing as by design.

**Closed by evanw** 2022-01-22 07:17 UTC
