### ISSUE TITLE
Bug recurred: error: Could not resolve "fs"

### ISSUE THREAD

**Issue by n0pj** [evanw/esbuild#1364] opened 2021-06-11 02:23 UTC
The bug has recurred on my Mac. https://github.com/evanw/esbuild/issues/90
It happened when I updated esbuild from 0.12.7 to 0.12.8.

`node -v`
14.15.0

I using esbuild with gulp, browserify.
```js
    // ...
    return esbuild
      .build({
        define: { 'process.env.NODE_ENV': mode },
        target: 'es6',
        entryPoints: files,
        bundle: true,
        outdir: `${buildDirectorySrc}/scripts`,
        minify: !isDev,
        sourcemap: isDev,
        plugins: [sassPlugin()]
      })
      .catch(e => {
        console.log(e)
        // process.exit(1)
      })
```

**Comment by LXSMNSYC** [comment] 2021-06-11 06:06
Have you tried checking https://esbuild.github.io/getting-started/#bundling-for-the-browser

**Comment by evanw** [comment] 2021-06-25 14:16
This is currently unactionable. There isn't enough information here to be able to reproduce it so it can be fixed. Please provide a way to reproduce the issue.

**Comment by evanw** [comment] 2021-09-21 23:22
Closing due to lack of a response.

**Closed by evanw** 2021-09-21 23:22 UTC
Labels: unactionable

**Comment by johrstrom** [comment] 2022-04-12 20:29
Hi can I open this back up?  I'm getting it out of the `handlebars` package while building for the browser.

```
[ERROR] Could not resolve "fs"

    node_modules/handlebars/lib/index.js:17:19:
      17 │   var fs = require('fs');
         ╵                    ~~~~
```

https://github.com/handlebars-lang/handlebars.js/blob/a9fe6d5a03cbb4a58ec80806d08c0602435c974c/lib/index.js#L18

Admittedly I'm a bit new the javascript toolchains so I don't know to force this dependency to build one way or another. I don't have a build.js - I'm just running this one command:

```
esbuild app/javascript/packs/*.* --bundle --sourcemap --loader:.svg=file --outdir=app/assets/builds
```

**Comment by evanw** [comment] 2022-04-12 20:35
I assume you are bundling for node because `fs` is a node-specific API. In that case you should use `--platform=node`. This is documented: https://esbuild.github.io/getting-started/#bundling-for-node. Or you can just do `--external:fs` to skip bundling `fs` if you are bundling for the browser and the code causing the problem is never used (you obviously can’t actually use `fs` in the browser because it’s a node-only API). Anyway this is not a bug with esbuild. You just need to configure esbuild correctly.

**Comment by johrstrom** [comment] 2022-04-12 20:36
> Or you can just do --external:fs to skip bundling fs

This is exactly what I'm looking for. Thank you so much!
