### ISSUE TITLE
Support returning js and jsSourceMap in build?

### ISSUE THREAD

**Issue by eigilsagafos** [evanw/esbuild#183] opened 2020-06-18 17:47 UTC
I have been looking into using esbuild with jest. There is a plugin on npm, put that uses rollup and rollup-plugin-esbuild which I think is unnecessary. I have been able to create a custom transformer for jest, but it is currently slower than using babel-jest, one of the reasons is probably that I'm using buildSync, saving that to a tmp file and reading it back. Would it be possible to allow returning the js directly like transform is doing? Or am I missing something here? :)

(I have also played with using transformSync, but that will return an error: `SyntaxError: Cannot use import statement outside a module`)

**Comment by evanw** [comment] 2020-06-18 20:56
It looks like the feature you're asking for is sort of ES6-to-CommonJS conversion for `transformSync`, which is a duplicate of #109. Keep in mind that this might have a similar performance profile to `buildSync` because the synchronous APIs both involve starting a new child process every time.

Have you done performance tests with the current `transformSync` API vs. babel-jest? It could very well be the case that babel-jest is already faster than `transformSync` for your use case even without ES6-to-CommonJS conversion, in which case this feature request wouldn't help you.

**Comment by evanw** [comment] 2020-06-22 01:57
The original request (`build` returning the output files) is a duplicate of #139, so I'm going to close this issue as a duplicate of that one.

**Closed by evanw** 2020-06-22 01:57 UTC

**Comment by eigilsagafos** [comment] 2020-06-22 05:36
Thanks @evanw. I'll follow the other two issues
