### ISSUE TITLE
Minify with newline character(s)

### ISSUE THREAD

**Issue by lukeed** [evanw/esbuild#545] opened 2020-11-17 22:39 UTC
Any strings with `\n` (literal) contained are left as is when `minify` is disabled. But enabling `minify` converts the string to template literal (_not a problem_ - found explanation [here](https://github.com/evanw/esbuild/issues/307#issuecomment-667486093)) but with unescaped special character(s).

***Example***

```ts
// input.ts
const green = (x: string) => x;
const write = (msg: string) => process.stdout.write(msg + '\n');
write('\n  ' + green('Your application is ready~! 🚀\n'));
```

```js
// esbuild.buildSync({
//   entryPoints: ['./input.ts'],
//   outfile: 'output.js',
// });

const green = (x) => x;
const write = (msg) => process.stdout.write(msg + "\n");
write("\n  " + green("Your application is ready~! \u{1F680}\n"));

// --- vs ---

// esbuild.buildSync({
//   entryPoints: ['./input.ts'],
//   outfile: 'output.js',
//   minify: true,
// });

const green=n=>n,write=n=>process.stdout.write(n+`
`);write(`
  `+green(`Your application is ready~! \u{1F680}
`));
```

---

Also found that `\t` is always unescaped, regardless of `minify` option.

**Comment by evanw** [comment] 2020-11-17 23:00
Sorry, I don't understand. Why is that a problem? This is done when minifying because the resulting file is smaller, just like it says in the explanation you linked to.

**Comment by lukeed** [comment] 2020-11-17 23:36
It's just inconsistent – something like `\r\n` becomes `\r`+newline.
If it were just about bytes, then I'd have thought `🚀` would have been left alone.

FWIW, this is Terser's output:

```js
var r;r="\n  Your application is ready~! 🚀\n",process.stdout.write(r+"\n");
```

Granted, they're mangling & squashing top-level identifiers by default, but I'm sharing for the string contents.

**Comment by lukeed** [comment] 2020-11-18 00:19
Ah, never saw that the `charset` option existed before. Thanks!

**Comment by evanw** [comment] 2020-11-18 01:46
> It's just inconsistent – something like `\r\n` becomes `\r`+newline.

Template literals undergo newline normalization during parsing which converts `\r` and `\r\n` into `\n`, so it's not possible to encode `\r` without an escape sequence. See the following note in [the standard](https://www.ecma-international.org/ecma-262/):

> TV excludes the code units of _LineContinuation_ while TRV includes them. `<CR><LF>` and `<CR>` _LineTerminatorSequences_ are normalized to `<LF>` for both TV and TRV. An explicit _EscapeSequence_ is needed to include a `<CR>` or `<CR><LF>` sequence.

Closing this issue as everything is working as intended.

**Closed by evanw** 2020-11-18 01:46 UTC

**Comment by Kein** [comment] 2023-07-05 14:29
@evanw is there a way to enforce window's line breaks?

**Comment by evanw** [comment] 2023-07-05 16:23
What does "window's line breaks" mean?

**Comment by Kein** [comment] 2023-07-05 17:22
'CRLF' instead of 'LF', which are commonly considered as `Windows' line breaks` vs `UNIX line breaks`.
Right now, by default, esbuild outputs my js with `LF`

**Comment by evanw** [comment] 2023-07-06 12:09
Ah ok. There is no way to do this. But it's trivial to transform the source code afterward to replace LF with CRLF if you want CRLF. I believe doing that shouldn't affect source maps or template literal contents.

**Comment by Kein** [comment] 2023-07-06 13:39
The whole point of using esbuild in a first place is to have one-package solution. If I still have to resort to other tools/system esbuild tries to superseed [then what the point of esbuild](https://xkcd.com/927/)?

**Comment by lazarljubenovic** [comment] 2023-07-08 18:26
> The whole point of using esbuild in a first place is to have one-package solution.

That was never the impression I got:

> The main goal of the esbuild bundler project is to bring about a new era of build tool performance, and create an easy-to-use modern bundler along the way. (https://esbuild.github.io/)

FAQ even specifically addresses this:

> I don't think esbuild should become an all-in-one solution for all frontend needs. In particular, I want to avoid the pain and problems of the "webpack config" model where the underlying tool is too flexible and usability suffers. (https://esbuild.github.io/faq/#upcoming-roadmap)

**Comment by Kein** [comment] 2023-07-08 18:44
> That was never the impression I got:

Well, it is all well to have our own impressions on thing, but the reality of the things is that esbuild being adopted too widely now:   
https://news.ycombinator.com/item?id=33441469

I have no issue with some members of the dev team having strong and bold opinions on some syntax things *by default*, **as long as there is an option for the end-user.** As it stands right now, [a lot of opinionated stuff in `esbuild`](https://github.com/evanw/esbuild/issues/623) does not have an option of a choice.
