### ISSUE TITLE
Execution error while switching between docker (alpine) and macOS.

### ISSUE THREAD

**Issue by hsblhsn** [evanw/esbuild#1223] opened 2021-04-28 22:52 UTC
Hello there!

### The problem.
In my development machine I use docker and I share the project directory with docker as a volume. Inside docker, I run `npm run serve` or `npm run dev` while using `vite`. And in my host machine (macos), sometimes I run `npm install` or `npm run build`. 

It works when I always use docker or always use macos. But when switch between these two as I have said above, that causes an execution errror. I think it's because of the binary execution format. The binary compile for linux, does not work on macos. And the binary compiled for macos, does not work for linux.

### Possible solution.

What if we do not store the bin as `bin/esbuild` or `bin/esbuild.exe`. Instead we store it like `bin/esbuild_darwin_x64`, `bin/esbuild_darwin_silicon`, `bin/esbuild_linux_x64` e.t.c.

So, when running the binary, we will detect the underlying system, then install & run the exact appropriate binary for the system.

**How is the idea? Good enough to implement? I can open a PR then.**

**Comment by hsblhsn** [comment] 2021-04-28 22:55
I think it also fixed #1151

**Comment by evanw** [comment] 2021-04-28 23:35
The package is not designed to change once installed. People sometimes run esbuild in an environment that doesn’t have access to the internet, so I plan to keep it that way.

You will need to either reinstall esbuild if you want to use the same directory tree on different operating systems, or you can use the `esbuild-wasm` package if you want to share the same directory tree between operating systems without reinstalling.

**Comment by nihalgonsalves** [comment] 2021-04-29 19:38
I've seen this question a couple of times, including at vitejs/vite#2671. 

Here's an easy workaround using an ENTRYPOINT:

- `entrypoint.sh`

  ```sh
  #!/bin/sh

  npm rebuild esbuild

  exec "$@"
  ```

- `Dockerfile`

  ```dockerfile
  FROM node:14-alpine

  WORKDIR /usr/app/

  COPY entrypoint.sh /entrypoint.sh
  RUN chmod +x /entrypoint.sh

  ENTRYPOINT ["/entrypoint.sh"]

  # for example, to include node_modules built on the
  # macOS host with the wrong architecture
  # (this would also happen if mounted as a volume)
  ADD . .

  # use your original command
  CMD ["yarn", "esbuild", "--help"]
  ```

**Comment by evanw** [comment] 2021-04-30 21:12
I'm going to close this since it sounds like esbuild's installer is working as intended. The problem is instead that a `node_modules` directory from one operating system is being run using another operating system, which isn't something that generally works (e.g. with other packages that use native node bindings).

**Closed by evanw** 2021-04-30 21:12 UTC
