### ISSUE TITLE
How to minify exclude MySQL - PROTOCOL_INCORRECT_PACKET_SEQUENCE

### ISSUE THREAD

**Issue by FLavalliere** [evanw/esbuild#2611] opened 2022-10-14 04:28 UTC
Looks like there is a bug with MySQL and minification.

I am not sure how to use the `mangle` options with ESBuild to make it work with mysql and minification.

See:

https://github.com/serverless/serverless/issues/5946

https://stackoverflow.com/questions/33261828/serverless-framework-with-node-mysql-protocol-incorrect-packet-sequence-error

Any help would be appreciated. Thank you.

**Comment by evanw** [comment] 2022-10-14 13:41
What does `mangle` mean? Do you mean esbuild's [`--mangle-props`](https://esbuild.github.io/api/#mangle-props) option? That option is an advanced feature that by design isn't safe to use on all code. You can only use it on code that has been specifically written for it. If you are using a library that wasn't written for it and it's not working, then the fix is to just not use `--mangle-props`.

**Comment by FLavalliere** [comment] 2022-10-15 14:44
I am not sure what other people were saying, but in webpack it seems that the `mangle: false` with `minify: true` does works.

I wonder if there is an mangle props to make it work.

Note: This was to do an simple connect from AWS Lambda to MySQL.

**Comment by evanw** [comment] 2022-10-15 19:14
You are talking about Webpack options on an issue with esbuild, which has nothing to do with Webpack. So I'm marking this issue as `unactionable` because there's nothing I can do with this issue. To demonstrate the issue here, you would likely need to provide the problematic input code and the esbuild command used.

**Comment by FLavalliere** [comment] 2022-10-16 15:36
Ok, i understand that this is marked as unactionable, though it would be interesting for the esbuild project to have an option that allows minification of the code using mysql, that supports aws lambda.

**Comment by evanw** [comment] 2022-10-16 15:53
Sure but you haven't sufficiently described what the problem is, so it's not possible to know what to fix. That's what the `unactionable` label means.

**Comment by evanw** [comment] 2022-10-23 13:51
Closing this issue because it has remained unactionable.

**Closed by evanw** 2022-10-23 13:51 UTC
Labels: unactionable
