### ISSUE TITLE
Rebuild after reload

### ISSUE THREAD

**Issue by deviant310** [evanw/esbuild#3250] opened 2023-07-19 15:52 UTC
Why esbuild rebuilds each time I reload page in the browser?

I understand the behavior "reload after rebuild".
But I absolutely don't understand the behavior "rebuild after reload". For what?

UPD: Docs doesn't explain the reason of this behavior.
<img width="970" alt="image" src="https://github.com/evanw/esbuild/assets/38217402/8fd7a42c-65a9-4f5e-bd3a-e181aee6e448">

Thanks.

Esbuild version: 0.18.14

**Comment by evanw** [comment] 2023-07-19 15:57
It's right there in the screenshot you posted:

> Incoming requests automatically start new builds so your web app is always up to date when you reload the page in the browser.

**Comment by deviant310** [comment] 2023-07-19 16:03
Yes, but I don't understand why reloading the page should manage build state (reload -> rebuild)? Usually editing the code manages build state (editing -> rebuild -> reload). At least that's typical behavior for webpack.

**Comment by deviant310** [comment] 2023-07-19 16:07
That is, I don't understand how rebuilding after reloading can help to keep my app to date. My app doesn't change after reloading, isn't?

**Comment by evanw** [comment] 2023-07-20 13:04
If esbuild didn't do this, then requests could potentially be out of date. For example if you quickly edited a file and then reloaded the page before the next build had finished, you would get a stale page when you reloaded. Or you might get a garbled page where some of the files are from the new build and others are from the old build.

This feature you are complaining about is the primary point of using esbuild's built-in development server. If you don't like it, then you don't have to use it. You can use any other web server to serve the output that esbuild generates. You can even use esbuild's built-in web server without this behavior if you make a separate call to esbuild's `serve` API and only pass the `servedir` parameter.

**Comment by evanw** [comment] 2023-07-22 00:25
I'm closing this issue because esbuild is working as intended here.

**Closed by evanw** 2023-07-22 00:25 UTC
