### ISSUE TITLE
Minify whitespaces removing `/* @__PURE__ */`

### ISSUE THREAD

**Issue by Xenfo** [evanw/esbuild#1990] opened 2022-02-05 01:07 UTC
How do I prevent this behaviour? I need the comment to be there but the file to also be minified.

**Comment by hyrious** [comment] 2022-02-05 01:13
As I know there's no way to keep it with `--minify-whitespace` currently. I'd recommend you to turn off minifying when exporting an esm library.

**Comment by Xenfo** [comment] 2022-02-05 01:16
The other minify options are fine though?

**Comment by evanw** [comment] 2022-02-05 02:57
Whitespace removal is intended for distribution to end users, in which case pure annotations are meaningless.

**Comment by evanw** [comment] 2022-02-16 17:56
Closing as by design.

**Closed by evanw** 2022-02-16 17:56 UTC
