### ISSUE TITLE
Conflicting symbols w/ inject and imports

### ISSUE THREAD

**Issue by arcanis** [evanw/esbuild#1588] opened 2021-09-10 10:05 UTC
Unfortunately I'm not able to repro it in a minimal code ... after trying for some time I figured I should still open an issue, perhaps you'll have an idea what might cause this. Feel free to close if you have no idea how to find the bug.

Essentially I have the following injected code:

```ts
import * as React from 'react';
export { React };
```

Some source codes use the auto-imported React symbols, some don't, and some import React on their own (usually for types; sometimes via `import * as React`, and sometimes via `import React, {useState}` when they use hooks).

The generated outputs (with `--splitting --format esm`) looks like this:

```ts
import {
  React,
  __toModule,
  init_inject,
  require_react
} from "./chunk-Q3YUXC5F.js";

// y.js
init_inject();
var React = __toModule(require_react());

// z.js
init_inject();
console.log(React);

// y.js
console.log(React);
```

Which yields a conflicting declaration error, since `var React` tries to override the imported `React` symbol. However, when I try to reproduce this in a vaccum, ESBuild correctly turns it into `var React2`, and the problem doesn't trigger...

**Comment by arcanis** [comment] 2021-09-10 10:06
If it can help, it seems that replacing the inject file:
```ts
import * as React from 'react';
export { React };
```

By a different import:
```ts
import React from 'react';
export { React };
```

Seems to work (or at least it doesn't crash at the same spot, and this new crash looks unrelated).

**Comment by evanw** [comment] 2021-09-13 00:30
I believe you that this is an issue. This is likely caused by a subtle bug in the linker. However, it's probably going to be close to impossible to track down without a way for me to reproduce it. Don't worry about creating a minimal test case. I can still fix this with a very large test case, just as long as I can reproduce it.

**Comment by arcanis** [comment] 2021-09-14 15:38
The problem is that it covers a proprietary code, so I can't share it 🤔 I'll put some time aside to try to craft something suitable for a repro.

**Comment by evanw** [comment] 2022-12-04 04:45
This issue is unfortunately unactionable. Closing due to lack of a reply.

**Closed by evanw** 2022-12-04 04:45 UTC
Labels: unactionable
