### ISSUE TITLE
Cannot bundle validate.js

### ISSUE THREAD

**Issue by peterjanes** [evanw/esbuild#1034] opened 2021-03-22 20:26 UTC
I'm not sure why, but esbuild can't bundle `validate.js`. For example,

```
$ cat test.js
import validate from 'validate.js';
$ yarn esbuild test.js --bundle
 > test.js:1:21: error: Could not resolve "validate.js" (mark it as external to exclude it from the bundle)
    1 │ import validate from 'validate.js';
      ╵                      ~~~~~~~~~~~~~

1 error
```

After a bit of fiddling it seems to be the `main` property in the `package.json` for `validate.js`: when it's
```
"main": "validate.js"
```
it fails, and when it's
```
"main": "./validate.js"
```
it's successful.

That doesn't appear to be the entire issue, though, as a similarly-named package (`ipaddr.js`) doesn't exhibit the same problem when I manually change it to have a similar structure (I moved `lib/ipaddr.js` to its root directory and set the `main` value `ipaddr.js`).

The behaviour is the same whether I use yarn 1 (with or without pnp), yarn 2, or npm.

**Comment by evanw** [comment] 2021-03-22 23:37
I'm unable to reproduce this given the description. It seems to work fine for me. Can you provide a sample project and build command that reproduces the issue? Also, what platform are you on?

**Comment by peterjanes** [comment] 2021-03-23 14:32
Curious... maybe because I started with yarn 2 and tried the others afterwards, but yarn 2 is the only one I can duplicate with now. (I'm running on Linux.)

I've put some scripts in a gist: https://gist.github.com/peterjanes/dd5c5c48bb5bbbe8e1bfc19363138e9c

**Comment by evanw** [comment] 2021-03-23 21:17
Yarn 2's PnP mode breaks a lot of node-based tooling including esbuild because it comes up with its own way of doing file resolution instead of following node's specification. And their file resolution algorithm is deliberately opaque (e.g. it's not specified and may be changed at any time) so it's not something that esbuild can handle itself. Instead, the Yarn 2 team has made [an esbuild plugin for Yarn 2 PnP support](https://github.com/yarnpkg/berry/tree/master/packages/esbuild-plugin-pnp#yarnpkgesbuild-plugin-pnp) that you have to use instead.

Alternatives to this include using a package manager that implements normal path resolution rules (basically everything except Yarn 2 with PnP enabled), or disabling Yarn 2's PnP mode.

**Comment by evanw** [comment] 2021-03-23 21:35
Closing because this is a problem with Yarn 2 with PnP enabled, not with esbuild.

**Closed by evanw** 2021-03-23 21:35 UTC
