### ISSUE TITLE
ESBuild breaks valid JS expression in the CoreJS library resulting in a SyntaxError

### ISSUE THREAD

**Issue by diego-carvallo** [evanw/esbuild#3975] opened 2024-11-12 18:05 UTC
We use ViteJS in multiple of our services, we have CoreJS as a dependency and as sub-dependecy.

When building Vite minifies using ESBuild and this particular expressions get's broken: 
`var toString = uncurryThis(1.0.toString);`

ref: [see related core-js code here](https://github.com/zloirock/core-js/blob/master/packages/core-js/internals/uid.js#L6)

ESBuild removes the zero and the minified result is:  `var toString$b=uncurryThis$y(1.toString);` which give us the Syntax Error in the following screenshot:

<img width="1079" alt="image" src="https://github.com/user-attachments/assets/ac34a2c9-462a-4fc8-bd7e-94a1755a4b7e">

**Comment by hyrious** [comment] 2024-11-12 22:39
esbuild doesn't do this, as someone has pointed out in the core-js's issue. If you can provide a minimal reproduction maybe we can help find out which tool is erasing the important space.

There was an issue here (#3766) but seems not related to yours.

**Comment by evanw** [comment] 2024-11-16 01:19
You can see what esbuild does here:

https://esbuild.github.io/try/#dAAwLjI0LjAALS1taW5pZnkAIHZhciB0b1N0cmluZyA9IHVuY3VycnlUaGlzKDEuMC50b1N0cmluZyk7

Specifically `1.0.toString` turns into `1 .toString` (note the space in between `1` and `.`) when it's minified with esbuild, which is valid JavaScript. It is not turned into `1.toString` by esbuild, which as you point out is invalid JavaScript.

Your problem is likely neither with esbuild nor with core-js. Rather, your problem is with whatever tool is removing the space that esbuild added. It's possible that Vite is the problem (since you mentioned using Vite). Vite's repo is here if you want to send them a bug report: https://github.com/vitejs/vite

I'm closing this issue both because it doesn't seem to be a bug with esbuild, and because you didn't provide any reproduction information as indicated in esbuild's issue reporting instructions.

**Closed by evanw** 2024-11-16 01:19 UTC
