### ISSUE TITLE
Question: How do return a function and not a promise from the bundle?

### ISSUE THREAD

**Issue by secretlifeof** [evanw/esbuild#1069] opened 2021-03-27 10:46 UTC
Hi @evanw.

It is so much fun to use Esbuild! Beside the speed, reading the documentation is a joy. Not too much, not too little.

Now to my question and I don't really know if it is possible or even should be. At work we are using Yahoo YUI and how this works, is that we have a global YUI object that is used like this in different files.

```javascript
YUI.add("module-name", (Y => {
  Y.myString = "mindful"
}, "version", { requires: [ "different-module-name" ] } )
```

There is a global YUI.use method that loads all the YUI.add methods before starting the app. Due to calling Promise.resolve this does not work.

```js
Promise.resolve().then(() => __toModule(require_fileName()));
```

If I remove Promise.resolve it works.

```js
__toModule(require_fileName()
```

Is there a way to change this behaviour in Esbuild?
The files are bundled using IIFE. Is there a different workaround to make bundling work without removing Promise.resolve?

Thank you very much upfront! I wish you a happy weekend.

**Comment by evanw** [comment] 2021-03-27 20:44
I'm unable to understand what you're saying. I think there is some code missing. It's not clear to me where `Promise.resolve()` is coming from. Could you provide a more complete code example that can independently reproduce the problem? Also esbuild only supports CommonJS modules and ES modules but not Yahoo YUI modules (in case that's where the problem is coming from).

**Comment by secretlifeof** [comment] 2021-03-27 21:06
Thanks for answering so quickly. Yes you are right there is some code missing. I am sorry about that. I am using CommonJS modules.

```javascript
(() => {
    var __create = Object.create;
    var __defProp = Object.defineProperty;
    var __getProtoOf = Object.getPrototypeOf;
    var __hasOwnProp = Object.prototype.hasOwnProperty;
    var __getOwnPropNames = Object.getOwnPropertyNames;
    var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
    var __markAsModule = target =>
        __defProp(target, "__esModule", { value: true });
    var __commonJS = (cb, mod) => () => (
        mod || cb((mod = { exports: {} }).exports, mod), mod.exports
    );
    var __exportStar = (target, module, desc) => {
        if (
            (module && typeof module === "object") ||
            typeof module === "function"
        ) {
            for (let key of __getOwnPropNames(module)) {
                if (!__hasOwnProp.call(target, key) && key !== "default") {
                    __defProp(target, key, {
                        get: () => module[key],
                        enumerable:
                            !(desc = __getOwnPropDesc(module, key)) ||
                            desc.enumerable
                    });
                }
            }
        }
        return target;
    };
    var __toModule = module => {
        return __exportStar(
            __markAsModule(
                __defProp(
                    module != null ? __create(__getProtoOf(module)) : {},
                    "default",
                    module && module.__esModule && "default" in module
                        ? { get: () => module.default, enumerable: true }
                        : { value: module, enumerable: true }
                )
            ),
            module
        );
    };

    // directory/Activity.cl.js
    var require_Activity_cl = __commonJS(() => {
        // each file has a YUI.add function
        YUI.add("Activity", function(Y) {
            Y.log = "test log";
            Y.createSomeStuff = function() {};
            // more code inside here 
        });
    });

    // esbuild.client.js
    Promise.resolve().then(() =>
        __toModule(require_Activity_cl())
    );
})();
```

Sorry about not expressing that clearly. YUI is a global object.
```javascript
// Activity is the module from above. This file below is not bundled.
YUI().use('Activity', function (Y) {
    // YUI will call this function and pass in the YUI instance (Y) once all
    // modules have finished loading and are ready to use.
    // Due to Promise.resolve() YUI thinks the "Activity" module is not loaded
    ....code that uses the "Activity" module from above
});
````

Is that somewhat more understandable?

**Comment by evanw** [comment] 2021-03-27 21:09
What does the original source code for `esbuild.client.js` look like?

**Comment by secretlifeof** [comment] 2021-03-27 21:14
Like this
```
YUI.add(
    "Activity",
    function(Y) {
        Y.log = "test log";
        Y.createSomeStuff = function() {};
        // more code inside here
    },
    "1.0.0",
    {
        requires: ["module1", "module2", "module3"]
    }
);
```

**Comment by evanw** [comment] 2021-03-27 21:24
From https://github.com/evanw/esbuild/issues/1069#issuecomment-808802439 it looks like that is the contents of `directory/Activity.cl.js` not of `esbuild.client.js`. From your description, I'm assuming `esbuild.client.js` looks something like this:

```js
import('./directory/Activity.cl.js')
```

That code would cause esbuild to generate `Promise.resolve()`. But this must use promises because `import()` is [specified to return a promise](https://tc39.es/ecma262/#sec-import-call-runtime-semantics-evaluation). It is an asynchronous import mechanism by design. If you want a synchronous import mechanism you should use `require()` instead:

```js
require('./directory/Activity.cl.js')
```

**Comment by secretlifeof** [comment] 2021-03-27 21:34
It is a bit late over here. I got confused about the file names. Yes you are right! Learned something new about the difference of require and import.
Thank you so so very much 🙏 That solved it. Can definitely fall asleep happy now.

**Comment by evanw** [comment] 2021-03-27 21:35
Sure thing. Closing as this seems to be resolved.

**Closed by evanw** 2021-03-27 21:35 UTC
