### ISSUE TITLE
How do you get locally hosted fonts working?

### ISSUE THREAD

**Issue by RichMatthews** [evanw/esbuild#3461] opened 2023-10-23 10:27 UTC
I am hoping to find a way whereby I can do this:

`import Bold from "pdf/fonts/bold.ttf"` and it will import the font but I'm wondering how I do this?

I'm using nodemon with esbuild and in the nodemon config I have: `  "exec": "esbuild src/index.ts --loader:.ttf=file",
I haven't included all the code just the relevant stuff but this still 

I get the error: `Error: ENOENT: no such file or directory, open './bold-D4CCEYNO.ttf'` is it appending something to that file and then not able to find it?

**Comment by evanw** [comment] 2023-11-18 19:16
You didn't follow the issue reporting instructions. There isn't enough information here to reproduce your problem. I'm marking this issue as `unactionable` because there's nothing I can do with it. It will be closed later if the issue reporting instructions are still not followed.

**Comment by noBaldAaa** [comment] 2023-11-30 02:06
hi

**Comment by evanw** [comment] 2023-11-30 03:03
Closing this issue due to lack of a follow-up reply.

**Closed by evanw** 2023-11-30 03:03 UTC
Labels: unactionable
