### ISSUE TITLE
How to using this with Vue project?

### ISSUE THREAD

**Issue by xuelabi123** [evanw/esbuild#488] opened 2020-10-28 02:16 UTC

**Comment by evanw** [comment] 2020-10-28 02:22
Closing as a duplicate of #113. From that thread:

> This is a duplicate of #75. Apparently you can use Vue with esbuild if you use JSX syntax. Otherwise, Vue syntax is not supported by esbuild itself. However, esbuild is being integrated into the Vue ecosystem as a library to transform TypeScript to JavaScript. See the thread for details.

**Closed by evanw** 2020-10-28 02:22 UTC

**Comment by tnorthcutt** [comment] 2021-11-17 14:29
FWIW, for anyone else googling Vue + esbuild things and ending up here, the above comment mentions #113, but I believe should actually mention [#133](https://github.com/evanw/esbuild/issues/133)
