### ISSUE TITLE
Default export of a class produce a default variable that reference the class

### ISSUE THREAD

**Issue by MrSimsure** [evanw/esbuild#1346] opened 2021-06-03 23:23 UTC
I recently switched from rollup to esbuild for my project looking for an increment in speed and performance.
In my project i have several classes in modules that export themself as default, like here:

> export default class hello_there {
>     constructor(){ 
>         //stuff here
>     }
> }

This module is referenced in another one, wich is the entry point for esbuild.
But in the final bundle the result is something like that:

> var hello_there = class {
>     constructor() {
>      //stuff here
>     }
>   }
>   var hello_there _default = hello_there ;

The class is exported properly, but then another variable is added, created by the default statement in the export, and all the reference to the class name is substituted with this default variable.
This gives me problem when i go to minify the file with an external minifier, as in the minification process the class name is substituted with the default variable name.

The problem of this is actually in the minifier as the bundle  esbuild produced works exatcly as it should, but i would prefer to avoid the creation of this default variable at the root if this is possible. 
While working with rollup default exports were not making this default variable that references the classes itself.
I tried looking for some options when calling the bundler but nothing seems to feet this need.
Some one can help me?

Some more information 

- The classes are the only thing in the file, that's the reason they are default exported
- The behaviour that i would like is the bundling of only the classes as it is, without creating other variables and most importantly without substituting every reference of the class with this variable
- The bundle works as it is, but for my needs i have to be sure that the classes names stay the same across all my files

**Comment by evanw** [comment] 2021-06-04 02:59
It looks like this is a bug in esbuild, but not for the reason you think. It seems like this is actually a correctness issue. The code `export default class x {} x = 0` should export 0 but esbuild currently exports the class, which is incorrect. I assume the problem is that esbuild is treating this similar to `export default (class x {}); x = 0` instead of `export {x as default}; class x {}; x = 0`. This should be fixed.

However, the fix likely won't address your concern. Class declarations are deliberately transformed into variable declarations when bundling is enabled. The reason for doing this is complex. Part of it has to do with [severe performance issues](https://github.com/evanw/esbuild/issues/478) that some JS engines have with class declarations in large bundles, and part of it has to do with ensuring bundling correctness in esbuild's parallel and performance-optimized architecture, which is complex to explain.

Converting the class declaration to a variable declaration here should not be a correctness issue, since they are equivalent. There is one exception: by default, esbuild does not make any guarantees about preserving the value of the `.name` property on functions and classes by default since the need for that is somewhat uncommon and doing so comes at a code size cost. If the `.name` property of the class object is important to you, you should enable the [keep names](https://esbuild.github.io/api/#keep-names) option.

**Comment by MrSimsure** [comment] 2021-06-04 07:59
Thank you very much, the keep names option preserved my calsses name also after the minification, this should work for my case for now.

> Class declarations are deliberately transformed into variable declarations when bundling is enabled

I wasn't minding the class declaration itself becoming a variable, but the default statement making a second variable under the class declaration and substituting every class reference with this second variable.
Actually if i remove the default statement from the class export, in the final bundle the class is exported correctly, and the second variable isn't present, but keeping the export as default is a lot more convenient when importing in other files.

**Comment by MrSimsure** [comment] 2021-06-04 08:16
Ok, i tried the last version after the new commits (0.12.6) and everything is working as expected, thank you very much, especially for the rapidity of the fix!

**Closed** 2021-06-04 08:19 UTC
