### ISSUE TITLE
Bundle Generated using esbuild throwing the exception

### ISSUE THREAD

**Issue by hassanazharkhan** [evanw/esbuild#1597] opened 2021-09-12 19:13 UTC
I'm getting the following exception while running my bundled file on local, I'am using the library called [dynamo-easy](https://github.com/shiftcode/dynamo-easy) which is heavily relies on typescript decorators.

**Exception:**  

```js
throw new Error("make sure you have enabled the typescript compiler options which enable us to work with decorators (see doc)");
```

**tsconfig.json:**

```json
{
  "extends": "../../tsconfig.build.json",
  "compilerOptions": {
    "rootDir": "./",
    "outDir": "./dist"
  },
  "include": [
    "./src/**/*"
  ]
}
```

**tsconfig.build.json**

```json
{
  "compilerOptions": {
    "sourceMap": true,
    "target": "es2019",
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "importHelpers": true,
    "declaration": true,
    "module": "commonjs"
  },
  "exclude": [
    "node_modules",
    "dist",
    "build",
    "**/build",
    "**/dist",
    "**/node_modules",
    "cdk.out",
    "**/cdk.out",
    "__mocks__",
    "**/__mocks__/**",
    "**/__tests__/**",
    "**/*.test.ts"
  ]
}
```

esbuild version: ^0.12.25
Os: MacOS BigSur

**Comment by evanw** [comment] 2021-09-12 20:21
Looks like TypeScript decorators are working fine to me:

```
$ cat foo/bar/tsconfig.json 
{
  "extends": "../../tsconfig.build.json",
  "compilerOptions": {
    "rootDir": "./",
    "outDir": "./dist"
  },
  "include": [
    "./src/**/*"
  ]
}

$ cat tsconfig.build.json 
{
  "compilerOptions": {
    "sourceMap": true,
    "target": "es2019",
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "importHelpers": true,
    "declaration": true,
    "module": "commonjs"
  },
  "exclude": [
    "node_modules",
    "dist",
    "build",
    "**/build",
    "**/dist",
    "**/node_modules",
    "cdk.out",
    "**/cdk.out",
    "__mocks__",
    "**/__mocks__/**",
    "**/__tests__/**",
    "**/*.test.ts"
  ]
}

$ cat foo/bar/check.ts 
let didDecoratorsWork = false
let decorator = () => didDecoratorsWork = true
@decorator class Foo {}
console.log({ didDecoratorsWork })

$ esbuild foo/bar/check.ts | node
{ didDecoratorsWork: true }
```

You'll have to be more specific about what isn't working. Right now I have no way of reproducing your issue.

**Comment by hassanazharkhan** [comment] 2021-09-12 22:47
@evanw Thank you for looking into this, I have created a repo with the bug stated above, would you able to check there?

https://github.com/hassanazharkhan/esbuild-decorator-bug

Reproduction steps:

`npx projen && node esbuild.js && node -e "console.log(require('./build/index.js').handler({}));" `


<img width="1154" alt="Screenshot 2021-09-13 at 3 46 46 AM" src="https://user-images.githubusercontent.com/57677979/133005147-ad5fdb1e-b599-49f6-9073-b5d3dfbdea6d.png">

**Comment by evanw** [comment] 2021-09-13 00:13
It looks like this library you're trying to use relies on TypeScript's [`emitDecoratorMetadata`](https://www.typescriptlang.org/tsconfig#emitDecoratorMetadata) setting. This does not work with esbuild because it requires a type system to function, and [replicating TypeScript's type system within esbuild is out of scope due to complexity](https://esbuild.github.io/content-types/#no-type-system). One workaround is to run `tsc` first to convert `.ts` files into `.js` files and then run esbuild on the resulting `.js` files. But your issue is not a problem with esbuild because `emitDecoratorMetadata` is intentionally not supported.

**Closed** 2021-09-13 20:33 UTC
Labels: unactionable
