### ISSUE TITLE
"esbuild" should be marked as external for use with "require.resolve" [require-resolve-not-external]   

### ISSUE THREAD

**Issue by huangjihua** [evanw/esbuild#2698] opened 2022-11-23 14:16 UTC
```bash
$ tsup src/index.ts --dts --format cjs,esm
CLI Building entry: src/index.ts
CLI Using tsconfig: tsconfig.json
CLI tsup v6.5.0
CLI Using tsup config: /Users/hank/Documents/ah-pub-lib/test/tsup.config.ts
CLI Target: esnext
CLI Cleaning output folder
CJS Build start
ESM Build start
DTS Build start

 WARN  ▲ [WARNING] "esbuild" should be marked as external for use with "require.resolve" [require-resolve-not-external]                                                                                               22:01:31

    node_modules/.pnpm/esbuild@0.15.15/node_modules/esbuild/lib/main.js:1718:36:
      1718 │   const libMainJS = require.resolve("esbuild");
```

**Comment by evanw** [comment] 2022-11-23 14:32
The error message already explains what you need to do here:

> ```
> "esbuild" should be marked as external for use with "require.resolve"
> ```

Documentation is here: https://esbuild.github.io/api/#external

**Comment by evanw** [comment] 2022-11-23 16:35
Closing this as this is working as intended, and the error message is already working as it should be.

**Closed by evanw** 2022-11-23 16:35 UTC

**Comment by nandorojo** [comment] 2023-08-10 16:09
Sorry to ping an old (and resolved) issue. But I'm getting this warning too, and I'm not sure how to solve the associated issue.

I am bundling a VSCode Extension with `esbuild`. The extension is wrapping `@tamagui/static`, which itself uses `esbuild`. The VSCode extension relies on `@tamagui/static` to load files, etc.

If I do `esbuild ... --external:esbuild`, then the extension throws `cannot find module esbuild` at runtime.

If I don't mark it as an external, I get the warning, but it does build properly. However, at runtime, the plugin appears to hang at the esbuild step (without even throwing an error).

I _think_ I need `esbuild` to get bundled so that my upstream library (`@tamagui/static`) can use it.

What's the best way to handle this situation? It's possible I just need to learn more about what the externals would do.

Thank you!

**Comment by evanw** [comment] 2023-08-10 17:00
Unfortunately the `esbuild` package does not support bundling. One reason is because it uses a native executable that needs to be run by the OS, not by the JS runtime. You'd need to mark `esbuild` as external in this case so that it's not bundled, but then also somehow make sure that your run-time environment has the `esbuild` package available.

However, this is probably not what you should do here because if you're packaging a VSCode extension then I imagine you'd need to somehow include a copy of esbuild for every possible platform, which is not straightforward or desirable. Normally when you `npm install esbuild`, npm just downloads the compiled copy of esbuild for the current platform. But I assume VSCode extension installation doesn't run npm and doesn't have the ability to do per-platform installation.

One thing you could do here is try to substitute the `esbuild` package for the `esbuild-wasm` package. This package doesn't support bundling either but at least it only has a single copy of the binary executable that works on all platforms. So you would have `esbuild-wasm` be external and then make sure that your published package includes a copy of the `esbuild-wasm` package in the `node_modules` folder on the file system. Note that `esbuild-wasm` only supports a subset of the features of `esbuild` so this may or may not work depending on what `@tamagui/static` does.

**Comment by nandorojo** [comment] 2023-08-10 17:45
@evanw Thanks so much for the detailed response. This adds a lot of useful context. 

> I assume VSCode extension installation doesn't run npm and doesn't have the ability to do per-platform installation.

Correct, it runs a single node script and expects the entire file to be bundled in place. 

> So you would have esbuild-wasm be external and then make sure that your published package includes a copy of the esbuild-wasm package in the node_modules folder on the file system.

By “published package”, are you referring to `@tamagui/static` here, or the extension? Presumably I would still need `esbuild-wasm` to get bundled, right? My guess is `@tamagui/static` would need to export a bundled version of itself with esbuild-wasm in it, but I may have missed something.

Going to see if I can coordinate with `@tamagui/static` to try esbuild-wasm as a solution.

Thanks again for the help (and for esbuild generally).

**Comment by evanw** [comment] 2023-08-10 17:51
> By “published package”, are you referring to `@tamagui/static` here, or the extension? Presumably I would still need `esbuild-wasm` to get bundled, right? My guess is `@tamagui/static` would need to export a bundled version of itself with esbuild-wasm in it, but I may have missed something.

It's been a while but I think I remember that when you publish a VSCode extension, it will zip your local file structure including your `node_modules` folder and then unzip it when that extension is installed. So you may not need anything changed about `@tamagui/static`. You may be able to bundle code that uses `@tamagui/static` with `esbuild` marked as external, then somehow substitute `esbuild` for `esbuild-wasm`. This substitution may just automatically work because `esbuild` and `esbuild-wasm` deliberately expose the same API. 

You could try doing this substitution with an esbuild plugin. You may also be able to do this substitution with npm itself (e.g. using [`overrides`](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides), maybe like `"overrides": { "esbuild": "npm:esbuild-wasm@v0.19.0" }`). I'm not sure though. It'll likely require some experimentation.

**Comment by hyrious** [comment] 2023-08-10 22:46
I [made](https://github.com/hyrious/vscode-import-cost) a VS Code extension before that uses esbuild. The solution is like what evan said to substitute esbuild with esbuild-wasm. On the other hand, you can also try to find the user's local esbuild by looking at `$(npm root -g)/esbuild/lib/main.js` in real fs. But invoking that package can be a bit tricky since you do not control the dependency's code.

**Comment by nandorojo** [comment] 2023-08-10 22:50
We got around the issue altogether by having tamagui write a json file to the user's filesystem. The VSCode extension is going to read that file instead of use tamagui's esbuild helpers to simplify things.

Appreciate the help.
