### ISSUE TITLE
Define's only support string as of 0.16.0

### ISSUE THREAD

**Issue by shammahatdivvy** [evanw/esbuild#2764] opened 2022-12-21 21:38 UTC
Getting the following error now:

```
  errors: [
    {
      id: '',
      pluginName: '',
      text: 'Expected value for define "__IS_DEVELOPMENT_BUILD__" to be a string, got boolean instead',
      location: {
```

from the following config:

```
  define: {
    __GIT_COMMITHASH__: JSON.stringify(gitCommitHash),
    __IS_DEVELOPMENT_BUILD__: false,
    __BROWSER__: false,
  },
```

We can work around it, but it would be nice to have this functionality back.

**Comment by evanw** [comment] 2022-12-21 21:46
This is by design. You are using esbuild incorrectly. I recommend reading [the release notes](https://github.com/evanw/esbuild/releases/tag/v0.16.0) to understand why this works the way it does. Closing this as “working as intended.”

**Closed by evanw** 2022-12-21 21:46 UTC
