### ISSUE TITLE
Incorrect `suspicious-nullish-coalescing` warning after upgrade

### ISSUE THREAD

**Issue by Stumblinbear** [evanw/esbuild#3602] opened 2024-01-18 13:43 UTC
Upgrading from `v0.19.5` to `v0.19.6` causes incorrect warnings around nullish coalescing:

```
▲ [WARNING] The "??" operator here will always return the left operand [suspicious-nullish-coalescing]

The left operand of the "??" operator here will never be null or undefined, so it will always be returned. This usually indicates a bug in your code:

new URLSearchParams().get("test") ?? false;
```

This is not correct, as this function will return `null` when the parameter does not exist. Note that I do not have `strictNullChecks` enabled in this project, so the possibility of `null` is not reflected in the signature during typechecking.

I have confirmed that upgrading to `v0.19.6` only changes the esbuild dependency and does not change other dependencies.

**Comment by evanw** [comment] 2024-01-18 17:27
I cannot reproduce this: https://esbuild.github.io/try/#dAAwLjE5LjExAABuZXcgVVJMU2VhcmNoUGFyYW1zKCkuZ2V0KCJ0ZXN0IikgPz8gZmFsc2U7

Please provide a way to reproduce your problem. I'm marking this issue as `unactionable` because there's nothing I can do with it without a reproduction.

**Comment by Inqnuam** [comment] 2024-01-19 13:45
@evanw Not sure what is the initial problem but with your repro link if we add `--minify` we lose nullish coalescing

```js
// original code
new URLSearchParams().get("test") ?? false;


// output without minify
new URLSearchParams().get("test") ?? false;


// output with minify
new URLSearchParams().get("test") 
```

https://esbuild.github.io/try/#dAAwLjE5LjExAC0tbWluaWZ5AG5ldyBVUkxTZWFyY2hQYXJhbXMoKS5nZXQoInRlc3QiKSA/PyBmYWxzZTs

**Comment by evanw** [comment] 2024-01-19 16:32
The `?? false` in that case is being removed by the minifier because it has no effect on the result of the evaluation of the code (the `false` value is discarded and never assigned to anything). If you assign it to something so it's actually used, then the minifier won't remove it:

https://esbuild.github.io/try/#dAAwLjE5LjExAC0tbWluaWZ5AHggPSBuZXcgVVJMU2VhcmNoUGFyYW1zKCkuZ2V0KCJ0ZXN0IikgPz8gZmFsc2U7

So that is also not a bug with esbuild.

**Closed** 2024-01-23 17:07 UTC
Labels: unactionable
