### ISSUE TITLE
Is TDZ avoidance still needed?

### ISSUE THREAD

**Issue by robpalme** [evanw/esbuild#2889] opened 2023-02-05 15:24 UTC
When bundling with `ESNext` output, classes can still get downleveled, due to an intentional performance-workaround called ***TDZ avoidance***.  This creates a consequential performance hazard when private fields end up using WeakMaps.

It looks like TDZ avoidance workaround originated in ESBuild as a response to [this issue](https://github.com/evanw/esbuild/issues/478) which highlighted a performance bug in Safari.  That bug was [fixed over two years ago](https://bugs.webkit.org/show_bug.cgi?id=199866) and has long since rolled out to all stable versions of Safari.  So it looks like Safari performance is no longer a justification for this feature.

ESBuild still has the `avoidTDZ` code branches and [the attached comment](https://github.com/evanw/esbuild/blob/d8a86cae1b77555838c94cd9acb77947bcd42606/internal/js_parser/js_parser_lower.go#L1988-L1989) explains it exists due to Safari.

Is it ok to remove this feature now?  Or should the comment be updated to describe some other reason?

**Comment by evanw** [comment] 2023-02-05 19:07
Part of the reason for doing this is indeed TDZ avoidance. It was originally added to work around a severe bug in Safari, but it sounds like it's still relevant despite that bug being fixed. When the TypeScript compiler's build process was switched to esbuild, it was reported that if esbuild did TDZ avoidance at all levels instead of at the top level, the TypeScript compiler would make their parser 5-9% faster: https://github.com/evanw/esbuild/issues/297#issuecomment-1251537365. So I assume that removing esbuild's TDZ would have very real performance consequences. There is also an argument for doing even more TDZ avoidance to improve performance further.

Another reason that this exists is that esbuild's linker may need to turn a module into a lazily-evaluated one in certain situations such as if it's dynamically imported. To avoid introducing binding overhead between modules when this happens, the linker represents module exports as variables outside of the lazy evaluation closure instead of inside.

So this:

```js
export class Foo {}
```

turns into this when the file needs to be lazily-evaluated:

```js
var Foo;
var init_a = __esm(() => {
  Foo = class {
  };
});
```

instead of something to this effect:

```js
var a_exports = {};
var init_a = __esm(() => {
  __export(a_exports, {
    Foo: () => Foo
  });
  class Foo {
  }
});
```

That way external files can reference `Foo` directly instead of having to reference `a_exports.Foo`, which has additional performance overhead.

So exported top-level variables have to be hoisted out of the lazy evaluation closure. This is straightforward for variable declarations: `var` is trivially hoisted, and `let`/`const` are converted to `var` (with compile-time safety checks that `const` variables are never reassigned). This is also trivial for function declarations since they are already hoisted and don't evaluate any code by themselves. But hoisting class declarations outside the closure would be incorrect as class declarations cause code evaluation in many ways (the base class expression, computed static fields, static blocks, etc...).

This means classes must be rewritten to store themselves outside of their scope. It's not necessarily trivial to expose the class to the outer scope. You might thing you could just do `exported_Foo = Foo` after the class body. But JavaScript lets you reassign class declaration symbols (e.g. `Foo = decorate(Foo)`) and the exported live binding symbol needs to change when that happens. Storing the class outside of the scope is a straightforward way to make this work.

Due to esbuild's parallel and performance-oriented design, esbuild does this transformation at the parsing stage. However, it's not yet known at that point whether or not the current module will need to be lazily-evaluated or not, so esbuild always does this transformation when bundling is active. It turns out this transformation is the same thing as TDZ avoidance.

This transformation could likely be improved. It's something I'll probably get around to doing at some point. I've been tracking several large areas of upcoming work (e.g. `tsconfig.json` issues, code splitting, plugin API) and the category of class declaration problems is one of these.

**Comment by jakebailey** [comment] 2023-02-07 20:27
Just to link back here, I re-tried applying babel's let/const transformation to the TypeScript compiler (which I did many months ago while working on the module conversion, but not on its own), and the results are really stunning: https://github.com/microsoft/TypeScript/pull/52656#issuecomment-1421249664

Back on https://github.com/evanw/esbuild/issues/297#issuecomment-1252657706 I mentioned that I was willing to ignore this problem because my impression was that eventually we'd have ESM and `export var` could be slower (and we already got a perf bump in most other areas that compensated), but it turns out that [esbuild already does](https://jakebailey.github.io/esbuild-playground/#Ly8gQGZpbGVuYW1lOiBjb25maWcuanNvbgp7CiAgImVudHJ5UG9pbnRzIjogWyIvaW5kZXgudHMiXSwKICAiZm9ybWF0IjogImVzbSIKfQoKLy8gQGZpbGVuYW1lOiBpbmRleC50cwpleHBvcnQgY29uc3QgZm9vID0gMTIzNDs=) emit `export var`.

I'd really love for engines to get better at this, but at this point in time the performance bump is so great that I am sort of flipping back to wanting to propose a minimal form of this downleveling (i.e. just the easy ones ignoring loops) in esbuild solely for performance (so not the entirety of #297), which is unfortunately the opposite direction @robpalme is looking for.

**Comment by jakebailey** [comment] 2023-02-07 20:47
> wanting to propose a minimal form of this downleveling

Just to make it clear what this proposal would be, a new option like "--avoid-tdz" would simply replace `let`/`const` with `var` where it doesn't have any semantic difference, and potentially, the flag also controls the `avoidTDZ` flag added for that one Safari case.

For the TypeScript compiler, I would enable this option for all of our outputs except for our test bundle; that combined with type checking would allow us to catch any real TDZ violations while improving performance.

But, I know that this is _exactly_ the opposite of this issue's premise, which is definitely unfortunate.

**Comment by evanw** [comment] 2023-02-07 20:49
> I'd really love for engines to get better at this, but at this point in time the performance bump is so great that I am sort of flipping back to wanting to propose a minimal form of this downleveling (i.e. just the easy ones ignoring loops) in esbuild solely for performance (so not the entirety of #297), which is unfortunately the opposite direction @robpalme is looking for.

Thanks for following up. Yeah I'd like to do this in esbuild too (to help make `tsc` faster). I think it'd have to be opt-in instead of applied automatically because it would change semantics around TDZ in nested scopes. Currently esbuild mostly handles TDZ in nested scopes correctly.

If it's just to improve performance, I'm wondering if it would be a better idea to only transform `let`/`const` if it's not closed over by a closure in a loop. Then there wouldn't be any need to hoist loop bodies out into a closure, which is the complex transformation that makes this non-trivial. I have a suspicion (but haven't done any testing) that down-leveling `let`/`const` that's closed over by a closure in a loop would be slower than just leaving it alone and letting the VM handle it due to the extra function call and scope creation overhead. My suspicion is that this case is pretty rare already and the overhead of adding an additional function call for every loop iteration in these cases is less than the overhead of a few TDZ checks. In any case, skipping `let`/`const` => `var` for complex cases is less work and complexity.

I've been thinking of a new flag `--opt:ignore-tdz` that would enable the `ignore-tdz` optimization, which would tell esbuild to pretend that TDZ can't happen. Sort of like undefined behavior in C/C++ I guess. This would enable this `let`/`const` => `var` transformation to improve performance. But it would also allow esbuild to potentially do other things too (maybe only when minifying) such as inlining `const` constants, which isn't currently done right now due to TDZ correctness. The structure of the `--opt:` flag is for extensibility, to allow for additional optimizations in the future.

**Comment by jakebailey** [comment] 2023-02-07 20:55
Semi-jinx? 😄 

Yeah, this is sort of what I was thinking; I'm definitely happy to test something like this out (I was going to try and implement it myself but I'm sure you can do it a lot faster than me).

The reality is that TS before 5.0 already downleveled down to ES5 specifically for this performance win; and I gave it up by switching to esbuild (which still made things better despite this regression), so from my perspective, I'm okay with the "undefined" behavior, especially now that we actually do run tests with TDZ enabled (which caught two bugs: https://github.com/microsoft/TypeScript/pull/50151).

**Comment by robpalme** [comment] 2023-02-08 10:42
FYI I've created a bug report for this in upstream V8.

https://bugs.chromium.org/p/v8/issues/detail?id=13723

**Comment by ChrisShank** [comment] 2023-02-09 00:33
> I've been thinking of a new flag --opt:ignore-tdz that would enable the ignore-tdz optimization, which would tell esbuild to pretend that TDZ can't happen.

To clarify, would this flag prevent the case where `export const foo = 1;` is transformed to `var o=1;export{o as foo};` ([playground](https://esbuild.egoist.dev/#W1siaW5kZXgudHMiLHsiY29udGVudCI6ImV4cG9ydCBjb25zdCBmb28gPSAxIn1dLFsiZXNidWlsZC5jb25maWcuanNvbiIseyJjb250ZW50Ijoie1xuICBcImZvcm1hdFwiOiBcImVzbVwiLFxuICBcImRlZmluZVwiOiB7IFwicHJvY2Vzcy5lbnYuTk9ERV9FTlZcIjogXCJcXFwicHJvZHVjdGlvblxcXCJcIiB9LFxuICBcImNkblVybFwiOiBcImh0dHBzOi8vY2RuLnNreXBhY2suZGV2XCIsXG4gIFwibWluaWZ5XCI6IHRydWVcbn0ifV0sWyJzdW0udHMiLHsiY29udGVudCI6ImV4cG9ydCBjb25zdCBzdW0gPSAoYTogbnVtYmVyLCBiOiBudW1iZXIpID0+IGEgKyBiIn1dXQ==))? I am trying to use esbuild to bundle a JavaScript library, but this TDZ optimization is preventing dead code elimination when consumers bundle their code for production.

Related #2695 .

**Comment by evanw** [comment] 2023-06-16 15:20
> This creates a consequential performance hazard when private fields end up using WeakMaps.

FWIW #3167 should resolve this particular issue.

**Comment by evanw** [comment] 2023-06-24 14:36
I have written up a FAQ entry about this: http://127.0.0.1:8001/faq/#top-level-var. I'm closing this issue because a) yes, it's still needed, b) the performance issue regarding private fields has been fixed, and c) it's now described in the documentation.

**Closed by evanw** 2023-06-24 14:36 UTC
