### ISSUE TITLE
Incorrect .node module require

### ISSUE THREAD

**Issue by stalker8610** [evanw/esbuild#3294] opened 2023-08-06 15:51 UTC
Hi guys!
Either here is a bug with .node modules requiring or I can't understand what is wrong with my script.

[Here](https://github.com/stalker8610/esbuild-bug) is a repo with bug reproduction

How to reproduce:
1. clone repo
2. run 'npm i'
3. run not built source - 'node index' to see in console that ActiveX is a function (is expected behavior)
4. run 'npm run build'
5. run 'node build/index.cjs' to see the bug in built 

Expected behavior - requires content of .node module, then uses it as a module. 
Current behavior - it seems like after build it tries to use PATH to module instead of it's content. Please see the screenshots, if I add 'require(..)' it starts work right.

![bug](https://github.com/evanw/esbuild/assets/38187405/6dc85f82-f71e-4a1f-ba64-e425778119ea)
![fixed](https://github.com/evanw/esbuild/assets/38187405/6683699b-d841-4e3b-9ecd-3f00aca98a4e)

**Comment by evanw** [comment] 2023-08-06 16:38
You explicitly told esbuild to do this when you passed `--loader:.node=file`. That's what the `file` loader does: https://esbuild.github.io/content-types/#file. This is not a bug with esbuild.

**Comment by stalker8610** [comment] 2023-08-06 17:33
If I hadn't set --loader:.node=file then I would get error "No loader is configured for ".node" files: node-activex/node_activex.node".
It's no problem that it copied .node file and put it near the bundle (it's nice!), the problem is that it is not used correctly after.

**Comment by stalker8610** [comment] 2023-08-06 17:36
omg, I'm blind :) thanks, I just need to use 'copy' mode

**Comment by evanw** [comment] 2023-08-06 17:37
I'm closing this issue because this is not a bug. You told esbuild to embed the path to the file in the bundle as a string, so that's what it did. _You don't have to do that._ There are other loaders for other things. For example, you can use the `copy` loader if you want esbuild to continue reference the file instead.

But you should probably just exclude the relevant package for the bundle entirely because many packages with native `.node` modules expect a arrangement of files on the file system and don't like being copied to a different location. This is covered in the getting started instructions for node: https://esbuild.github.io/getting-started/#bundling-for-node.

**Closed by evanw** 2023-08-06 17:37 UTC
