### ISSUE TITLE
Runtime panic when attempting to parse SVG files

### ISSUE THREAD

**Issue by jcomack** [evanw/esbuild#170] opened 2020-06-04 11:32 UTC
While I was attempting to use the `dataurl` loader for SVGs that are present in my React code, I got the following error:

```
panic: runtime error: index out of range [3] with length 1

goroutine 592 [running]:
github.com/evanw/esbuild/internal/bundler.bitSet.hasBit(...)
        /Users/evan/dev/esbuild/internal/bundler/linker.go:27
github.com/evanw/esbuild/internal/bundler.(*linkerContext).includeFile(0xc001d35c80, 0x1d, 0x1d, 0xc000000000)
        /Users/evan/dev/esbuild/internal/bundler/linker.go:1004 +0x929
github.com/evanw/esbuild/internal/bundler.(*linkerContext).markPartsReachableFromEntryPoints(0xc001d35c80)
        /Users/evan/dev/esbuild/internal/bundler/linker.go:985 +0x219
github.com/evanw/esbuild/internal/bundler.(*linkerContext).link(0xc001d35c80, 0xc0025f88a0, 0x1402500, 0xc0000da280)
        /Users/evan/dev/esbuild/internal/bundler/linker.go:345 +0x61
github.com/evanw/esbuild/internal/bundler.(*Bundle).Compile.func1(0xc0021cc310, 0xc0025f88a0, 0xc0000b22a0, 0xc002b3c000, 0x1d, 0x1d, 0xc0029ea860, 0x1c, 0x1d)
        /Users/evan/dev/esbuild/internal/bundler/bundler.go:444 +0x136
created by github.com/evanw/esbuild/internal/bundler.(*Bundle).Compile
        /Users/evan/dev/esbuild/internal/bundler/bundler.go:442 +0x1b4
```

The basic configuration I'm using is:

```js
const config = {
	outdir: paths.jsDist,
	sourcemap: mode === "development",
	resolveExtensions: [ ".json", ".js", ".jsx" ],
	loader: {
		".js": "jsx",
		".svg": "dataurl",
	}
};
```

The reason why I _think_ this is related to SVGs, is because when I remove the SVG entry from the loaders, I receive the ` File extension not supported` error when trying to build.

**Additional question:** I'm guessing that there is no real support for SVGs (yet), but is there a certain approach you recommend to still be able to use esbuild in combination with SVG, CSS etc? I haven't been able to deduce any solutions from the docs/other issues.

**Comment by evanw** [comment] 2020-06-04 20:07
I believe this issue is actually a duplicate of #162. If it's what I think it is, it has nothing to do with SVG files, which are supported via other loaders like you are doing here. The issue is that there's are crash when there are more than 8 entry points. I will fix this soon.

**Closed** 2020-06-04 20:18 UTC
