### ISSUE TITLE
serve React Router

### ISSUE THREAD

**Issue by dudo** [evanw/esbuild#1601] opened 2021-09-14 03:48 UTC
Of note, I can't seem to get the webserver via:

```sh
esbuild src/index.js --servedir=dist --outdir=dist/js --serve=1274 --bundle
```

That being said, I can start the webserver via the js api:

```js
const { build, serve } = require('esbuild')

// Start devserver
serve(
  { servedir: 'dist', port: 1274 },
  { outdir: 'dist/js' }
);
```

This seems to be loading my js. I tested a few window functions, and it's there.

![image](https://user-images.githubusercontent.com/2963800/133191672-861ef796-9e1d-4a44-bce8-0cb4ac91fc74.png)

The app uses react-router, though, and setting the url manually results in a 404

![image](https://user-images.githubusercontent.com/2963800/133191760-b423dce9-6dbf-4765-b2f9-37c57589a650.png)

Any ideas on how to make this work?

**Comment by hyrious** [comment] 2021-09-14 04:01
You should write yourself a single-page-application server, which redirects all normal requests to `/`.
Here's a quick & stupid [implementation](https://github.com/hyrious/esbuild-serve/blob/main/src/index.ts#L90-L98).

**Comment by dudo** [comment] 2021-09-14 15:15
Eh... what's the point of `serve`, then?

I solved this using build/watch and mounting the outdir to nginx.

docker-compose.yml
```yaml
services:
  ngninx:
    image: nginx:1
    volumes:
      - ./dist:/usr/share/nginx/html
      - ${PWD}/default.conf:/etc/nginx/conf.d/default.conf

  app:
    context: .
    entrypoint: npm
    command: start
```

default.conf
```conf
server {
   listen 80;

   location / {
      root      /usr/share/nginx/html;
      index     index.html index.htm;
      try_files $uri $uri/ /index.html;

      if ($request_method = 'OPTIONS') {
         add_header 'Access-Control-Allow-Origin: $http_origin');
         add_header 'Access-Control-Allow-Origin: GET, POST, DELETE, PUT, PATCH, OPTIONS');
         add_header 'Access-Control-Allow-Credentials: true');
         add_header 'Vary: Origin');
      }

      add_header 'Access-Control-Allow-Origin' "$http_origin" always;
      add_header 'Access-Control-Allow-Credentials' 'true' always;
      add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, PATCH, DELETE, OPTIONS' always;
      add_header 'Access-Control-Allow-Headers' 'Accept,Authorization,Cache-Control,Content-Type,DNT,If-Modified-Since,Keep-Alive,Origin,User-Agent,X-Requested-With' always;
   }

   error_page 500 502 503 504  /50x.html;
   location = /50x.html {
      root   /usr/share/nginx/html;
   }
}
```

**Comment by evanw** [comment] 2021-09-14 15:31
The built-in development server is a simple file server, which already meets many people's needs. More complex needs can be met by adding a proxy in front (JS or nginx or whatever). This is by design since a proxy is a simple and very flexible way to extend the development server. You are welcome to either use the built-in development server or not, whatever works best for you. It's just provided in case it's useful.

Closing this issue as built-in support for doing this is out of scope.

**Closed by evanw** 2021-09-14 15:31 UTC

**Comment by eqqe** [comment] 2024-01-02 15:51
You could also use a hash router instead of browser router. It works for me!
```js
const router = createHashRouter([
	{
		path: "/",
[...]
```
https://reactrouter.com/en/main/routers/create-hash-router

**Comment by SALeon** [comment] 2024-01-06 02:25
In my case just used [fallback](https://esbuild.github.io/api/#serve-arguments:~:text=for%20more%20information.-,fallback,-This%20is%20a)

```
import * as esbuild from 'esbuild';
import { esbuildConfig, OUT_PATH } from './esbuild-config.mjs';
import env from '../.env/config.mjs';

const devServer = await esbuild.context({
  ...esbuildConfig,
  sourcemap: true,
  outdir: OUT_PATH,
  dropLabels: [],
});

await devServer.watch();

const { host, port } = await devServer.serve({
  host: env.HOST,
  port: env.PORT,
  servedir: OUT_PATH,
  fallback: `${OUT_PATH}/index.html`,
});

console.info(`app listen on ${host}:${port}`);
```
