### ISSUE TITLE
When the input code has nested function declaration, the output code errors with `Identifier 'foo' has already been declared`

### ISSUE THREAD

**Issue by sapphi-red** [evanw/esbuild#2809] opened 2023-01-10 12:02 UTC
When this code is input,
```js
const n = ''

for (let i of [0,1]) {
  function f () {}
}
```
esbuild outputs (`--minify-identifiers --format=esm`)
```js
const f = "";
for (let o of [0, 1]) {
  let n = function() {
  };
  var f = n;
}
```
This code redeclares `f` and throws `SyntaxError: Identifier 'f' has already been declared`.

[repl](https://hyrious.me/esbuild-repl/?version=0.16.16&mode=transform&input=const+n+%3D+%27%27%0A%0Afor+%28let+i+of+%5B0%2C1%5D%29+%7B%0A++function+f+%28%29+%7B%7D%0A%7D%0A&options=--minify-identifiers+--format%3Desm)

It doesn't happen when (1) `--format=esm` is not set or (2) `export {}` is appended or (3) `'use strict'` is prepended.
This seems to happen from at least v0.9.0.

Original issue: https://github.com/vitejs/vite/issues/11642

**Comment by hyrious** [comment] 2023-01-11 02:18
Interesting example, it seems that `var f = function(){}` does not act the same as `function f(){}` in nested blocks. The latter **tries to pollute the outer block** but **silently fail** if there's name conflicting **in non-strict mode**:

```js
// code below are tested in node.js non-strict mode,
// it may output different in other runtimes

const foo = 1; // same result as `let foo = 1`
if (true) {
  function foo() {}
}
console.log(foo); // 1

if (true) {
  function bar() {}
}
console.log(bar); // [Function: bar]

var buzz = 1
if (true) {
  function buzz() {}
}
console.log(buzz); // [Function: buzz]
```

And the doc says declaring functions in non-strict mode behaves differently across runtimes. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function#block-level_function_declaration

So the problem is `--minify-identifiers` does not take outer block names into account in non-strict context. esbuild does `var f = n` simply for keeping non-strict behaviors as much as possible, since `var`s can pollute out of current block, but it will throw error when the pollution fails.

What if we keep the function declaration but only re-assign it to another `let` variable?

```js
// original output
let n = function() {
};
var f = n;

// new output
function f() {};
let n = f;
```

**Comment by sapphi-red** [comment] 2023-01-18 04:25
> What if we keep the function declaration but only re-assign it to another `let` variable?
> 
> ```js
> // original output
> let n = function() {
> };
> var f = n;
> 
> // new output
> function f() {};
> let n = f;
> ```

I think this would work. But I guess the function name was removed because leaving that will make the scope calculation difficult.

**Closed** 2023-06-25 16:57 UTC
