### ISSUE TITLE
Dedupe dependencies

### ISSUE THREAD

**Issue by ebeloded** [evanw/esbuild#1038] opened 2021-03-23 03:56 UTC
While analyzing the bundle, I found that two of my dependencies -`rxjs` and `rxfire`, both depend on `tslib`. This results in `tslib` being included twice.

![image](https://user-images.githubusercontent.com/5859177/112090112-87e9d980-8bc5-11eb-9b5a-15d47252cafe.png)

Is there any way to dedupe `tslib` so that only one version is included in the final bundle?

**Comment by remorses** [comment] 2021-03-23 13:25
This is more a problem with your package manager, if your package manager has duplicate dependencies esbuild will duplicate that code too

If you use yarn you can use the `resolutions` field to force the resolution of a package versions to only one versoin
https://classic.yarnpkg.com/en/docs/selective-version-resolutions/

**Comment by merceyz** [comment] 2021-03-23 19:20
Yarn has a builtin dedupe command so you can run `yarn dedupe tslib` - https://yarnpkg.com/cli/dedupe

**Comment by evanw** [comment] 2021-03-23 21:12
What esbuild is doing here appears to be correct. The file `node_modules/rxjs/node_modules/tslib/tslib.js` is a different path from the file `node_modules/rxfire/node_modules/tslib/tslib.js` and so must be duplicated in the bundle for correctness.

Unlike some other programming languages, a duplicate copy of code is not equivalent to the original in JavaScript. Function objects in JavaScript have their own referential identity and each copy of the library would have its own copy of its internal state. It would be incorrect for esbuild to make this transformation itself, so I'm going to close this issue as "working as intended". See also #928.

Note that using [`--preserve-symlinks`](https://esbuild.github.io/api/#preserve-symlinks) can cause this because it tells esbuild to treat two separate symlinks to the same file as two separate files. Make sure you don't have that enabled if you don't need it (it's not on by default). Otherwise the way to fix this is to fix your package manager.

You can also work around this with an on-resolve plugin: https://esbuild.github.io/plugins/#resolve-callbacks. The plugin could intercept these separate paths and map them to the same path. Then they would be considered to be the same module and be merged.

**Closed by evanw** 2021-03-23 21:12 UTC

**Comment by lukeed** [comment] 2021-03-24 01:12
I just ran into this too w/o anything fancy going on.

Here's [a reproduction](https://github.com/lukeed/cfw/tree/esbuild), but the gist of it is that 5 source files include:

```ts
import colors from 'kleur';
```

...which, with esbuild, produces an output file with 5 instances of the same statement. I'm targeting `esm` output & using `bundle: true`. By default, this should dedupe as esbuild already handles much more complex dependency-resolution logic by default.

My reproduction includes the output code that Rollup was producing.

* esbuild: 0.9.6
* pnpm 5.13.6 for installs (uses symlinks, but all references point to the same file)

**Comment by ebeloded** [comment] 2021-03-24 01:26
@evanw thank you for the explanation
@remorses resolutions was exactly what I needed

**Comment by evanw** [comment] 2021-03-24 02:52
@lukeed That sounds like an unrelated issue, and a duplicate of #475. I'm working on fixing this one. The problem in that case is not that a file is present in the bundle multiple times like this issue, since two import statements for the same path do not result in that path being imported multiple times.

**Comment by lukeed** [comment] 2021-03-24 04:38
@evanw Ah sorry, thanks! Should I freeze the reproduction branch in its current state or is it of no help to you?

**Comment by evanw** [comment] 2021-03-24 04:46
I don't need it, no. It's covered by #475.

**Comment by strogonoff** [comment] 2025-03-12 11:14
> You can also work around this with an on-resolve plugin: https://esbuild.github.io/plugins/#resolve-callbacks. The plugin could intercept these separate paths and map them to the same path. Then they would be considered to be the same module and be merged.

Unfortunately, it seems that `onResolve` is given only a module specified (e.g., `react`) and not the full path, which seems to make it of limited use when deduplication logic is concerned. In my case, Yarn’s behavior with zero installs & PnP + transitive peer dependencies results in duplicate “virtual” packages (some libs getting an instance of `react-virtual-d7c21d2ba0` and others of `react-virtual-8bc80094e9`, even though only one precise version of `react` is enforced throughout codebase). If there was a way to get a hold of the full path returned by the default esbuild’s resolver and override it, that could make it possible to dedupe such cases.

I suppose I could query Yarn’s PnP API (which presumably esbuild does in its default resolver), but at that point it’s unclear whether it’s easier to just stop using zero-installs…
