### ISSUE TITLE
Static class variables thwart tree shaking

### ISSUE THREAD

**Issue by steveluscher** [evanw/esbuild#3500] opened 2023-11-20 19:56 UTC
The presence of the calls to `__publicField()` and `__privateAdd()` in classes with static properties prevents tree shaking.

[Repro link](https://esbuild.github.io/try/#YgAwLjE5LjYAewogIHRyZWVTaGFraW5nOiB0cnVlLAogIHRhcmdldDogJ2VzMjAyMCcsCiAgb3V0ZGlyOiAnZGlzdCcsCiAgYnVuZGxlOiB0cnVlCn0AZQBlbnRyeS5qcwBpbXBvcnQgeyBGb28gfSBmcm9tICcuL2Zvbyc7CgovLyBTaW5jZSBgRm9vYCBpcyBub3QgdXNlZCBpdCBzaG91bGQgYmUgdHJlZSBzaGFrZW4gYXdheQovLyBjb25zb2xlLmxvZyhuZXcgRm9vKCkudGhpbmcpOwAAZm9vLmpzAHZhciBfX2FjY2Vzc0NoZWNrID0gKG9iaiwgbWVtYmVyLCBtc2cpID0+IHsKICBpZiAoIW1lbWJlci5oYXMob2JqKSkKICAgIHRocm93IFR5cGVFcnJvcigiQ2Fubm90ICIgKyBtc2cpOwp9Owp2YXIgX19wcml2YXRlR2V0ID0gKG9iaiwgbWVtYmVyLCBnZXR0ZXIpID0+IHsKICBfX2FjY2Vzc0NoZWNrKG9iaiwgbWVtYmVyLCAicmVhZCBmcm9tIHByaXZhdGUgZmllbGQiKTsKICByZXR1cm4gZ2V0dGVyID8gZ2V0dGVyLmNhbGwob2JqKSA6IG1lbWJlci5nZXQob2JqKTsKfTsKdmFyIF9fcHJpdmF0ZUFkZCA9IChvYmosIG1lbWJlciwgdmFsdWUpID0+IHsKICBpZiAobWVtYmVyLmhhcyhvYmopKQogICAgdGhyb3cgVHlwZUVycm9yKCJDYW5ub3QgYWRkIHRoZSBzYW1lIHByaXZhdGUgbWVtYmVyIG1vcmUgdGhhbiBvbmNlIik7CiAgbWVtYmVyIGluc3RhbmNlb2YgV2Vha1NldCA/IG1lbWJlci5hZGQob2JqKSA6IG1lbWJlci5zZXQob2JqLCB2YWx1ZSk7Cn07CnZhciBfX3ByaXZhdGVTZXQgPSAob2JqLCBtZW1iZXIsIHZhbHVlLCBzZXR0ZXIpID0+IHsKICBfX2FjY2Vzc0NoZWNrKG9iaiwgbWVtYmVyLCAid3JpdGUgdG8gcHJpdmF0ZSBmaWVsZCIpOwogIHNldHRlciA/IHNldHRlci5jYWxsKG9iaiwgdmFsdWUpIDogbWVtYmVyLnNldChvYmosIHZhbHVlKTsKICByZXR1cm4gdmFsdWU7Cn07CnZhciBfcHJpdmF0ZVByb3BlcnR5OwpleHBvcnQgY2xhc3MgRm9vIHsKICBzdGF0aWMgZ2V0IHRoaW5nKCkgewogICAgaWYgKCFfX3ByaXZhdGVHZXQodGhpcywgX3ByaXZhdGVQcm9wZXJ0eSkpIHsKICAgICAgX19wcml2YXRlU2V0KHRoaXMsIF9wcml2YXRlUHJvcGVydHksIDEpOwogICAgfQogICAgcmV0dXJuIF9fcHJpdmF0ZUdldCh0aGlzLCBfcHJpdmF0ZVByb3BlcnR5KTsKICB9Cn0KX3ByaXZhdGVQcm9wZXJ0eSA9IG5ldyBXZWFrTWFwKCk7Cl9fcHJpdmF0ZUFkZChGb28sIF9wcml2YXRlUHJvcGVydHksIHZvaWQgMCk7)

# Source

```ts
export class Foo {
    static #privateStaticProperty;
    static publicStaticProperty;
};
```

# Compiled code

```js
var __defProp = Object.defineProperty;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __publicField = (obj, key, value) => {
  __defNormalProp(obj, typeof key !== "symbol" ? key + "" : key, value);
  return value;
};
var __privateAdd = (obj, member, value) => {
  if (member.has(obj))
    throw TypeError("Cannot add the same private member more than once");
  member instanceof WeakSet ? member.add(obj) : member.set(obj, value);
};
var _privateStaticProperty;
export class Foo {
}
_privateStaticProperty = new WeakMap();
__privateAdd(Foo, _privateStaticProperty, void 0);
__publicField(Foo, "publicStaticProperty");
;
```

[Playground link](https://esbuild.github.io/try/#dAAwLjE4LjE3AHt0YXJnZXQ6J2VzMjAyMCd9AGV4cG9ydCBjbGFzcyBGb28gewogICAgc3RhdGljICNwcml2YXRlU3RhdGljUHJvcGVydHk7CiAgICBzdGF0aWMgcHVibGljU3RhdGljUHJvcGVydHk7Cn07Cg).

**Comment by evanw** [comment] 2023-11-20 20:14
You are misunderstanding what that annotation does. That annotation means a function call is safe to remove if the result is unused. Since the results are never used (each call is a top-level expression statement), that would cause all of these function calls to always be removed even when the corresponding class is used. So it would be incorrect for esbuild to add these annotations here. 

One way to do this correctly is to always transpile for older browsers once at the end of your build step instead of doing it multiple times in succession, since as you have discovered doing so erases information.

**Comment by steveluscher** [comment] 2023-11-20 20:40
The pure annotation marks a function as side effect free. Optimizing compilers do not reap such functions just because the results are unused, but rather _will_ reap the function calls if `Foo` is unused.

Try this: throw this into `test.js`:

```js
var __defProp = Object.defineProperty;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __publicField = (obj, key, value) => {
  __defNormalProp(obj, typeof key !== "symbol" ? key + "" : key, value);
  return value;
};
var __privateAdd = (obj, member, value) => {
  if (member.has(obj))
    throw TypeError("Cannot add the same private member more than once");
  member instanceof WeakSet ? member.add(obj) : member.set(obj, value);
};
var _privateStaticProperty;
export class Foo {
}
_privateStaticProperty = new WeakMap();
__privateAdd(Foo, _privateStaticProperty, void 0);
__publicField(Foo, "publicStaticProperty");
;
```

Then run a tree-shaking tester `npx agadoo test.js`.

If you add the pure annotation and run it again, it can unwind the thread of references and tree-shake the whole module.

**Comment by evanw** [comment] 2023-11-20 21:56
I'm not sure why you're telling me how optimizing compilers work. I'm the author of esbuild, which is an optimizing compiler, and I'm telling you how it works. You can [see for yourself](https://esbuild.github.io/try/#dAAwLjE5LjYALS10cmVlLXNoYWtpbmc9dHJ1ZQB2YXIgX19kZWZQcm9wID0gT2JqZWN0LmRlZmluZVByb3BlcnR5Owp2YXIgX19kZWZOb3JtYWxQcm9wID0gKG9iaiwga2V5LCB2YWx1ZSkgPT4ga2V5IGluIG9iaiA/IF9fZGVmUHJvcChvYmosIGtleSwgeyBlbnVtZXJhYmxlOiB0cnVlLCBjb25maWd1cmFibGU6IHRydWUsIHdyaXRhYmxlOiB0cnVlLCB2YWx1ZSB9KSA6IG9ialtrZXldID0gdmFsdWU7CnZhciBfX3B1YmxpY0ZpZWxkID0gKG9iaiwga2V5LCB2YWx1ZSkgPT4gewogIF9fZGVmTm9ybWFsUHJvcChvYmosIHR5cGVvZiBrZXkgIT09ICJzeW1ib2wiID8ga2V5ICsgIiIgOiBrZXksIHZhbHVlKTsKICByZXR1cm4gdmFsdWU7Cn07CnZhciBfX3ByaXZhdGVBZGQgPSAob2JqLCBtZW1iZXIsIHZhbHVlKSA9PiB7CiAgaWYgKG1lbWJlci5oYXMob2JqKSkKICAgIHRocm93IFR5cGVFcnJvcigiQ2Fubm90IGFkZCB0aGUgc2FtZSBwcml2YXRlIG1lbWJlciBtb3JlIHRoYW4gb25jZSIpOwogIG1lbWJlciBpbnN0YW5jZW9mIFdlYWtTZXQgPyBtZW1iZXIuYWRkKG9iaikgOiBtZW1iZXIuc2V0KG9iaiwgdmFsdWUpOwp9Owp2YXIgX3ByaXZhdGVTdGF0aWNQcm9wZXJ0eTsKZXhwb3J0IGNsYXNzIEZvbyB7Cn0KX3ByaXZhdGVTdGF0aWNQcm9wZXJ0eSA9IG5ldyBXZWFrTWFwKCk7Ci8qI19fUFVSRV9fKi8gX19wcml2YXRlQWRkKEZvbywgX3ByaXZhdGVTdGF0aWNQcm9wZXJ0eSwgdm9pZCAwKTsKLyojX19QVVJFX18qLyBfX3B1YmxpY0ZpZWxkKEZvbywgInB1YmxpY1N0YXRpY1Byb3BlcnR5Iik7Cjs) that esbuild removes unused calls to pure functions. This behavior is documented on esbuild's website here: https://esbuild.github.io/api/#pure. You can also paste that exact same code into other minifiers such as [Terser](https://try.terser.org/) or [Uglify](https://skalman.github.io/UglifyJS-online/) or [swc](https://play.swc.rs/?version=1.3.94-nightly-20231016.1&code=H4sIAAAAAAAAA3WST0%2FCQBDF73yKsV5abMCzpBpj4KYS0Xgwptm2U1lod5vptkgI393pPwsEjvtm8nvvTbYUBL4fYTwnnYEHr8EKQzNiQSqsNCSznQzKbu1FUyqSdtnWwcqFNW5dKEVSoAPeffUEqYBH8NCjD1Z3gKpIkUSQ4B0YKtCFUKtY%2FhRH2oakOXzXFrB34K6CfzHrmzPUahcwK4JEhjOJSXQp3m4Ap02aPbPNUMd1%2FCvPAyvfpoFOLC5RSTdgWWx8AJswiNAUpLoM%2B%2F8YJEth8DHqU6SYBkinQWQMdjMZLUVebToOywBmSXoD7xxpSqTJtp6EUtqAYKRZIuQiRWhtWjakmpCHgm%2BvQrTqgO1IqtwIFrnfJ4r1Ag3Xao0ZWRtzu1bJ0TShu6JdsdZwYYSRYf858DfTZCBMRJ7DTGuuth%2BcX%2BZ7KNzUIZ5FZjN7PLz2%2FfnH29T3h%2BOj29mMci%2BYcjYtI7g9B%2Bj%2FQEOwGuUYUJ1n8gcaEC%2Fs%2FQIAAA%3D%3D&config=H4sIAAAAAAAAA32UO3LjMAxA%2B5zCo3qLHRcpcoB0ewYOLYIysxShIUDHmozvHoiSP4khdRIePsT362W3az6obd52X%2FIpP4PNBPn2LxIaE9uzSBoeB6A2h4GbP1fKNCFvI0EVXWbSRESCK1lkfUjBj4%2B%2BW%2ByHDEQPMpHa3JUeEtNP%2B4Vl%2FJwA5%2FIoPyBGsGmDGEsmJIYOsua4xRjtQGBONiteppfaHAi1EBMsDM4MGQeVJxc4YJKYz9SBdaZFBwoKGVoOJ9DMJJaYJZL0lHwqdnAoXVf7%2BcsaTjYWy0pMONeWyGsVr0cMxMaXpJVwhis1mOFS3N%2BWwZsMXHJ6tvvAkFZ68h9AKhAtUbI9aH6rhpd5WrP2m5YheRlZHhUu861lmaCTopoQvFLZqTKQOWjdzOBKC1NlW%2B05C14pHwUHBryXWVFc02fg9qgFnRYavQKkv9ZrUzUDc9vCFT4txAZ%2BlyxZH7BFo7d8XKc09geMGwF64CO6DQVpBeM6znIlzsM6L8mBjAY4VaVQBc9HQBaA0URgbTZkPcSj6SIe7mdiUbjc7m1vU3ff9x8nl2XOq%2BsGaP93v69HusKmR1eq1XLlp8bPiq%2FNXel6nm8ZNYH%2BXS3n916%2BAWiGjv8yBgAA). They all treat pure annotations the same way. So adding the annotations that you are proposing would break your code in all of those tools.

**Comment by steveluscher** [comment] 2023-11-20 22:47
I mean you no disrespect, and appreciate that you created and work on esbuild. My only aim is to produce a library that tree-shakes in all the compilers that my customers use.

Here's a repro that demonstrates the problem with Webpack. Without the pure annotation on `__privateAdd()` Webpack is unable to reap the import. Add it and it's all good. In no case does the top-level call to `__privateAdd()` get reaped. You can observe that by adding `(new Foo().thing)` in the body of the index files.

https://gist.github.com/steveluscher/6b64d3bbc70166348a6326d123544c0c

**Comment by steveluscher** [comment] 2023-11-21 00:25
Updated the issue description to simply state the problem.

**Comment by hyrious** [comment] 2023-11-21 00:59
I guess the issue means to shake the whole class when it is not used. The lowering code to add static fields causes the shaking impossible.

The only solution is to wrap the class in an iife with pure annotations:

```js
export var Foo = /*@__PURE__*/ (() => class Foo { static bar })()
```

Maybe you don't like the helper function `__publicField()`, in which case you can manually assign your fields in an old way

```js
export var Foo = /*@__PURE__*/ (() => {
  class Foo {}
  Foo.bar = void 0
  return Foo
})()
```

**Comment by steveluscher** [comment] 2023-11-21 05:50
> I guess the issue means to shake the whole class when it is not used. The lowering code to add static fields causes the shaking impossible.

Precisely.

> …you can manually assign your fields in an old way

That is what I ended up doing as a workaround for this bug.

> …if you're making a library, I recommend you to set the target as esnext/es2022 to keep these syntaxes…

That's an excellent idea. This pushes the choice of target to the consumer of my library, which results in much more flexibility overall. Thanks!

**Comment by evanw** [comment] 2023-11-22 19:45
I'm closing this because this is working as intended. Adding `@__PURE__` annotations here might have the desired effect in certain tools such as agadoo, but it will result in broken code when that code is used with at least esbuild, Terser, Uglify, and swc, where the `@__PURE__` annotation means something very specific. So it would be incorrect for esbuild to add these annotations.

As described above, the general way to annotate an arbitrary chunk of JavaScript code as being safe to remove if it's unused is to enclose it in an IIFE with a `@__PURE__` annotation. That way it's unambiguous that either all of it is needed or none of it is needed.

**Closed by evanw** 2023-11-22 19:45 UTC

**Comment by HanabishiRecca** [comment] 2024-07-13 06:45
> The presence of the calls to `__publicField()` and `__privateAdd()` in classes with static properties prevents tree shaking.

> However, if you're making a library, I recommend you to set the `target` as `esnext/es2022` to keep these syntaxes (which is tree-shakeable).

No, static fields always prevent classes from being tree-shaken, even with ES2022+ syntax. `__publicField` doesn't matter.

```js
class FooTest {
    static x = 1;
}
```
↓
```js
var FooTest = class {
  static {
    this.x = 1;
  }
};
```
