### ISSUE TITLE
async generators/iterators not supported

### ISSUE THREAD

**Issue by fijiwebdesign** [evanw/esbuild#2984] opened 2023-03-11 15:30 UTC
Using latest version. `^0.17.00`

Will async generators and iterators be supported? 

```
async function* foo() {
  yield 1;
  yield 2;
}

(async function() {
  for await (const num of foo()) {
    console.log(num);
    // Expected output: 1

    break; // Closes iterator, triggers return
  }
})();
```

Gives error: 

```
✘ [ERROR] Transforming async generator functions to the configured target environment ("es2015") is not supported yet

    src/test.ts:33:4:
      33 │     async function* foo() {
         ╵     ~~~~~

✘ [ERROR] Transforming for-await loops to the configured target environment ("es2015") is not supported yet

    src/test.ts:39:10:
      39 │       for await (const num of foo()) {
         ╵           ~~~~~
```

**Comment by evanw** [comment] 2023-03-11 17:38
Closing as a duplicate of #2780. This is a known issue.

**Closed by evanw** 2023-03-11 17:38 UTC
