### ISSUE TITLE
Support `--out-extension` when without bundle

### ISSUE THREAD

**Issue by abetoots** [evanw/esbuild#2600] opened 2022-10-11 06:27 UTC
Using the Build API caused a lot of problems for us when using ESM in node.

We're running ```npx esbuild `find server/src \\( -name '*.ts' -o -name '*.mts' \\)` --platform=node --format=esm --outdir=server/dist```
as we've learned in #263 . 

The problem is the output files are in `.js` and the emitted code contains imports to `.mjs` files.

Here is our tsconfig
```
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "isolatedModules": true,
    "baseUrl": ".",
    "skipLibCheck": true,
    "outDir": "dist",
    "paths": {
      "@globalShared/*": ["../shared/*"]
    }
  },
  "exclude": ["dist", "node_modules"],
  "include": ["./src"]
}
```

This would've been solved if `--out-extension` was supported by the transform API.

**Comment by thgh** [comment] 2022-10-17 14:42
Hi, not sure if my issue is the same, but it seems related. I have typescript files (ts/tsx) and would like to publish them as cjs&esm and keep it treeshakeable (so no bundle).
```sh
esbuild ./src/* --outdir=esm --out-extension:.js=.mjs
```

It seems that out-extension is outputting the correct extensions, but it breaks the imports as these are explicit. From esbuild docs:
>  Node's resolution algorithm doesn't treat these as implicit file extensions, so esbuild doesn't either.

I think it would make more sense that if out-extension ends with .mjs, it should rewrite the import/export statements to valid imports (ending in .mjs).

**Comment by evanw** [comment] 2022-10-17 15:19
> I think it would make more sense that if out-extension ends with .mjs, it should rewrite the import/export statements to valid imports (ending in .mjs).

I'm not convinced doing something like this is a good idea. By design, the transform API doesn't access the file system and doesn't run import resolution, so it doesn't know where a given import will resolve. Blindly changing imports like `foo/bar` into `foo/bar.mjs` doesn't mean things will "just work" because node's path resolution algorithm is complex. An Importing `foo/bar` could resolve into `foo/bar.mjs` but also `foo/bar.js`, `foo/bar/index.js`, or even `foo/something/else.js` if `foo` has a `package.json` file with an `exports` field.

**Comment by thgh** [comment] 2022-10-17 18:37
If I write `.mjs` in my imports, can I use esbuild to get a cjs build from it?

Note to self, conditions for adding .mjs:
* `--out-extension:.js=.mjs`
* `--target=node18` or higher
* import starts with `./` or `../`

Not sure if [package imports](https://nodejs.org/api/packages.html#imports) have impact.

Today I'm using the script below to add `.mjs` to relative paths. Will consider to wrap it into a plugin.
```ts
const { readFile, writeFile } = require('fs')
for (const filename of process.argv.slice(2)) {
  readFile(filename, 'utf-8', function (err, contents) {
    if (err) return console.log(err)
    contents = contents
      .replaceAll(/(import[{}\sa-z,A-Z0-9]+from "\.\/[^"]+)"/gm, '$1.mjs"')
      .replaceAll(/(export[{}\sa-z,A-Z0-9*]+from "\.\/[^"]+)"/gm, '$1.mjs"')
      .replaceAll('format from "date-fns/format', '{ format } from "date-fns')
    writeFile(filename, contents, 'utf-8', err => err && console.log(err))
  })
}
```

**Comment by evanw** [comment] 2022-11-27 16:03
The way to do this is to use the build API with a plugin that customizes the import paths to match your requirements. Documentation for the relevant plugin API is here: https://esbuild.github.io/plugins/#on-resolve.

I'm closing this issue because I don't believe this behavior should be built in to esbuild, as it's error-prone and likely needs to be customized for each use case.

**Closed by evanw** 2022-11-27 16:03 UTC

**Comment by Tobbe** [comment] 2024-04-07 09:20
I'm running into this same problem. I tried implementing the renaming from `.js` to `.cjs` and `.mjs` using a plugin, but because I'm not bundling it seems my `onResolve` callback is never invoked with any `kind: 'import-statement'` paths. All I'm seeing is `kind: 'entry-point'` with paths like `./src/some/folder/fileName.ts`. So the plugin never gets a chance to modify the import paths.

Am I misunderstanding something here?
