### ISSUE TITLE
CSS-in-JS integration?

### ISSUE THREAD

**Issue by tuanddd** [evanw/esbuild#355] opened 2020-08-30 03:36 UTC
Has anyone been able to use `esbuild` along with a CSS-in-JS tool such as `styled-componnents`? Would be great to see an example, thanks 🙂

**Comment by intrnl** [comment] 2020-08-30 13:27
styled-components and any other CSS-in-JS runtime libraries like emotion should work as usual. 

Are you expecting to get the benefits of using the respective libraries' Babel plugin, or...?

**Comment by Ventajou** [comment] 2020-09-01 16:26
styled-components works, there's nothing special to do.

**Comment by evanw** [comment] 2020-09-02 04:05
I'm going to close this since, as others have said above, any JavaScript library that implements CSS using JavaScript should work fine with esbuild since esbuild already has good support for JavaScript libraries. So this issue is not currently actionable. If there are problems with esbuild and a specific library, please report the issue with a description of the problem and a way to reproduce the problem.

**Closed by evanw** 2020-09-02 04:05 UTC
