### ISSUE TITLE
"esbuild-linux-long64". The registry may be down.

### ISSUE THREAD

**Issue by DarthJarJarJar** [evanw/esbuild#2433] opened 2022-08-02 21:52 UTC
This is causing an error in my deployment to Vercel

**Comment by DarthJarJarJar** [comment] 2022-08-02 21:53
error Received malformed response from registry for "esbuild-linux-loong64". The registry may be down.
17:51:19.949

**Comment by evanw** [comment] 2022-08-02 21:53
Duplicate of #2432

**Closed by evanw** 2022-08-02 21:53 UTC
