### ISSUE TITLE
`onLoad` how to directly return a module instead of its contents

### ISSUE THREAD

**Issue by mjafari98** [evanw/esbuild#2478] opened 2022-08-17 13:40 UTC
How is to have an `OnLoadResult` with the module itself, instead of its contents?

```js
  build.onLoad({ filter: /logger/ }, () => {
    const logger = () => console.log
    const result: OnLoadResult = {
      loader: "module",          // <- it is a module
      contents: logger,          // <- module reference
    };
    return result;
  });
```

**Comment by evanw** [comment] 2022-08-17 13:41
You can't do that because that's not how the API works. You need to return a string.

**Comment by evanw** [comment] 2022-08-17 13:54
That's what `onResolve` plugins are for: https://esbuild.github.io/plugins/#on-resolve. You would remap `fs` to `browserfs` at the resolve stage. For example, your `onResolve` plugin might intercept imports of `fs` and return `{ path: require.resolve('browserfs') }` or something.

**Comment by evanw** [comment] 2022-08-22 17:25
Closing since this is by design.

**Closed by evanw** 2022-08-22 17:25 UTC
