### ISSUE TITLE
sideEffects in on-resolve result is not effective when without path in result.

### ISSUE THREAD

**Issue by 10Derozan** [evanw/esbuild#3374] opened 2023-09-11 12:53 UTC
Thank you for taking the time to read this issue!

It seems like that if we have not returned path in on-resolve result, sideEffects in on-resolve result is not effective.
You can see this problem in this example: https://github.com/10Derozan/esbuild-resolve-without-path/tree/main.
In a word, this is not effective.
```js
build.onResolve({ filter: /.*/ }, args => {
  return {
    sideEffects: false,
  }
});
```

By the way, if the path is not set, esbuild will not continue to run on-resolve callbacks that were registered after the current one. 
This conflicts with the document.

> * `path`
>
>     Set this to a non-empty string to resolve the import to a specific path. If this is set, no more on-resolve callbacks will be run for this import path in this module. If this is not set, esbuild will continue to run on-resolve callbacks that were registered after the current one. Then, if the path still isn't resolved, esbuild will default to resolving the path relative to the resolve directory of the current module.

**Comment by evanw** [comment] 2023-09-14 00:09
Yes, if you don't resolve the path in `onResolve` then esbuild will continue on to try other plugins instead. By not returning a path your plugin is delegating everything about the resolution of the path back to esbuild. Closing as by design.

**Closed by evanw** 2023-09-14 00:09 UTC

**Comment by 10Derozan** [comment] 2023-09-14 02:55
Thank you for your reply
