### ISSUE TITLE
Compatibility for TemplateLiterals is incorrect on Safari

### ISSUE THREAD

**Issue by sgarfinkel** [evanw/esbuild#3399] opened 2023-09-20 22:06 UTC
Per caniuse (https://caniuse.com/template-literals) template literals are fully supported on Safari going back to version 9, but are marked as being supported since version 13: https://github.com/evanw/esbuild/blob/main/internal/compat/js_table.go#L824

**Comment by evanw** [comment] 2023-09-20 22:19
The source for compatibility data that I’m using (https://github.com/kangax/compat-table) says that Safari 12 has a bug where caching of template literal objects was broken: https://bugs.webkit.org/show_bug.cgi?id=190756. That bug was fixed in Safari 13. So esbuild appears to be correct here, since template literals were not fully implemented correctly before Safari 13 and need to be transpiled for Safari 12. I’m closing this issue as “working as intended”.

**Closed by evanw** 2023-09-20 22:19 UTC
