### ISSUE TITLE
Unable to import default and specific objects

### ISSUE THREAD

**Issue by devunion** [evanw/esbuild#2615] opened 2022-10-17 06:30 UTC
Hello, I'm trying to port my app from Webpack to ESBuild and see the following problem with imports resolving:

```
module.js
export const FOO = 'foo';
export default {
  bar: 'bar'
}

app.js
import Module, {FOO} from './module.js';
```
This kind of import does not work in the app. Is there any option to configure ESBuild to resolve the problem?

**Comment by hyrious** [comment] 2022-10-17 06:42
I don't see any issue regarding to your code, [REPL](https://hyrious.me/esbuild-repl/?version=0.15.11&mode=build&modules=%5B%5B%22app.js%22%2C%22import+Module%2C+%7BFOO%7D+from+%27.%2Fmodule.js%27%3B%5Cnconsole.log%28Module%2C+FOO%29%22%2C1%5D%2C%5B%22module.js%22%2C%22export+const+FOO+%3D+%27foo%27%3B%5Cnexport+default+%7B%5Cn++bar%3A+%27bar%27%5Cn%7D%22%2C0%5D%5D&buildOptions=%7B%22bundle%22%3Atrue%7D)

Please provide some reproduction steps.

**Comment by devunion** [comment] 2022-10-17 09:55
Thank you, the problem appears in Vue components only. I use "esbuild-plugin-vue3", so, it seems that it is related to the plugin itself. Imports work for me on plain JS files.

**Comment by evanw** [comment] 2022-10-17 12:17
I'm closing this issue because there is nothing to do here; this is already how esbuild works. If you're having trouble with a plugin then you'll have to ask the developer of that plugin for help. The esbuild issue tracker is not a forum for plugin-related support requests.

**Closed by evanw** 2022-10-17 12:17 UTC
