### ISSUE TITLE
Private Network Access

### ISSUE THREAD

**Issue by atompkins** [evanw/esbuild#2921] opened 2023-02-14 18:08 UTC
Any chance of supporting [Private Network Access](https://developer.chrome.com/blog/private-network-access-preflight/) for chromium browsers?

**Comment by evanw** [comment] 2023-02-15 16:55
I can't reproduce the issue. I tried loading a page using esbuild's dev server in Chrome 112 but there are no warnings in the console. Please provide instructions for how to reproduce the issue you're having.

**Comment by atompkins** [comment] 2023-02-15 20:12
Yes of course, my apologies.

So, run esbuild's dev server in https mode.

console looks like this:
![image](https://user-images.githubusercontent.com/6729161/219138209-7ab2fea0-0fc0-4560-800b-ba41fbbccc4f.png)
what you are looking for is in the top right hand corner. Ignore the messages in the console.
if you hover you see this:
![image](https://user-images.githubusercontent.com/6729161/219138547-58dd2a14-2d47-4037-a267-afc1e1524b3e.png)
you can click on it to bring up the issues panel like this:
![image](https://user-images.githubusercontent.com/6729161/219138796-10a8aa6f-8825-4138-a05f-20f9c5a727c5.png)
if you expand the CORS bit you see this:
![image](https://user-images.githubusercontent.com/6729161/219139190-cdef3349-588f-432d-b501-4ec6eaac1dab.png)
if you open up requests you will see lots of these:
![image](https://user-images.githubusercontent.com/6729161/219140478-96653438-9940-4abd-8d6b-59d8e60089e4.png)
if you go to the network tab and select "Other" you can see the preflights:
![image](https://user-images.githubusercontent.com/6729161/219141013-0fab4c0b-dee7-43d6-818e-5a06685cd182.png)
here are the headers:
![image](https://user-images.githubusercontent.com/6729161/219141434-33afbdf1-8c23-408f-aa06-ef9cb86c99e3.png)

Obviously it's not a blocking problem at the moment, just an additional round trip. At least it's giving 404 instead of timing out.

**Comment by evanw** [comment] 2023-02-15 22:49
I still can't reproduce the issue. Here's essentially what I did:

```
$ cat index.html
<!DOCTYPE html>
<script src="x.js"></script>

$ cat x.js
console.log('hello')

$ openssl req -x509 -newkey rsa:4096 -keyout your.key -out your.cert -days 9999 -nodes -subj /CN=127.0.0.1

$ esbuild --servedir=. --certfile=your.cert --keyfile=your.key
```

Then open https://localhost:8000/ in Chrome 112, click past the silly security warning, and then look in the console. I only see a single error: `GET https://localhost:8000/favicon.ico 404`:

<img width="957" src="https://user-images.githubusercontent.com/406394/219205900-76a85dd0-cd4b-47bb-a07c-da2e0601d05a.png">

There is no red X bubble icon. Also the "Other" section of the network tab only shows a single request for `favicon.ico`.

**Comment by atompkins** [comment] 2023-02-15 23:08
Sorry, I'm so wrapped up in my project I buried the lede! The origin should be another domain.
Using the same setup you have above, go here [https://ad.tompkins.je/cors_repro/](https://ad.tompkins.je/cors_repro/)

**Comment by evanw** [comment] 2023-02-15 23:34
If I do that I just see `GET https://localhost:8000/x.js net::ERR_CERT_AUTHORITY_INVALID`.

**Comment by atompkins** [comment] 2023-02-16 13:24
ok that's because your CA isn't trusted by your system. You are clicking past the security warning every time you open it.
i just use [mkcert](https://github.com/FiloSottile/mkcert) to set that up for me.

i really appreciate your patience with me, this is a terrible issue.

**Comment by evanw** [comment] 2023-08-06 18:52
I'm closing this issue both because there were insufficient instructions and because I'm not sure this is something esbuild should do. It seems like the point of this feature is to prevent random websites from fetching content served on the local network, and doing what this issue is suggesting would bypass this security feature. This feature is also a custom enough use case and is hard enough to test that I think it makes sense to have to configure a custom proxy yourself if you want to be able to do this.

**Closed by evanw** 2023-08-06 18:52 UTC
