### ISSUE TITLE
Support browserlist as target option

### ISSUE THREAD

**Issue by tom-sherman** [evanw/esbuild#324] opened 2020-08-11 21:40 UTC
I'm not sure how feasible this is because of the lack of formal spec for browserlist queries so it might not be feasible to port to Go.

**Comment by evanw** [comment] 2020-08-11 22:27
I'm going to close this as a duplicate of #121.

I've already done the hard work of adding targets for specific browser versions to esbuild. For example, you can set the environment target to `--target=chrome58,firefox57,safari11,edge16` and esbuild will do the right thing. It includes [fine-grained per-feature syntax compatibility](https://github.com/evanw/esbuild/blob/889ae2df977b0cd9c35729f6ed8a2e552734b824/internal/compat/table.go) built in. When specific targets are specified, esbuild will either convert the newer syntax to older syntax as necessary or report an error and fail the build if converting that syntax isn't supported (e.g. for big integer literals).

Literally adding support for browserslist queries themselves to esbuild itself doesn't feel appropriate to me. There is already [a JavaScript package](https://www.npmjs.com/package/browserslist) that interprets the queries and converts them to a list of browser versions, with a lot of custom logic and history around it, and to me it makes more sense for people to just invoke that package instead of replicating that package's code inside esbuild. And having the esbuild package itself depend on the browserslist package would add an unnecessary dependency for most people, which I don't want to do. Also the fact that browserslist queries are dependent on the time the query was executed (e.g. `> 5% in US` or `current node`) means that your build output would change without the esbuild configuration options changing, which is a source of non-deterministic behavior that I don't want esbuild to have.

I think the best way to do this is to have esbuild provide the underlying mechanism for this via the `--target` option and allow the community to experiment with optional 3rd-party packages that can be used to convert a browserslist query into an esbuild target string. That preserves separation of concerns and doesn't closely couple the two projects together.

**Closed by evanw** 2020-08-11 22:27 UTC

**Comment by vuolter** [comment] 2020-12-13 15:59
I handled it this way in my (snowpack) config to collect the browser targets to pass to esbuild:

```
const browserslist = require('browserslist');

function getBuildTargets() {
  const SUPPORTED_BUILD_TARGETS = [
    'es',
    'chrome',
    'edge',
    'firefox',
    'ios',
    'node',
    'safari',
  ];

  const sep = ' ';
  const supported = (b) =>
    SUPPORTED_BUILD_TARGETS.some((t) => b.startsWith(t + sep))
      ? b.replace(sep, '')
      : undefined;

  return browserslist().map(supported).filter(Boolean);
}

const targets = getBuildTargets();

...
```

Basically, queries browserslist to get the targets and change them just a bit to be parsed correctly by esbuild (looks like whitespaces are not welcome here XD), ofc ignoring unsupported targets.

**Comment by danny007in** [comment] 2021-05-01 09:39
> const browserslist = require('browserslist');
> 
> function getBuildTargets() {
>   const SUPPORTED_BUILD_TARGETS = [
>     'es',
>     'chrome',
>     'edge',
>     'firefox',
>     'ios',
>     'node',
>     'safari',
>   ];
> 
>   const sep = ' ';
>   const supported = (b) =>
>     SUPPORTED_BUILD_TARGETS.some((t) => b.startsWith(t + sep))
>       ? b.replace(sep, '')
>       : undefined;
> 
>   return browserslist().map(supported).filter(Boolean);
> }
> 
> const targets = getBuildTargets();

Actual ouput 

```js
[
  'chrome90',  'chrome89',   'chrome88',  'chrome87',
  'chrome86',  'chrome85',   'chrome84',  'chrome83',
  'chrome81',  'chrome80',   'chrome79',  'chrome78',
  'chrome77',  'chrome76',   'chrome75',  'chrome74',
  'chrome73',  'chrome72',   'chrome71',  'chrome70',
  'chrome69',  'chrome68',   'chrome67',  'chrome66',
  'chrome65',  'chrome64',   'chrome63',  'chrome62',
  'chrome61',  'chrome60',   'edge90',    'edge89',
  'edge88',    'firefox88',  'firefox87', 'firefox86',
  'firefox85', 'firefox84',  'firefox83', 'firefox82',
  'firefox81', 'firefox80',  'firefox79', 'firefox78',
  'firefox77', 'firefox76',  'firefox75', 'firefox74',
  'firefox73', 'firefox72',  'firefox71', 'firefox70',
  'firefox69', 'firefox68',  'firefox67', 'firefox66',
  'firefox65', 'firefox64',  'firefox63', 'firefox62',
  'firefox61', 'firefox60',  'safari14',  'safari13.1',
  'safari13',  'safari12.1', 'safari12'
]

**Comment by danny007in** [comment] 2021-05-01 10:26
> 
> Actual ouput
> 
> ```js
> [
>   'chrome90',  'chrome89',   'chrome88',  'chrome87',
>   'chrome86',  'chrome85',   'chrome84',  'chrome83',
>   'chrome81',  'chrome80',   'chrome79',  'chrome78',
>   'chrome77',  'chrome76',   'chrome75',  'chrome74',
>   'chrome73',  'chrome72',   'chrome71',  'chrome70',
>   'chrome69',  'chrome68',   'chrome67',  'chrome66',
>   'chrome65',  'chrome64',   'chrome63',  'chrome62',
>   'chrome61',  'chrome60',   'edge90',    'edge89',
>   'edge88',    'firefox88',  'firefox87', 'firefox86',
>   'firefox85', 'firefox84',  'firefox83', 'firefox82',
>   'firefox81', 'firefox80',  'firefox79', 'firefox78',
>   'firefox77', 'firefox76',  'firefox75', 'firefox74',
>   'firefox73', 'firefox72',  'firefox71', 'firefox70',
>   'firefox69', 'firefox68',  'firefox67', 'firefox66',
>   'firefox65', 'firefox64',  'firefox63', 'firefox62',
>   'firefox61', 'firefox60',  'safari14',  'safari13.1',
>   'safari13',  'safari12.1', 'safari12'
> ]
> ```
> 
> Expected
> 
> ```js
> [
>   'chrome60',
>   'edge88',
>   'firefox60',  
>   'safari12'
> ]
> ```
> 
> @vuolter how?

Better solution
```js
const browserslist = require('browserslist')

function getBuildTargets() {
  const SUPPORTED_BUILD_TARGETS = [
    'es',
    'chrome',
    'edge',
    'firefox',
    'ios',
    'node',
    'safari'
  ]

  const sep = ' '
  const supported = b =>
    SUPPORTED_BUILD_TARGETS.some(t =>
      b.startsWith(t + sep)) ?
      b.replace(sep, '') :
      undefined

  const getEveryTar = browserslist().map(element => supported(element)).filter(Boolean).reverse()

  let singleTar = ''
  const targets = []
  let i = 0
  for (const tar of getEveryTar) {
    for (const selTar of SUPPORTED_BUILD_TARGETS) {
      if (tar.startsWith(selTar) && !singleTar.startsWith(selTar)) {
        singleTar = tar
        if (targets !== []) {
          i++
          targets[i] = singleTar
        }
      }
    }
  }

  return targets.filter(Boolean)
}

const targets = getBuildTargets()

console.log(targets)
```

**Comment by danny007in** [comment] 2021-05-01 13:33
> 
> 
> I handled it this way in my (snowpack) config to collect the browser targets to pass to esbuild:
> 
> ```
> const browserslist = require('browserslist');
> 
> function getBuildTargets() {
>   const SUPPORTED_BUILD_TARGETS = [
>     'es',
>     'chrome',
>     'edge',
>     'firefox',
>     'ios',
>     'node',
>     'safari',
>   ];
> 
>   const sep = ' ';
>   const supported = (b) =>
>     SUPPORTED_BUILD_TARGETS.some((t) => b.startsWith(t + sep))
>       ? b.replace(sep, '')
>       : undefined;
> 
>   return browserslist().map(supported).filter(Boolean);
> }
> 
> const targets = getBuildTargets();
> 
> ...
> ```
> 
> Basically, queries browserslist to get the targets and change them just a bit to be parsed correctly by esbuild (looks like whitespaces are not welcome here XD), ofc ignoring unsupported targets.

More accurately code in https://github.com/evanw/esbuild/issues/121#issuecomment-830632769
