### ISSUE TITLE
Chrome doesn't allow setting breakpoints on esbuild bundles that include @sentry packages

### ISSUE THREAD

**Issue by jfirebaugh** [evanw/esbuild#2274] opened 2022-05-28 00:21 UTC
This is probably a Chrome devtools bug, because the sourcemap looks okay in https://evanw.github.io/source-map-visualization/ and works in Firefox. But I thought you may be interested nonetheless, and I would welcome any suggestions. E.g. have you reported similar issues upstream and where?

Minimal reproduction: https://github.com/jfirebaugh/sentry_tracing_sourcemap_bug

1. Run: `npm i && npm run build && npm start`.
1. Open http://localhost:3000 in Chrome.
1. Open developer tools.
1. Open app.js.

Result: You can't put breakpoints on lines 4 (`console.log('foo')`) or 7 (`foo()`).

`require('@sentry/tracing')` is the trigger. It also happens with `@sentry/react`, but not with `@sentry/browser`. Also it only happens with sentry versions >= 6.19.5.

**Comment by jfirebaugh** [comment] 2022-05-28 00:31
I also opened https://bugs.chromium.org/p/chromium/issues/detail?id=1330029.

**Comment by evanw** [comment] 2022-05-29 03:47
I couldn't reproduce this on my currently-installed copy of Chrome (version 101.0.4951.64). I was able to set a breakpoint on both lines 4 and 7 of `app.js`. However, it broke when I allowed Chrome to update (version 102.0.5005.61). So I can confirm that this is a recent regression in Chrome. I'm going to close this issue because it's not a bug with esbuild.

I don't think I have personally had experience reporting source map issues in Chrome, although I did encounter one that had already been fixed in Chrome Canary: #209. I was able to bisect Chrome's devtools frontend codebase to find the fix so you could try bisecting it to find what broke it if that would be helpful for you. I have forgotten what's involved with doing that though, sorry. I did that two years ago.

**Closed by evanw** 2022-05-29 03:47 UTC

**Comment by rmtsrc** [comment] 2022-05-30 13:50
@jfirebaugh I've also experienced this issue in Chrome & Chromium 102 and Chrome Dev & Canary 104.

My workaround for now is to downgrade to Chromium 101 or use Firefox and hope that a later release fixes this issue.
