### ISSUE TITLE
Append version query to chunk imports

### ISSUE THREAD

**Issue by LXSMNSYC** [evanw/esbuild#1303] opened 2021-05-21 13:14 UTC
Is there a way to append url queries to chunk imports? Something like

```jsx
import * as ChunkExports from './chunk-hash.js?v=SOME_VERSION';
```

I'm bundling for the browser and hope that I can leverage my `Cache-Control` header not just for entrypoints but also for chunks.

**Comment by evanw** [comment] 2021-05-23 00:43
I'm confused. The hash in the chunk name is designed to be used with a `Cache-Control` header since the file contents for a given file name should never change (if the contents did change, the file name should also change). In that case why do you need a version number?

**Comment by LXSMNSYC** [comment] 2021-05-23 03:31
> since the file contents for a given file name should never change (if the contents did change, the file name should also change)

Oh, so the hash is based from the file's content? If so then I think my problem is solved. However, given a wider application for queries, is it possible to add this feature?

**Comment by evanw** [comment] 2021-05-26 22:32
Yes, the content of the file is included in the hash (along with some other stuff). It's not possible to do this with esbuild itself but you could do this yourself by modifying the output files after the build has finished.

**Comment by evanw** [comment] 2021-06-28 04:55
I'm closing this as the way to do this is the hash, which is working as designed.

**Closed by evanw** 2021-06-28 04:55 UTC
