### ISSUE TITLE
Watch option.

### ISSUE THREAD

**Issue by kostya-konev** [evanw/esbuild#3190] opened 2023-06-23 07:58 UTC
Hello. You deleted `watch` option from config, but you didn't delete it from typescript type definition. For example, when I pass watch option to ESBuild.build() like
```
ESBuild.build({
  outdir: path.resolve(__dirname, '..', '..', 'build'),
  entryPoints: [path.resolve(__dirname, '..', '..', 'src', 'index.jsx')],
  entryNames: 'bundle',
  bundle: true,
  minify: isProd,
  sourcemap: isDev,
  watch: true
})
```

I get warning "Argument type {entryPoints: string[], minify: boolean, entryNames: string, sourcemap: boolean, watch: boolean, bundle: boolean, outdir: string} is not assignable to parameter type SameShape<BuildOptions, {entryPoints: string[], minify: boolean, entryNames: string, sourcemap: boolean, watch: boolean, bundle: boolean, outdir: string}>   Type boolean is not assignable to type never". 

So, if you look closely, they are the same overall, both of them have 'watch' option, however it was deleted, which is confusing.

**Comment by hyrious** [comment] 2023-06-23 08:04
> …but you didn't delete it from typescript type definition

Not at all, the `SameShape` is defined as follows:

```ts
// This is a TypeScript type-level function which replaces any keys in "In"
// that aren't in "Out" with "never". We use this to reject properties with
// typos in object literals. See: https://stackoverflow.com/questions/49580725
type SameShape<Out, In extends Out> = In & { [Key in Exclude<keyof In, keyof Out>]: never }
```

Which is to say, because `watch` is not in `BuildOptions`, then you will get `watch: never`. This is exactly what `Type boolean is not assignable to type never` says (since `watch: boolean` is not assignable to `watch: never`).

**Comment by evanw** [comment] 2023-06-24 01:38
I’m closing this issue because this is working as intended. I don’t believe TypeScript’s type system has a way to remove a member from a type in this scenario while retaining the type parameter inference, so this was the best I could do. In any case, if you use the API incorrectly like this at least there will be an error so your code won’t pass type checking.

**Closed by evanw** 2023-06-24 01:38 UTC
