### ISSUE TITLE
Does esbuild support Micro-frontend architectures?

### ISSUE THREAD

**Issue by cerencimer** [evanw/esbuild#1302] opened 2021-05-21 11:20 UTC
Does esbuild support Micro-frontend architectures? I am devoloping ReactJS  project which builds with webpack 4.  I want to transform webpack to esbuild. During this period, I encountered some problems that I could not solve.

LibraryA -> I have one library project, it is compiled with rollup and it contains components that I will use.

MicroB-> I have one micro-frontend project, it is using LibraryA via package.json. I want to change builder to Esbuild. 

MacroC-> I have one macro project, it is using LibraryA and MicroB via package.json. I want to change builder to esbuild.

1- The Micro B project I compiled with esbuild cannot be viewed in the main project(Macro C). 

I have also compiled with rollup library project(Library A), I can viewed library in MicroB project also I compiled viewed and build with esbuild.  But; esbuild couldnot resolve own build package.

2-  It is deleting the index.html file under the dist folder in every compilation. How can I deal with this?

I put the index.html file elsewhere and wrote the command to the configuration file to copy it under dist after each compilation, But this was not an effective solution.

Thank for your help

**Comment by LXSMNSYC** [comment] 2021-05-21 13:11
if your entrypoint is `.html`, iirc `esbuild` does not support `.html` files.

**Comment by cerencimer** [comment] 2021-05-21 13:57
> if your entrypoint is `.html`, iirc `esbuild` does not support `.html` files.

I am using index.html to view the build file also, it serve to project localhost: 8080 as an example.
In the example of reactjs+esbuild projects the index.html file was added under the dist / folder.
then that is not suitable for the structure of the my project ?
esbuild was compiling really fast, it is a pity that it is not suitable for my project.

**Comment by evanw** [comment] 2021-05-23 00:49
I'm not sure what micro-frontend means. It's possible that you may need to continue to use Webpack for this.

> esbuild couldnot resolve own build package

This sounds like the problem is about path resolution. If so, you could potentially [write a plugin](https://esbuild.github.io/plugins/#resolve-callbacks) to inject whatever custom path resolution logic you require. This will be necessary if your path resolution logic deviates from node since esbuild's built-in path resolution logic just replicates what node does. I could take a look if you provide a code sample that reproduces the issue.

**Comment by evanw** [comment] 2021-06-11 05:02
Closing due to age and lack of a response.

**Closed by evanw** 2021-06-11 05:02 UTC
