### ISSUE TITLE
Named namespace and function import doesn't work.

### ISSUE THREAD

**Issue by tmikaeld** [evanw/esbuild#24] opened 2020-02-19 10:27 UTC
This works:
```
import KJUR from 'jsrsasign';
import { b64toBA, b64utob64 } from 'jsrsasign';
```

This doesn't:
```
import { KJUR, b64toBA, b64utob64 } from 'jsrsasign';
```

`KJUR` is a namespace, while the others are functions or classes.

Webpack handles this as expected.

**Comment by tmikaeld** [comment] 2020-02-19 10:30
I'm guessing this is the right way to use this:
```
import KJUR, { b64toBA, b64utob64 } from 'jsrsasign';
```

Feel free to close the issue if you don't want to handle both.

**Comment by evanw** [comment] 2020-04-07 18:12
It's possible that this was fixed earlier. I'm guessing the fix was adding support for CommonJS default exports via `__esModule` in #17.

I'm going to close this since it looks like this is working fine now:

```js
import KJUR from 'jsrsasign';
import { b64toBA, b64utob64 } from 'jsrsasign';
console.log(KJUR.crypto.DSA, b64toBA, b64utob64);
```

```js
import { KJUR, b64toBA, b64utob64 } from 'jsrsasign';
console.log(KJUR.crypto.DSA, b64toBA, b64utob64);
```

```js
import KJUR, { b64toBA, b64utob64 } from 'jsrsasign';
console.log(KJUR.crypto.DSA, b64toBA, b64utob64);
```

When bundled with esbuild using `--bundle` and then executed using node, all three of these output the same thing: `[Function (anonymous)] [Function: b64toBA] [Function: b64utob64]`.

**Closed by evanw** 2020-04-07 18:12 UTC

**Comment by gabrielalmeida** [comment] 2023-06-08 18:13
I've run into a situation where re-exported namespaces are not bundled properly as named exports when using barrel files and export star syntax.

When doing this:
```ts
import {
  namedPropFromB,
  proto
} from "pkg";
```

I'd get the following on node runtime:
```SyntaxError: The requested module 'pkg' does not provide an export named 'proto'```

It will build and generate valid DTS about the exported proto NS.

---

Original pkg exports are as follows:

index.js
```js
import A from './A'

export * from '../proto'
export * from './B'

export default A
```

Proto is generated by [pbjs](https://github.com/protobufjs/protobuf.js) from protobufjs, not to confuse with [pbjs](https://github.com/evanw/pbjs) also from @evanw:
```sh
yarn pbjs -t static-module -w commonjs -o ./Proto/index.js ./Proto/Proto.proto;
yarn pbts -o ./Proto/index.d.ts ./Proto/index.js;
```
```js
...
// Exported root namespace
var $root = $protobuf.roots["default"] || ($protobuf.roots["default"] = {});

$root.proto = (function() {

    /**
     * Namespace proto.
     * @exports proto
     * @namespace
     */
    var proto = {};

     proto.Something = (function() {
       ...
    }

    return proto;
})();

module.exports = $root;
```

esbuild bundle:
```js
...
Object.defineProperty(exports, "__esModule", { value: true });
const A_1 = __importDefault(require("./A"));
__exportStar(require("./B"), exports);
__exportStar(require("../Proto"), exports);
exports.default = A_1.default;
```

---

I'd expect `proto` to be accessible as a named export but it won't. The only way to use its types and runtime methods is:

```ts
import {
  namedPropFromB,
  // proto // typescript finds it but node will fail on runtime
} from "pkg";

import * as pkg from "pkg";

const sample = pkg.proto.Something.Method(value) as pkg.proto.Something.ISomething;
```

**Comment by evanw** [comment] 2023-06-09 13:09
@gabrielalmeida You should file a new issue if you believe you have found a bug with esbuild. It would also be helpful to have a self-contained reproduction on https://esbuild.github.io/try/.

> ```ts
>   // proto // typescript finds it but node will fail on runtime
> ```

Keep in mind that you need `--platform=node` when building for node. In this case esbuild generates annotations for node so node's syntactic CommonJS analyzer can find the re-exported export names: https://github.com/evanw/esbuild/issues/2486.
