### ISSUE TITLE
Custom options for plugins

### ISSUE THREAD

**Issue by caramboleyo** [evanw/esbuild#3576] opened 2024-01-04 13:44 UTC
```javascript
const builds = await build({
	entryPoints,
	bundle: true,
	format: 'esm',
	plugins: [dynamicInjection],
	myCustomOption: true,
});
```

When i add a custom option to the build options esbuild throws an error

✘ [ERROR] Invalid option in build() call: "myCustomOption"

but inside the plugin it would be easy to access a custom option with `build.initialOptions.myCustomOption`

Any way to achieve this?

**Comment by caramboleyo** [comment] 2024-01-04 16:11
Ah, ok, i will try that

**Comment by evanw** [comment] 2024-01-04 18:08
Yes, that's the typical way to do this. That's also how [plugin options work in Rollup](https://rollupjs.org/plugin-development/#plugins-overview), for example. Closing this as it's working as intended.

**Closed by evanw** 2024-01-04 18:08 UTC
