### ISSUE TITLE
Inability to tree shake in a particular case

### ISSUE THREAD

**Issue by badeball** [evanw/esbuild#1569] opened 2021-09-02 13:18 UTC
Hi,

I stumbled across a case where esbuild did not tree shake, to my surprise. This might very well just be me expecting too much due to ignorance, but I figured I'd share it and hear what you have to say.

I created a [gist](https://gist.github.com/badeball/465fd101f5da6a3cb1232d25ae83affe) which contains the example. Run the following to see esbuild fail.

```
$ git clone https://gist.github.com/badeball/465fd101f5da6a3cb1232d25ae83affe
$ cd 465fd101f5da6a3cb1232d25ae83affe
$ npm install
$ npx esbuild --bundle a.ts --outfile=output.js
 > foobar-crypto.js:1:23: error: Could not resolve "crypto" (use "--platform=node" when building for node)
    1 │ const crypto = require("crypto");
      ╵                        ~~~~~~~~

1 error
```

Since `invokeFoobar` is never used by the entry file, I expected it to not be included in the bundle (and thus not cause any errors). It does however compile if you omit the reference to `foobar.foo` in `c.ts`.

**Comment by evanw** [comment] 2021-09-02 13:26
The way the JavaScript language works is that imports are always evaluated, even if none of the imports are used. It would be incorrect for a bundler to omit code that is supposed to be evaluated. Even if you replace `import foobar from "./foobar-crypto"` with just `import "./foobar-crypto"`, that file is still supposed to be evaluated. Tree shaking also happens after all imports have been resolved and all code is present, not before.

**Comment by badeball** [comment] 2021-09-02 13:32
Alright, but I'm still a bit lost as to whether that also explain why it works if omitting the reference to `foobar.foo` in `c.ts` and replacing it with just `"foo"`? I was hoping that'd be irrelevant to tree shaking.

**Comment by evanw** [comment] 2021-09-02 14:45
Ah, I see. That's just a quirk of how TypeScript works. It has nothing to do with tree shaking. In TypeScript, imports that are not used as values are assumed to be types and are removed. You can see this behavior for yourself with the following TypeScript code (here's a [live link to the TypeScript playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAMwhARgQyoqERwEQB0A9EqhngNwBQoksiy6UATFjvsaU85VVQKYAPOvAQBXAHYBjGMAgS4wCQDcIAa34AxRhgAUSgM4w00-gC4GZKAW0QAQhgA0iiUZNT+zC1wzMbyBygASjgAbyo4OCh+GDEoBUNjU10fa1IQgGoXN1NmXTxSPCDqAF8qIA)):

```ts
import foobar from "./foobar";
import foobar2 from "./foobar2";

export function invokeFoobar(instance: foobar.FooBar, instance2: foobar2.FooBar) {
  return instance(foobar.foo) + instance2("foo");
}
```

The TypeScript compiler converts that to the following JavaScript:

```js
import foobar from "./foobar";
export function invokeFoobar(instance, instance2) {
  return instance(foobar.foo) + instance2("foo");
}
```

Since `foobar2` isn't used as a value (only as a type), it ends up being removed. This is the case even though types from `foobar2` are in use.

Tree shaking operates on the JavaScript after it has been converted to TypeScript. So since this happens during the conversion from TypeScript to JavaScript, it's not related to tree shaking. And this isn't an issue with esbuild since the official TypeScript compiler has the exact same behavior.

**Comment by evanw** [comment] 2021-09-13 01:20
I think everything here has been explained and esbuild appears to be working as intended, so I'm going to close this issue.

**Closed by evanw** 2021-09-13 01:20 UTC
