### ISSUE TITLE
Plugins for transform api

### ISSUE THREAD

**Issue by Djaler** [evanw/esbuild#790] opened 2021-02-11 13:11 UTC
Currently, the only way to use plugins is the build API. But if I use transform API instead, I cannot do it

**Comment by evanw** [comment] 2021-02-11 13:26
Yes, that’s correct. The transform API is a special case of the build API and deliberately cannot use plugins. The build API is the more general form of the transform API. Use the build API if you need plugins. More rationale is here in case it’s useful: #779.

**Comment by Djaler** [comment] 2021-02-11 13:48
I am using esbuild-loader (which transforms files using transform api) in my webpack-based application

**Comment by Djaler** [comment] 2021-02-11 14:02
Hmm, maybe I can just create webpack loader for this purpose

**Comment by iamakulov** [comment] 2021-02-11 19:33
> Yes, I can use babel-loader after esbuild-loader, but it is too slow

Would something like this work for you? 

```js
// webpack.config.js
module.exports = {
  module: {
    rules: [
      // 1) Your ESBuild loader
      { test: /\.js$/, loader: 'esbuild-loader' },
      // 2) An additional babel loader...
      {
        loader: 'babel-loader',
        options: { presets: ['@babel/preset-env'] },
        // ...that’s ran only against that single file that imports core-js...
        test: path.resolve(__dirname, '../src/index.js'),
        // ...and is ran before esbuild-loader
        enforce: 'pre',
      }
    ]
  }
}
```

I believe this setup should be quick enough as it runs Babel only against a single file. (I didn’t run this code, so there’s a chance there’s a minor mistake or typo somewhere.)

**Comment by Djaler** [comment] 2021-02-11 20:17
It's a little hacky, but will work, I'm sure. Will try tomorrow, thanks for the idea!

**Comment by evanw** [comment] 2021-03-29 21:06
Closing because the lack of plugins for the transform API is by design. The transform API is a subset of the build API for convenience, but if you need the full power of the build API then you should use the build API instead.

**Closed by evanw** 2021-03-29 21:06 UTC

**Comment by Djaler** [comment] 2021-03-29 21:10
That's sad because there are so many tools which uses esbuild transform internally, not build.
