### ISSUE TITLE
Could the watch command update the modification on the outfiles?

### ISSUE THREAD

**Issue by samsieber** [evanw/esbuild#2902] opened 2023-02-08 02:55 UTC
I use the following command in conjunction with Caddy running to both serve the static files and reverse proxy my API server:

`esbuild --outdir=public/assets --bundle src/index.tsx --watch`

Unless the timestamps are updated the default file serving through Caddy serves up cached outdated versions. My work around is to disable the browser cache while working, but it'd be nice to not have to do that. And I'd also love to avoid dipping into the js api.

**Comment by hyrious** [comment] 2023-02-08 03:32
> Unless the timestamps are updated the default file serving through Caddy serves up cached outdated versions

I do see esbuild updates mtime on watch mode:

<img width="287" alt="image" src="https://user-images.githubusercontent.com/8097890/217422558-4a61466f-29d9-46b0-9143-f4137781c3d4.png">

**Comment by samsieber** [comment] 2023-02-08 04:06
Hmm... well now I feel foolish, because I'm seeing the same thing. I'll close this ticket in the next few days if I can't reproduce this errant behavior.

**Comment by evanw** [comment] 2023-02-11 18:14
I'm closing this for now because it's currently unactionable. We can reopen it later if a way to reproduce the issue is provided.

**Closed by evanw** 2023-02-11 18:14 UTC
Labels: unactionable
