### ISSUE TITLE
incorrect module order

### ISSUE THREAD

**Issue by gludion** [evanw/esbuild#1318] opened 2021-05-26 15:33 UTC
I'm using typescript.
I have 2 classes with a circular reference:
Animal.ts
```
import Dog from "./Dog";
export default class Animal {
    jump() {
        // I know it's bad style but it's for keeping the example minimal
        if (this instanceof Dog) this.dogJump();
    }
}
```
Dog.ts:
```
import Animal from "./Animal";
export default class Dog extends Animal {
    dogJump() {
        console.log('wooff');
    }
}
```
Main.ts:
```
import Animal from "./libs/Animal";
export default class Main{
    animal: Animal;
    constructor() {
        this.animal = new Animal();
        this.animal.jump();
    }
}
```
If I bundle using default settings, the js file is:
```
(() => {
  // src/ts/libs/Dog.ts
  var Dog = class extends Animal_default {
    dogJump() {
      console.log("wooff");
    }
  };
  var Dog_default = Dog;

  // src/ts/libs/Animal.ts
  var Animal = class {
    jump() {
      if (this instanceof Dog_default)
        this.dogJump();
    }
  };
  var Animal_default = Animal;

  // src/ts/index.ts
  var Main= class {
    constructor() {
      this.animal = new Animal_default();
      this.animal.jump();
    }
  };
  var ts_default = Main;
})();
```

which causes an error since ` class extends Foo_default` (line 3) appears before Foo_default is defined.

If I manually move Animal definition before Dog, no error.
If I use a Dog() instead of Animal() in index.ts, then Animal is declared before Dog, no error.
Isn't esbuild supposed to find a "working" order?

**Comment by evanw** [comment] 2021-05-26 18:12
This code fails in the exact same way when run in node or in the browser without being bundled:

```
$ node ./Main.js
./Dog.js:2
export default class Dog extends Animal {
                                 ^

ReferenceError: Cannot access 'Animal' before initialization
    at ./Dog.js:2:34
```

All esbuild is doing is combining the files together. Bundling is intended to not change the semantics of the code. If your code crashes when run in node or in the browser before bundling, it will likely crash after bundling too.

> Isn't esbuild supposed to find a "working" order?

Sorry, that's not how JavaScript works. I recommend searching for information and learning more about how imports in JavaScript work (such as [this article](https://exploringjs.com/impatient-js/ch_modules.html#esms-transparent-support-for-cyclic-imports-advanced)). If your code can't be made to work well with import cycles, then I recommend removing the import cycles to avoid problems like this.

Closing this issue as "working as intended."

**Closed by evanw** 2021-05-26 18:12 UTC
