### ISSUE TITLE
Advice: Patching Modules with OpenTelemetry Instrumentation

### ISSUE THREAD

**Issue by drewcorlin1** [evanw/esbuild#3348] opened 2023-08-28 01:53 UTC
This is not an issue nor feature request, but rather just me looking for some advice/seeing if anyone else has thought about this case.

The issue I'm running into is with OpenTelemetry's method for auto-instrumentation. In short the approach relies on their instrumentation libraries being registered as the first module in the node application, where they register listeners for other modules to be `require`'d. When those other modules are `require`'d they patch them and insert instrumentation. The approach makes it very easy to get started, but has 1 major flaw: it relies on modules being `require`'d at runtime, and [breaks if you bundle your code ahead of time](https://github.com/open-telemetry/opentelemetry-js/tree/main/experimental/packages/opentelemetry-instrumentation#limitations:~:text=modules%20are%20not%20included%20in%20a%20bundle.%20Tools%20like%20esbuild%2C%20webpack%2C%20...%20usually%20have%20some%20mechanism%20to%20exclude%20specific%20modules%20from%20bundling).

There is a suggestion to [allow modules to be passed into the instrumentation to avoid this scenario](https://github.com/open-telemetry/opentelemetry-js/issues/2708), but there is no movement on that yet.

My organization uses esbuild for our microservices (fastify apps) and it has worked wonderfully until this hitch, so my though is to create an esbuild plugin that could resolve modules, pass them to OpenTelemetry's patching logic and then continue on at build time. I'm still trying to understand the build API and how to do this, so would love to hear if anyone else has thoughts on this approach or has tried something similar.

For more context: I could also mark the modules I want patched as external, but that's a hassle because then I need to make those modules (and any transitive dependencies) available at runtime, which is less convenient than having a single bundled JS file to execute.

**Comment by evanw** [comment] 2023-09-04 11:33
You can use an [on-load plugin](https://esbuild.github.io/plugins/#on-load) to substitute the contents of a module with something else. This is the correct point in esbuild's build cycle to patch them and insert instrumentation.

I'm closing this issue as this is not a bug with esbuild.

**Closed by evanw** 2023-09-04 11:33 UTC

**Comment by reecefenwick** [comment] 2024-04-15 09:02
@drewcorlin1 curious to know if you found a way forward here?

**Comment by drewcorlin1** [comment] 2024-04-15 12:50
@reecefenwick I have [this open MR](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1856) over in opentelemetry-js-contrib that I'm waiting for reviews on. Would appreciate your +1 on it if it's something you're interested in 😄

**Comment by mbrevda** [comment] 2024-09-16 14:32
Would it make sense for build to allow hooking into its runtime module loader? This might offer a simpler way for libraries like OpenTelemetry to hook into the loading process (as the do with node's native loaders) and automatically instrument libs as necessary. Such an approach might also allow for a much simpler setup as no plugins would be needed.
