### ISSUE TITLE
there are two  ‘’Io‘’ variable in one project

### ISSUE THREAD

**Issue by zhanxu33** [evanw/esbuild#3672] opened 2024-02-28 11:57 UTC
When esbuild is compressing, it extracts portions of code, but if there are instances of the same name across different files, this can lead to conflicts during execution, resulting in very peculiar behaviors.
![image](https://github.com/evanw/esbuild/assets/16716445/aaf9a495-515c-4929-a3cd-b5093908b9d8)
![image](https://github.com/evanw/esbuild/assets/16716445/18aefc16-0357-47dc-ac6d-f5d0399899d6)

there are two  ‘’Io‘’ variable in one project，lead to bug

**Comment by evanw** [comment] 2024-02-29 00:03
I'm closing this issue for two reasons:

1. You did not follow [esbuild's issue reporting instructions](https://raw.githubusercontent.com/evanw/esbuild/cc74e6042a9f573bf58e1e3f165ebda70af4ad3b/.github/ISSUE_TEMPLATE/new-issue.md) as there is no way for me to tell how the text in your screenshot was generated:

    > Provide a way to reproduce the issue. The best way to do this is to demonstrate the issue on the playground (https://esbuild.github.io/try/) and paste the URL here. A link to a minimal code sample with instructions for how to reproduce the issue may also work. Issues without a way to reproduce them may be closed.

2. It looks like you did not follow [esbuild's documentation about output formats](https://esbuild.github.io/api/#format). This situation should not happen when esbuild's output is used correctly. See https://esbuild.github.io/faq/#top-level-name-collisions for more information.

**Closed by evanw** 2024-02-29 00:03 UTC
