### ISSUE TITLE
use transform service with node as a platform?

### ISSUE THREAD

**Issue by wcastand** [evanw/esbuild#115] opened 2020-05-16 01:13 UTC
Hi, i'd like to use esbuild to transform some typescript code to be run as node worker.

In the read me it says that it can be used to transform Typescript to Javascript or newer Js to an older one. 

when i run the transform service on this file, it just remove the annotations if there is any: 
```
import test from './worker'

test('simple', (a) => {
  a.equal(1, 0, 'not equal')
})
test('async', async (a) => {
  await new Promise((r) => {
    setTimeout(() => {
      a.equal(1, 1, 'not equal')
      r()
    }, 1000)
  })
})
test('simple 2', (a) => {
  a.equal(1, 1, 'not equal')
})
```

is it related to issue #109 ?

**Comment by evanw** [comment] 2020-05-16 01:16
Yes this seems like a duplicate of #109 to me.

**Closed by evanw** 2020-05-16 01:16 UTC
