### ISSUE TITLE
CSS minification incorrectly changes `::before` to `:before`

### ISSUE THREAD

**Issue by mhevery** [evanw/esbuild#2871] opened 2023-01-27 05:38 UTC
```
% ./node_modules/.bin/esbuild --version
0.16.11
% cat test.css 
span::before {
  color: red;
}
% ./node_modules/.bin/esbuild test.css --minify
span:before{color:red}
```

Expected: `span::before{color:red}` notice `:` when it should be `::`

**Comment by mhevery** [comment] 2023-01-27 05:41
Tried on latest still same issue:
```
% ./node_modules/.bin/esbuild --version        
0.17.4
% cat test.css                                 
span::before {
  color: red;
}
% ./node_modules/.bin/esbuild test.css --minify
span:before{color:red}
```

**Comment by evanw** [comment] 2023-01-27 06:25
That behavior comes from [this part of the CSS specification](https://www.w3.org/TR/selectors-4/#single-colon-pseudos):

> * The four [Level 2](https://www.w3.org/TR/CSS2/selectors.html#pseudo-element-selectors) [pseudo-elements](https://www.w3.org/TR/selectors-4/#pseudo-element) ([::before](https://www.w3.org/TR/css-pseudo-4/#selectordef-before), [::after](https://www.w3.org/TR/css-pseudo-4/#selectordef-after), [::first-line](https://www.w3.org/TR/css-pseudo-4/#selectordef-first-line), and [::first-letter](https://www.w3.org/TR/css-pseudo-4/#selectordef-first-letter)) may, for legacy reasons, be represented using the [\<pseudo-class-selector>](https://www.w3.org/TR/selectors-4/#typedef-pseudo-class-selector) grammar, with only a single ":" character at their start.

I checked again and `::before` and `:before` seem equivalent to me in Chrome, Firefox, and Safari. In what situations are you observing them being not equivalent? Can you provide a way to reproduce the issue?

**Comment by sslotsky** [comment] 2023-01-27 13:27
[The issue initially reported to the Qwik repo](https://github.com/BuilderIO/qwik/issues/2189#issuecomment-1406045330) has a reproduction case in the description.

**Comment by evanw** [comment] 2023-01-27 16:01
That issue says their bug is that something is inserting extra stuff after the `:before` pseudo-element. In the description it's saying that `span::before` should become `span.⭐️iizyr0-0::before` but instead becomes `span:before.⭐️iizyr0-0`. The problem isn't `:` instead of `::`, it's that `:before` should come last but doesn't. Swapping pseudo-element selectors with class selectors not a transformation that esbuild does, so I'm assuming this bug is not related to esbuild.

You can see for yourself that `:` vs. `::` is irrelevant with the following HTML:

```html
<!DOCTYPE html>
<style>
  span.⭐️iizyr0-0::before{content:" not ";user-select:all}
  span.⭐️iizyr0-1:before{content:" not ";user-select:all}
  span::before.⭐️iizyr0-2{content:" not ";user-select:all}
  span:before.⭐️iizyr0-3{content:" not ";user-select:all}
</style>
<div>This is <span class="⭐️iizyr0-0">broken.</span></div>
<div>This is <span class="⭐️iizyr0-1">broken.</span></div>
<div>This is <span class="⭐️iizyr0-2">broken.</span></div>
<div>This is <span class="⭐️iizyr0-3">broken.</span></div>
```

That renders as follows:

```
This is not broken.
This is not broken.
This is broken.
This is broken.
```

**Comment by evanw** [comment] 2023-01-27 16:31
I'm closing this issue as esbuild is not doing anything incorrect here. As described in [the Vite issue linked from that same thread](https://github.com/vitejs/vite/issues/11808#issuecomment-1403195199), the problem seems to be that Quik doesn't correctly handle the `<legacy-pseudo-element-selector>` production in [the CSS grammar](https://drafts.csswg.org/selectors/#grammar).

**Closed by evanw** 2023-01-27 16:31 UTC
