### ISSUE TITLE
old project js files without module

### ISSUE THREAD

**Issue by peterchealse** [evanw/esbuild#171] opened 2020-06-08 06:46 UTC
I am dealing with an old browser project which js file  is not in any module, the functions and variables are defined on the window. So these js files depends on the pre script and must be in order. When i  have the config {minify:true,bunlde:false}, I find that all the identifiers defined on window are transfered if the file is big. And the depends cross multiple js files will fail, and  I have to  manually define Window.foo = 'foo' .  But if the file is small, only the local variables in a function is transfered.  The identifiers defined on window do not change. How can I preserve the variables defined on window  just like how esbuild process the small js files?

**Comment by evanw** [comment] 2020-06-08 19:27
Thanks for the report.

I have a guess for what's causing this. I don't think it's just about big files vs. small files. Even when a file isn't a module, it turns out a file can sort of become a module internally if it imports something from the esbuild runtime, which contains internal support code that may be needed to implement certain things. For example, using the `**` operator with `--target=es2015` generates an import for the `__pow` runtime function. The bug is that this import causes the file to incorrectly be considered a module. This can easily be fixed by ignoring imports from the runtime during module-or-not detection.

I'd need to have a code sample that reproduces the issue to confirm the fix though. Are you able to share one?

**Comment by peterchealse** [comment] 2020-06-09 02:13
wow, it works, thanks!

**Closed** 2020-06-09 02:45 UTC
