### ISSUE TITLE
not support return 'base64:text/javascript' path in resolve hook

### ISSUE THREAD

**Issue by hardfist** [evanw/esbuild#2404] opened 2022-07-21 02:17 UTC
It seems that esbuild supports  import from "data:text/javascript" by default
```ts
import x from "data:text/javascript,export default 42"
console.log('x:',x);
```
but when i use resolve hook to return "data:text/javascript" it throw error.
```ts
const esbuild = require('esbuild');

esbuild.build({
  entryPoints: ['./src/index.mjs'],
  outdir: 'dist',
  bundle: true,
  plugins: [{
    name: 'data-url',
    setup(build){
      build.onResolve({filter:/.*/},x => {
        console.log('x:',x);
       if(x.path.startsWith('data:')){
          return {
            path: x.path,
            
          }
       }
      })
    }
  }]
})
```
it throws error
```
src/index.mjs:1:14: ERROR: Plugin "data-url" returned a non-absolute path: data:text/javascript,export default 42 (set a namespace if this is not a file path)
```
I know I could just return undefined to let esbuild handle it internally, but i'm wondering whether it is not supported by design?

**Comment by evanw** [comment] 2022-07-23 03:25
If you don't specify the namespace, it'll default to `file` which requires the path to be an absolute file system path. The built-in resolver for `dataurl` uses the `dataurl` namespace instead, which the built-in loader for `dataurl` then recognizes, and knows to parse the text as a data URL. This is an implementation detail of esbuild. But if you want to take advantage of it and use esbuild's built-in loader for `dataurl`, you could just do the same thing as esbuild's built-in resolver for `dataurl`. You would then need to return the `namespace: 'dataurl'` along with the path.

**Comment by evanw** [comment] 2022-07-25 01:42
Closing as by design.

**Closed by evanw** 2022-07-25 01:42 UTC
