### ISSUE TITLE
Watch certain locations

### ISSUE THREAD

**Issue by hassanzohdy** [evanw/esbuild#3486] opened 2023-11-12 19:25 UTC
Hello,  i've looked multiple times over the docs to check if this option is available but no luck.

 The idea is how to tell esbuild what files/directories to watch?

Basically, i'm building a nodejs backend that i autoload files from certain locations then create a file to merge some code, the created file is what esbuild works with, but i want to tell the watcher what locations (files and directories) to watch.

Another case, is when a new file is being created the watcher won't recognize it because it is not listed in the watch list (one of the autoloaded files for example)

**Comment by evanw** [comment] 2023-11-15 17:09
This is not how esbuild's watch mode works. It only detects changes that affect the build output. If you want to use esbuild's watch mode for this, then you should make these files be a part of the build. Some options:

* Load these files with an esbuild loader (such as [`file` or `copy`](https://esbuild.github.io/content-types/#external-file))
* Return these files in `watchDirs` or `watchFiles` from an [esbuild plugin](https://esbuild.github.io/plugins/)
* Use [another file watcher](https://github.com/paulmillr/chokidar) instead or in addition to esbuild's file watcher (e.g. call [`rebuild()`](https://esbuild.github.io/api/#rebuild) on esbuild's context after a file watcher event from another file watcher library)

**Comment by evanw** [comment] 2023-11-18 21:07
I'm closing this issue because this is by design (esbuild's watch mode doesn't work this way on purpose) and there are other ways to do this, as described above.

**Closed by evanw** 2023-11-18 21:07 UTC
