### ISSUE TITLE
Can I remove/ignore an entry from `knownGlobals`?

### ISSUE THREAD

**Issue by JumpLink** [evanw/esbuild#2815] opened 2023-01-11 15:15 UTC
I am working an a custom Implementation of `EventTarget` for [Gjs](https://gjs.guide/) and I do not want this to be renamed or reordered.  `EventTarget` is [list in knownGlobals](https://github.com/evanw/esbuild/blob/main/internal/config/globals.go#L180):

> If something is in this list, then a direct identifier expression or property access chain matching this will be assumed to have no side effects and will be removed. This also means code is allowed to be reordered past things in this list.

 Is it possible to exclude some entries from this list?

**Comment by evanw** [comment] 2023-01-11 15:45
You can't do that right now. Can you describe why you need this? Please provide an example where reordering causes an issue, and describe what the issue is.

**Comment by JumpLink** [comment] 2023-01-12 10:15
Hey @evanw, thank you for the response. I have the following problem: I have [forked the Deno runtime](https://github.com/gjsify/gjsify/tree/main/packages/deno/runtime), in which some web APIs are implemented, including [EventTarget](https://github.com/gjsify/deno/blob/main/ext/web/02_event.ts) and [AbortSignal](https://github.com/gjsify/deno/blob/main/ext/web/03_abort_signal.ts). I have implemented [some examples](https://github.com/gjsify/deno/blob/main/ext/web/03_abort_signal.ts) which has this fork as a dependency and where I now have the problem that in the bundle the declaration of `EventTarget` is moved far to the end of the bundle, it should be at the very beginning, because there are further classes such as `AbortSignal` that inherit from `EventTarget`, but at this position `EventTarget` is still undefined.

Since I don't know what the problem is, my approach would have been to remove `EventTarget` from `knownGlobals` in order to get closer to finding the error. But maybe you have a tip for me as to what the problem could be and what I should look for? Or a workaround? I have already looked for circular dependencies to `EventTarget`, but couldn't find any. I can also share the manifest if that helps.

I am trying to create an example, but so far I have not been able to reproduce it, but I will try again.

**Comment by JumpLink** [comment] 2023-01-12 10:38
[Here is the manifest of the bundle](https://pastebin.com/zUfhnM6u), `EventTarget` is defined in `./../node_modules/@gjsify/deno-runtime/lib/ext/web/02_event.js`.

**Comment by JumpLink** [comment] 2023-01-12 11:30
I was able to fix my issue by adding 
```
    "sideEffects": [
        "./lib/ext/web/02_event.js"
    ],
```
to the package.json of my deno runtime fork.

**Comment by JumpLink** [comment] 2023-01-12 15:30
@evanw Okay, with this change all other files are now marked as side effect free, which leads to other problems, is there another way I could fix my issue?

```bash
▲ [WARNING] Ignoring this import because "lib/globals.js" was marked as having no side effects [ignored-bare-import]

    src/globals.spec.ts:2:7:
      2 │ import '@gjsify/deno-runtime/globals';
        ╵        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  It was excluded from the "sideEffects" array in the enclosing "package.json" file

    package.json:25:4:
      25 │     "sideEffects": [
 ```

**Comment by evanw** [comment] 2023-01-12 17:41
> I now have the problem that in the bundle the declaration of `EventTarget` is moved far to the end of the bundle. It should be at the very beginning in the bundle

I doubt this is caused by `knownGlobals`. The reordering that `knownGlobals` introduces is very local and I think also only happens when minification optimizations are enabled. It's described in [the comment at the top of the file](https://github.com/evanw/esbuild/blob/5d80704f1c64213da83c5f18d6f95255ccdff86e/internal/config/globals.go#L20-L25):

```go
// This also means code is allowed to be reordered past things in this list. For
// example, if "console.log" is in this list, permitting reordering allows for
// "if (a) console.log(b); else console.log(c)" to be reordered and transformed
// into "console.log(a ? b : c)". Notice that "a" and "console.log" are in a
// different order, which can only happen if evaluating the "console.log"
// property access can be assumed to not change the value of "a".
```

Are you building your code with `--minify` or `--minify-syntax` enabled? If so, is it a problem for you if esbuild transforms `if (EventTarget) console.log(b); else console.log(c)` into `console.log(EventTarget ? b : c)`? Or is it a problem for you if esbuild transforms `if (a) EventTarget(b); else EventTarget(c)` into `EventTarget(a ? b : c)`? If not, then you shouldn't need to care about `knownGlobals`.

> Is there another way to mark `EventTarget` - or the file in which `EventTarget` is defined - as not being side-effect free in order to prevent it from being moved?

Putting something in `knownGlobals` only affects uses of the global, not the definition of the global. There's no code in esbuild that will use membership in this list to attempt to figure out where `EventTarget` is defined. So there isn't a way to stop esbuild from doing this because it's not something that esbuild does in the first place.

The order that imported files are evaluated in JavaScript (assuming code splitting is off, which it is by default) is determined by how you write your `import` statements. It's done with a graph traversal that evaluates dependencies (in the order they appear in the source code) before dependents. My guess would be that you have an import cycle somewhere that's causing the unwanted ordering.

> I was able to fix my issue by adding
> 
> ```
>     "sideEffects": [
>         "./lib/ext/web/02_event.js"
>     ],
> ```
> 
> to the package.json of my deno runtime fork.

That doesn't sound right. By default all files are considered to have side effects. Putting this declaration here isn't telling esbuild that `02_event.js` now has side effects. It's instead telling esbuild that all files except `02_event.js` now don't have side effects. I'm guessing that doing this has caused some bare import statements to be ignored, which has changed your module ordering, which has fixed this particular ordering issue with `EventTarget` but has introduced other problems. I recommend not using `sideEffects` and instead fixing the import ordering issue.

The code that determines evaluation ordering is [here](https://github.com/evanw/esbuild/blob/main/internal/linker/linker.go#L3320). It looks complicated but it's basically this:

```js

const visit = node => {
  if (!visited.has(node)) {
    visited.add(node)
    node.dependencies.forEach(visit)
    evaluationOrder.push(node)
  }
}

const visited = new Set
const evaluationOrder = []
visit(entryPoint)
```

Hopefully that helps debug your ordering issue. If you still believe that this is a problem with esbuild, then please provide a way to reproduce the issue (input code + esbuild command used + a description of how to demonstrate the problem).

**Comment by evanw** [comment] 2023-07-14 00:43
I'm closing this issue because a way to reproduce it was not provided.

**Closed by evanw** 2023-07-14 00:43 UTC
