### ISSUE TITLE
Monorepo with Yarn PnP in the root and standalone project with esbuild in a subdir

### ISSUE THREAD

**Issue by JanVoracek** [evanw/esbuild#2495] opened 2022-08-24 11:28 UTC
We have a repository with the following structure:

```
.
├── .pnp.cjs
├── package.json // { "workspaces": ["packages/*"] } - notice that `prototypes` are not part of the workspaces
├── packages
│   ├── package-a/
│   ├── package-b/
│   └── ...
└── prototypes
    ├── esbuild-prototype // uses npm
    │   ├── package.json
    │   └── package-lock.json
    ├── some-other-prototype // can use pnpm, yarn + node_modules linker, etc.
    └── ...
```

In this case, the esbuild bundler doesn't work correctly because it finds the `.pnp.cjs` file in the repository root and tries to resolve dependencies using the PnP strategy - even though the esbuild project is not part of the Yarn workspaces and doesn't even use Yarn at all.

**Comment by merceyz** [comment] 2022-08-25 13:34
This is working as intended, if you want a directory to not be part of the project you need to tell Yarn about it using [`pnpIgnorePatterns`](https://yarnpkg.com/configuration/yarnrc#pnpIgnorePatterns).

```yaml
pnpIgnorePatterns:
    - "./prototypes/**"
```

**Comment by evanw** [comment] 2022-08-29 02:52
Closing because it sounds like this is working as intended, and there is an easy workaround available.

**Comment by JanVoracek** [comment] 2022-09-06 08:34
I'm not sure it works as intended. Here's a demo repository that reproduces the problem: https://github.com/JanVoracek/esbuild-yarn-demo. There is also a GH Action demonstrating the failure: https://github.com/JanVoracek/esbuild-yarn-demo/actions/runs/2998205785

Also, it seems that Yarn can resolve the import but esbuild crashes on `Could not resolve "react"` anyway: 
```
$ echo "[\"react\", \"$PWD/prototypes/esbuild-prototype/src/app.tsx\"]" | node .pnp.cjs
[null,".../prototypes/esbuild-prototype/node_modules/react/index.js"]
```

**Comment by evanw** [comment] 2022-09-10 00:43
Thank you for providing a way to reproduce this. It looks like the problem is that Yarn's regular expression for `ignorePatternData` uses regular expression features that work in JavaScript but not in Go. Specifically [this](https://github.com/JanVoracek/esbuild-yarn-demo/blob/28e10cb457338d65d00570059b4b27a7cf9c1508/.pnp.cjs#L29) is not a valid Go regular expression:

```
(^(?:\.yarn\/sdks(?:\/(?!\.{1,2}(?:\/|$))(?:(?:(?!(?:^|\/)\.{1,2}(?:\/|$)).)*?)|$))$)|(^(?:prototypes(?:\/(?!\.{1,2}(?:\/|$))(?:(?:(?!(?:^|\/)\.{1,2}(?:\/|$)).)*?)|$))$)
```

I'm not sure what to do about this.

**Closed** 2022-09-10 02:16 UTC

**Comment by hichemfantar** [comment] 2025-01-16 17:40
i had the problem with https://stackoverflow.com/questions/74958055/why-yarn-creates-a-pnp-loader-mjs-and-pnp-cjs-files in the home directory `~` and fixed it by deleting them
