### ISSUE TITLE
Double extension problem in outdir 

### ISSUE THREAD

**Issue by tchoutri** [evanw/esbuild#2646] opened 2022-10-30 23:04 UTC
* Esbuild version: 0.15.10
* NodeJS version: 18.4.0

## Problem

When building and bundling my assets, the `outdir` has the following files:

```
app.css.css  app.css.css.map  app.js.js  app.js.js.map  favicon.svg  icons/  node_modules/
```

As we can see, the files have a double extension (`.css.css`, `.js.js`), which is not the desired behaviour.

I first tried to use `outExtension` to hopefully match on the double extension and deduplicate them, but to no avail. 

## Configuration

<details>
<summary>click here to show </summary>

```js
const esbuild = require("esbuild");
const assetsManifestPlugin = require("esbuild-plugin-assets-manifest");

const minify = false;
const sourcemap = true;
const watch_fs = true;

const plugins = [];
const entryNames = "[name]";

esbuild.build({
  entryPoints: {
    "app.js": "./js/app.js",
    "app.css": "./css/app.css",
  },
  outdir: "../static",
  bundle: true,
  sourcemap: sourcemap,
  minify: minify,
  target: "es2018",
  entryNames: entryNames,
  watch: watch_fs,
  plugins: plugins
});

```
</details>

**Comment by evanw** [comment] 2022-10-30 23:12
From [esbuild's documentation](https://esbuild.github.io/api/#entry-points):

> In addition, you can also specify a fully custom output path for each individual entry point using an alternative entry point syntax:
> 
> ```js
> require('esbuild').buildSync({
>   entryPoints: {
>     out1: 'home.js',
>     out2: 'settings.js',
>   },
>   bundle: true,
>   write: true,
>   outdir: 'out',
> })
> ```
> 
> This will generate two output files, `out/out1.js` and `out/out2.js` corresponding to the two entry points `home.ts` and `settings.ts`.

As the documentation demonstrates, you don't need to include the extensions in the `entryPoints` map keys.

**Comment by evanw** [comment] 2022-10-31 14:06
Closing as by design.

**Closed by evanw** 2022-10-31 14:06 UTC

**Comment by tchoutri** [comment] 2022-10-31 14:22
Perfect, thank you very much!!
