### ISSUE TITLE
tslib_1.__exportStar is not a function

### ISSUE THREAD

**Issue by benjaminbours** [evanw/esbuild#746] opened 2021-02-03 17:55 UTC
I'm facing an issue I don't understand. Looks like it's related to https://github.com/evanw/esbuild/issues/284

![2021-02-03_18-51](https://user-images.githubusercontent.com/8804297/106788121-d6acd580-6650-11eb-83cf-6f2ad8d1094f.png)

From the research I made, I should enable `importHelpers` and `esModuleInterop` in my tsconfig but its not changing anything.

Any idea where it comes from?

Here is my tsconfig.json
```jsonc
{
  "compilerOptions": {
    /* Basic Options */
    // "incremental": true,                   /* Enable incremental compilation */
    "target": "es5",                          /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019' or 'ESNEXT'. */
    "module": "commonjs",                     /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', or 'ESNext'. */
    "lib": ["WebWorker", "ES6", "DOM", "ESNext"],              /* Specify library files to be included in the compilation. */
    "allowJs": true,                          /* Allow javascript files to be compiled. */
    // "checkJs": true,                       /* Report errors in .js files. */
    "jsx": "react",                           /* Specify JSX code generation: 'preserve', 'react-native', or 'react'. */
    // "declaration": true,                   /* Generates corresponding '.d.ts' file. */
    // "declarationMap": true,                /* Generates a sourcemap for each corresponding '.d.ts' file. */
    "sourceMap": true,                        /* Generates corresponding '.map' file. */
    // "outFile": "./",                       /* Concatenate and emit output to single file. */
    "outDir": "./build",                      /* Redirect output structure to the directory. */
    "rootDir": "./",                          /* Specify the root directory of input files. Use to control the output directory structure with --outDir. */
    // "composite": true,                     /* Enable project compilation */
    // "tsBuildInfoFile": "./",               /* Specify file to store incremental compilation information */
    // "removeComments": true,                /* Do not emit comments to output. */
    // "noEmit": true,                        /* Do not emit outputs. */
    "importHelpers": true,                 /* Import emit helpers from 'tslib'. */
    // "downlevelIteration": true,            /* Provide full support for iterables in 'for-of', spread, and destructuring when targeting 'ES5' or 'ES3'. */
    // "isolatedModules": true,               /* Transpile each file as a separate module (similar to 'ts.transpileModule'). */
    /* Strict Type-Checking Options */
    "strict": true,                           /* Enable all strict type-checking options. */
    // "noImplicitAny": true,                 /* Raise error on expressions and declarations with an implied 'any' type. */
    // "strictNullChecks": true,              /* Enable strict null checks. */
    // "strictFunctionTypes": true,           /* Enable strict checking of function types. */
    // "strictBindCallApply": true,           /* Enable strict 'bind', 'call', and 'apply' methods on functions. */
    // "strictPropertyInitialization": true,  /* Enable strict checking of property initialization in classes. */
    // "noImplicitThis": true,                /* Raise error on 'this' expressions with an implied 'any' type. */
    // "alwaysStrict": true,                  /* Parse in strict mode and emit "use strict" for each source file. */
    /* Additional Checks */
    "noUnusedLocals": true,                /* Report errors on unused locals. */
    "noUnusedParameters": true,            /* Report errors on unused parameters. */
    "noImplicitReturns": true,             /* Report error when not all code paths in function return a value. */
    "noFallthroughCasesInSwitch": true,    /* Report errors for fallthrough cases in switch statement. */
    /* Module Resolution Options */
    // "moduleResolution": "node",            /* Specify module resolution strategy: 'node' (Node.js) or 'classic' (TypeScript pre-1.6). */
    "baseUrl": "./src",                       /* Base directory to resolve non-absolute module names. */
    "paths": {
      "project-core/*": ["project-core/*"]
    },                           /* A series of entries which re-map imports to lookup locations relative to the 'baseUrl'. */
    // "rootDirs": [],                        /* List of root folders whose combined content represents the structure of the project at runtime. */
    "typeRoots": [
      "./node_modules/@types",
      "./src/typings"
    ],                                        /* List of folders to include type definitions from. */
    // "types": [],                           /* Type declaration files to be included in compilation. */
    // "allowSyntheticDefaultImports": true,  /* Allow default imports from modules with no default export. This does not affect code emit, just typechecking. */
    "esModuleInterop": true,                   /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */
    // "preserveSymlinks": true,              /* Do not resolve the real path of symlinks. */
    // "allowUmdGlobalAccess": true,          /* Allow accessing UMD globals from modules. */
    /* Source Map Options */
    // "sourceRoot": "",                      /* Specify the location where debugger should locate TypeScript files instead of source locations. */
    // "mapRoot": "",                         /* Specify the location where debugger should locate map files instead of generated locations. */
    // "inlineSourceMap": true,               /* Emit a single file with source maps instead of having a separate file. */
    // "inlineSources": true,                 /* Emit the source alongside the sourcemaps within a single file; requires '--inlineSourceMap' or '--sourceMap' to be set. */
    /* Experimental Options */
    // "experimentalDecorators": true,        /* Enables experimental support for ES7 decorators. */
    // "emitDecoratorMetadata": true,         /* Enables experimental support for emitting type metadata for decorators. */
    "resolveJsonModule": true
  },
  "include": [
    "./src/**/*.ts",
    "./src/**/*.tsx",
    "./src/**/*.spec.ts",
    "./src/**/*.spec.tsx",
    "./tests/**/*.ts",
    "./tests/**/*.tsx",
  ],
  "exclude": [
    "build",
    "config",
    "i18n",
    "local",
    "temp",
    "node_modules"
  ]
}

```

**Comment by evanw** [comment] 2021-02-03 21:58
There is no code in esbuild that generates anything called `tslib`. If you are getting code that looks like that, it must be coming from somewhere else on your end. There are very few `tsconfig.json` settings that esbuild pays attention to and esbuild does not currently look at the `importHelpers` or `esModuleInterop` settings at all.

**Comment by evanw** [comment] 2021-02-03 23:02
Closing because this seems like a bug with some other tooling instead of with esbuild, as described above. Providing some code that reproduces the issue should allow for determining where this problem comes from.

**Closed by evanw** 2021-02-03 23:02 UTC

**Comment by michelson** [comment] 2023-01-12 15:46
this is really odd I'm having the exact same issue ts_lib `__assign is not a function`  in https://unpkg.com/browse/use-sidecar@1.0.1/dist/es5/medium.js
what could be causing this? I'm using version 0.14
an example of this is at https://campus.universidadisep.com/login/index.php , is the embed.js file, note that the file is large because I'm showing a development version.

**Comment by michelson** [comment] 2023-01-12 16:55
it seems that the page uses requirejs and it may have problems with define function? as it is stated here: 
https://requirejs.org/docs/errors.html#mismatch
not sure how to tackle this problem, should we define `define` in an specific way?

**Comment by smg-tilman** [comment] 2024-04-16 13:40
Maybe not relevant for you and also maybe not relevant for esbuild but if you come here via googeling here is some solution:

importHelpers need to be set to false (Not to true as in issue description). That way import helpers will get added to packages automatically instead of needing to import them from tslib:
```
{
  ...
  "compilerOptions": {
    ...
    "importHelpers": false
    ...
  },
  ...
}

```

See here: https://www.typescriptlang.org/tsconfig#importHelpers
