### ISSUE TITLE
Remove unused classes

### ISSUE THREAD

**Issue by flunderpero** [evanw/esbuild#782] opened 2021-02-10 18:04 UTC
We use custom generator code to generate Typescript classes from a Protobuf definition. We keep all classes in a single, rather big module. A class looks roughly like this:
```
class MyEntity {
    // Some static constants
    static string HTTP_METHOD = "GET"

    // Properties
    public name: string

    // Static entry point for deserialization
    static _from_pb() { ... }

    to_pb() { ... }
}
```
When bundling the code for the web-app, _all_ classes are preserved in the output whether they are used or not.

We build like this:
```
await esbuild(
{
        entryPoints: ["index.ts"],
        outdir: "out",
        format: "esm",
        tsconfig: "./tsconfig.json"),
        sourcemap: "external",
        minifyIdentifiers: false,
        minifySyntax: true,
        minifyWhitespace: true,
        bundle: true,
        keepNames: true,
        target: "es2017",
})
```

Edit: I just checked: _Some_ classes are removed from the output, but I cannot see any pattern.

**Comment by flunderpero** [comment] 2021-02-10 18:21
If I remove the static "constants" (`HTTP_METHOD`) then the unused classes are removed from output.

**Comment by flunderpero** [comment] 2021-02-10 18:29
I tried to generate the Typescript code like this `static HTTP_METHOD = <const>"GET"` but it did not change anything. I know that esbuild only works on JS and ignores Typescript's syntax.

Is there a chance to make this work?

**Comment by flunderpero** [comment] 2021-02-10 18:30
But even after I "fix" the static constants there are still unused classes in the resulting bundle.

**Comment by evanw** [comment] 2021-02-10 21:33
I believe this is a duplicate of #175. Closing as a duplicate.

**Closed by evanw** 2021-02-10 21:33 UTC
