### ISSUE TITLE
which file watcher does ESBuild use?

### ISSUE THREAD

**Issue by WagnerMoreira** [evanw/esbuild#2953] opened 2023-02-27 17:33 UTC
title, I'm just curious, I checked the code I don't know go, so it's a bit hard to understand what's going on
I've seen people having issues with the file changes not being picked up, it doesn't seem like esbuild use watchman

**Comment by evanw** [comment] 2023-02-27 19:31
https://esbuild.github.io/api/#watch

> Watch mode in esbuild is implemented using polling instead of OS-specific file system APIs for portability.

**Comment by evanw** [comment] 2023-02-28 02:12
I'm closing this issue because this is a question, not a bug report, and the answer is already in the documentation.

**Closed by evanw** 2023-02-28 02:12 UTC
