### ISSUE TITLE
Question: debugging/limitations of sourcemaps

### ISSUE THREAD

**Issue by znewsham** [evanw/esbuild#3082] opened 2023-04-24 02:59 UTC
How would you advise debugging sourcemap generation with esbuild?

When I use `splitting: true` the sourcemap is off by about 5-10 lines (different amounts), but at least gets the right file - this is in the main entry point, not one of the chunks

When I turn on minification, it's way off, opening totally different files. 

I've not been able to put together a simple reproduction, however it doesn't appear to be related to:
- `onLoad` plugins
- `define`

The code I'm bundling is pretty large, and does generate a handful of warnings and a large number of debug logs (if I enable those) none seem like they would be relevant. 

The (relevant) args I'm using are:

```
await esbuild.context({
    entryPoints: ['./client.js'],
    minify: true,
    sourcemap: 'linked',
    splitting: true,
    bundle: true,
    outdir: 'build',
    format: 'esm',
})
```

**Comment by evanw** [comment] 2023-04-25 11:00
I'm not sure, sorry. I have written a source map visualizer that you may find helpful: https://evanw.github.io/source-map-visualization/.

I can only do something with this report if you provide a way to reproduce the issue here. I'm marking this issue as `unactionable` until something like that is provided.

**Comment by znewsham** [comment] 2023-04-26 02:13
This was exceptionally helpful - the problem, at least in part, is that chrome caches the sourcemap :facepalm: seeing the sourcemap in your viewer showed the sourcemap to be correct. I'll start using a hashed output instead.

I'm hoping the minified version is the same problem!

**Comment by evanw** [comment] 2023-05-12 19:27
I'm closing this issue because it's been unactionable for a while and there's still nothing I can do with it.

**Closed by evanw** 2023-05-12 19:27 UTC
Labels: unactionable
