### ISSUE TITLE
--mangle-props mangles too much

### ISSUE THREAD

**Issue by knaccc** [evanw/esbuild#2333] opened 2022-06-19 20:12 UTC
If I start with the following Javascript:

```js
let obj = {alice: 1, bob: 2};
console.log(Math.max(obj.alice, obj.bob));
```

Using terser: `terser --toplevel --mangle --mangle-props --output test-terser.js test.js`
```js
let e={l:1,o:2};console.log(Math.max(e.l,e.o));
```

Whereas using esbuild: `esbuild --minify --mangle-props=".*" --outfile=test-esbuild.js test.js`
```js
let obj={o:1,e:2};console.l(Math.t(obj.o,obj.e));
```

Obviously, the esbuild output won't run, because `console.l` is not a function, and neither is `Math.t`.

I think terser is applying the simple rule of not mangling properties of objects where those particular objects are not declared inside the code.

Please could you consider using the same rule for esbuild? And please could you also allow the equivalent of terser's `--toplevel` flag, so that class names, function names and variables declared at the top level (such as `obj` in the code above) can be also mangled? 

Thank you for your incredible work!

**Comment by evanw** [comment] 2022-06-20 13:08
I think you are misunderstanding what Terser is doing. Consider this code:

```js
obj = {
  foo() {},
  bar() {},
  log() {},
  max() {}
};
console.log(
  obj.foo(),
  obj.bar(),
  obj.log(),
  obj.max()
);
```

Running that through `terser --mangle-props` gives this:

```js
obj={o(){},j(){},log(){},max(){}};console.log(obj.o(),obj.j(),obj.log(),obj.max());
```

As you can see, `log` and `max` are not mangled despite being declared inside the code. Terser is open source and you can see what they are doing here: https://github.com/terser/terser/blob/645a092323fad50d2fc4c1c6b49ce1db0d9eeb4f/lib/propmangle.js#L72. They scan the objects built in to node for property names and mark them all as reserved. So it has nothing to do with whether properties are declared inside the code or not.

I could take this approach in esbuild too, but I decided not to. I believe that the way to use this feature that makes the most sense is to only quote properties which follow a naming pattern that doesn't show up in any built-in JavaScript APIs such as ending in `_` (as is [described in the documentation](https://esbuild.github.io/api/#mangle-props)). My rationale:

* This is an extremely simple and effective way of automatically avoiding all name collisions. You shouldn't ever even encounter the situation that you are worried about.

* It also makes it possible to tell which properties are mangled when reading the code, which seems pretty important given that they behave differently than normal properties.

* It also guarantees that mangling will happen, while using names that look like built-in JavaScript APIs doesn't. For example, if built-in API names are reserved like Terser and you make an internal-only API that uses `get` and `set` methods then your API will not be mangled, while they would be mangled fine if you had used `get_` and `set_` instead. This would lead to sub-optimal output (or sub-obfuscated output, depending on your reasons for using the feature).

You can still do what Terser is doing with esbuild if you want to. Just run the code in Terser that's linked to above, and write all of those reserved properties to a JSON file (mapped to `false`) and pass that to esbuild using `--mangle-cache=` (documentation is here: https://esbuild.github.io/api/#mangle-cache). This tells esbuild to avoid mangling any of those properties. I recommend against doing this but you are still welcome to do it if you prefer.

> And please could you also allow the equivalent of terser's `--toplevel` flag, so that class names, function names and variables declared at the top level (such as obj in the code above) can be also mangled?

This already happens when you specify an output format, such as `--format=esm` (although any output format will do). That's the way to do this in esbuild. Without an output format, esbuild can't know that top-level names are safe to minify because your code may be run in the global scope, or in some other unexpected way. But with an output format you are telling esbuild how your code will be run, so it's then safe to minify top-level names (since all three output formats that esbuild supports have a private encapsulated top-level scope).

**Comment by evanw** [comment] 2022-06-20 22:05
You are welcome to do things that way with esbuild if you prefer. Just use `--mangle-cache=` and pass the JSON file of the properties that you want to be reserved. Here's the JSON file that should match Terser's built-in set of reserved property names:

<details>

```json
{
  "$&": false,
  "$'": false,
  "$+": false,
  "$1": false,
  "$2": false,
  "$3": false,
  "$4": false,
  "$5": false,
  "$6": false,
  "$7": false,
  "$8": false,
  "$9": false,
  "$_": false,
  "$`": false,
  "-Infinity": false,
  "BYTES_PER_ELEMENT": false,
  "E": false,
  "EPSILON": false,
  "Infinity": false,
  "LN10": false,
  "LN2": false,
  "LOG10E": false,
  "LOG2E": false,
  "MAX_SAFE_INTEGER": false,
  "MAX_VALUE": false,
  "MIN_SAFE_INTEGER": false,
  "MIN_VALUE": false,
  "NEGATIVE_INFINITY": false,
  "NaN": false,
  "PI": false,
  "POSITIVE_INFINITY": false,
  "SQRT1_2": false,
  "SQRT2": false,
  "UTC": false,
  "__defineGetter__": false,
  "__defineSetter__": false,
  "__lookupGetter__": false,
  "__lookupSetter__": false,
  "abs": false,
  "acos": false,
  "acosh": false,
  "add": false,
  "all": false,
  "allSettled": false,
  "anchor": false,
  "any": false,
  "apply": false,
  "arguments": false,
  "asin": false,
  "asinh": false,
  "assign": false,
  "asyncIterator": false,
  "at": false,
  "atan": false,
  "atan2": false,
  "atanh": false,
  "big": false,
  "bind": false,
  "blink": false,
  "bold": false,
  "buffer": false,
  "byteLength": false,
  "byteOffset": false,
  "call": false,
  "caller": false,
  "captureStackTrace": false,
  "catch": false,
  "cbrt": false,
  "ceil": false,
  "charAt": false,
  "charCodeAt": false,
  "clear": false,
  "clz32": false,
  "codePointAt": false,
  "compile": false,
  "concat": false,
  "construct": false,
  "constructor": false,
  "copyWithin": false,
  "cos": false,
  "cosh": false,
  "create": false,
  "defineProperties": false,
  "defineProperty": false,
  "delete": false,
  "deleteProperty": false,
  "description": false,
  "dotAll": false,
  "endsWith": false,
  "entries": false,
  "every": false,
  "exec": false,
  "exp": false,
  "expm1": false,
  "false": false,
  "fill": false,
  "filter": false,
  "finally": false,
  "find": false,
  "findIndex": false,
  "fixed": false,
  "flags": false,
  "flat": false,
  "flatMap": false,
  "floor": false,
  "fontcolor": false,
  "fontsize": false,
  "for": false,
  "forEach": false,
  "freeze": false,
  "from": false,
  "fromCharCode": false,
  "fromCodePoint": false,
  "fromEntries": false,
  "fround": false,
  "get": false,
  "getBigInt64": false,
  "getBigUint64": false,
  "getDate": false,
  "getDay": false,
  "getFloat32": false,
  "getFloat64": false,
  "getFullYear": false,
  "getHours": false,
  "getInt16": false,
  "getInt32": false,
  "getInt8": false,
  "getMilliseconds": false,
  "getMinutes": false,
  "getMonth": false,
  "getOwnPropertyDescriptor": false,
  "getOwnPropertyDescriptors": false,
  "getOwnPropertyNames": false,
  "getOwnPropertySymbols": false,
  "getPrototypeOf": false,
  "getSeconds": false,
  "getTime": false,
  "getTimezoneOffset": false,
  "getUTCDate": false,
  "getUTCDay": false,
  "getUTCFullYear": false,
  "getUTCHours": false,
  "getUTCMilliseconds": false,
  "getUTCMinutes": false,
  "getUTCMonth": false,
  "getUTCSeconds": false,
  "getUint16": false,
  "getUint32": false,
  "getUint8": false,
  "getYear": false,
  "global": false,
  "has": false,
  "hasIndices": false,
  "hasInstance": false,
  "hasOwn": false,
  "hasOwnProperty": false,
  "hypot": false,
  "ignoreCase": false,
  "imul": false,
  "includes": false,
  "indexOf": false,
  "input": false,
  "is": false,
  "isArray": false,
  "isConcatSpreadable": false,
  "isExtensible": false,
  "isFinite": false,
  "isFrozen": false,
  "isInteger": false,
  "isNaN": false,
  "isPrototypeOf": false,
  "isSafeInteger": false,
  "isSealed": false,
  "isView": false,
  "italics": false,
  "iterator": false,
  "join": false,
  "keyFor": false,
  "keys": false,
  "lastIndexOf": false,
  "lastMatch": false,
  "lastParen": false,
  "leftContext": false,
  "length": false,
  "link": false,
  "localeCompare": false,
  "log": false,
  "log10": false,
  "log1p": false,
  "log2": false,
  "map": false,
  "match": false,
  "matchAll": false,
  "max": false,
  "message": false,
  "min": false,
  "multiline": false,
  "name": false,
  "normalize": false,
  "now": false,
  "null": false,
  "of": false,
  "ownKeys": false,
  "padEnd": false,
  "padStart": false,
  "parse": false,
  "parseFloat": false,
  "parseInt": false,
  "pop": false,
  "pow": false,
  "preventExtensions": false,
  "propertyIsEnumerable": false,
  "prototype": false,
  "push": false,
  "race": false,
  "random": false,
  "raw": false,
  "reduce": false,
  "reduceRight": false,
  "reject": false,
  "repeat": false,
  "replace": false,
  "replaceAll": false,
  "resolve": false,
  "reverse": false,
  "revocable": false,
  "rightContext": false,
  "round": false,
  "seal": false,
  "search": false,
  "set": false,
  "setBigInt64": false,
  "setBigUint64": false,
  "setDate": false,
  "setFloat32": false,
  "setFloat64": false,
  "setFullYear": false,
  "setHours": false,
  "setInt16": false,
  "setInt32": false,
  "setInt8": false,
  "setMilliseconds": false,
  "setMinutes": false,
  "setMonth": false,
  "setPrototypeOf": false,
  "setSeconds": false,
  "setTime": false,
  "setUTCDate": false,
  "setUTCFullYear": false,
  "setUTCHours": false,
  "setUTCMilliseconds": false,
  "setUTCMinutes": false,
  "setUTCMonth": false,
  "setUTCSeconds": false,
  "setUint16": false,
  "setUint32": false,
  "setUint8": false,
  "setYear": false,
  "shift": false,
  "sign": false,
  "sin": false,
  "sinh": false,
  "size": false,
  "slice": false,
  "small": false,
  "some": false,
  "sort": false,
  "source": false,
  "species": false,
  "splice": false,
  "split": false,
  "sqrt": false,
  "stackTraceLimit": false,
  "startsWith": false,
  "sticky": false,
  "strike": false,
  "stringify": false,
  "sub": false,
  "substr": false,
  "substring": false,
  "sup": false,
  "tan": false,
  "tanh": false,
  "test": false,
  "then": false,
  "toDateString": false,
  "toExponential": false,
  "toFixed": false,
  "toGMTString": false,
  "toISOString": false,
  "toJSON": false,
  "toLocaleDateString": false,
  "toLocaleLowerCase": false,
  "toLocaleString": false,
  "toLocaleTimeString": false,
  "toLocaleUpperCase": false,
  "toLowerCase": false,
  "toPrecision": false,
  "toPrimitive": false,
  "toString": false,
  "toStringTag": false,
  "toTimeString": false,
  "toUTCString": false,
  "toUpperCase": false,
  "trim": false,
  "trimEnd": false,
  "trimLeft": false,
  "trimRight": false,
  "trimStart": false,
  "true": false,
  "trunc": false,
  "undefined": false,
  "unicode": false,
  "unscopables": false,
  "unshift": false,
  "valueOf": false,
  "values": false
}
```

</details>

> the simple rule is that I assume any property that is not quoted may be mangled unpredictably

That approach should work as well. Then your source code would look like this:

```js
let obj = {alice: 1, bob: 2};
console['log'](Math['max'](obj.alice, obj.bob));
```

One caveat is that I just discovered a bug with property mangling when combined with minification. Minification automatically converts `x['y']` into `x.y` for size reasons which then interferes with quoted property mangling. I'll push out a fix.

**Comment by knaccc** [comment] 2022-06-20 22:52
@evanw Thanks! I've also noticed that terser references [domprops.js](https://github.com/terser/terser/blob/master/tools/domprops.js), and it isn't hard for me to import the latest version of domprops.js and run a script to invoke [find_builtins](https://github.com/terser/terser/blob/645a092323fad50d2fc4c1c6b49ce1db0d9eeb4f/lib/propmangle.js#L72) to ensure my mangle-cache is up-to-date.

Btw, I noticed that terser must be doing something slightly more than just whitelisting certain properties.

For examle, If I mangle this code in terser:

```js
let props = {text: 'loading...'};
chrome.browserAction.setBadgeText(props);
```

the result is:
```js
let a={text:"loading..."};chrome.browserAction.setBadgeText(a);
```

Therefore, terser somehow knows to preserve `browserAction` and `setBadgeText`, even though those two properties are not in the reserved list. I verified this as follows:

```js
let reserved = new Set();
find_builtins(reserved);
['chrome', 'browserAction', 'setBadgeText', 'text']
  .forEach(i=>console.log(`${i} is reserved? ${reserved.has(i)}`))
```

It is possible that this is not actually terser being clever, but actually a bug in terser, as I've documented [here](https://github.com/terser/terser/issues/1215).
output:

````
chrome is reserved? true
browserAction is reserved? false
setBadgeText is reserved? false
text is reserved? true
````

**Comment by knaccc** [comment] 2022-06-20 23:02
Following up on the chrome.* APIs issue, one way to solve the issue with esbuild would be for me to figure out some way to parse and import names into mangle-cache from https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/chrome/index.d.ts

**Comment by evanw** [comment] 2022-06-20 23:35
Well it seems like you aren't concerned with precision (i.e. it's ok if some names aren't mangled), so you could just use a regular expression. Maybe `/(?:\p{ID_Start}|[$_])(?:\p{ID_Continue}|\$)*/gu` or something. In any case, I'm going to close this issue since this is intended behavior, and the existing mangle cache feature is the intended way to do what you're suggesting. The set of reserved properties is entirely up to you and you can customize it to your liking.

**Closed by evanw** 2022-06-20 23:35 UTC
