### ISSUE TITLE
Custom external resolver?

### ISSUE THREAD

**Issue by dipakw** [evanw/esbuild#3112] opened 2023-05-10 08:59 UTC
Hi, I came across a situation where I need a custom external resolver. When I mark a library as an external, it doesn't always mean that I am going to run this bundle in nodejs environment where `require` is available. Look at the code below,

`Please note "I want this section of my own" in the code.`

```js
(() => {
  // ------------------------------------------- //
  // I want this section of my own //
 // ------------------------------------------- //
  var __require = /* @__PURE__ */ ((x) => typeof require !== "undefined" ? require : typeof Proxy !== "undefined" ? new Proxy(x, {
    get: (a, b) => (typeof require !== "undefined" ? require : a)[b]
  }) : x)(function(x) {
    if (typeof require !== "undefined")
      return require.apply(this, arguments);
    throw new Error('Dynamic require of "' + x + '" is not supported');
  });
 // ------------------------------------------- //
// end of the section I want of my own //
  // ------------------------------------------- //

  // src/module.jsx
  var import_jsx_runtime = __require("react/jsx-runtime");
  function SettingsModule() {
    return /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { children: "Settings module" });
  }

  // src/index.jsx
  registerModule("settings-module", SettingsModule);
})();
```
I am gonna have to run this bundle in a browser where require is unavailable. I could do the following to fix my issue:

```js
function require(lib) {
   if ( lib === "react/jsx-runtime" ) {
      return myObject.libs.jsxRuntime;
  }
}
```

I don't want my jsx runtime to be conflicting with others so I stored it as `myObject.libs.jsxRuntime`. So is there any way I could do to inject my external library resolver? A manual way would be editing the bundle, but, is there any better workaround at the moment for my problem?

**Comment by dipakw** [comment] 2023-05-11 14:55
Thanks @evanw I tried creating a plugin but only `module.exports` works. I would  prefer (es6 way) `export default` for some reason but it says **No matching export in "jsx-runtime:react/jsx-runtime" for import "jsx"**. Is there any way to disable this checking or other ways to get `export` worked?

Below is my onLoad part:

```js
build.onLoad({ filter: /.*/, namespace: 'jsx-runtime' }, () => ({
    // Needs matching export
    contents: 'const jsxRuntime = myObject.libs.jsxRuntime; export default  jsxRuntime;',
   // Works
    contents: 'const jsxRuntime = myObject.libs.jsxRuntime; module.exports = jsxRuntime;',
    loader: 'jsx',
}));
```

**Comment by evanw** [comment] 2023-05-11 16:32
You mean like this?

```js
const { jsx } = myObject.libs.jsxRuntime
export { jsx }
```

That's how you do an export the ES6 way.

Using `export default` doesn't work because React's new JSX conventions do not use an export named `default`. This problem has nothing to do with esbuild. If you want to use React's new JSX conventions, then you must export six different exports from three different paths:

```js
import { createElement } from "your-pkg"
import { Fragment, jsx, jsxs } from "your-pkg/jsx-runtime"
import { Fragment, jsxDEV } from "your-pkg/jsx-dev-runtime"
```

These requirements are documented in esbuild's documentation here: https://esbuild.github.io/api/#jsx-import-source. Note that these requirements were determined by React, not esbuild, so the esbuild project is not the right place to discuss these requirements. If you have an issue with how these requirements work, then you should ask React instead.

I'm closing this issue because this is not a bug with esbuild. Custom external resolvers are already possible, and everything is already documented.

**Closed by evanw** 2023-05-11 16:32 UTC
