### ISSUE TITLE
This call to "require" will not be bundled because the argument is not a string literal (surround with a try/catch to silence this warning)

### ISSUE THREAD

**Issue by Valexr** [evanw/esbuild#1132] opened 2021-04-09 16:15 UTC
Can't bundling mongoose module

![Screenshot 2021-04-09 at 19 00 47](https://user-images.githubusercontent.com/5656366/114209836-c1616980-9967-11eb-9139-c735d08b0737.jpg)

**Comment by ggoodman** [comment] 2021-04-09 17:14
Looks like a dupe of #1127.

**Comment by evanw** [comment] 2021-04-10 01:15
Yes, it's not possible to bundle things like this. The warnings are correct. They are warnings instead of errors because your bundle could hypothetically still work if these code paths are not relied upon. But if you need this to work then you're out of luck. You'll either have to run the code unbundled or use another tool instead of esbuild.

**Comment by evanw** [comment] 2021-04-10 04:31
Closing this because this is by design.

**Closed by evanw** 2021-04-10 04:31 UTC

**Comment by Valexr** [comment] 2021-04-10 04:34
Ok. Tx for res @evanw 🤓

**Comment by ndr47** [comment] 2021-06-23 14:12
Does somebody know any workaround to bundle mongoose module with this?
