### ISSUE TITLE
JSON loader uses commonjs

### ISSUE THREAD

**Issue by LarsDenBakker** [evanw/esbuild#344] opened 2020-08-24 06:18 UTC
When using the JSON loader to transform a single file, the output is commonjs format. Setting the `format` option has no effect, I think that's only used when bundling.

See https://repl.it/repls/SuburbanMediumblueLinuxkernel#index.js for a reproduction.

**Comment by evanw** [comment] 2020-09-03 07:11
I think this looks like a duplicate of #109 to me.

**Comment by LarsDenBakker** [comment] 2020-09-03 08:14
Being able to specify the format would solve this, but it seems like it will be some work still.

But I was expecting that loaders for non-js files would return an es module.

**Comment by evanw** [comment] 2020-09-07 00:24
Closing as a duplicate of #109 (which was just implemented).

**Closed by evanw** 2020-09-07 00:24 UTC
