### ISSUE TITLE
Fail to npm install greater version than esbuild@0.14.28

### ISSUE THREAD

**Issue by Drozerah** [evanw/esbuild#2206] opened 2022-04-23 11:48 UTC
Fail to npm install greater version than esbuild@0.14.28, last valid install esbuild@0.14.27

node version => v16.14.2
npm version => 8.7.0
macOs => 10.12.6

 ```bash
MBPdeAYAMDEV:my-app ayamdev$ npm i -D esbuild@0.14.28
npm ERR! code 1
npm ERR! path /Users/ayamdev/Desktop/my-app/node_modules/esbuild
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! node:child_process:828
npm ERR!     err = new Error(msg);
npm ERR!           ^
npm ERR! 
npm ERR! Error: Command failed: /Users/ayamdev/Desktop/my-app/node_modules/esbuild/bin/esbuild --version
npm ERR! dyld: Symbol not found: _SecTrustEvaluateWithError
npm ERR!   Referenced from: /Users/ayamdev/Desktop/my-app/node_modules/esbuild/bin/esbuild
npm ERR!   Expected in: flat namespace
npm ERR! 
npm ERR! 
npm ERR!     at checkExecSyncError (node:child_process:828:11)
npm ERR!     at Object.execFileSync (node:child_process:866:15)
npm ERR!     at validateBinaryVersion (/Users/ayamdev/Desktop/my-app/node_modules/esbuild/install.js:101:32)
npm ERR!     at /Users/ayamdev/Desktop/my-app/node_modules/esbuild/install.js:251:5 {
npm ERR!   status: null,
npm ERR!   signal: 'SIGABRT',
npm ERR!   output: [
npm ERR!     null,
npm ERR!     Buffer(0) [Uint8Array] [],
npm ERR!     Buffer(171) [Uint8Array] [
npm ERR!       100, 121, 108, 100,  58,  32,  83, 121, 109,  98, 111, 108,
npm ERR!        32, 110, 111, 116,  32, 102, 111, 117, 110, 100,  58,  32,
npm ERR!        95,  83, 101,  99,  84, 114, 117, 115, 116,  69, 118,  97,
npm ERR!       108, 117,  97, 116, 101,  87, 105, 116, 104,  69, 114, 114,
npm ERR!       111, 114,  10,  32,  32,  82, 101, 102, 101, 114, 101, 110,
npm ERR!        99, 101, 100,  32, 102, 114, 111, 109,  58,  32,  47,  85,
npm ERR!       115, 101, 114, 115,  47, 116, 104, 111, 109,  97, 115, 103,
npm ERR!        97, 117, 116, 104, 105, 101, 114,  47,  68, 101, 115, 107,
npm ERR!       116, 111, 112,  47,
npm ERR!       ... 71 more items
npm ERR!     ]
npm ERR!   ],
npm ERR!   pid: 12694,
npm ERR!   stdout: Buffer(0) [Uint8Array] [],
npm ERR!   stderr: Buffer(171) [Uint8Array] [
npm ERR!     100, 121, 108, 100,  58,  32,  83, 121, 109,  98, 111, 108,
npm ERR!      32, 110, 111, 116,  32, 102, 111, 117, 110, 100,  58,  32,
npm ERR!      95,  83, 101,  99,  84, 114, 117, 115, 116,  69, 118,  97,
npm ERR!     108, 117,  97, 116, 101,  87, 105, 116, 104,  69, 114, 114,
npm ERR!     111, 114,  10,  32,  32,  82, 101, 102, 101, 114, 101, 110,
npm ERR!      99, 101, 100,  32, 102, 114, 111, 109,  58,  32,  47,  85,
npm ERR!     115, 101, 114, 115,  47, 116, 104, 111, 109,  97, 115, 103,
npm ERR!      97, 117, 116, 104, 105, 101, 114,  47,  68, 101, 115, 107,
npm ERR!     116, 111, 112,  47,
npm ERR!     ... 71 more items
npm ERR!   ]
npm ERR! }
```

**Comment by evanw** [comment] 2022-04-23 11:58
Closing as a duplicate of #2183.

[Go's official website](https://go.dev/dl/) says that Go requires macOS 10.13 or later, and you are using macOS 10.12. So you are using an unsupported platform. Your options are to either update your OS, try to build esbuild for yourself using an older version of the Go compiler, use the WebAssembly version of esbuild, or to use another tool instead.

**Closed by evanw** 2022-04-23 11:58 UTC

**Comment by DespertaWeb** [comment] 2022-06-01 08:47
how did you manage to fix it? @Drozerah ?
