### ISSUE TITLE
Load separate builds based on the environment

### ISSUE THREAD

**Issue by ad1992** [evanw/esbuild#3567] opened 2023-12-28 12:49 UTC
I have two separate ESM builds for development and production, is there a way to communicate which build should be loaded based on env ?
eg webpack supports an  [exports field](https://webpack.js.org/guides/package-exports/#providing-devtools-or-production-optimizations), is there something similar in esbuild as well ?

The reason I am having separate builds is the dev build has source maps and is unminified where as prod build is minified.

**Comment by evanw** [comment] 2023-12-28 14:04
The `exports` field is not just for Webpack, esbuild supports it too. For example: https://esbuild.github.io/api/#conditions. Did you try it?

**Comment by ad1992** [comment] 2023-12-29 06:50
Hi @evanw yes I tried with the exports field, it loads the separate builds however the source maps aren't loaded for the dev build, do I need to specify in exports for sourcemaps?

On other side, any plans to move the docs to [docusaurus](https://docusaurus.io/) or something similar so you get the features like searching, version etc out of the box ?

**Comment by evanw** [comment] 2023-12-29 18:22
> the source maps aren't loaded for the dev build, do I need to specify in exports for sourcemaps?

There's no way to answer this without a way to reproduce the issue, sorry. The instructions you deleted when you created this issue said this:

> When reporting a bug or requesting a feature, please do the following:
>
> * Provide a way to reproduce the issue. The best way to do this is to demonstrate the issue on the playground (https://esbuild.github.io/try/) and paste the URL here. A link to a minimal code sample with instructions for how to reproduce the issue may also work. Issues without a way to reproduce them may be closed.

Source maps are supposed to be automatically picked up based on the presence of the `//# sourceMappingURL=` comment somewhere in the source code. I can only investigate why it's not working if I have something to investigate.

> On other side, any plans to move the docs to [docusaurus](https://docusaurus.io/) or something similar so you get the features like searching, version etc out of the box ?

I currently have no plans to do that. Everything is deliberately on one page so you can use your browser's built-in search feature to search through the documentation.

**Comment by evanw** [comment] 2024-01-18 23:21
I'm closing this issue because a way to produce it was not provided. We can reopen it later if there's more information.

**Closed by evanw** 2024-01-18 23:21 UTC
Labels: unactionable
