### ISSUE TITLE
bundle only css produce empty .js file

### ISSUE THREAD

**Issue by bes-internal** [evanw/esbuild#3921] opened 2024-09-24 17:24 UTC
1 - only css
--

I wish bundle only css and run:
```
echo " import './some.css'; " | esbuild \
--log-level=info \
--bundle \
--minify \
--platform=browser \
--format=iife \
--outdir=dist/ \
```

That produce `dist/stdin.css`  as expected and `dist/stdin.js` with content:
```
(()=>{})();
```

**Expected**:
no dist/stdin.js if there is no content of js

2 - only css outfile
--
I wish bundle only css with use `--outfile` for that and run:
```
echo " import './some.css'; " | esbuild \
--log-level=info \
--bundle \
--minify \
--platform=browser \
--format=iife \
--outfile=final.css \
```

That produce error:
```
✘ [ERROR] Two output files share the same path but have different contents: css.css
```
because outfile means one file but there is css content and **empty** js content!
  
**Expected**:

ebsuild produce only final.css if no js bundle output

3 - empty
--
emtpy input:

```
echo "  " | esbuild \
--log-level=info \
--bundle \
--minify \
--platform=browser \
--format=iife \
```
Expected - empty, but produce - `(()=>{})();`

**Comment by evanw** [comment] 2024-09-24 19:00
Instead of `echo " import './some.css'; " | esbuild ...` you can use either `cat some.css | esbuild --loader=css ...` or even just `esbuild some.css ...`.

**Comment by evanw** [comment] 2024-09-27 14:42
I'm closing this issue as invalid. You are getting a .js file because you are bundling JavaScript. This is expected behavior. You have to bundle only CSS input to produce only CSS output (as described above).

**Closed by evanw** 2024-09-27 14:42 UTC
