### ISSUE TITLE
Does not support typescript@5 decorator

### ISSUE THREAD

**Issue by sirenkovladd** [evanw/esbuild#3309] opened 2023-08-11 22:08 UTC
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html#decorators

small reproduce: https://stackblitz.com/edit/node-ebpglb

```ts
> esbuild index.ts

function wrap(value, ctx) {
  console.log("Wrapping", value, ctx);
  ctx.addInitializer(function W() {
    console.log("Initialized", this, value);
  });
}
class A {
  @wrap
  a = 1;
}
const a = new A();
```

**Comment by evanw** [comment] 2023-08-11 22:10
Closing as a duplicate of #104.

**Closed by evanw** 2023-08-11 22:10 UTC
