### ISSUE TITLE
Order of class property initialization in typescript files

### ISSUE THREAD

**Issue by Akxe** [evanw/esbuild#3104] opened 2023-05-05 13:03 UTC
This code will cork when compiled using typescript as typescript reorders
```typescript
const invertColor = hex => hex;

export class Motive {
  readonly hexCopy = invertColor(this.hex); // Error `this.hex` is undefined

  constructor(public readonly hex: string ) { }
}
```

This will work as expected
```typescript
const invertColor = hex => hex;

export class Motive {
  readonly hexCopy: string;

  constructor(public readonly hex: string ) {
    this.hexCopy = invertColor(this.hex);
  }
}
```

This surprisingly works too:
```typescript
const invertColor = hex => hex;

export class Motive {
  readonly hexCopy = this.hex;

  constructor(public readonly hex: string ) { }
}
```

The issue is, when a property is used as function parameter in declared property inside a class.

*The code above is simplification*

**Comment by evanw** [comment] 2023-05-05 20:19
You haven't provided your settings so it's impossible to say for certain, but I suspect you are encountering TypeScript's `useDefineForClassFields` behavior.

With [`useDefineForClassFields: false`](https://www.typescriptlang.org/play?target=99#code/MYewdgzgLgBAlmAbgUwE5QMIgDYlTAXhgAtkAPQgPhPIG4AoYbAQwghgFkQo4UYBvejBipkzACbhsATxpksAB1lEEKdFlyoAFFGJwIAOlJkAlEJihIUVAFdgUPFoU2ARtjjARYyWBlyAXDDQqAgA5jAmAjAAvvSxlhA4yAa4oVpgyADunNy8yFoA5MwuwAUmRuSK0mZAA) (i.e. legacy TypeScript-style class fields) you will get the string. With [`useDefineForClassFields: true`](https://www.typescriptlang.org/play?useDefineForClassFields=true&target=99#code/MYewdgzgLgBAlmAbgUwE5QMIgDYlTAXhgAtkAPQgPhPIG4AoYbAQwghgFkQo4UYBvejBipkzACbhsATxpksAB1lEEKdFlyoAFFGJwIAOlJkAlEJihIUVAFdgUPFoU2ARtjjARYyWBlyAXDDQqAgA5jAmAjAAvvSxlhA4yAa4oVpgyADunNy8yFoA5MwuwAUmRuSK0mZAA) (i.e. modern JavaScript-style class fields) you will get undefined. This is how the TypeScript team has decided that TypeScript should behave, and this is what esbuild replicates. These links are to TypeScript's playground on TypeScript's website. You can click **Run** in the playground to see how they behave.

Make sure specify `useDefineForClassFields` in `tsconfig.json` to get the effect you want, and make sure esbuild is reading `tsconfig.json` during your build. You can read more about this setting in [the release notes from TypeScript 3.7](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#the-usedefineforclassfields-flag-and-the-declare-property-modifier).

**Comment by Akxe** [comment] 2023-05-05 20:51
I used it with angular's settings... Angular documentation did not mention that. It did talk about default export but not this... I suppose this might be a more common problem...

PS: ESBuild should then also fain in the 3rd code snippet, as typescript does. Or neither...

**Comment by hyrious** [comment] 2023-05-07 03:46
I guess angular has set that config to `false` by default: https://angular.io/guide/typescript-configuration where your first example would work as expected.

**Comment by Akxe** [comment] 2023-05-07 11:31
They should mention this in the esbuild preview documentation page. Same as the default export module…

**Comment by evanw** [comment] 2023-05-14 14:38
I'm closing this as esbuild is working as intended here.

**Closed by evanw** 2023-05-14 14:38 UTC
