### ISSUE TITLE
Class constructor parameter is being renamed when its type and name are identical

### ISSUE THREAD

**Issue by Newbie012** [evanw/esbuild#2244] opened 2022-05-11 09:27 UTC
Given the following source code:
```ts
class OtherClass {}

class MyClass {
  constructor(private OtherClass: OtherClass) {}
}
```

it gets compiled to:

```js
class OtherClass {
}
class MyClass {
  constructor(OtherClass2) {
    this.OtherClass = OtherClass2;
  }
}
```

As you can see, `OtherClass` parameter has been renamed to `OtherClass2`. Changing the parameter to have a different name than its class name, seems to be valid:

```diff
- constructor(private OtherClass: OtherClass) {}
+ constructor(private otherClass: OtherClass) {}
```

```js
class OtherClass {
}
class MyClass {
  constructor(otherClass) {
    this.otherClass = otherClass;
  }
}
```

While it shouldn't affect anything in runtime (since it sets the parameter inside the constructor), it does messes up dependency injection (that injects by parameter name).

I'm not sure how exactly esbuild works behind the scene, but since the type annotation is dropped in transpilation, should there be any reason to rename the parameter?

**Comment by hyrious** [comment] 2022-05-11 09:45
There's nothing to do with types, it is the same as this [example](https://hyrious.me/esbuild-repl/?version=0.14.38&mode=transform&input=var+A+%3D+1%0Afunction+f%28A%29+%7B%7D):

```js
var A = 1
function f(A) {} // "A" will be renamed to "A2"
```

**Comment by Newbie012** [comment] 2022-05-11 09:55
@hyrious Thanks for the clarification. In any case, in your example, it would make sense to rename the parameter, since `A` of `f` and global `A` are colliding.

what about [this](https://hyrious.me/esbuild-repl/?version=0.14.38&mode=transform&input=import+%7B+A+%7D+from+%22A%22%3B%0Afunction+f%28A%3A+A%29+%7B%7D&options=--loader%3Dts)?

```ts
import { A } from "A";
function f(A: A) {}
```

which is being transpiled to:
```js
function f(A2) {}
```

**Comment by evanw** [comment] 2022-05-11 18:15
This is not a bug because esbuild's output is equivalent to the original code. Closing this issue as invalid.

**Closed by evanw** 2022-05-11 18:15 UTC
