### ISSUE TITLE
Bundling with MJS and CJS sources produces unexpected behaviour

### ISSUE THREAD

**Issue by pfumagalli** [evanw/esbuild#2142] opened 2022-03-29 23:04 UTC
I observed a somewhat difference of behaviours when bundling (vs simply transpiling) a TypeScript source importing a dependency providing _both_ MJS and CJS formats.

To reduce the case to the minimum, this is what I'm working with:

##### ./node_modules/dependency/package.json
```json
{
  "name": "one",
  "main": "./index.cjs",
  "module": "./index.mjs",
  "exports": {
    "import": "./index.mjs",
    "require": "./index.cjs"
  },
  "type": "module"
}
```

##### ./node_modules/dependency/index.cjs
```js
const value = 'this is cjs'
module.exports = { value }
```

##### ./node_modules/dependency/index.mjs
```js
const value = "this is mjs"
export { value }
```

Just to verify that everything is working all right, I ran this through Node manually:

##### as a simple CJS

```
$ node -p 'require("dependency").value'
this is cjs
```

##### as a simple ESM

```
$ node -e 'import * as d from "dependency"; console.log(d.value)' --input-type=module
this is esm
```

When running through `esbuild` though, I'm finding an odd behaviour I wouldn't expect. I have a very simple file `runme.ts` containing the following:

```ts
import * as dependency from 'dependency'
console.log(dependency.value)
```

When running as CJS (_without bundling_) everything works as expected:

```
$ esbuild --platform=node --format=cjs runme.ts | node
this is cjs
```

But when the same file is _bundled_ (still, in CJS format), the MJS is bundled instead:

```
$ esbuild --platform=node --format=cjs --bundle runme.ts | node
this is mjs
```

I am sure I'm doing something wrong, but I would have expected the _bundled_ source to be the CJS one.

**Comment by pfumagalli** [comment] 2022-03-29 23:05
For the records, when using MJS everything is normal:

```
$ esbuild --platform=node --format=esm runme.ts | node --input-type=module
this is mjs
$ esbuild --platform=node --format=esm --bundle runme.ts | node --input-type=module
this is mjs
```

**Comment by pfumagalli** [comment] 2022-03-29 23:09
Attached is a little tarball with all the above mentioned files for convenience...

[sample.tar.gz](https://github.com/evanw/esbuild/files/8375499/sample.tar.gz)

**Comment by pfumagalli** [comment] 2022-03-29 23:13
And as a side note, running transpiler and bundler in succession produces the _correct_ (or whatever I think might be correct) output...

```
$ esbuild --format=cjs --bundle runme.ts | node
this is mjs
$ esbuild --format=cjs runme.ts | esbuild --bundle | node
this is cjs
```

**Comment by pfumagalli** [comment] 2022-03-30 09:17
Thanks @hyrious, understood...

For now the double-pipe into esbuild (one for transpiling, and one for bundling) works for me, but as more and more modules start exposing both CJS and ESM I can see that this behavioural difference in bundling vs transpiling might create some problems.

For example, let's assume we have two modules:

* The module `first-dependency` is a mixed CJS/MJS (similar to what's described above) exporting a `class ParentClass`
* The module `another-dependency` is a plain CJS module, importing `ParentClass` from `first-dependency`and exporting a `class ChildClass extends ParentClass`
* My code imports `ParentClass` from `first-dependency`, and `ChildClass` from `another-dependency`

Simple example:

```ts
import { ParentClass} from 'first-dependency'
import { ChildClass } from 'another-dependency'

const child = new ChildClass()

console.log('instanceof =', child instanceof ParentClass)
console.log('   => parent type =', new ParentClass().type)
console.log('   => child  type =', child.type)
```

When *not bundling* instances of `ChildClass` are `instanceof ParentClass`, but *when bundling* they are not.

The `first-dependency` gets bundled twice, so the prototype chain will get wonky, and this could create issues, as there's a completely different runtime behaviour between the two versions...

```
$ esbuild --platform=node --format=cjs runme.ts | node
instanceof = true
   => parent type = this is cjs
   => child  type = this is cjs

$ esbuild --platform=node --format=cjs --bundle runme.ts | node
instanceof = false
   => parent type = this is mjs
   => child  type = this is cjs

$ esbuild --platform=node --format=cjs runme.ts | esbuild --bundle | node
instanceof = true
   => parent type = this is cjs
   => child  type = this is cjs
```

Again, attached is a simple tarball with the code highlighting this difference of behaviour...

[sample-instanceof.tar.gz](https://github.com/evanw/esbuild/files/8378995/sample-instanceof.tar.gz)

**Comment by hyrious** [comment] 2022-03-30 09:56
I see, however esbuild is still doing right here -- it follows the same logic with node.js. Here's a quick test about that:

```js
// a.mjs
import { Child } from "child";
import { Parent } from "parent";

console.log(new Child() instanceof Parent);

// node_modules/child/index.js
const { Parent } = require("parent")

class Child extends Parent {}

module.exports = { Child }

// node_modules/child/package.json
{
  "name": "child",
  "main": "./index.js"
}

// node_modules/parent/index.cjs
class Parent {}

module.exports = {
  Parent
}

// node_modules/parent/index.mjs
export class Parent {}

// node_modules/parent/package.json
{
  "name": "parent",
  "exports": {
    "import": "./index.mjs",
    "require": "./index.cjs"
  }
}
```

Running `node a.mjs` will prints `false`. This has the same reason as I said before -- `import "parent"` (in a.mjs) and `require("parent")` (in child/index.js) will resolve to different files.

```bash
> node a.mjs
false
> esbuild a.mjs --bundle --platform=node | node
false
```

If you want to dedupe a specific package, you can write a [plugin](https://esbuild.github.io/plugins/#on-resolve) to resolve the common dependency to the same file, like such:

```js
var dedup_parent = {
  name: 'dedup_parent',
  setup({ onResolve }) {
    var path = require.resolve('parent') // path/to/parent/index.cjs
    onResolve({ filter: /^parent$/ }, () => ({ path }))
  }
}
```

**Comment by Hideman85** [comment] 2022-07-11 09:52
I have a simillar issue, I'm using prosemirror in my library and I'm having both bundled:
```js
...
// node_modules/prosemirror-model/dist/index.cjs
var require_dist12 = __commonJS({
  "node_modules/prosemirror-model/dist/index.cjs"(exports) {
...
// node_modules/prosemirror-model/dist/index.js
function findDiffStart(a, b, pos)
...
```

I do not quite get what is the workaround :slightly_frowning_face:

**Comment by hyrious** [comment] 2022-07-11 10:18
@Hideman85 You can write a plugin to deduplicate that library:

```js
var dedup_prosemirror_model = {
  name: 'dedup:prosemirror-model',
  setup({ onResolve }) {
    // force resolve to the esm file
    var path = require.resolve('prosemirror-model').replace('index.cjs', 'index.js')
    onResolve({ filter: /^prosemirror-model$/ }, args => {
      return { path }
    })
  }
}
```

**Comment by Hideman85** [comment] 2022-07-11 10:33
I found out that telling esBuild mainFields to module,main solve the issue of treeshaking as [mentioned in the doc](https://esbuild.github.io/api/#platform)
It does look to works fine for me :slightly_smiling_face:

**Comment by nkeynes** [comment] 2022-07-28 05:59
I've run into this one as well, and while we were able to work around it with explicit resolutions I can see this being a pain point in future -
a) there's no obvious indication that a module has had multiple versions imported unless it breaks completely (as seen with prosemirror)

**Comment by evanw** [comment] 2022-07-28 06:46
I’m going to close this because esbuild is working as intended. Node made a [very exact specification](https://nodejs.org/api/esm.html#resolver-algorithm) for how their package format behaves, which esbuild follows. They have deliberately designed the dual-package hazard into their system and this is the result. It’s very unfortunate and it requires a lot of work to work around (either on the package authoring side or on the package consumption side) but that’s not esbuild’s fault.

**Closed by evanw** 2022-07-28 06:46 UTC
