### ISSUE TITLE
Ionic Integration

### ISSUE THREAD

**Issue by Apro123** [evanw/esbuild#434] opened 2020-10-05 22:55 UTC
Is there a way to use this esbuild in ionic (Angular) projects?

**Comment by evanw** [comment] 2020-10-06 00:12
I don't know anything about this framework myself, so I can't say. Perhaps you can investigate this and report back?

FWIW this may be a duplicate of #42, which was someone asking about Angular. There I said that esbuild doesn't support Angular applications because Angular relies on a custom compiler instead of standard JavaScript modules. However, I'm not sure what an Ionic project is or how it relates to Angular, so it's possible that the situation here is different.

**Comment by evanw** [comment] 2020-10-14 05:30
I'm going to close this as a duplicate of #42. I'm unfamiliar with Angular but I suspect the answer is no. Feel free to comment with more information if you think otherwise.

**Closed by evanw** 2020-10-14 05:30 UTC
