### ISSUE TITLE
 Dynamic require of "https" is not supported

### ISSUE THREAD

**Issue by bharathimarella** [evanw/esbuild#3815] opened 2024-06-28 20:22 UTC
I'm getting  **Dynamic require of "https" is not supported** error when i try to turn a js file to generate cypress reports.I see this is related to esbuild .How to fix this issue ?

**Comment by evanw** [comment] 2024-06-29 14:25
You will probably find your answer by reading the documentation:

* https://esbuild.github.io/api/#non-analyzable-imports
* https://esbuild.github.io/getting-started/#bundling-for-node

**Comment by evanw** [comment] 2024-06-30 17:49
I'm closing this because it's not a bug with esbuild, and the ways to avoid this problem are already documented in the "getting started" instructions.

**Closed by evanw** 2024-06-30 17:49 UTC
