### ISSUE TITLE
Irrelevant files slow down builds

### ISSUE THREAD

**Issue by MathijsMeijer** [evanw/esbuild#2995] opened 2023-03-15 17:24 UTC
Hey Evan, thanks for the great tool! I'm trying it out on a project with thousands of modules and I got its build time down from 15 seconds to 300 milliseconds with near feature parity. Part of this build is a directory containing ±100 module repositories, which I included in the `nodePaths` option.

At first I used a fresh archive copy of these repositories, resulting in the 300 millisecond build time. When I replaced these with fresh clones I noticed that the build time went up to about 400 milliseconds. Deleting their Git directories one by one gradually brought the build time back down. Inversely, I also tried older, up to date clones containing more local Git history and the build time went up to about 1400 milliseconds. In all these scenarios the actual modules to include were the same.

I haven’t tested whether this is specific to Git directories or can also be caused by e.g. having large amounts of unit test fixtures. I _think_ I noticed something similar when the repositories contained large `node_module` directories.  As far as I can tell I haven’t indicated to esbuild that the files contained therein are relevant for the build (nor that they’re irrelevant, I don’t believe there’s an option for that). Do you have an idea about what might be the issue here? Have I misconfigured something?

**Comment by evanw** [comment] 2023-03-15 21:53
Please provide a self-contained example that reproduces the problem.

**Comment by MathijsMeijer** [comment] 2023-03-16 17:00
I traced the issue back to an eager directory walker used in a plugin. Sorry for the inconvenience. If you can reliably measure build time spent in plugins then it would be useful to have a (limited) breakdown of that in the logs, I think.

**Comment by evanw** [comment] 2023-03-17 03:20
> If you can reliably measure build time spent in plugins then it would be useful to have a (limited) breakdown of that in the logs, I think.

I don't think it's possible to do that reliably unfortunately. Plugins are asynchronous so their evaluations overlap and can potentially be split across many call stacks. It's theoretically possible to track this with very invasive changes such as trying to hook into all asynchronous entry points in the JS VM (e.g. `setTimeout`, `fs` callbacks, etc.) but I don't think that's something esbuild should attempt to do.

**Comment by evanw** [comment] 2023-03-17 03:21
I'm closing this issue because it's not a problem with esbuild.

**Closed by evanw** 2023-03-17 03:21 UTC
