### ISSUE TITLE
Class injected into the bundle after its use.

### ISSUE THREAD

**Issue by vovacodes** [evanw/esbuild#460] opened 2020-10-14 16:38 UTC
I ran into the following issue. My files look similar to this:
```
// A.ts
import { ClassB } from "./B.ts"

class ClassA { 
  private b = new ClassB()
}

export const instanceA = new ClassA()


// B.ts
export ClassB {}
```

The resulting bundle has them injected in the same order as above which causes `ReferenceError: Cannot access 'ClassB' before initialization`. There are no circular references between the modules, I double checked that. Unfortunately I cannot share the exact code but let me know if more details are needed.

**Comment by evanw** [comment] 2020-10-14 22:22
Can you provide some sample code to reproduce the issue? I tried bundling `A.ts` in your example and (after fixing `B.ts` to contain `export class ClassB {}`) I get `B.ts` coming before `A.ts`, so I am unable to reproduce the issue myself.

**Comment by zmitry** [comment] 2020-10-15 11:04
I've seen similar issue but with react imports but I didn't manage to reproduce it

**Comment by brianmhunt** [comment] 2020-11-06 13:22
@khangdinhmb This looks like the problem we encountered but I can't reproduce it either with `esbuild^0.8.0`.  Can you still reproduce it?

**Comment by evanw** [comment] 2020-11-18 03:39
It sounds like #542 is the same issue. Can I close this as a duplicate of that since that has a way to reproduce the problem?

**Comment by evanw** [comment] 2020-11-25 09:47
I'm going to close this as #542 has been fixed and there's no way to reproduce this. Please let me know if you experience any problems like this with the latest release.

**Closed by evanw** 2020-11-25 09:47 UTC
