### ISSUE TITLE
Regression: cjs bundling in 0.14.27 broke skypack for @faker-js/faker

### ISSUE THREAD

**Issue by Shinigami92** [evanw/esbuild#2114] opened 2022-03-19 11:26 UTC
Continue of issue report: https://github.com/faker-js/faker/issues/635

Please compare:

https://unpkg.com/@faker-js/faker@6.0.0/dist/cjs/index.js (bundled with esbuild 0.14.27)

with 

https://unpkg.com/@faker-js/faker@6.0.0-beta.0/dist/cjs/index.js (bundled with esbuild 0.14.24)

**Comment by Shinigami92** [comment] 2022-03-24 14:52
I assume that skypack does something like trying to optimize the package that is delivered.
https://cdn.jsdelivr.net/npm/@faker-js/faker does not do that, and that is working just fine.
So it may be that the issue (for cjs) is not directly by esbuild but skypack 🤔 
But before esbuild `< 0.14.27` it was working fine´. So maybe something like a flag that skypack reads was removed.

**Comment by evanw** [comment] 2022-03-27 02:13
From https://github.com/skypackjs/skypack-cdn/issues/269 it looks like perhaps the issue is that Skypack assumes there is always a `default` export from CommonJS modules that have been compiled from ES modules? That was previously true with esbuild due to what was considered an esbuild bug, but that's no longer true now that the bug in esbuild has been fixed.

One possible workaround could be for them to export the default export using `import * as obj from` and either `export default obj.default` or `export default obj` which is mostly equivalent (it's not equivalent for a mutable default export, but that probably isn't relevant for real-world code). There may be other workarounds depending on how Skypack works. Not sure. Anyway, this looks like something that needs to be fixed in Skypack, not in esbuild.

I'm closing this issue as "working as intended" since this bug fix has brought esbuild's behavior inline with the rest of the ecosystem (see https://github.com/evanw/bundler-esm-cjs-tests).

**Closed by evanw** 2022-03-27 02:13 UTC

**Comment by Shinigami92** [comment] 2022-03-27 10:04
Thanks for your effort, this is really good to know :+1: 
Keep up with your great projects :slightly_smiling_face:
