### ISSUE TITLE
Live Reload perpetual loop.

### ISSUE THREAD

**Issue by mctrafik** [evanw/esbuild#3075] opened 2023-04-20 21:04 UTC
Trying to setup live reloading according to the guides:

```
    const app = await context(clientBuildOptions);
    await app.watch();
    const server = await app.serve({ ..});
```

But running into a loop here because per [documentation](https://esbuild.github.io/api/#build):

`[Serve mode](https://esbuild.github.io/api/#serve) starts a local development server that serves the results of the latest build. Incoming requests automatically start new builds so your web app is always up to date when you reload the page in the browser. Here's an example:`

My compilation takes `> 1 second`.

So it goes:

- I load the page on localhost
- A rebuild gets triggered
- Page loads, starts listening on `/esbuild` for `change` events
- Rebuild finishes. Publishes a change on `/esbuild`
- My code picks it up and does `location.reload()` as in the docs
- Page loads on localhost.
- ...et infinity.

Now in reality this only happens 2-15 times in a row because sometimes the page takes longer to load than it does to compile and the loop stops.

Can we have a flag to disable the `rebuild on incoming requests` feature?

**Comment by evanw** [comment] 2023-04-22 20:36
> Rebuild finishes. Publishes a change on `/esbuild`

That's not exactly what happens. A change event is only generated if the output has changed from the previous build's output. So causing a new build to happen without changing any of the input files since the previous build should not generate a new change event. Something else is likely going on here.

If you are using esbuild such that your build output is always different every time you do a build (even when the input hasn't changed), then the problem is likely that you have some plugin that's injecting a source of non-determinism. The solution would be to fix or remove that plugin.

> Webpack picks it up and does `location.reload()`

Why are you mentioning Webpack? This repository has nothing to do with Webpack. Perhaps what you are experiencing is a bug with Webpack instead?

> Can we have a flag to disable the `rebuild on incoming requests` feature?

Having this is the point of using a development server that's integrated into esbuild. If you don't need this feature, then you are free to use any development server instead of esbuild. Other development servers are likely much more useful and flexible than esbuild's built-in one.

Or, if you really want to, you can also use esbuild as a plain development server without it building anything on page loads. You can do that like this:

```js
// Serve a directory with esbuild
const server = await context({}).then(c => c.serve({ servedir: '.' }))
```

**Comment by mctrafik** [comment] 2023-04-24 06:47
Thank you for the reply.

UIpdated post s/webpack/esbuild. Habit. No, not using other frameworks. Just one esbuild.ts file.

But yeah, I guess the output is different. 🤷🏻 

I went w/ the write my own serving server as a plugin because I do need it to respond to the watcher. Had to implement the `/esbuild` endpoint, too in case this bug get fixed.

**Comment by evanw** [comment] 2023-05-13 16:23
I'm closing this issue because esbuild is working as intended (live reload reloads when the output changes). Non-determinism due to a plugin is a problem with that plugin, not with esbuild.

**Closed by evanw** 2023-05-13 16:23 UTC
