### ISSUE TITLE
Q: How do use esbuild-sass-plugin with Go and only css aggregation and minify?

### ISSUE THREAD

**Issue by idc77** [evanw/esbuild#2133] opened 2022-03-26 16:25 UTC
I'm trying to use https://github.com/glromeo/esbuild-sass-plugin with Go.

```go
		var sassPlugin = api.Plugin{
			Name:  "esbuild-sass-plugin",
			Setup: nil,
		}
		result := api.Build(api.BuildOptions{
			EntryPoints:       []string{"ssr/scripts/app.jsx"},
			Bundle:            true,
			MinifyWhitespace:  true,
			MinifyIdentifiers: true,
			MinifySyntax:      true,
			Engines: []api.Engine{
				{api.EngineChrome, "58"},
				{api.EngineFirefox, "57"},
				{api.EngineSafari, "11"},
				{api.EngineEdge, "16"},
			},
			Write:   true,
			Plugins: []api.Plugin{sassPlugin},
		})

		if len(result.Errors) > 0 {
			spew.Dump(result.Errors)
			os.Exit(1)
		}
```
results in
```
ssr called
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xed34c9]

goroutine 1 [running]:
github.com/evanw/esbuild/pkg/api.loadPlugins(0xc0001d82c0, {0x129bc40?, 0xc0000473c0}, {0xc000275b20, 0xc000116ba0, 0xc000116bb8, 0xc00011a9a0, 0x6}, 0xc0000ced80)
        /home/darko/go/pkg/mod/github.com/evanw/esbuild@v0.14.28/pkg/api/api_impl.go:1818 +0x629
github.com/evanw/esbuild/pkg/api.buildImpl({0x0, 0x0, 0x0, 0x0, {0x0, 0x0}, 0x0, 0x0, {0xc0000cecc0, 0x4, ...}, ...})
        /home/darko/go/pkg/mod/github.com/evanw/esbuild@v0.14.28/pkg/api/api_impl.go:812 +0x45e
github.com/evanw/esbuild/pkg/api.Build(...)
        /home/darko/go/pkg/mod/github.com/evanw/esbuild@v0.14.28/pkg/api/api.go:370
git.icod.de/dalu/blogs/cmd.glob..func3(0x18f6400?, {0x10ae500?, 0x0?, 0x0?})
        /home/darko/go/src/git.icod.de/dalu/blogs/cmd/ssr.go:23 +0x1f8
github.com/spf13/cobra.(*Command).execute(0x18f6400, {0x1938360, 0x0, 0x0})
        /home/darko/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x18f5f00)
        /home/darko/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /home/darko/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
git.icod.de/dalu/blogs/cmd.Execute()
        /home/darko/go/src/git.icod.de/dalu/blogs/cmd/root.go:46 +0x25
main.main()
        /home/darko/go/src/git.icod.de/dalu/blogs/main.go:21 +0x17

Process finished with the exit code 2
```

seems like it doesn't know where to find the plugin.

What would be the correct way to load and use the plugin?
I'm genuinely stuck.

As an alternative I'd like to bundle all css files that I import in a main.css
```css
@import "~@material/top-app-bar";
@import "~@material/icon-button";
```
but that too results in errors.

```
ssr called
([]api.Message) (len=2 cap=2) {
 (api.Message) {
  PluginName: (string) "",
  Text: (string) (len=42) "Could not resolve \"~@material/top-app-bar\"",
  Location: (*api.Location)(0xc0002b5140)({
   File: (string) (len=27) "ssr/scripts/styles/main.css",
   Namespace: (string) "",
   Line: (int) 1,
   Column: (int) 8,
   Length: (int) 24,
   LineText: (string) (len=33) "@import \"~@material/top-app-bar\";",
   Suggestion: (string) ""
  }),
  Notes: ([]api.Note) (len=1 cap=1) {
   (api.Note) {
    Text: (string) (len=119) "You can mark the path \"~@material/top-app-bar\" as external to exclude it from the bundle, which will remove this error.",
    Location: (*api.Location)(<nil>)
   }
  },
  Detail: (interface {}) <nil>
 },
 (api.Message) {
  PluginName: (string) "",
  Text: (string) (len=42) "Could not resolve \"~@material/icon-button\"",
  Location: (*api.Location)(0xc0002b51a0)({
   File: (string) (len=27) "ssr/scripts/styles/main.css",
   Namespace: (string) "",
   Line: (int) 2,
   Column: (int) 8,
   Length: (int) 24,
   LineText: (string) (len=33) "@import \"~@material/icon-button\";",
   Suggestion: (string) ""
  }),
  Notes: ([]api.Note) (len=1 cap=1) {
   (api.Note) {
    Text: (string) (len=119) "You can mark the path \"~@material/icon-button\" as external to exclude it from the bundle, which will remove this error.",
    Location: (*api.Location)(<nil>)
   }
  },
  Detail: (interface {}) <nil>
 }
}

Process finished with the exit code 1
```
Is there a way to define a resource root for ~ css imports?

**Comment by evanw** [comment] 2022-03-26 18:32
> ```go
> Setup: nil,
> ```

You are giving esbuild a nil pointer as a callback, which is why it's crashing. Also [esbuild-sass-plugin](https://github.com/glromeo/esbuild-sass-plugin) is a JavaScript plugin, not a Go plugin. You can't use JavaScript plugins from Go. If you want to use it, I recommend using esbuild's JavaScript API instead of esbuild's Go API.

> Is there a way to define a resource root for ~ css imports?

Yes. You can intercept imports during bundling and write custom code in a plugin to do whatever you want. Documentation is here: https://esbuild.github.io/plugins/#on-resolve.

**Comment by evanw** [comment] 2022-03-27 01:28
I'm closing this issue as "by design" because it's not intended to be possible to use JS plugins with the Go API or Go plugins with the JS API.

**Closed by evanw** 2022-03-27 01:28 UTC

**Comment by metalim** [comment] 2023-08-20 19:29
but why..?
was looking to use sass plugin from Go. Now you say I can't...
