### ISSUE TITLE
Transform fails when using a nightly build of Node

### ISSUE THREAD

**Issue by notpeelz** [evanw/esbuild#2766] opened 2022-12-22 02:31 UTC
I'm trying to use esbuild on a nightly build of Node, but I get this error:
```
Error: Transform failed with 1 error:
error: Invalid version: "20.0.0-nightly2022122151246139e7"
```

From the looks of it, the version regexp seems a bit too strict:
https://github.com/evanw/esbuild/blob/270a210e9833f516f0d058bccae29aa989e3ece8/pkg/api/api_impl.go#L287

[semver.org](https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string) suggests this regexp:

```regex
^(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)(?:-(?P<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?P<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
```

**Comment by evanw** [comment] 2022-12-22 02:36
Closing as a duplicate of #2760. This prerelease version of node is not in esbuild’s internal feature database, so it is meaningless to ask for esbuild to accept it. The `target` setting deliberately only accepts version triples.

**Closed by evanw** 2022-12-22 02:36 UTC
