### ISSUE TITLE
3rd party issues with ESBuild using namespace + class

### ISSUE THREAD

**Issue by arobinson** [evanw/esbuild#2429] opened 2022-08-01 17:28 UTC
I've created a simple reproduction use case here with Bazel+tsc+esbuild:
https://github.com/arobinson/esbuild-namespace-issue

Note that we normally use Angular in the browser, but this reproduction is more simple to just reproduce the issue without a full Angular setup.

We are having 3 problems, two of which are blocking and one that seems more of a warning.

Issues:
1. `dragula` seen as a namespace and not a function
2. `MessageFormat` seen as a namespace and not a class with a constructor
3. Warnings produced with method decorators regarding `"this"` usage

I haven't been able to find a configuration or anything that helps, as far as I can tell, this seems to be a bug with esbuild and the combination of namespaces and classes/functions. Not sure of the issue with the decorators. This code has been working without warnings nor issues with Angular CLI which uses Webpack to bundle. I'd rather not use Webpack as we need to use some hacks to use it with our system and it isn't as fast, but this problem is currently preventing us from using esbuild.

We are planning on getting off of dragula and MessageFormat, but I'm not sure of the timing on those. I'm not yet aware if the decorator issue would cause code to fail as our code throws an error with MessageFormat before we get to where the decorators are used.

Note that we cannot use esbuild directly with the typescript source as Angular requires us to use `tsc` (the Angular compiler), so our build steps must first compile using `tsc`, then bundle and link (Babel plugin to esbuild). 

Any help would be appreciated.

Errors:
```
▲ [WARNING] Calling "dragula" will crash at run-time because it's an import namespace object, not a function

    ../../../../../../../../execroot/esbuild-namespace-issue/bazel-out/darwin-fastbuild/bin/reproduce-issue.ts:16:2:
      16 │   dragula(options);
         ╵   ~~~~~~~

  Consider changing "dragula" to a default import instead:

    ../../../../../../../../execroot/esbuild-namespace-issue/bazel-out/darwin-fastbuild/bin/reproduce-issue.ts:2:7:
      2 │ import * as dragula from "dragula";
        │        ~~~~~~~~~~~~
        ╵        dragula

  Make sure to enable TypeScript's "esModuleInterop" setting so that TypeScript's type checker generates an error when you try to do this. You can read more about this setting here: https://www.typescriptlang.org/tsconfig#esModuleInterop

▲ [WARNING] Constructing "MessageFormat" will crash at run-time because it's an import namespace object, not a constructor

    ../../../../../../../../execroot/esbuild-namespace-issue/bazel-out/darwin-fastbuild/bin/reproduce-issue.ts:23:17:
      23 │   const mf = new MessageFormat("en-US");
         ╵                  ~~~~~~~~~~~~~

  Consider changing "MessageFormat" to a default import instead:

    ../../../../../../../../execroot/esbuild-namespace-issue/bazel-out/darwin-fastbuild/bin/reproduce-issue.ts:3:7:
      3 │ import * as MessageFormat from "messageformat";
        │        ~~~~~~~~~~~~~~~~~~
        ╵        MessageFormat

  Make sure to enable TypeScript's "esModuleInterop" setting so that TypeScript's type checker generates an error when you try to do this. You can read more about this setting here: https://www.typescriptlang.org/tsconfig#esModuleInterop

▲ [WARNING] Top-level "this" will be replaced with undefined since this file is an ECMAScript module

    ../../../../../../../../execroot/esbuild-namespace-issue/bazel-out/darwin-fastbuild/bin/example-decorator.js:1:18:
      1 │ var __decorate = (this && this.__decorate) || function (decorators,...
        │                   ~~~~
        ╵                   undefined

  This file is considered to be an ECMAScript module because of the "export" keyword here:

    ../../../../../../../../execroot/esbuild-namespace-issue/bazel-out/darwin-fastbuild/bin/example-decorator.js:30:0:
      30 │ export { ExampleClass };
         ╵ ~~~~~~
```

This seems to at least be caused by the 3rd party code using a namespace with the same name as a class, at least for MessageFormat. Here is the index.d.ts file from MessageFormat:

```
declare namespace MessageFormat {
  type Msg = { (params: {}): string; toString(global?: string): string };
  type Formatter = (val: any, lc: string, arg?: string) => string;
  type SrcMessage = string | SrcObject;

  interface SrcObject {
    [key: string]: SrcMessage;
  }

  interface Options {
    biDiSupport?: boolean;
    customFormatters?: { [name: string]: Formatter };
    pluralKeyChecks?: boolean;
    strictNumberSign?: boolean;
  }
}

declare class MessageFormat {
  constructor(
    locales?: { [locale: string]: Function } | string[] | string,
    options?: MessageFormat.Options
  );
  addFormatters: (format: { [name: string]: MessageFormat.Formatter }) => this;
  disablePluralKeyChecks: () => this;
  setBiDiSupport: (enable: boolean) => this;
  setStrictNumberSign: (enable: boolean) => this;
  compile: (
    messages: MessageFormat.SrcMessage,
    locale?: string
  ) => MessageFormat.Msg;
}

export = MessageFormat;
```

**Comment by evanw** [comment] 2022-08-01 17:45
> * `dragula` seen as a namespace and not a function
> * `MessageFormat` seen as a namespace and not a class with a constructor
>
> I haven't been able to find a configuration or anything that helps, as far as I can tell, this seems to be a bug with esbuild and the combination of namespaces and classes/functions.

This is not a bug with esbuild. The warning is just explaining to you how JavaScript works. In JavaScript, doing `import * as x from "y"` means `x` is _always_ an object (specifically the "module namespace exotic object"). No exceptions. This is in [the JavaScript specification itself](https://tc39.es/ecma262/#sec-static-semantics-importentriesformodule).

You are welcome to ignore the warning, but keep in mind that your code will still crash at run-time. If you want to hide the warning you can use `--log-override:call-import-namespace=silent`. If you want to resolve the warning, the code causing the warning will have to be fixed.

The warning you pasted into the issue literally already tells you how to fix it for yourself:

```
  Consider changing "dragula" to a default import instead:

    ../../../../../../../../execroot/esbuild-namespace-issue/bazel-out/darwin-fastbuild/bin/reproduce-issue.ts:2:7:
      2 │ import * as dragula from "dragula";
        │        ~~~~~~~~~~~~
        ╵        dragula

  Consider changing "MessageFormat" to a default import instead:

    ../../../../../../../../execroot/esbuild-namespace-issue/bazel-out/darwin-fastbuild/bin/reproduce-issue.ts:3:7:
      3 │ import * as MessageFormat from "messageformat";
        │        ~~~~~~~~~~~~~~~~~~
        ╵        MessageFormat
```

> * Warnings produced with method decorators regarding `"this"` usage

I'm guessing you are using an old version of esbuild. This warning no longer happens for me in the latest version of esbuild.

Closing this issue since esbuild is behaving as expected here.

**Closed by evanw** 2022-08-01 17:45 UTC
