### ISSUE TITLE
PnP loader chokes on certain packages

### ISSUE THREAD

**Issue by jleedev** [evanw/esbuild#2461] opened 2022-08-12 20:51 UTC
Using version 0.15.1.

This works with `node_modules`, but not with PnP:

```bash
 ¶ echo {} >package.json
 ¶ yarn set version stable
 ¶ yarn add esbuild osmtogeojson
 ¶ echo 'import "osmtogeojson"' | yarn exec esbuild --bundle          
✘ [ERROR] Do not know how to load path: .yarn/cache/osmtogeojson-npm-3.0.0-beta.4-5532f069b5-ce2199680e.zip/node_modules/osmtogeojson/osmtogeojson
 ¶ echo 'import "osmtogeojson/index.js"' | yarn exec esbuild --bundle
✘ [ERROR] Do not know how to load path: .yarn/cache/@mapbox-geojson-rewind-npm-0.4.0-25b0818717-82020c6324.zip/node_modules/@mapbox/geojson-rewind/geojson-rewind
```

Works with `node_modules`:

```bash
 ¶ yarn config set nodeLinker node-modules 
 ¶ yarn
 ¶ echo 'import "osmtogeojson"' | yarn exec esbuild --bundle | head 
(() => {
  var __create = Object.create;
[etc…]
```

Also works with the `@yarnpkg/esbuild-plugin-pnp`.

I think what these two packages (`osmtogeojson` and `@mapbox/geojson-rewind`) have in common is a `package.json`, containing a `bin` key, whose values contain file names that don't end in `.js`, but I'm not sure. Could also be just the presence of a file with the same name as the package (and no `.js` suffix).

**Comment by jleedev** [comment] 2022-08-12 21:12
Yes, this works:

```bash
 ¶ zip -d .yarn/cache/osmtogeojson-npm-3.0.0-beta.4-5532f069b5-ce2199680e.zip node_modules/osmtogeojson/osmtogeojson 
deleting: node_modules/osmtogeojson/osmtogeojson
 ¶ echo 'import "osmtogeojson"' | yarn exec esbuild --bundle
(ok)
```

Curiously, this doesn't:

```bash
 ¶ echo 'import "osmtogeojson/index.js"' | yarn exec esbuild --bundle 
| head 
✘ [ERROR] Do not know how to load path: .yarn/cache/@mapbox-geojson-rewind-npm-0.4.0-25b0818717-82020c6324.zip/node_modules/@mapbox/geojson-rewind/geojson-rewind
```

But this makes it work:

```bash
 ¶ zip -d .yarn/cache/@mapbox-geojson-rewind-npm-0.4.0-25b0818717-82020c6324.zip node_modules/@mapbox/geojson-rewind/geojson-rewind
```

**Comment by evanw** [comment] 2022-08-12 21:21
Closing as a duplicate of #2455. It looks like the same underlying issue.

**Closed by evanw** 2022-08-12 21:21 UTC
