### ISSUE TITLE
error: replace \d to d

### ISSUE THREAD

**Issue by yanqing233** [evanw/esbuild#1908] opened 2022-01-05 09:27 UTC
![image](https://user-images.githubusercontent.com/23711381/148193619-8d777700-6f70-485f-a6d0-bc8d2a863701.png)
esbuild replaced the `\d` to `\` in the regexp string, which caused the problem of inconsistent regular matching in the wx miniprogram。

**Comment by hyrious** [comment] 2022-01-05 09:32
Should be `"\\d"`.

**Comment by yanqing233** [comment] 2022-01-05 09:37
![image](https://user-images.githubusercontent.com/23711381/148195292-7b2ec733-1cbc-41c5-bfc6-21c6504f0811.png)
`\\d` Will not be replaced，Only `\d `will be replaced with `d`

**Comment by hyrious** [comment] 2022-01-05 09:48
I don't know the js runtime in wx miniprogram, at least in node.js and chrome `\d` is **equal to** `d`, try it yourself:

```js
console.log('\d' === 'd') // true
```

If that runtime has some special cases in escaping string literals to regexp (for example, not using `/abc/` syntax but a fake function call), it's their fault to not conform to the javascript spec. Thus esbuild won't support a broken runtime.

**Comment by yanqing233** [comment] 2022-01-05 10:06
![image](https://user-images.githubusercontent.com/23711381/148199569-3db42467-d910-445a-8f15-79414d9f78c9.png)

Thanks for the reply!  I tried using babel and it won’t be deleted. I want to confirm whether I can provide a parameter to control not to delete?

**Comment by hyrious** [comment] 2022-01-05 10:12
As I know, there's no way to control that in esbuild.

**Comment by evanw** [comment] 2022-01-05 15:30
Yes, the above information is correct; esbuild compiles JavaScript, and in JavaScript `\d` and `d` are the same thing. There is no way for the generated code to tell the difference, so esbuild is free to transform one into the other and there is no option to configure this. JavaScript has regular expression literals for this purpose, which you may want to use instead: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions. If you are using a broken JavaScript runtime that interprets `\d` and `d` differently, then that's a bug with that JavaScript runtime, not with esbuild. Closing as "working as intended."

**Closed by evanw** 2022-01-05 15:30 UTC
