### ISSUE TITLE
ESBuild imports bootstrap completely when only one named import is used

### ISSUE THREAD

**Issue by UtkarshVerma** [evanw/esbuild#3141] opened 2023-06-02 05:56 UTC
I have a TS file which does the following import:

```js
import { Modal } from "bootstrap";
```

When I bundle the source, I get a bundle of 180KB.

However, if I do this instead:

```js
import Modal from "bootstrap/src/modal";
```

The bundle is reduced to 40KB. Looking at https://github.com/twbs/bootstrap/blob/main/js/index.esm.js#L13, it is clear that both cases are equivalent.

How do I get ESBuild to work in the first case as it is much more readable.

**Comment by hyrious** [comment] 2023-06-02 06:21
esbuild's tree-shaking is a much simpler algorithm which cannot handle these cases in the `bootstrap` package:

```js
// 1. @popperjs/core is imported by namespace imports (* as ns),
//    if used, it will be transformed to an object that cannot
//    be tree-shaked.
// bootstrap@5.3.0/package/dist/js/bootstrap.esm.js:6
import * as Popper from '@popperjs/core';

// 2. Global function calls are kept because esbuild don't know
//    whether it makes side effects
// bootstrap@5.3.0/package/dist/js/bootstrap.esm.js:4430
enableDismissTrigger(Toast);
```

Here's an minimal example to demonstrate the cases above: [try it online](https://esbuild.github.io/try/#YgAwLjE3LjE5AC0tYnVuZGxlAGUAZW50cnkuanMAZXhwb3J0IHsgTW9kYWwgfSBmcm9tICcuL2Jvb3RzdHJhcCcAAGJvb3RzdHJhcC5qcwBpbXBvcnQgKiBhcyBQb3BwZXIgZnJvbSAnLi9wb3BwZXIuanMnCgovLyAnRHJvcGRvd24nIGlzIHJlZmVyZW5jaW5nICdQb3BwZXInIGluIGl0cyBBU1QKZXhwb3J0IGNsYXNzIERyb3Bkb3duIHsKICBmb28oKSB7CiAgICBQb3BwZXIKICB9Cn0KCi8vICdmb28nIG1heSBoYXMgc2lkZSBlZmZlY3RzIHNvIGFsbCBBU1QKLy8gaXQgcmVsYXRlcyBhcmUga2VwdCBpbiB0aGUgZmluYWwgYnVuZGxlCmZvbyhEcm9wZG93bikKCmV4cG9ydCBsZXQgTW9kYWwgPSAxAABwb3BwZXIuanMAZXhwb3J0IGxldCBhID0gMQ)

**Comment by UtkarshVerma** [comment] 2023-06-03 11:13
But I'm using the exports from this file:
https://github.com/twbs/bootstrap/blob/main/js/index.esm.js

I'm a bit new to the build process, so I don't understand most of the stuff you said. But, from what I can see, you seem to be referencing js files in `dist` while my project uses `js/src` files.

Anyways, is there something I can do to have this fixed on the Bootstrap side of things?

**Comment by hyrious** [comment] 2023-06-03 11:27
> But I'm using the exports from this file:
> [twbs/bootstrap@`main`/js/index.esm.js](https://github.com/twbs/bootstrap/blob/main/js/index.esm.js?rgh-link-date=2023-06-03T11%3A13%3A22Z)

You are using this file only when importing like this:

```js
import {} from 'bootstrap/js/index.esm.js'
```

This is because the boostrap package has this line in [its package.json](https://unpkg.com/bootstrap@5.3.0/package.json), so bundlers must use bootstrap/dist/js/bootstrap.esm.js when importing from the name `bootstrap`.

```js
"module": "dist/js/bootstrap.esm.js"
```

Anyway, no matter whether it's js/index.esm.js or dist/js/bootstrap.esm.js, you cannot get rid of the issues you're asking for becasue of the 2 un-shakeable codes I mentioned above.

> Anyways, is there something I can do to have this fixed on the Bootstrap side of things?

There's a simple workaround to wrap any code that having side effects into a pure function calling like this:

```js
// old code
class Toast {}
enableDismissTrigger(Toast)

// new code
let Toast = /* @__PURE__ */ (() => {
  class Toast {}
  enableDismissTrigger(Toast)
  return Toast
})();
```

Here's the [playground link](https://esbuild.github.io/try/#YgAwLjE3LjE5AC0tYnVuZGxlAGUAZW50cnkuanMAZXhwb3J0IHsgTW9kYWwgfSBmcm9tICcuL2Jvb3RzdHJhcCcAAGJvb3RzdHJhcC5qcwBpbXBvcnQgKiBhcyBQb3BwZXIgZnJvbSAnLi9wb3BwZXIuanMnCgpleHBvcnQgbGV0IERyb3Bkb3duID0gLypAX19QVVJFX18qLyAoKCkgPT4gewogIGNsYXNzIERyb3Bkb3duIHsKICAgIGZvbygpIHsKICAgICAgUG9wcGVyCiAgICB9CiAgfQogIGZvbyhEcm9wZG93bikKfSkoKQoKZXhwb3J0IGxldCBNb2RhbCA9IDEAAHBvcHBlci5qcwBleHBvcnQgbGV0IGEgPSAx) to demonstrate that.

**Comment by evanw** [comment] 2023-06-05 00:02
Thanks for the investigation. I'm closing this issue because this is by design.

Package authors can use tree-shaking annotations to enable tree shaking for their packages if they want their packages to have that feature. One way is `/* @__PURE__ */` comments, and another way is the `sideEffects` list in `package.json`.

This is not something that's esbuild's responsibility to figure out. Figuring out automatically whether code has side effects or not gets slow and complicated very quickly (as it involves symbolic interpretation of the program) and is impossible in the general case.

**Closed by evanw** 2023-06-05 00:02 UTC
