### ISSUE TITLE
bug: console.log + pure + minify + JSON.stringify, or even just a template literal

### ISSUE THREAD

**Issue by revelt** [evanw/esbuild#1879] opened 2021-12-22 19:24 UTC
Tested on 0.14.7.

There are three more cases related to `console.log` on `--pure` and `--minify` settings:

---

source `index.js`:

```js
function test() {
	const obj = { "z": 1 };
	console.log(
		`obj: ${obj}`
	);
}

export { test }
```

```
npx esbuild index.js --platform=node --minify --target=node16 --outfile=out.js --pure:console.log
```

yields `out.js`:

```js
function o(){`${{z:1}}`}export{o as test};
```

---

source `index.js`:

```js
function test() {
	const obj = { "z": 1 };
	console.log(
		JSON.stringify(
			obj,
			null,
			4
		)
	);
}

export { test }
```

same command,

```
npx esbuild index.js --platform=node --minify --target=node16 --outfile=out.js --pure:console.log
```

yields `out.js`:

```js
function n(){const o={z:1};JSON.stringify(o,null,4)}export{n as test};
```

---

source `index.js`:

```js
function test() {
	const obj = { "z": 1 };
	console.log(
		`obj: ${JSON.stringify(
			obj,
			null,
			4
		)}`
	);
}

export { test }
```

same command,

```
npx esbuild index.js --platform=node --minify --target=node16 --outfile=out.js --pure:console.log
```

yields `out.js`:

```js
function n(){const o={z:1};`${JSON.stringify(o,null,4)}`}export{n as test};
```

---

**Comment by evanw** [comment] 2021-12-22 19:35
Marking a function call as pure means "remove the function call but still evaluate the arguments" so this is expected behavior. The arguments will be preserved if they can't be proven to have no side effects, and esbuild considers running the `ToString` operation on a variable to be a side effect. I do not consider this to be a bug.

If you want to remove the `console.log` call entirely (including not evaluating the arguments), marking the function call as pure is not the way to do that. One way to do that is to move the `console.log` behind a conditional and then use `--define` to disable the conditional. An example would be doing something like this and then using something like `--define:global.NO_LOG=true` to remove the call entirely:

```js
!global.NO_LOG && console.log(`obj: ${obj}`);
```

Closing as working as intended.

**Closed by evanw** 2021-12-22 19:35 UTC

**Comment by revelt** [comment] 2021-12-22 21:17
Thank you for quick response! It makes sense.
