### ISSUE TITLE
Does Hermes really support `ConstAndLet`?

### ISSUE THREAD

**Issue by tido64** [evanw/esbuild#2365] opened 2022-07-01 07:06 UTC
First of all, thanks for adding the Hermes target in 4e631f5643. We're maintaining a small plugin that targets Hermes, and this makes our lives so much easier.

It looks like the target is listed to support `ConstAndLet`, and I'm wondering what that means in terms of transpilation output. I know that `let` and `const` are listed under [In Progress](https://hermesengine.dev/docs/language-features#in-progress) on their website, and the engine does parse them just fine, but I also know that it basically just interprets them as `var`. There is no support for block-scoped variables (https://github.com/facebook/hermes/issues/575#issuecomment-902048116), and you can still overwrite the values. If `ConstAndLet` assumes either of these, then it's probably a bug and should be removed.

**Comment by evanw** [comment] 2022-07-01 14:53
Compatibility data is managed by another project: https://github.com/kangax/compat-table. I added the data assuming it would be correct, and therefore useful. If it’s incorrect and not useful then I can remove the Hermes target from esbuild in the next breaking change release. I do not want to test for and maintain JavaScript feature compatibility matrices for obscure targets like Hermes myself.

**Comment by kelset** [comment] 2022-07-01 14:56
thanks for the info @evanw! I just noticed that over there there's a draft PR by the team at Meta maintaining the project: https://github.com/kangax/compat-table/pull/1808 so I'd say that once that's merged the data will most likely be correct

**Comment by tido64** [comment] 2022-07-04 08:12
> Also it’s really strange how broken this is. Making `let` and `const` an alias for `var` seems worse than just only supporting `var` since it’s inevitable that it’ll cause problems. I wonder what other features that Hermes “supports” are also fundamentally broken like this.

I completely agree with this. I still think the Hermes target is useful, so I hope it will stay. Until the PR to compat-table lands, I've submitted a PR to remove Hermes from `ConstAndLet`. Please let me know if this is okay, or if there's anything else you need.

**Comment by evanw** [comment] 2022-07-06 04:16
I have investigated this and determined that the bug is with esbuild's compatibility table generator, not with the compatibility data. The compatibility data correctly marks Hermes as broken regarding `const` and `let` but the script has a bug that overlooks that data.

Specifically the problem is when the test for a feature has many sub-tests and some of those sub-tests have always been broken and have never been fixed. This situation hasn't come up before because previously esbuild has only supported targets that fix their bugs (and that ship at least one version where the feature works) instead of leaving them broken in all shipped versions.

I'll fix esbuild's compatibility table generator script which will fix this problem, and which will mark a lot of features as unsupported in Hermes.

**Closed** 2022-07-06 04:45 UTC

**Comment by tido64** [comment] 2022-07-06 06:45
@evanw Thanks for fixing this 🙏
