### ISSUE TITLE
css sourcemap comment not included

### ISSUE THREAD

**Issue by Somepub** [evanw/esbuild#1387] opened 2021-06-21 22:52 UTC
Hello,

I'm trying to make scss source map implementation with my custom plugin, unfortunately source map comment is being eaten away.

```
build.onLoad({ filter: /.*/, namespace: "sass" }, (args) => {
      const compiled = sass.renderSync({
        file: args.path,
        sourceMap: pluginArgs.sourceMap,
        outFile: outCss,
        outputStyle: pluginArgs.outputStyle,
        includePaths: ['styles', 'vendor'],
        sourceMapContents: true
      });

      return {
        contents: compiled.css.toString(),
        loader: "css",
      };
    });
```

compiled.css.toString() returns me:
```
* {
  background-color: black;
  color: red; }

/*# sourceMappingURL=index.css.map */
```

but the output of the css file is `*{background-color:#000;color:red}
`

I also looked into legal comments, but that seems to only work with .js, ts files.
Am I doing something wrong or this is a default esbuild behavior?

**Comment by evanw** [comment] 2021-06-22 00:30
You're not doing something wrong. This is a default esbuild behavior. Source maps in CSS are not supported yet. Just copying the input source map comment over to the output file would be incorrect because the input source map contains mappings for the input file, not the output file. The source map would need to be rewritten by esbuild to get this to work correctly.

Closing as a duplicate of #519.

**Closed by evanw** 2021-06-22 00:30 UTC
