### ISSUE TITLE
How to build for adobe jsx?

### ISSUE THREAD

**Issue by pigLoveRabbit520** [evanw/esbuild#3619] opened 2024-01-30 10:21 UTC
Adobe [jsx](https://ai-scripting.docsforadobe.dev/scriptingJavascript/yourFirstScript.html) is just es5 syntax. However, there is a special syntax `#include`
```
#include "./api/index.jsx"
```
`#include` is just including code like C.

now I will get the error using the esbuild
```
> build
> esbuild index.jsx --bundle --outfile=out.js

✘ [ERROR] Unexpected "#include"

    index.jsx:1:0:
      1 │ #include "./api/index.jsx"
        ╵ ~~~~~~~~

1 error
node:child_process:899
    throw err;
    ^
```
Adobe jsx is not React jsx.

**Comment by hyrious** [comment] 2024-01-30 11:46
If it follows the cpp (c pre processor)'s grammar, I guess you can just use `cpp` to pre-process it before feeding it to esbuild. For example, use plugins and write a custom on-load to execute `cpp path/to/file.jsx` and return its stdout with loader = js.

**Comment by evanw** [comment] 2024-02-02 13:54
I'm closing this issue as out of scope. Using `cpp` as a "bundler" is probably a pretty good solution for this, assuming it works as intended (I'm not familiar at all with Adobe-style JavaScript).

**Closed by evanw** 2024-02-02 13:54 UTC
