### ISSUE TITLE
Error: Cannot find module './uws_linux_x64_93.node'

### ISSUE THREAD

**Issue by atshushi** [evanw/esbuild#2846] opened 2023-01-19 02:50 UTC
```
Error: This version of uWS.js supports only Node.js 16 and 18, and 19 on (glibc) Linux, macOS and Windows, on Tier 1 platforms (https://github.com/nodejs/node/blob/master/BUILDING.md#platform-list).        

Error: Cannot find module './uws_linux_x64_93.node'
```
```js
const { buildSync } = require('esbuild');
const process = require('process');
const glob = require('glob');


buildSync({
  entryPoints: glob.sync(`${process.argv.pop()}/**/**`)
    .filter((path) => path.endsWith('.ts')),
  platform: 'node',
  bundle: true,
  minify: true,
  outdir: 'dist',
  format: 'esm',
  loader: {
    '.html': 'text',
    '.css': 'text',
  },
});
```

node -v: v16.19.0

**Comment by atshushi** [comment] 2023-01-19 02:51
the problem is in the import

**Comment by evanw** [comment] 2023-01-19 02:54
https://esbuild.github.io/getting-started/#bundling-for-node

> You also may not want to bundle your dependencies with esbuild. There are many node-specific features that esbuild doesn't support while bundling such as `__dirname`, `import.meta.url`, `fs.readFileSync`, and `*.node` native binary modules. You can exclude all of your dependencies from the bundle by setting [packages](https://esbuild.github.io/api/#packages) to external:
>
> ```js
>   packages: 'external',
> ```
>
> If you do this, your dependencies must still be present on the file system at run-time since they are no longer included in the bundle.

**Comment by atshushi** [comment] 2023-01-19 02:59
finally it worked, thanks for the quick reply

**Comment by evanw** [comment] 2023-01-19 03:10
I'm closing this issue as it's a question, not a bug report, and the answer is already on the first page of the docs.

**Closed by evanw** 2023-01-19 03:10 UTC
