### ISSUE TITLE
new versions of `esbuild/linux-x64` are not published on the npm registry?

### ISSUE THREAD

**Issue by cliffordfajardo** [evanw/esbuild#2858] opened 2023-01-21 14:18 UTC
### Background Context
I currently work at a company that uses a proxy to fetch packages from npm / other package providers.
We have a tool where we put in the name and version of a package we want to use & our infra will go out and safely fetch those resources from the web:

### What is the Issue?
I think `esbuild-linux-64` is not publishing the most recent artifacts on npm after version 0.15.18 (Dec 2022)

✅  Our tool was able to successfully fetch `esbuild-linux-64@0.15.18` successfully. 

<img width="1633" alt="image" src="https://user-images.githubusercontent.com/6743796/213870740-05e4bd20-8495-4032-b552-53d720793ff9.png">

❌ However, fetching `esbuild-linux-64@0.16.17` fails (npmjs page for [`esbuild-linux-64`](https://www.npmjs.com/package/esbuild-linux-64?activeTab=versions)

![CleanShot 2023-01-21 at 06 15 11@2x](https://user-images.githubusercontent.com/6743796/213870889-4854d141-936c-46be-9fd4-9c5d6bed9fd6.png)

Our tool attempts to fetch packages from the npm registry but the newest versions of `esbuild-linux-64` dont seem to be published

@evanw - is there a way to have the most recent versions of esbuild `esbuild-linux-64` published to npm?

## References
- npmjs page for `esbuild-linux-64`: https://www.npmjs.com/package/esbuild-linux-64?activeTab=versions

**Comment by hyrious** [comment] 2023-01-21 14:35
https://www.npmjs.com/package/@esbuild/linux-x64

**Comment by evanw** [comment] 2023-01-21 16:05
Heads up that esbuild's internal packages changed in [version 0.16.0](https://github.com/evanw/esbuild/releases/v0.16.0). They are an internal implementation detail of esbuild and may change again from time to time.

This request is strange for a few reasons. First of all, you're never supposed to depend on `esbuild-linux-64` directly. You're supposed to depend on `esbuild`. So it seems like your tool is broken. Your tool should be automatically picking up the dependencies of the `esbuild` package, whatever they currently are. As you can see, the latest versions of esbuild do not depend on the `esbuild-linux-64` package at all: https://www.npmjs.com/package/esbuild?activeTab=dependencies.

Also esbuild no longer mentions `esbuild-linux-64` anywhere in its documentation. If you do want to manually download esbuild from npm without using the `esbuild` package, then you should be using the `@esbuild/linux-x64` package as documented here: https://esbuild.github.io/getting-started/#download-a-build.

I'm closing this issue because esbuild is working as intended. Either you have a bug in your internal tool that isn't downloading esbuild's dependencies correctly and/or you should read https://esbuild.github.io/getting-started/#download-a-build about how to manually download esbuild if you want to do that instead.

**Closed by evanw** 2023-01-21 16:05 UTC
