### ISSUE TITLE
Sources processed by a plugin not present in source maps

### ISSUE THREAD

**Issue by prantlf** [evanw/esbuild#1886] opened 2021-12-25 17:53 UTC
Could you help me to track this problem with source maps, please? The code generated by the plugin is bundled well. But source file names processed by the plugin are not included in the `sources` array in the source map.

## Synopsis

The plugin is supposed to convert text files to a JavaScript by wrapping them to a string and apply a function to them. For example, a source file `counter.ts`, where the plugin handles imports with the extension `.thtml`:

    import template from './counter.thtml'

The converted output of `counter.thtml`:

    import { templ } from 'bacom'
    export default templ('<content of counter.thtml>')

And the simplified plugin:

    {
      setup(build) {
        build.onLoad({ filter: /\.thtml$/ }, async ({ path }) => async () => {
          const source = await readFile(path, 'utf8')
          const { code, map } = await compileHtml(path, source)
          const contents = `${code}
    ${inlineMap(map)}`
          return { contents, resolveDir: dirname(path) }
        })
      }
    }

## Example

Let us have a project like this:

    ├── counter-fonts.ts
    ├── counter.thtml
    └── counter.ts

The file `counter.ts` looks like this:

    import { comp, prop, elem, event } from '../../dist/index.esm.js'
    import template from './counter.thtml'
    import './counter-fonts'

The content of `counter.thtml`:

    <span>Count: <span id=display></span></span>

The converted output of `counter.thtml` together with the inlined source map:

    import { templ } from 'bacom'
    export default templ(`<span>Count: <span id=display></span></span>\n`)
    //# sourceMappingURL=data:application/json;charset=utf-8;base64,e...9

The source map for `counter.thtml`:

    {
      "file": "counter.thtml.js",
      "mappings": ";sBAAA;CACC",
      "names": [],
      "sources": ["counter.thtml"],
      "sourcesContent": ["<span>Count: <span id=display></span></span>\n"],
      "version": 3
    }

The source map `counter.js.map` for the bundle created from `counter.ts`:

    {
      "version": 3,
      "sources": [
        "../../src/memoize.ts", "../../src/style.ts", "../../src/comp.ts", "../../src/attr.ts",
        "../../src/prop.ts", "../../src/elem.ts", "../../src/event.ts", "../../src/templ.ts",
        "../../src/memoize.ts", "../../src/style.ts", "../../src/comp.ts", "../../src/attr.ts",
        "../../src/prop.ts", "../../src/elem.ts", "../../src/event.ts", "../../src/templ.ts",
        "counter-fonts.ts", "counter.ts"
      ],
      "sourcesContent":[
        "...", "...", "...", "...",
        "...", "...", "...", "...",
        "...", "...", "...", "...",
        "...", "...", "...", "...",
        "...", "..."
      ],
      "names": [],
      "mappings": "..."
    }

The source map includes every source file imported from the source map of `../../dist/index.esm.js`. It includes also `counter-fonts.ts`, `counter.ts` from the local directory. However, **it is missing `counter.thtml` from the local directory**. A weird thing is also that **source files imported from the source map of `../../dist/index.esm.js` are duplicated**.

## Rollup

I wrote the same plugin for `rollup`. The API is very similar, which helped me to reuse all code and source map generation behind the plugin:

    {
      async transform(source, id) {
        if (filter(id)) {
          const { code, map } = await compileHtml(id, source)
          return { code, map: map.toJSON() }
        }
    }

Both the generated code and the source map were bundled well by `rollup`. The source map `counter.js.map` for the bundle created from `counter.ts`:

    {
      "version": 3,
      "file": "counter.js",
      "sources": [
        "../../node_modules/tslib/tslib.es6.js", "../../src/memoize.ts", "../../src/style.ts",
        "../../src/comp.ts", "../../src/attr.ts", "../../src/prop.ts",
        "../../src/elem.ts", "../../src/event.ts", "../../src/templ.ts",
        "counter.thtml", "counter-fonts.ts", "counter.ts"
      ],
      "sourcesContent":[
        "...", "...", "...",
        "...", "...", "...",
        "...", "...", "...",
        "<span>Count: <span id=display></span></span>\n", "...", "..."
      ],
      "names": ["style"],
      "mappings": "..."
    }

The source map includes also `counter.thtml` from the local directory. (The `../../node_modules/tslib/tslib.es6.js` is needed by `@rollup/plugin-typescript`.)

## Questions

Are there circumstances when `esbuild` omits sources from the source map of the output bundle? Or are the sources always included, unless the inlined source map is malformed?

May `esbuild` be confused by values of `file` and and `sources` in the source map returned by the plugin? `Rollup` does not mind, but are there some expectations about them for `esbuild`? I return a fabricated name `counter.thtml.js` for the source file `counter.thtml`:

      "file": "counter.thtml.js",
      "sources": ["counter.thtml"],

Thank you for your help!

**Comment by hyrious** [comment] 2021-12-26 09:31
Okay, I found some clue to it ([see it live](https://hyrious.me/esbuild-repl/?version=0.14.8&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLnRzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRiUyRiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCU3QyUyMCUzQy0lMjBjb2x1bW4lMjAyMiUyQyUyMHJpZ2h0JTIwYWZ0ZXIlMjAlNjAuJTIwJTJGJTJGJTIwdHJ5JTIwcGxhY2UlMjBvbmUlMjBtb3JlJTIwc3BhY2UlMjBiZWZvcmUlMjAlNjAlNUNuZXhwb3J0JTIwZGVmYXVsdCUyMHRlbXBsKCU2MHdoYXRldmVyJTYwKSU1Q24lMkYlMkYlMjMlMjBzb3VyY2VNYXBwaW5nVVJMJTNEZGF0YSUzQWFwcGxpY2F0aW9uJTJGanNvbiUzQmJhc2U2NCUyQ2V5SjJaWEp6YVc5dUlqb3pMQ0ptYVd4bElqb2lZUzVxY3lJc0luTnZkWEpqWlhNaU9sc2lZUzVvZEcxc0lsMHNJbk52ZFhKalpYTkRiMjUwWlc1MElqcGJJanh6Y0dGdVBrTnZkVzUwT2lBOGMzQmhiaUJwWkQxa2FYTndiR0Y1UGp3dmMzQmhiajQ4TDNOd1lXNCUyQlhHNGlYU3dpYm1GdFpYTWlPbHRkTENKdFlYQndhVzVuY3lJNklqdHpRa0ZCUVNKOSUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmJ1bmRsZSUyMiUzQXRydWUlMkMlMjJmb3JtYXQlMjIlM0ElMjJlc20lMjIlMkMlMjJzcGxpdHRpbmclMjIlM0FmYWxzZSUyQyUyMnNvdXJjZW1hcCUyMiUzQXRydWUlN0QlN0Q%3D)):

```js
//                    | <- column 22, right after `
export default templ(`whatever`)
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiYS5qcyIsInNvdXJjZXMiOlsiYS5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIjxzcGFuPkNvdW50OiA8c3BhbiBpZD1kaXNwbGF5Pjwvc3Bhbj48L3NwYW4+XG4iXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtzQkFBQSJ9
```
This is a simplified example with your compiled `counter.thtml`. The sourcemap saied:
```js
{
  version: 3,
  file: 'a.js',
  sources: [ 'a.html' ],
  sourcesContent: [ '<span>Count: <span id=display></span></span>\n' ],
  names: [],
  mappings: ';sBAAA'
}
```
What is `sBAAA`? Let `vlq` decode that:

```js
require('vlq').decode('sBAAA') // => [ 22, 0, 0, 0 ]
```

It simply means: the line 2 - column 22 of the result code is mapping from the first (0) column of the first (0) sourcesContent.

```js
//                    | <- column 22, right after `
export default templ(`whatever`)
```

As you can see the place is inside a string &mdash; which is the problem from:

Esbuild will _remap_ the generated code to the original source, the _remapping_ happens on every **token**'s left side. For example, `\`whatever\`` is a token, but the left side of it is column **21**. So esbuild does not remap it because it did not find a token at column **22**.

**Comment by prantlf** [comment] 2021-12-26 10:22
I created a a testing project with small `esbuild` and `rollup` plugins demonstrating the problem with a small web page: https://github.com/prantlf/esbuild-incomplete-sourcemap.

**Comment by prantlf** [comment] 2021-12-26 10:33
Thanks a lot for your analysis, @hyrious! I did not know that `esbuild` is drilling down to the source maps. Adding a space space before ` in your example works like magic :-)

It did not occur to me, because trying the source map at https://evanw.github.io/source-map-visualization/ succeeded. I uploaded the following file:

    import { templ } from 'bacom'
    export default templ(`<span>Count: <span id=display></span></span>\n`)
    //# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbImNvdW50ZXIudGh0bWwiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtzQkFBQTtDQUNDIiwiZmlsZSI6ImNvdW50ZXIudGh0bWwuanMiLCJzb3VyY2VzQ29udGVudCI6WyI8c3Bhbj5Db3VudDogPHNwYW4gaWQ9ZGlzcGxheT48L3NwYW4+PC9zcGFuPlxuIl19

and thought that what I saw was correct:

![grafik](https://user-images.githubusercontent.com/733193/147405511-e2d1bf1b-481b-4601-80fd-22ecffe9158e.png)

I will make sure to map the text to a token. Thanks again!

**Comment by prantlf** [comment] 2021-12-26 10:49
I paid too much attention to `sources` in the source map and ignored `mappings`, as long as they pointed to the original source somehow. Always pointing to JavaScript tokens is the key.

I updated the https://github.com/prantlf/esbuild-incomplete-sourcemap project about the fix and I am closing this issue. Thanks again, @hyrious, for the quick help!

**Comment by hyrious** [comment] 2021-12-26 11:01
Not so quick to close this issue &mdash; maybe esbuild has done wrong? Since rollup and chrome can handle this case correctly, I'd like to @evanw to look at it.

**Comment by prantlf** [comment] 2021-12-26 11:37
OK, @hyrious, let me reopen it.

Yes, it appears that `rollup` handles well any source maps that map the source text to parts of the generated JavaScript, regardless the boundaries of tokens. It may be an intentional limitation of the source map processing in `esbuild`, or just an unintentional bug.

**Comment by evanw** [comment] 2021-12-28 03:50
After looking into this, it looks like esbuild isn't behaving incorrectly to me. I tested this by running the following file containing the broken source map (copied from the comment above) through various implementations:

```js
let templ = window.templ
export default templ(`<span>Count: <span id=display></span></span>\n`)
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbImNvdW50ZXIudGh0bWwiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtzQkFBQTtDQUNDIiwiZmlsZSI6ImNvdW50ZXIudGh0bWwuanMiLCJzb3VyY2VzQ29udGVudCI6WyI8c3Bhbj5Db3VudDogPHNwYW4gaWQ9ZGlzcGxheT48L3NwYW4+PC9zcGFuPlxuIl19
```

The mappings data is `sBAAA;CACC`. I both looked at generated source maps in the visualizer and tried running it in various browsers with `templ` being a function that throws an error to test stack traces. Nothing works with it. Chrome and Firefox both don't generate a stack trace. Webpack with `source-map-loader` omits the source map completely, just like esbuild.

I then tried a minimal fix of the source map which moves the first mapping so it doesn't start after the last expression:

```js
let templ = window.templ
export default templ(`<span>Count: <span id=display></span></span>\n`)
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbImNvdW50ZXIudGh0bWwiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtxQkFBQTtBQUNBIiwiZmlsZSI6ImNvdW50ZXIudGh0bWwuanMiLCJzb3VyY2VzQ29udGVudCI6WyI8c3Bhbj5Db3VudDogPHNwYW4gaWQ9ZGlzcGxheT48L3NwYW4+PC9zcGFuPlxuIl19
```

The mappings data is `qBAAA;AACA`. This works fine with esbuild, and with Webpack with `source-map-loader`. But it still doesn't work in Firefox or node, presumably because the location of the function call expression is still mapped to null.

Finally I tried a real fix where the whole export statement is mapped instead of just the last expression:

```js
let templ = window.templ
export default templ(`<span>Count: <span id=display></span></span>\n`)
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbImNvdW50ZXIudGh0bWwiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBLHFCQUFBO0FBQ0EiLCJmaWxlIjoiY291bnRlci50aHRtbC5qcyIsInNvdXJjZXNDb250ZW50IjpbIjxzcGFuPkNvdW50OiA8c3BhbiBpZD1kaXNwbGF5Pjwvc3Bhbj48L3NwYW4+XG4iXX0=
```

The mappings data is `AAAA,qBAAA;AACA`. This works fine with esbuild, with Webpack with `source-map-loader`, with Firefox, and with node, presumably because the function call expression now has a mapping.

Anyway, the original file in question maps all expressions in the file to null, so I think it's reasonable for it to have a null source map. Especially because [`source-map-loader`](https://webpack.js.org/loaders/source-map-loader/), Webpack's official plugin for remapping source maps, also omits the source map data in this case. The source map is explicitly saying that the code is not to be mapped. I think it's reasonable to fix these kinds of issues by fixing the broken source map instead of having esbuild try to figure out what was intended.

Rollup doesn't seem to really understand the source map either, since it generates a broken source map (i.e. "garbage in, garbage out"). If I recall correctly, Rollup uses a library called `magic-string` to splice together the input files to form the output file, which is why the source mappings happen to be carried through in this case. However, esbuild's intermediate representation is an AST, not a string, and it doesn't support an analogous operation. This is why the trailing mappings after the last expression are dropped instead of being preserved. But this doesn't seem like a bug to me since the mappings don't map to anything anyway.

Closing because esbuild appears to be working as intended. The problem is with the source map, not with esbuild.

**Closed by evanw** 2021-12-28 03:50 UTC

**Comment by hyrious** [comment] 2021-12-28 04:13
Thank you for so detailed comment. Maybe we should give libraries like `magic-string` an advice to edit sourcemap to a correct state &mdash; move carets before function call.

**Comment by evanw** [comment] 2021-12-28 04:25
I think what `magic-string` is doing is correct. It's preserving the intent of the input. The problem is that the input isn't right in the first place. I would not expect `magic-string` to automatically try to adjust the input to guess at its intent, especially because it's not necessarily obvious what the correct intent is and it's easy to guess wrong. Maybe the problem is that the line number was off by one instead of the column number, for example. It's a lot harder to debug a build pipeline that tries to automatically fix things in the middle than a build pipeline that respects the input.
