### ISSUE TITLE
Support new `satisfies` Typescript Operator

### ISSUE THREAD

**Issue by eastlondoner** [evanw/esbuild#2571] opened 2022-09-24 11:26 UTC
When using the new satisfies TypeScript operator, esbuild fails as it doesn't understand the syntax.

Documentation for operator: https://devblogs.microsoft.com/typescript/announcing-typescript-4-9-beta/#the-satisfies-operator

## code
```
const myObject = {
    foo: 1,
    bar: 2
} satisfies Record<string, number>;
```

## error
```
 errors: [
    {
      detail: undefined,
      id: '',
      location: [Object],
      notes: [],
      pluginName: '',
      text: 'Expected ";" but found "satisfies"'
    }
  ],
  warnings: []
```

## expected behaviour
esbuild succeeds without error (ignoring the satisfies operator)

**Comment by evanw** [comment] 2022-09-24 11:41
TypeScript has removed features in the beta period before, so I’m waiting until it’s part of a real release. 

Closing as a duplicate of #2509.

**Closed by evanw** 2022-09-24 11:41 UTC
