### ISSUE TITLE
Issue importing bwip-js

### ISSUE THREAD

**Issue by jpike88** [evanw/esbuild#1484] opened 2021-07-31 18:11 UTC
Am testing this, this worked with other bundlers, but not this one:

see:

```
> server/src/components/core.ts:19:19: error: Could not resolve "bwip-js" (mark it as external to exclude it from the bundle)
    19 │ import bwipjs from 'bwip-js';
       ╵                    ~~~~~~~~~
   server/node_modules/bwip-js/package.json:7:13: note: The path "." is not currently exported by package "bwip-js"
     7 │   "exports": {
       ╵              ^
   server/node_modules/bwip-js/package.json:7:13: note: None of the conditions provided ("browser", "electron", "node") match any of the currently active conditions ("default", "import", "node")
     7 │   "exports": {
       ╵              ^
```

**Comment by hyrious** [comment] 2021-07-31 23:34
The bwip-js uses "browser" in "exports", while [SPEC](https://nodejs.org/api/packages.html#packages_conditional_exports) suggests using "default".

You could use [conditions](https://esbuild.github.io/api/#conditions) option to tell esbuild to read this field.

```js
conditions: ['browser']
```

**Comment by evanw** [comment] 2021-08-01 12:43
Are you using `bwip-js@3.0.0`? That appears to have a defective package definition. The `exports` field looks like this:

```json
  "exports": {
      "browser": {
          "import":  "./dist/bwip-js.mjs",
          "require": "./dist/bwip-js.js",
          "script":  "./dist/bwip-js-min.js"
      },
      "electron": "./dist/bwip-js-node.js",
      "node": {
          "require": "./dist/bwip-js-node.js"
      }
  },
```

This definition forbids you from using `import` to import the package when you are bundling for node. You'd have to use `require` instead.

This is arguably a bug with the package. They really should be providing a `default` condition so this kind of thing doesn't happen. It looks like they "fixed" this here: https://github.com/metafloor/bwip-js/commit/6f681bcc454c4408ed9456b49b141f0949f11fec. They added an `import` condition to allow you to use `import` with the package. You just need to update to `bwip-js@3.0.1`.

The package is still kind of broken since you can't bundle the package directly (`esbuild --bundle bwip-js` will still fail with the same error since that's neither `import` nor `require`) but that's a problem with the package, not with esbuild. If you would like to get that fixed then you should contact author of the broken package.

Closing as "working as intended."

**Closed by evanw** 2021-08-01 12:43 UTC

**Comment by evanw** [comment] 2021-08-01 13:42
The error message for this has been improved. With the next release, the error message will now be:

```
 > server/src/components/core.ts:19:19: error: Could not resolve "bwip-js" (mark it as external to exclude it from the bundle)
    19 │ import bwipjs from 'bwip-js';
       ╵                    ~~~~~~~~~
   node_modules/bwip-js/package.json:7:13: note: The path "." is not currently exported by package "bwip-js"
     7 │   "exports": {
       ╵              ^
   node_modules/bwip-js/package.json:14:14: note: None of the conditions provided ("require") match any of the currently active conditions ("default", "import", "node")
    14 │       "node": {
       ╵               ^
   server/src/components/core.ts:19:19: note: Consider using a "require()" call to import this file
    19 │ import bwipjs from 'bwip-js';
       ╵                    ~~~~~~~~~
```
