### ISSUE TITLE
Possible issue with watch mode on 0.14.37 and 0.14.38

### ISSUE THREAD

**Issue by geoffharcourt** [evanw/esbuild#2243] opened 2022-05-11 03:37 UTC
I'm still trying to produce a reproduction of this issue on a smaller setup than our application. 

We've noticed that in 0.14.37 (continuing in 0.14.38) that our application loops over and over again rebuilding the application in watch mode. esbuild doesn't show this behavior in 0.14.36.

We've reproduced this on MacOS with both Intel and Apple Silicon.

Our configuration (in case it helps):

```js
  await esbuild.build({
    bundle: true,
    define: {
      global: 'globalThis',
      // Shim for react-table-fixed-columns
      __webpack_require__: 'webpackShim',
      AWS_CLOUDFRONT_BASE_URL: `'${process.env.AWS_CLOUDFRONT_BASE_URL || ''}'`,
      CI: process.env.CI,
      DEBUG_ANNOTATIONS: process.env.DEBUG_ANNOTATIONS,
      'process.env.NODE_ENV': `'${process.env.NODE_ENV || 'development'}'`,
      'process.env.RAILS_ENV': `'${process.env.RAILS_ENV || 'development'}'`,
      'window.__REACT_DEVTOOLS_SHOW_INLINE_WARNINGS_AND_ERRORS__': 'false',
    },
    entryNames: '[dir]/[name]-[hash]',
    entryPoints: files.reduce(
      (accumulator, filename) => {
        accumulator.push(`app/javascript/packs/${filename}`);

        return accumulator;
      },
      [],
    ),
    // [NOTE] If you need to debug framework code, edit NODE_ENV in the process
    // shim.
    inject: [
      'app/javascript/lib/esbuild/processShim.ts',
      'app/javascript/lib/esbuild/webpackShim.ts',
    ],
    legalComments: process.env.NODE_ENV === 'production' ? 'linked' : 'none',
    loader: {
      '.eot': 'file',
      '.jpg': 'file',
      '.png': 'file',
      '.svg': 'file',
      '.ttf': 'file',
      '.vtt': 'file',
      '.woff': 'file',
      '.woff2': 'file',
    },
    metafile: true,
    minify: process.env.NODE_ENV === 'production',
    outdir: 'public/builds',
    platform: 'browser',
    plugins,
    publicPath: '/builds',
    sourcemap: !process.env.NO_SOURCE_MAPS,
    sourcesContent: true,
    target: [
      'es2015',
      'chrome60',
      'firefox54',
      'ios12',
      'safari11.1',
    ],
    watch,
  }).then((result) => {
    if (process.env.WRITE_METAFILE) {
      fs.writeFileSync(
        path.join(__dirname, 'metafile.json'),
        JSON.stringify(result.metafile),
      );
    }
  }).catch((error) => {
    console.error('\x1b[31m%s\x1b[0m', 'Failed!', error);
    process.exit(1);
  });
```

In these runs, `WRITE_METAFILE` is not defined. We're still seeing this after I disabled all plugins except for `esbuild-plugin-postcss2`, which is necessary for some of our inputs to be processed.

**Comment by evanw** [comment] 2022-05-11 21:25
If you add `logLevel: 'info'` esbuild should print out why it's rebuilding in the terminal. It should look something like this:

```
[watch] build started (change: "index.js")
[watch] build finished
```

What does it say when you do that?

**Comment by geoffharcourt** [comment] 2022-05-11 21:35
@evanw that was useful! It's a file way outside of our file tree:

```
esbuild | Building...
esbuild | [watch] build finished, watching for changes...
esbuild | [watch] build started (change: "../../../../var/folders/ld/fxwcklmn4fqg_tdgkfnqxx_00000gn/T/tmp-82087-ZgxehH1KyCaZ/180b50bd36faf")
```

**Comment by evanw** [comment] 2022-05-11 21:45
It looks like the `esbuild-plugin-postcss2` plugin is [creating a temporary directory](https://github.com/martonlederer/esbuild-plugin-postcss2/blob/f8c4ce7453ccfe18a09da3c6abdb4d00486b2423/src/index.ts#L136) and then telling esbuild to load the file at that directory. If that path changes on the file system and watch mode is active, then esbuild will rebuild (since that's what it's being told to do).

Maybe the plugin is deleting the temporary directory when the build is done? If so, the plugin could potentially be changed to use a virtual file instead of an actual file. In any case this problem is being caused by the plugin you're using.

**Comment by lgollut** [comment] 2022-05-12 07:01
@geoffharcourt FYI after several postcss plugin tests, I finally settle on [esbuild-postcss](https://www.npmjs.com/package/esbuild-postcss)

**Comment by geoffharcourt** [comment] 2022-05-12 11:43
@lgollut thanks!

**Comment by evanw** [comment] 2022-05-15 15:23
I'm closing this because this is a problem with the plugin, not with esbuild. It looks like they are already aware of this problem: https://github.com/martonlederer/esbuild-plugin-postcss2/issues/19.

**Closed by evanw** 2022-05-15 15:23 UTC

**Comment by geoffharcourt** [comment] 2022-05-16 01:26
Sounds good, thank you for your help figuring this out!
