### ISSUE TITLE
Same hashId for entry file and named chunks even if file is not changed on every build

### ISSUE THREAD

**Issue by jay-cheon** [evanw/esbuild#3061] opened 2023-04-14 01:51 UTC
When I configure, { splitting: true, entryNames: 'main-[hash]', chunkNames: '[name]-[hash'] }
and when I try build multiple times without changing my codebase,
only chunks files hash is keep same name but named chunk files and main entry file's hash value is changed every build time even if I didn't change any code.
I'm just wondering if content is not changed, whether it's better that hash value is remained or not.

**Comment by evanw** [comment] 2023-04-14 01:55
In the past when this has come up, the reason was that a plugin was being used that dynamically generates files at a different path for every build. So that would be my initial guess. 

If you believe this to be a bug with esbuild (and not with a plugin), then please provide a self-contained way to reproduce the issue. Otherwise the problem is with the plugin.

**Comment by jay-cheon** [comment] 2023-04-14 02:12
@evanw  Thanks , I couldn't think about dynamically generates file paths in some plugins.
I'll firstly investigate my whole plugins behavior !

**Comment by evanw** [comment] 2023-04-16 19:48
I'm marking this issue as `unactionable` because no way to reproduce the issue was provided.

**Comment by evanw** [comment] 2023-04-22 19:07
I'm closing this issue because it has been unactionable for a while and no additional information was provided.

**Closed by evanw** 2023-04-22 19:07 UTC
Labels: unactionable

**Comment by jay-cheon** [comment] 2023-05-24 00:14
@evanw Sorry for late reply, It's not ESBuild's issue just from my plugin side as you said. Thank you!
