### ISSUE TITLE
[Feature] Reverse argument order inside if/else branches when right value is "null", "void 0" etc during minify

### ISSUE THREAD

**Issue by MaxGraey** [evanw/esbuild#2364] opened 2022-06-30 19:58 UTC
Example code:
```js
if (a == null) {...}
if (b == undefined) {...}
if (c != Infinity) {...}
if (d > 0) {...}
else if (typeof e == "number") {...}
```
Current minification (preserve new lines for readability):
```js
if(a==null){...}
if(b==void 0){...}
if(c!=Infinity){...}
if(d>0) {...}
else if(typeof e=="number"){...}
```
But much better in terms of entropy for gzip / Brotli compressors is reversing such comparisons to this:
```js
if(null==a){...}
if(void 0==b){...}
if(Infinity!=c){...}
if(0<d) {...}
else if("number"==typeof e){...}
```
`if(null==`, `if(Infinity!=`, `if("number"==` are longer by 1 char than `==null){`, `!=Infinity){` and `=="number"){`

**Comment by evanw** [comment] 2022-07-06 05:13
I remember trying this before for exactly this reason and not doing it because the gzip size strangely came out bigger instead of smaller afterward. I should give this another shot.

**Comment by evanw** [comment] 2022-07-06 06:51
I'm testing this with esbuild's primary benchmark (10 copies of Three.js). Here's the result of putting all primitives on the left for equality operators (disregarding whether it's in an `if` statement or not):

| | Uncompressed | `gzip -9` |
|---|---|---|
| Primitives on the right | 6,083,940 bytes | 1,536,648 bytes |
| Primitives on the left | 6,083,810 bytes (0.002% smaller) | 1,538,012 bytes (0.09% bigger) |

This causes the uncompressed output to shrink slightly, but it causes the compressed output to expand slightly. If we are optimizing for compressed size then that makes this suggestion a size regression.

Here's the same thing but just putting `null`/`undefined` on the left:

| | Uncompressed | `gzip -9` |
|---|---|---|
| `null`/`undefined` on the right | 6,083,940 bytes | 1,536,648 bytes |
| `null`/`undefined` on the left | 6,083,940 bytes (no change) | 1,537,924 bytes (0.08% bigger) |

This is still a size regression, and so is not a helpful thing to do. Also the size differences are really pretty small so it's not that helpful of a change either way.

> I think you have to do it carefully here and only for frequent literals like `if(Infinity==`, `if("number"==typeof ` etc, but definitely shouldn't do it for every if-condition or non-if conditions

You are welcome to try to come up with a heuristic in a PR. If it improves compressed size (and isn't super complicated) then I'm open to a change, but from my basic testing doing this actually makes compressed size worse.

**Comment by MaxGraey** [comment] 2022-07-06 07:18
Hmm, thanks! I'm wondering about Brotli more due to it has much better entropy encoder and [currently supports on all browsers except IE](https://caniuse.com/brotli)

**Comment by hyrious** [comment] 2022-07-06 07:47
There's no enough occurances of `if(literal==` in minified code for gzip to pick up into his huffman table. As we know compression methods are based on re-using common strings, `if(` is far more common to see in the code.

I found [some tool](https://github.com/madler/infgen) to inspect compressed binary data, so I did a test:

```shell
$ npx degit madler/infgen
$ cd infgen && gcc infgen.c -o infgen && cd ..
$ ./infgen/infgen
infgen 2.8 ...

$ echo '{"dependencies":{"three":"*"}}' > package.json
$ npm i
$ gzip -c -9 node_modules/three/build/three.min.js | ./infgen/infgen | rg 'if\('
literal 'if(
literal ';if(s[i]=1,
literal 'if(

$ esbuild node_modules/three/build/three.js --minify | gzip -c -9 | ./infgen/infgen | rg 'if\('
literal 'if(
literal 'if(a
literal 'if(
```

I inspected the officially minified three.min.js and another one with `esbuild --minify`, both passed through `gzip -c -9` and `infgen`. As we can see in the output, gzip never picks up `if(something_longer==`.

You can also try on other sources with the steps above. Some additional info:
- [Dissecting the GZIP format](https://www.infinitepartitions.com/art001.html).
- The `rg` command used above is [ripgrep](https://github.com/BurntSushi/ripgrep).

**Comment by evanw** [comment] 2022-07-10 16:17
That's very interesting! Thanks for posting.

I'm marking this as `unactionable` for now because there currently isn't a clear path forward for this. We can move forward if someone demonstrates a heuristic that esbuild could apply that is a clear win (i.e. happens more often than not and is a significant size savings).

**Comment by evanw** [comment] 2022-07-26 01:38
Closing as this is unactionable and there was no follow-up. We can still reopen this if a clear win is demonstrated.

**Closed by evanw** 2022-07-26 01:38 UTC
Labels: unactionable
