### ISSUE TITLE
Assigning to the variable `name` doesn’t work when bundling to ESM output

### ISSUE THREAD

**Issue by brainkim** [evanw/esbuild#3631] opened 2024-02-05 17:54 UTC
Assigning to the variable `name` in modules doesn’t work correctly with the options `--format=esm` and `--bundle`. This is because ESBuild transforms `let`/`const` declarations to `var`, and assigning the top-level `var name` causes a collision with the `window.name` property.

Example:

https://esbuild.github.io/try/#YgAwLjIwLjAALS1mb3JtYXQ9ImVzbSIgLS1idW5kbGUAZQAAY29uc3QgbmFtZSA9IHtoZWxsbzogIndvcmxkIn0KY29uc29sZS5sb2cobmFtZSk7

```js
const name = {hello: "world"}
console.log(name);
```

Is transpiled to
```js
// <stdin>
var name = { hello: "world" };
console.log(name);
```

Running this code will log `[Object object]`. See https://stackoverflow.com/questions/10523701/using-the-variable-name-doesnt-work-with-a-js-object. I know, the browser is crazy. This doesn’t occur when using format `IIFE`.

**Comment by hyrious** [comment] 2024-02-05 22:53
Your executing context is not ESM. In browsers you have to put your code in

```html
<script type="module" src="bundle.js"></script>
```

instead of a normal script or just pasting into the console.

**Comment by evanw** [comment] 2024-02-08 12:06
I'm closing this because esbuild is working as intended. The instructions for how to use the `esm` format correctly are already in the documentation: https://esbuild.github.io/api/#format-esm

**Closed by evanw** 2024-02-08 12:06 UTC
