### ISSUE TITLE
Avoid spawning a new process on every call to transformSync?

### ISSUE THREAD

**Issue by zen0wu** [evanw/esbuild#1000] opened 2021-03-18 17:16 UTC
In additional to build client, I'm trying to use esbuild to run our CLI tools (written in TypeScript).
I read in the document saying 

```
First there is the synchronous API. This is the most convenient option because single-threaded JavaScript code has the cleanest syntax. It's also optimal performance-wise if all you need to do is run esbuild and then exit. However, it blocks the main thread so you do not want to use it if you have other work to perform in the meantime. This is also the only option that cannot use plugins (since plugins are asynchronous). It looks like this:
```

Also somewhere else seems to suggest that every call to `transformSync` spawn up a new esbuild process which is highly inefficient. This is especially true for the CLI use case since transformSync will be called on the require path for many many files in the codebase.

After shallow scan of the code, I'm wondering if it's possible to only spawn one process in the background that lives aside the node process, and restructure the API so that only the "communicating" the existing process part is synchronous, but avoid spawnSync-ing a new one every time (kind of like `ensureServiceIsRunning`).

Happy to contribute if that's the right direction, figured I might miss something so better to check first.

**Comment by evanw** [comment] 2021-03-18 18:56
I agree. Unfortunately the inefficiency was forced by node's limited child process communication APIs.

I actually tried making this more efficient by trying to use `worker_threads` and atomics, but I had to revert it due to a bug in node (specifically https://github.com/nodejs/node/issues/36531). It looks like the fix for that landed two weeks ago so it could be time to give that another shot. No contribution is needed as the code for this has already been written.

Additional context:

* The previous issue about this: #590
* The regression that caused: #595

**Closed** 2021-03-20 17:44 UTC

**Comment by zen0wu** [comment] 2021-03-20 22:40
Thanks for the informative reply and the quick fix!

I took the look at the underlying nodejs bug, it seems only applies to certain versions, for example, I'm using 12.16.3, which works fine with the issue reproducing snippet, also tested 12.21.0 (the latest version).

It seems that opting-in with an option is a nice move, looking forward to the next release with this feature!
