### ISSUE TITLE
[Feature] more aggressive optimizations/symbol minification

### ISSUE THREAD

**Issue by osdevisnot** [evanw/esbuild#476] opened 2020-10-20 19:11 UTC
Before anything else, thank you so much for this fantastic tool ❤️ 

I wonder if we can improve esbuild's symbol minification to consider more aggressive optimizations. 

For example, a common case for vdom based libraries is to use an `h` function something like this:
```
export function h(_name, _props, _children) {
  return { _name, _props, _children }
}
```

trying to minify this with esbuild produces:
```
function i(n, e, r) {
  return { _name: n, _props: e, _children: r };
}
```

for code example like this, a better minification would be:
```
export function h(n, r, e) {
  return { o: n, t: r, u: e };
}
```

or even better, something like this (** this might break other code):
```
export function h(n, r, e) {
  return { n, r, e };
}
```

`terser` offers this kind of prop mangling via `mangle-prop` option which accepts a regex to consider a property for a rename.

`google-closure-compiler` does this automatically for the variables that can be uniquely identified using `ADVANCED_OPTIMIZATION` strategy.

I created a minimal repro here -- https://github.com/osdevisnot/symbol-minification if you wanted to try it out.

**Comment by evanw** [comment] 2020-10-20 19:29
Closing as a duplicate of #218. FWIW this is pretty low priority for me given the other things on the roadmap.

**Closed by evanw** 2020-10-20 19:29 UTC

**Comment by osdevisnot** [comment] 2020-10-20 19:46
oops my bad, did not see #218 before. thank you @evanw
