### ISSUE TITLE
Dynamic import to CommonJS does not compile to `require`

### ISSUE THREAD

**Issue by LXSMNSYC** [evanw/esbuild#1540] opened 2021-08-22 12:24 UTC
There seems to be a regression that happened between `0.9.5` and `0.12.22`.

When bundling ESM code to Node(platform: "node" and format: "cjs"), the output code seems to be unchanged.

Output:
```js
async function lazyCode() {
  const mod = await import('path');
}
```
Expected:
```js
async function lazyCode() {
  const mod = await Promise.resolve().then(() => toModule(require('path')));
}
```

edit: looks like this happened on `0.10.0` when `import` and `require` behavior has been changed.

**Comment by hyrious** [comment] 2021-08-23 00:51
Dynamic import() is available since [node13.2](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#dynamic_imports). So if you need it to be transformed to `require()`, use `--target=node12`.

**Comment by LXSMNSYC** [comment] 2021-08-23 01:30
> Dynamic import() is available since [node13.2](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#dynamic_imports). So if you need it to be transformed to `require()`, use `--target=node12`.

Even though it is supported in Node 13.2 and above, the code only runs for packages with `"type": "module"`. The intended behavior when `format: "cjs"` is to always convert import statements to `require`, since CommonJS, regardless of the Node version, do not support import statements. Currently, this conversion only works for static imports and it used to be the case for the dynamic import expressions.

**Comment by clydin** [comment] 2021-08-23 18:08
Dynamic import statements are support in both CJS and ESM (https://nodejs.org/docs/latest-v14.x/api/esm.html#esm_import_expressions).
This is particularly useful when ESM code needs to be used from within CJS code.

**Comment by LXSMNSYC** [comment] 2021-08-24 02:05
> In CommonJS modules, it can be used to load ES modules

Now that's the behavior I never wanted. I'll try readjusting the node target then

**Comment by evanw** [comment] 2021-11-21 02:00
I'm going to close this because this is by design. Since `import()` and `require()` behave differently, it would be wrong to convert one into the other (unless of course you have to because it's unsupported and there's no other option). These are the differences I'm aware of:

* Doing `import()` on an ES module works but doing `require()` on an ES module doesn't work (described above).

* When resolving `exports` in `package.json`, `import()` uses the `import` condition while `require()` uses the `require` condition so using these two expressions with the same path can easily end up loading completely different files. You can learn more about this here: https://nodejs.org/api/packages.html#conditional-exports.

**Closed by evanw** 2021-11-21 02:00 UTC

**Comment by LXSMNSYC** [comment] 2021-11-21 02:12
Yes thank you @evanw, I went with `node12` target so that it won't preserve the dynamic import.
