### ISSUE TITLE
Environment variable isn't replaced if `process` is imported instead of using a global `process` variable

### ISSUE THREAD

**Issue by vadimdemedes** [evanw/esbuild#2671] opened 2022-11-11 10:16 UTC
I'm replacing environment variables via `define` and it works in this case:

Config:

```
{
	"define": {
		"process.env.VERSION": "'1.0.0'"
	}
}
```

Source code:

```js
console.log(process.env.VERSION);
//=> 1.0.0
```

Online playground → https://esbuild.egoist.dev/#W1siaW5kZXgudHMiLHsiY29udGVudCI6ImNvbnNvbGUubG9nKHByb2Nlc3MuZW52LlZFUlNJT04pO1xuIn1dLFsiZXNidWlsZC5jb25maWcuanNvbiIseyJjb250ZW50Ijoie1xuICBcImZvcm1hdFwiOiBcImNqc1wiLFxuICBcImNkblVybFwiOiBcImh0dHBzOi8vY2RuLnNreXBhY2suZGV2XCIsXG4gIFwiZGVmaW5lXCI6IHtcbiAgIFx0XCJwcm9jZXNzLmVudi5WRVJTSU9OXCI6IFwiJzEuMC4wJ1wiIFxuICB9XG59In1dXQ==.

However, when I import `process` from `process` or `node:process`, esbuild stops replacing that environment variable.

```js
import process from 'process'; // or node:process

console.log(process.env.VERSION);
//=> undefined
```

Online playground → https://esbuild.egoist.dev/#W1siaW5kZXgudHMiLHsiY29udGVudCI6ImltcG9ydCBwcm9jZXNzIGZyb20gJ3Byb2Nlc3MnOyAvLyBvciBub2RlOnByb2Nlc3NcblxuY29uc29sZS5sb2cocHJvY2Vzcy5lbnYuVkVSU0lPTik7XG4ifV0sWyJlc2J1aWxkLmNvbmZpZy5qc29uIix7ImNvbnRlbnQiOiJ7XG4gIFwiZm9ybWF0XCI6IFwiY2pzXCIsXG4gIFwiY2RuVXJsXCI6IFwiaHR0cHM6Ly9jZG4uc2t5cGFjay5kZXZcIixcbiAgXCJkZWZpbmVcIjoge1xuICAgXHRcInByb2Nlc3MuZW52LlZFUlNJT05cIjogXCInMS4wLjAnXCIgXG4gIH1cbn0ifV1d

This playground may not use the latest esbuild version, but I reproduced this issue locally with 0.15.13.

I use [XO](https://github.com/xojs/xo), which requires `process` to be imported instead of referencing a global `process` variable, that's how I stumbled upon this error. It may very well be an expected behavior, so if that's the case, I'll resort to disabling some lint rules to work around it.

Thank you for a wonderful project 💛

**Comment by evanw** [comment] 2022-11-11 13:16
This is not a bug. This is how the `define` feature works. From [the documentation](https://esbuild.github.io/api/#define):

> This feature provides a way to replace **_global_** identifiers with constant expressions.

The identifier must be global to be replaced by `define`.

**Comment by evanw** [comment] 2022-11-11 13:42
Closing since this is working as intended.

**Closed by evanw** 2022-11-11 13:42 UTC
