### ISSUE TITLE
Subpath imports like `#/` are not supported (but are supported by the spec)

### ISSUE THREAD

**Issue by matthew-dean** [evanw/esbuild#2696] opened 2022-11-22 21:16 UTC
Subpath imports with "#/" throw an error like this:
```
TypeError [ERR_INVALID_MODULE_SPECIFIER]: Invalid module "#/components" is not a valid internal imports specifier name imported from ...
```

**Comment by evanw** [comment] 2022-11-22 21:50
That error text isn’t anything esbuild generates. It looks like an error from node. Are you sure you’re not just having a problem with node? 

If you still believe it’s a problem with esbuild, you’ll have to provide more details. This issue description isn’t enough information for me to be able to do anything with it.

**Comment by bathos** [comment] 2022-11-22 23:37
This is Node, yes. ECMA-262 itself permits any specifier string, but the interpretation and resolution of specifiers is host-defined and hosts may constrain what constitutes a valid specifier. In Node, `#`-prefixed specifiers are internal [subpath imports](https://nodejs.org/api/packages.html#subpath-imports) which take the form `#identifier` (no slash after the #). The `#identifier` must correspond to a key in the package.json "imports" object.

**Comment by evanw** [comment] 2022-11-22 23:51
Yes. My point is that esbuild already supports bundling them. But this error message makes it sound like bundling is turned off or something. In that case esbuild doesn’t have anything to do with this problem.

**Comment by bathos** [comment] 2022-11-23 04:24
@evanw yep makes sense! that response was just my attempt at providing further context to the OP regarding Node’s “#” resolution behavior in case it might be helpful to them.

**Comment by evanw** [comment] 2022-11-23 15:19
Closing this issue as it seems irrelevant. If you enable bundling then esbuild will be the one to handle subpath imports. If you don't enable bundling then your JavaScript run-time environment will be the one to handle subpath imports. If that doesn't work, then the problem is not with esbuild. We can re-open this later if more information is provided and the problem is indeed with esbuild somehow.

**Closed by evanw** 2022-11-23 15:19 UTC
