### ISSUE TITLE
Bundling Library: Uncaught TypeError: import_decimal2.default is not a constructor

### ISSUE THREAD

**Issue by Montmorency** [evanw/esbuild#2673] opened 2022-11-14 10:26 UTC
I was trying  to bundle the [recharts](https://github.com/recharts/recharts) which has a dependency on the [Decimal light](https://github.com/MikeMcl/decimal.js-light.git) library. When running the bundled code I was getting an error:

`Uncaught TypeError: import_decimal2.default is not a constructor`
 
Inspecting the bundled code it looks like the imported library is being wrapped twice:

```
var require_decimal = __commonJS(..)
var import_decimal2 = __toESM(require_decimal());
```

After some reading around the esbuild docs I tried adding  ` --main-fields=module,main` to the esbuild cli call which fixed the problem nicely. 

I think this is not so much an issue as expected behaviour but I couldn't quite understand it :). Is this something to do with the way default namespaces are treated that only applies when esbuild uses the ` "browser": "decimal.js",` in the decimal `package.json`?

many thanks for any pointers.

**Comment by evanw** [comment] 2022-11-15 04:16
It's hard to say exactly without a reproducible test case. But in general, the problem is that there are two common module formats, CommonJS and ESM. They are sort of compatible except for the `default` export, which has divergent behavior between tools. The divergent behavior is explained in detail here: https://esbuild.github.io/content-types/#default-interop. If a package wants to be fully compatible with both formats and also with both the browser and node, then they need to specify a map in the `browser` field instead of a single string. This is described in detail here: https://esbuild.github.io/api/#main-fields. Although I didn't look into your problem in detail, I'm guessing this is where the problem is happening. This is something that's up to the package author to fix.

**Comment by evanw** [comment] 2022-11-21 04:46
Closing this because this is likely something the package itself can fix, as described by the link in my previous comment.

**Closed by evanw** 2022-11-21 04:46 UTC
