### ISSUE TITLE
Browser field always being used

### ISSUE THREAD

**Issue by ephjos** [evanw/esbuild#1275] opened 2021-05-11 19:49 UTC
When building our application with esbuild, we would like to ignore the `browser` field of package.json in external modules. For example, when using the [uuid library](https://github.com/uuidjs/uuid#readme) the build should fail when ignoring the browser field (due to `lib/rng.js` using the node-only `crypto` module). However, esbuild is still resolving the `lib/rng-browser.js` file through the package.json. 

It seems as though setting the [main fields](https://esbuild.github.io/api/#main-fields) to `["module", "main"]` should prevent this, but esbuild still resolves the file pointed to by the `browser` field. I then also looked into the [platform option](https://esbuild.github.io/api/#platform) and also had no luck regardless of the chosen platform. I expected that `platform: "neutral"` combined with the above mainFields should ignore the browser field, causing this build to fail; but this was not the case.

If the browser field is intentionally always being used, please clarify why. If not, it seems that there is a bug in how the user can set the mainFields/platform.

**Comment by evanw** [comment] 2021-05-13 22:48
I think you are mistaken. This appears to be working as intended as far as esbuild is concerned. You can use `--log-level=verbose` to get an explanation of esbuild's path resolution decisions:

```
$ esbuild --bundle uuid --platform=neutral --log-level=verbose
...
   note:   Looking for "." in "exports" map in "./node_modules/uuid/package.json"
   note:     Using the entry for "."
   note:     Checking condition map for one of ["default"]
   note:       The key "node" does not apply
   note:       The key "default" applies
   note:       Checking path "" against target "./dist/esm-browser/index.js"
   note:         Joined "" to "./dist/esm-browser/index.js" to get "./dist/esm-browser/index.js"
...
```

So this has nothing to do with the `browser` field. Rather, this is due to the exports map in that package:

```json
  "exports": {
    ".": {
      "node": {
        "module": "./dist/esm-node/index.js",
        "require": "./dist/index.js",
        "import": "./wrapper.mjs"
      },
      "default": "./dist/esm-browser/index.js"
    },
    "./package.json": "./package.json"
  },
```

It says that when not specifically targeting node, importing the package should import the file `./dist/esm-browser/index.js` by default.

This is happening because when present, the exports map always takes precedence over the main fields. From [node's documentation about package entry points](https://nodejs.org/api/packages.html#packages_package_entry_points):

> If both `"exports"` and `"main"` are defined, the `"exports"` field takes precedence over `"main"`. `"exports"` are not specific to ES modules or CommonJS; `"main"` is overridden by `"exports"` if it exists. As such `"main"` cannot be used as a fallback for CommonJS but it can be used as a fallback for legacy versions of Node.js that do not support the `"exports"` field.

You may be able to get this to work for your use case with `platform: "neutral", conditions: ["node"]` although it depends on what you're up to. You could also consider talking to the maintainer of that package about your use case because the issue here is with the package, not with esbuild.

Closing since this appears to be working as intended.

**Closed by evanw** 2021-05-13 22:48 UTC

**Comment by ephjos** [comment] 2021-05-14 13:12
@evanw Thank you for such a thorough response, I appreciate it! You've clarified quite a few things, but unfortunately there is still some confusion. On my part, I neglected to point out that we are using a very old version of the `uuid` lib, 3.4.0. This version of the package.json actually doesn't have an `exports` field and looks as follows:

```json
{
  "name": "uuid",
  "version": "3.4.0",
  "description": "RFC4122 (v1, v4, and v5) UUIDs",
  "commitlint": {
    "extends": [
      "@commitlint/config-conventional"
    ]
  },
  "keywords": [
    "uuid",
    "guid",
    "rfc4122"
  ],
  "license": "MIT",
  "bin": {
    "uuid": "./bin/uuid"
  },
  "devDependencies": {
    "@commitlint/cli": "~8.2.0",
    "@commitlint/config-conventional": "~8.2.0",
    "eslint": "~6.4.0",
    "husky": "~3.0.5",
    "mocha": "6.2.0",
    "runmd": "1.2.1",
    "standard-version": "7.0.0"
  },
  "scripts": {
    "lint": "eslint .",
    "test": "npm run lint && mocha test/test.js",
    "md": "runmd --watch --output=README.md README_js.md",
    "release": "standard-version",
    "prepare": "runmd --output=README.md README_js.md"
  },
  "browser": {
    "./lib/rng.js": "./lib/rng-browser.js",
    "./lib/sha1.js": "./lib/sha1-browser.js",
    "./lib/md5.js": "./lib/md5-browser.js"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/uuidjs/uuid.git"
  },
  "husky": {
    "hooks": {
      "commit-msg": "commitlint -E HUSKY_GIT_PARAMS"
    }
  }
}
```

Using the verbose `logLevel` you pointed out, I was able to inspect the process and see what was going on. It seems I was mistaken in my original issue: if I set `platform: "neutral"` and `mainFields: ["module", "main"]`, esbuild fails to find the browser version (which is what I expect to happen). This is what we can use in our builds going forward.

However, it seems that the source of confusion for me is that the platform being set to browser seems to ignore the user's provided mainFields setting. I assumed that my mainFields setting would take precedence over the platform setting, especially if I am not specifying it.  Is this intentional? If so, I think it should be communicated more clearly in the docs.

For example (with uuid 3.4.0):

```js
// index.js
import uuid from "uuid";

console.log(uuid());
```

```
// Bundles and uses uuid/lib/rng-browser.js (unexpected)
esbuild index.js --bundle --outfile=bundle.js --main-fields=module,main --log-level=verbose

// Fails trying to use uuid/lib/rng.js, which imports node-only crypto module (expected)
esbuild index.js --bundle --outfile=bundle.js --platform=neutral --main-fields=module,main --log-level=verbose
```

**Comment by evanw** [comment] 2021-05-14 16:55
Ah, I see. The `mainFields` setting only affects what field is used as the "main" field, which determines what to import if you import the package directly without a subpath (i.e. `import "uuid"`). However, although the `browser` field can be a main field if it holds a string, it can also be a map of subpaths to browser-based alternative subpaths if it holds an object instead of a string.

In this case the `browser` field in the `uuid` package is a map instead of a main field because it's an object instead of a string, so the `mainFields` setting has no effect. Instead, the setting that causes the path remapping in the `browser` field to be applied is `platform: 'browser'`. This is the same behavior as Webpack. In Webpack, omitting `browser` from `resolve.mainFields` also does not prevent the path remapping in the `browser` from being applied.

The way to disable this behavior in esbuild is to use `platform: 'neutral'`.

**Comment by ephjos** [comment] 2021-05-14 17:04
@evanw Understood, thank you!
