### ISSUE TITLE
error when code has \n or new line character

### ISSUE THREAD

**Issue by aelbore** [evanw/esbuild#725] opened 2021-01-30 06:36 UTC
```
(async function() {
  const esbuild = require('esbuild')
  const mockfs = require('mock-fs')

  const str = `export const str = 'Hello \n World'`

  mockfs({
    './fixtures/index.ts': str
  })

  const result = await esbuild.transform(str, {
    loader: 'ts',
    sourcefile: './fixtures/index.ts',
    sourcemap: true
  })

  console.log(result)

})()
```

when you remove '\n' character it will work as expected

![image](https://user-images.githubusercontent.com/18069807/106349471-f9658400-6308-11eb-8cd2-2fdce18c134a.png)

**Comment by evanw** [comment] 2021-01-30 07:53
I'm confused. It looks like you're saying you tried to compile a file that looks like this and esbuild gave you an error:

```js
export const str = '
//# sourceMappingURL=data:application/json;base64,' 
```

But that's not valid JavaScript syntax, so it's correct to treat this as a syntax error. Am I misunderstanding something?

**Comment by aelbore** [comment] 2021-01-30 08:02
@evanw if you have

hello.js
```
export const str = 'Hello \n World'
```
this code has an error

**Comment by evanw** [comment] 2021-01-30 08:08
But doesn't this code:

```js
  const str = `export const str = 'Hello \n World'`

  mockfs({
    './fixtures/index.ts': str
  })
```

result in a file that looks like this?

```js
export const str = 'Hello 
 World'
```

**Comment by aelbore** [comment] 2021-01-30 08:11
what i mean is if you compile the code above it throws an error in transform, 

```
  const result = await esbuild.transform(`export const str = "Hello \n World"`, {
    loader: 'ts',
    sourcefile: './fixtures/index.ts',
    sourcemap: true
  })
```

**Comment by evanw** [comment] 2021-01-30 08:18
But the code you're trying to transform has a syntax error. That's why esbuild reports a syntax error. The `\n` is the cause of the syntax error in your code. Any other JavaScript transformation library would also give you a syntax error on that code. Are you forgetting to escape the newline? Did you mean to type `\\n` instead?

**Comment by aelbore** [comment] 2021-01-30 08:25
i tried to execute that code using ts-node and node it works fine it doesn't have error, 
i tried to use swc to transform that code, theres not error.

**Comment by evanw** [comment] 2021-01-30 08:32
Running this code in node:

```js
require('child_process').execFileSync('node', ['--input-type=module'], {
  input: `export const str = "Hello \n World"`
})
```

gives this error:

```js
export const str = "Hello 
                   ^^^^^^^

SyntaxError: Invalid or unexpected token
```

**Comment by aelbore** [comment] 2021-01-30 08:43
![image](https://user-images.githubusercontent.com/18069807/106351922-4867e500-631a-11eb-916b-399ce98ea321.png)

**Comment by evanw** [comment] 2021-01-30 08:47
Using `\n` in a JavaScript template string inserts the newline character, not the literal characters `\n`. If you want the string to contain the characters `\n` you have to escape the backslash with `\\n`:

```js
> console.log(`export const str = "Hello \n World"`)
export const str = "Hello 
 World"

> console.log(`export const str = "Hello \\n World"`)
export const str = "Hello \n World"
```

I'm going to close this because this is not an issue with esbuild. You can read more about how escape sequences in JavaScript strings work [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String#escape_notation).

**Comment by aelbore** [comment] 2021-01-30 08:48
@evanw  thanks no worries you can close this. and appreciate for your time

**Closed by evanw** 2021-01-30 08:47 UTC
