### ISSUE TITLE
Support new TypeScript syntax - getters/setters in non-class scopes

### ISSUE THREAD

**Issue by RyanCavanaugh** [evanw/esbuild#1083] opened 2021-03-29 21:46 UTC
Title speaks for itself but here's an example of what's now legal in TS 4.3:
```ts
interface X {
  get foo(): string;
  set foo(v: string | number);
}
type Y = {
  get bar(): string;
  set bar(v: string | number);
}
```

See https://github.com/microsoft/TypeScript/issues/43420 for more details and to discuss further

**Comment by evanw** [comment] 2021-03-29 22:51
Thanks for reaching out! However, this syntax is already supported so no changes to esbuild are necessary. Closing as this is already working as intended.

**Closed by evanw** 2021-03-29 22:51 UTC

**Comment by RyanCavanaugh** [comment] 2021-03-29 22:58
Thanks!
