### ISSUE TITLE
v0.10.2 appears to produce circular references where `__commonJS` is not defined

### ISSUE THREAD

**Issue by pheuter** [evanw/esbuild#1070] opened 2021-03-27 21:27 UTC
```
TypeError: undefined is not a function (near '...__commonJS...')
```

<img width="781" alt="image" src="https://user-images.githubusercontent.com/92698/112735211-efcf5580-8f20-11eb-92eb-9e6f0758a1ca.png">

This likely has to do with the breaking changes in v0.10.0, `No longer support module or exports in an ESM file`. I'm guessing at some point in the dependency chain there's an `isarray` npm module being required and it has some problematic usage of module exports?

The problem is I have no control over this particular dependency.

**Comment by pheuter** [comment] 2021-03-27 21:29
**UPDATE:** Upon further debugging, it appears that this issue only comes up in v0.10.2, and appears to work find in v0.10.0.

**Comment by evanw** [comment] 2021-03-27 21:34
Is it possible to provide a code sample that would allow me to reproduce the problem?

**Comment by pheuter** [comment] 2021-03-27 21:54
Having difficulties reproducing in an isolated code sample, but have some more info from digging deeper.

Two files are being used: `index.js` and `chunk-xyz.js`:

**index.js** (sample from top of file)

```js
import {
  DeveloperMode,
  PrivateRoute,
  ProvideAuth,
  QueryClientProvider,
  React,
  Subscribable,
  __commonJS,
  __toModule,
  _extends,
  _inheritsLoose,
  _objectWithoutPropertiesLoose,
  // ... more app-specific dependencies
} from "/build/chunk-xyz";

// ../node_modules/isarray/index.js
var require_isarray = __commonJS((exports, module) => { // NOTE: this is where the error is thrown
  module.exports = Array.isArray || function(arr) {
    return Object.prototype.toString.call(arr) == "[object Array]";
  };
});
```

**chunk-xyz.js** (sample from top of file)

```js
import {
  Route,
  define_BUILD_ENV_default,
  useMutation
} from "/build//.//index.js";
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __markAsModule = (target) => __defProp(target, "__esModule", {value: true});
var __commonJS = (cb, mod) => () => (mod || cb((mod = {exports: {}}).exports, mod), mod.exports);
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, {get: all[name], enumerable: true});
};
```

If I'm understanding correctly, there's a possible circular reference here between **index.js** and **chunk-xyz.js**, so when index depends on `__commonJS` coming from chunk, it isn't actually defined yet?

**Comment by evanw** [comment] 2021-03-27 23:05
The bug here seems to be that a circular reference is generated in the first place. I believe one shouldn't ever be generated at all. The bug is presumably something to do with the `Route`, `define_BUILD_ENV_default`, and `useMutation` imports. If these symbols are used from another entry point other than `index.js`, then they should be moved into the shared output file `chunk-xyz.js` instead of residing in the entry point output file `index.js`. Unfortunately this is going to be tough for me to fix without a way to reproduce it myself. I checked and I can't reproduce this on any of my test projects.

Independent of that, this part of your reply also had me confused:

> Two files are generated: `index.js` and `chunk-xyz.js`:

Is that true? If so, are you attempting to load `chunk-xyz.js` instead of loading `index.js`? That would give you this error:

```
$ cat index.mjs 
import { __commonJS } from "./chunk-xyz.mjs";
var require_isarray = __commonJS();

$ cat chunk-xyz.mjs 
import "./index.mjs";
export var __commonJS = () => {};

$ node index.mjs 

$ node chunk-xyz.mjs 
index.mjs:2
var require_isarray = __commonJS();
                      ^

TypeError: __commonJS is not a function
```

But the entry point `index.js` should be loaded first because it's the entry point.

**Comment by pheuter** [comment] 2021-03-27 23:23
I have a single entrypoint:

```js
entryPoints: ['./src/index.tsx'],
bundle: true,
splitting: true,
format: 'esm'
```

that's loaded like so:

```html
<body>
  <div id="app"></div>
  <script src="build/index.js" type="module"></script>
</body>
```

Within that entrypoint, I do make use of lazy loading to create chunks for routes that have large dependencies, like the Dashboard view that pulls in a charting library:

```tsx
import './styles/base.css';

const Dashboard = lazy(() => import('./modules/Dashboard'));

function App() {
  return (
    <Route path="/dashboard">
      <Dashboard />
    </Route>
  );
}
```

After esbuild runs, it generates all of these files:

- `index.js`
- `index.css`
- `chunk-xyz.js`
- `modules/Dashboard/index.js`

Both `index.js` and `modules/Dashboard/index.js` import from `chunk-xyz.js`, and for some reason at the very top of chunk it imports those 3 items you called out from the top level `index.js`.

**Comment by pheuter** [comment] 2021-03-28 14:19
One weird thing I'm noticing is simply changing the name of one of my global define variables removes it from the chunk `import`:

In esbuild config:

```js
define: {
    global: JSON.stringify({}),
    'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV),
    __VERSION__: JSON.stringify(packageJson.version),
    __COMMIT_HASH__: JSON.stringify(commitHash),
    __BUILD_DATE__: JSON.stringify(new Date()),
    __BUILD_ENV__: JSON.stringify(clientBuildEnv)
```

Top of chunk:

```js
import {
  Route,
  define_BUILD_ENV_default,
  useMutation
} from "/build//.//index.js";
```

And then top of chunk after renaming `__BUILD_ENV__` to `__BUILDENV__`:

```js
```

**Comment by ggoodman** [comment] 2021-03-29 20:34
I'm also observing this issue but also don't have a small reproduction (yet).

Perhaps it's worth noting that I have a circular dependency loop but for type-only imports. @evanw maybe that bit of info could help identify the issue.

**Comment by pheuter** [comment] 2021-03-30 12:15
It looks like v0.11.2 fixes the issue I was having on v0.10.2 with no code changes in the app. There's still a couple of imports at the top of `chunk.js` but it no longer results in any runtime errors.

**Comment by evanw** [comment] 2021-04-03 21:33
This is likely a duplicate of #1081.

**Comment by evanw** [comment] 2021-04-03 21:46
Could you check again with version 0.11.5? I suspect that this issue will be resolved by the latest release.

**Comment by pheuter** [comment] 2021-04-04 15:08
@evanw 0.11.5 works 👍

**Comment by pheuter** [comment] 2021-04-04 15:08
fwiw it worked in 0.11.2 as well

**Comment by evanw** [comment] 2021-04-07 08:31
Closing as it sounds like this has been fixed.

**Closed by evanw** 2021-04-07 08:31 UTC
