### ISSUE TITLE
Runtime helper library

### ISSUE THREAD

**Issue by intrnl** [evanw/esbuild#284] opened 2020-07-22 08:35 UTC
A runtime helper library like `tslib` and `babel-runtime`

This can help deduplication when used in other bundlers like Webpack or Rollup, especially for libraries bundled with esbuild where it has the same runtime helper dependency.

**Comment by evanw** [comment] 2021-05-06 02:34
Closing as a duplicate of #1230. Even though this issue came first, that issue has more information and a longer discussion, so I'm going to keep that one open instead.

**Closed by evanw** 2021-05-06 02:34 UTC
