### ISSUE TITLE
Question: Build for browser with external modules in a folder?

### ISSUE THREAD

**Issue by Alex134831** [evanw/esbuild#3563] opened 2023-12-26 21:57 UTC
Hello

I want to build an app for browser and have its dependencies (**and** their dependencies) in a folder like `dist/libs/` separately. I don't want to merge anything. Of course this would need to update all import targets as well. Is this possible? If I need to make a plugin myself, what methods should I use?

**Comment by hyrious** [comment] 2023-12-27 01:58
What you're asking for is #708, which is not implemented in esbuild. You may use rollup instead to do so.

**Comment by evanw** [comment] 2023-12-27 18:45
You can probably manage to do this yourself. To rewrite import paths in a given file, you can enable bundling and then make each non-entry import an external path. And then you can use a queue that continues creating new entry points for each unique resolved module path and running more bundling operations until everything is processed. But it could make more sense to use a tool with built-in support for that. In any case, I can close this as a duplicate of #708.

**Closed by evanw** 2023-12-27 18:45 UTC
