### ISSUE TITLE
False report native module

### ISSUE THREAD

**Issue by yovanoc** [evanw/esbuild#2148] opened 2022-04-01 12:40 UTC
<img width="1164" alt="image" src="https://user-images.githubusercontent.com/7302317/161265449-c06ef0f4-e4dc-4e37-88e9-baca2236d332.png">

I think its a false report for the `.node` files ?

**Comment by evanw** [comment] 2022-04-01 17:25
It looks like the problem is that the plugin `native-node-modules` didn't set a resolve directory for the file `node-file:/Users/devchris/code/nodejs/adonis/adonis/node_modules/@jsdevtools/ono/esm/isomorphic.node.js`. This is a problem with the plugin. Documentation is here: https://esbuild.github.io/plugins/#on-load-results. I have copied the relevant part of the documentation here for you below:

> * `resolveDir`
>
>     This is the file system directory to use when resolving an import path in this module to a real path on the file system. For modules in the `file` namespace, this value defaults to the directory part of the module path. Otherwise this value defaults to empty unless the plugin provides one. If the plugin doesn't provide one, esbuild's default behavior won't resolve any imports in this module. This directory will be passed to any [on-resolve callbacks](https://esbuild.github.io/plugins/#on-resolve) that run on unresolved import paths in this module.

The part that says "If the plugin doesn't provide one, esbuild's default behavior won't resolve any imports in this module" is why this is happening.

I'm closing this issue as invalid because the error message is correct.

**Closed by evanw** 2022-04-01 17:25 UTC

**Comment by yovanoc** [comment] 2022-04-01 17:28
The fact is that is not a native module? Maybe I’m missing something but I think the plugin take it because of the ‘.node’ part in the name but is just a simple js file

**Comment by yovanoc** [comment] 2022-04-01 18:03
Oh yes it was not me but tsup. I will look this way, sorry for bothering.
