### ISSUE TITLE
Support printer minify ascii_only

### ISSUE THREAD

**Issue by ycjcl868** [evanw/esbuild#112] opened 2020-05-15 07:42 UTC
![image](https://user-images.githubusercontent.com/13595509/82024692-bc962600-96c2-11ea-8205-dccd6342308c.png)

**Comment by evanw** [comment] 2020-05-15 08:18
I believe this is a duplicate of [#70: Add an ASCII-only output mode](https://github.com/evanw/esbuild/issues/70).

I definitely agree that this feature should be added. But I'm curious: why do you need this? I'm asking because I've never run into this situation myself. Are you unable to serve your JavaScript as UTF-8? Do you need to use some other code page instead? Or is there another tool you want to use on the generated JavaScript that doesn't support UTF-8? Or is that not the issue and it's more of an aesthetic preference?

**Comment by evanw** [comment] 2020-05-18 21:50
Closing as a duplicate.

**Closed by evanw** 2020-05-18 21:50 UTC
