### ISSUE TITLE
Removes unescaped backslashes

### ISSUE THREAD

**Issue by Valexr** [evanw/esbuild#3014] opened 2023-03-22 12:32 UTC
input
```js
`pattern="^\w+"`;
```

output
```js
`pattern="^w+"`;
```

It's normally?

[Esbuild](https://hyrious.me/esbuild-repl/?version=0.17.12&mode=transform&input=%60pattern%3D%22%5E%5Cw%2B%22%60%3B)

[Rollup](https://rollupjs.org/repl/?version=3.20.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMiU2MHBhdHRlcm4lM0QlNUMlMjIlNUUlNUMlNUN3JTJCJTVDJTIyJTYwJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlMkMlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJvdXRwdXQlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiU3RCUyQyUyMnRyZWVzaGFrZSUyMiUzQWZhbHNlJTdEJTdE)

**Comment by evanw** [comment] 2023-03-22 17:15
Those two expressions are completely equivalent in JavaScript, so esbuild is not incorrect in removing the backslash:

```
$ node -p '`pattern="^\w+"`'
pattern="^w+"

$ node -p '`pattern="^w+"`' 
pattern="^w+"
```

I'm closing this issue as this is not a bug with esbuild.

If you want to preserve the backslash here you can use [`String.raw`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/raw), which exists for exactly this purpose:

```
$ node -p 'String.raw`pattern="^\w+"`'
pattern="^\w+"

$ node -p 'String.raw`pattern="^w+"`' 
pattern="^w+"
```

**Closed by evanw** 2023-03-22 17:15 UTC
