### ISSUE TITLE
Sourcemap's sources location and tree shaking

### ISSUE THREAD

**Issue by grimly** [evanw/esbuild#1928] opened 2022-01-11 11:55 UTC
Hello,

First of all, thank you for this wonderful tool, the feel of going from 40s to 1s builds is just amazing.

One issue I had with my previous tool was sourcemaps. To make it simple, I had no support from it at all (we had a really low time invested in our tools).
Currently with esbuild I can finally see the original sources from dependencies which by itself is already a big win.

Now to make it perfect I would foresee the following improvements :

### Context

Let's say you have a `@local/calculator` application which depends on a `@local/math` library. 

The `@local/calculator` module only uses one operation from the `@local/math` library as follow:

```typescript
import { add } from "@local/math";

console.log('Long calculus result is', add(12, 30));
```

The treeshake works well and only includes the `add` function in the bundle.
Today the sourcemap I get when building looks like the following.
*Note: I kept only the `sources` and `sourcesRoot` entries as they are the only relevant entries to my issue.*

From `@local/math`

```json
{
  "sources": ["../../src/add.ts", "../../src/div.ts", "../../src/mult.ts", "../../src/sub.ts"],
  "sourceRoot": "@local/math/dist/esm"
}
```

From `@local/calculator`

```json
{
  "sources": ["../../node_modules/@local/math/src/add.ts", "../../node_modules/@local/math/src/div.ts", "../../node_modules/@local/math/src/mult.ts", "../../node_modules/@local/math/src/sub.ts", "../../src/index.ts"],
  "sourceRoot": "@local/calculator/dist/esm"
}
```

### Sourcemap tree shaking

Just like the bundle, I would expect the `sub`, `mult` and `div` functions to be excluded from the `@local/calculator` source maps as they are never referenced in the mappings.

### ~~Sourcemap source location persistence~~ (check the comment below)

The `@local/math` exports in its sourcemap, and after resolution using `sourceRoot`, the sources for `@local/math/add.ts`, `@local/math/sub.ts` and so on.
I would expect these to be persisted instead of being relocated to `@local/calculator/node_modules/@local/math/add.ts` and so on.

I do not have in mind a use-case where such relocation has its use. It would even be harmful if you consider a larger dependency tree where a library is used several times.

**Comment by grimly** [comment] 2022-01-12 00:10
After more thoughts given to it, I think my issue with "Sourcemap source location persistence" is WAI.

Here is the use case :
* Three parts A, B and C
* B depends on A
* C depends on A and B
* B produces a bundle that includes A
* C produces a bundle that includes all of its dependencies
* B and C depends on different versions of A

In the above case, it would be legitimate to have `C/node_modules/B/node_modules/A` and `C/node_modules/A` with different content.

The sourcemap tree shaking still stands but would be of a low priority as it doesn't provide big improvements.

**Comment by evanw** [comment] 2022-01-12 16:21
> _Note: I kept only the sources and sourcesRoot entries as they are the only relevant entries to my issue._

The contents of the files appears to be relevant to the issue because I can't reproduce the issue without them. Here's what I tried:

```
$ cat \@local/calculator/index.ts 
import { add } from "@local/math";
console.log('Long calculus result is', add(12, 30));

$ cat \@local/math/index.ts 
export { add } from "./add";
export { sub } from "./sub";
export { mult } from "./mult";
export { div } from "./div";

$ cat \@local/math/add.ts 
export let add = (a: number, b: number) => a + b;

$ cat \@local/math/sub.ts 
export let sub = (a: number, b: number) => a - b;

$ cat \@local/math/mult.ts 
export let mult = (a: number, b: number) => a * b;

$ cat \@local/math/div.ts 
export let div = (a: number, b: number) => a / b;

$ NODE_PATH="`pwd`" esbuild --bundle --sourcemap @local/calculator --outfile=out.js

$ cat out.js.map 
{
  "version": 3,
  "sources": ["@local/math/add.ts", "@local/calculator/index.ts"],
  "sourcesContent": ["export let add = (a: number, b: number) => a + b;\n", "import { add } from \"@local/math\";\nconsole.log('Long calculus result is', add(12, 30));\n"],
  "mappings": ";;AAAO,MAAI,MAAM,CAAC,GAAW,MAAc,IAAI;;;ACC/C,UAAQ,IAAI,2BAA2B,IAAI,IAAI;",
  "names": []
}
```

**Comment by evanw** [comment] 2022-01-20 18:35
Marking as unactionable due to lack of information.

**Comment by evanw** [comment] 2022-02-16 20:21
Closing due to lack of a response.

**Closed by evanw** 2022-02-16 20:21 UTC
Labels: unactionable
