### ISSUE TITLE
Error external library not found

### ISSUE THREAD

**Issue by wanbinkimoon** [evanw/esbuild#1632] opened 2021-09-23 13:35 UTC
My code look like this 
```
esbuild
  .build({
    entryPoints: ['src/index.ts'],
    outdir: 'lib',
    bundle: true,
    sourcemap: true,
    minify: true,
    splitting: true,
    format: 'esm',
    // format: 'cjs',
    target: ['esnext'],
    external: ['react'],
    plugins: [vanillaExtractPlugin()]
  })
  .catch(e => {
    console.error(e);
    return process.exit(1);
  });
```

while building `esbuild` won't do it because of this errors 

```
error: Could not resolve "react" (mark it as external to exclude it from the bundle)
    1 │ import React, { ComponentProps, useMemo } from 'react';
```

**Comment by evanw** [comment] 2021-09-23 13:49
I can't reproduce that error. Here's what I tried:

```
$ cat package.json 
{
  "dependencies": {
    "@vanilla-extract/css": "1.6.0",
    "@vanilla-extract/esbuild-plugin": "2.0.0",
    "esbuild": "0.13.2",
    "react": "17.0.2"
  }
}

$ cat src/index.ts 
import React, { ComponentProps, useMemo } from 'react';
export let ExampleComponent = () => React.createElement("div", null);

$ cat run.js 
const esbuild = require('esbuild');
const { vanillaExtractPlugin } = require('@vanilla-extract/esbuild-plugin');

esbuild
  .build({
    entryPoints: ['src/index.ts'],
    outdir: 'lib',
    bundle: true,
    sourcemap: true,
    minify: true,
    splitting: true,
    format: 'esm',
    // format: 'cjs',
    target: ['esnext'],
    external: ['react'],
    plugins: [vanillaExtractPlugin()]
  })
  .catch(e => {
    console.error(e);
    return process.exit(1);
  });
  
$ node run.js 
```

No esbuild errors happen when I do this. So more information would be needed to reproduce and fix the problem. One thing to try is to remove `plugins: [vanillaExtractPlugin()]`. If that fixes that error, then the problem is likely with the plugin instead of with esbuild itself.

**Comment by wanbinkimoon** [comment] 2021-09-23 16:46
Sorry I messed some context, my issue is that if react is included int he dependencies is still included in the bundle.

**Comment by evanw** [comment] 2021-11-22 21:52
Closing due to age.

**Closed by evanw** 2021-11-22 21:52 UTC
