### ISSUE TITLE
esbuild adding bind functions to the build

### ISSUE THREAD

**Issue by iamaamir** [evanw/esbuild#1889] opened 2021-12-28 09:59 UTC
not sure if this is expected and why is this happening 
so if you define a function as binding and export it from a file esbuild adding that function to the build even when there is no import to it

see the left side of the image where i am defining my bindings 
and on the right they being included

![image](https://user-images.githubusercontent.com/8420386/147554084-d8534529-5cb8-4373-8783-019fc764bb56.png)

**Comment by hyrious** [comment] 2021-12-28 10:05
This is because esbuild treats property access (`console.log`) and function call (`.bind()`) as side effects. All side effects are kept unless you manually mark them as pure:

```js
export const log = /* @__PURE__ */ console.log.bind(console)
```

**Comment by evanw** [comment] 2021-12-29 08:01
Yes, this is expected. As an additional data point, many other JavaScript tools also don't consider `.bind()` to be side-effect free without `/* @__PURE__ */`, including UglifyJS, Terser, and Rollup. Marking these as `/* @__PURE__ */` is the recommended way to do this, especially since that means it'll automatically be compatible with most other tools in the JavaScript ecosystem. Closing as working as intended.

**Closed by evanw** 2021-12-29 08:01 UTC
