### ISSUE TITLE
[question] switching branches causes build to fail and stop producing results

### ISSUE THREAD

**Issue by ZuBB** [evanw/esbuild#3364] opened 2023-09-03 21:30 UTC
disclaimer: I definitely faced a bug, but not sure which bit of software is buggy. 1st thing is to diagnose it.

I can't share a repository so will post meaningful bits of code here

```json
  "devDependencies": {
    "autoprefixer": "^10.4.14",
    "chokidar": "^3.5.3",
    "esbuild": "~0.18.20",
    "esbuild-plugin-clean": "^1.0.1",
    "esbuild-sass-plugin": "^2.10.0",
    "postcss": "^8.4.27"
  },
```
base config
```js
const baseESBuildOptions = {
  logLevel: 'info',
  bundle: true,
  entryPoints: getEntryPoints(),
  outdir: 'static/css',
  banner: {},
  external: [
    '*.svg',
    'images/*'
  ],
  plugins: [
    clean({
      patterns: ['./static/css/*']
    }),
    sassPlugin({
      async transform(source) {
        const { css } = await postcss([autoprefixer]).process(source, { from: undefined });
        return css;
      },
    }),
  ]
};
```

I have several `.scss` entry points; all the build is doing is building those entry points to the final `.css`.

The `main` branch has a file at the 2nd level of dependency, and in the feature branch, it got deleted. When I switch from the `main` to the feature, I get a trace (see screen), and after that, ESbuild stops to build. Even if I add new changes and save files

<img width="1728" alt="image" src="https://github.com/evanw/esbuild/assets/597016/acffa390-c547-4ab0-897f-918a56668740">

----

So the question is next: Is it a buggy plugin, or is this something that can be improved in ESbuild? Or because of this transition between branches, it is hard to find a good solution here...

**Comment by evanw** [comment] 2023-09-03 22:56
In general, if you mutate the file system during a build (any kind of build), that build could fail. File system changes are not atomic and build tools generally expect the file system to be in a self-consistent state. This is not bug with the build tool. It just means you are running the build tool on a partially-updated file system.

If you are building repeatedly in response to file system changes, then you can just ignore errors that happen during a branch switch because the following file system changes will trigger another build. The build that starts after the last file system change (i.e. after the branch switch) should succeed. Again all of this is general to any build system and is not specific to esbuild.

> and after that, ESbuild stops to build

Since the image you posted contains the text `chokidar`, I assume you are rolling your own watch mode and not using esbuild's watch mode. So I'm assuming that a build error breaking the build is a bug with your custom watch mode code and not a bug with esbuild.

**Comment by ZuBB** [comment] 2023-09-04 03:05
> Since the image you posted contains the text chokidar, I assume you are rolling your own watch mode and not using esbuild's watch mode. So I'm assuming that a build error breaking the build is a bug with your custom watch mode code and not a bug with esbuild.

My setup is somehow unusual. I have 3 types of content: scss, js, and html. Only scss is being handled (watch & build) by ESbuild. The Django app serves all those. I have only a small JS snippet in the browser that does 2nd part of the reload feature
```
        (() => new EventSource("http://127.0.0.1:8082").onmessage = () => location.reload())();
```
And on the "backend" I do a dummy write to that address (I can provide full config if you really need it)

On the screenshot, you see 3 lines after the crash itself. The thing is, 1st line (ESbuild-related) has been printed alongside the crash output itself (but no assets have been produced). The next items appeared because I edited html, and chokidar spotted that. Any further changes to scss files do not trigger new cycles of esbuild work. So, I have to restart my build script, though chokidar's part still works

**Comment by ZuBB** [comment] 2023-09-04 03:10
I am OK with having one cycle fail because of crucial changes in content on FS. But I really would like to see the next cycles work as intended.

However, I do admit this whole thing may/should be considered an edge case.

**Comment by evanw** [comment] 2023-09-04 11:42
If your watch mode implementation triggers a build when `header.scss` doesn't yet exist (because a branch switch is in progress) and it fails, then your watch mode implementation should also trigger another build after that when `header.scss` exists (because the branch switch has finished). If it doesn't do that, then that's a bug with your watch mode implementation. That's not a problem with esbuild.

> Any further changes to scss files do not trigger new cycles of esbuild work.

Is your watch mode implementation perhaps not catching exceptions properly, and then failing to continue to watch?

In any case, I'm closing this issue because it doesn't seem like a bug with esbuild. You also didn't provide a way to reproduce the issue so it's impossible to determine if it is a problem with esbuild or not.

**Closed by evanw** 2023-09-04 11:42 UTC

**Comment by ZuBB** [comment] 2023-09-04 15:31
I feel that my inability to share the code directed you to probably false assumptions. I do understand that a repro would be the best solution here, but right now, I can't do that. What I can do right now is to share a build script. It is not a rerpo, but it should demonstrate that my custom watcher has nothing to do with esbuild.

https://gist.github.com/ZuBB/943abd9cdd5ed21f8b6d24a0ebfe5db5

I will try to craft repro in next days

**Comment by ZuBB** [comment] 2023-09-05 20:27
for all who will find this later: I have replaced `esbuild-sass-plugin` with a simple sass plugin I used before, and I do not have this error. I am going to report this to the plugin's repo

**Comment by ZuBB** [comment] 2023-09-05 22:10
@evanw could you please take a look at repro I have mentioned above?
