### ISSUE TITLE
Node: Support `esbuild/register` hook?

### ISSUE THREAD

**Issue by lukeed** [evanw/esbuild#260] opened 2020-07-16 01:39 UTC
Hey!

Are you interested in offering an `esbuild/register` hook, or should I plan on creating my own package for this? (Willing to PR)

The idea is to take the place of these:

```sh
$ node -r ts-node/register example.ts
$ node -r esm example
```

Since esbuild can fill the same role, it would make sense for this to exist. Nearly all `ts-node/register` use cases are only transpiling ([example](https://github.com/lukeed/uvu/blob/master/examples/typescript/package.json#L5)).

You'll also see this a lot with `@babel/register` once JSX is involved ([example](https://github.com/lukeed/uvu/blob/master/examples/preact/package.json#L4)).

Don't recall if esbuild can read a config file, but like the rest of these, the register hook would pick up & apply config to all files.

Thanks!

**Comment by egoist** [comment] 2020-07-16 08:05
I made https://github.com/egoist/esbuild-register but it requires `esm` too, btw this seems like a duplicate of #148

**Comment by evanw** [comment] 2020-07-16 19:12
Yes, closing as a duplicate of #148. Since ts-node looks kind of complicated, I think it would be good for people to experiment with "register" functionality outside of esbuild core in an independent package.

**Closed by evanw** 2020-07-16 19:12 UTC
