### ISSUE TITLE
esbuild 0.14.35 Error

### ISSUE THREAD

**Issue by chenli1989** [evanw/esbuild#2176] opened 2022-04-12 03:36 UTC
vite@2.9.1
vue@3.2.31
@ant-design/icons-vue@6.1.0

**esbuild@0.14.35** ❌
**[ERROR]**
![截屏2022-04-12 11 29 21](https://user-images.githubusercontent.com/8178749/162874932-8e62630e-94e3-4df2-b152-b5febdf741ec.png)

Fallback version
**esbuild@0.14.34** ✅

**Comment by agileago** [comment] 2022-04-12 03:38
the same problem

**Comment by iamoldli** [comment] 2022-04-12 04:28
+1

**Comment by evanw** [comment] 2022-04-12 06:29
Closing as a duplicate of #2177.

**Closed by evanw** 2022-04-12 06:29 UTC
