### ISSUE TITLE
esbuild sometimes produces chunks with same hashes but different contents

### ISSUE THREAD

**Issue by iamakulov** [evanw/esbuild#1076] opened 2021-03-28 13:55 UTC
While investigating into https://github.com/evanw/esbuild/issues/1075, I stumbled upon a chunk _with the same hash but different content_. The only difference between chunks was the name of the dynamic import:

<img width="962" alt="Screen Shot 2021-03-28 at 17 48 07" src="https://user-images.githubusercontent.com/2953267/112754589-c4ff0300-8fed-11eb-894e-3356143e38e6.png">

Unlike #1075 which simply worsens cacheability, this might break a live app if the developer deploys a new version where `./exportSandbox.K6EQ6MKU.js` is no longer present.

Would a repro for this be useful? I believe a minimal reproducible repro for this would also be hard to compose (it reproduces on the Framer codebase – but not with every build config), but I could try.

**Comment by evanw** [comment] 2021-03-28 18:45
> Would a repro for this be useful? I believe a minimal reproducible repro for this would also be hard to compose (it reproduces on the Framer codebase – but not with every build config), but I could try.

Yes it would be very useful as I can't reproduce this either. Although it could turn out that this is the same underlying issue as #1075, so we should probably just try to solve one of them first if this is a lot of work.

**Comment by GoodForOneFare** [comment] 2021-04-08 01:33
I may have run into a similar bug. Here's a repo that demonstrates what I'm running into: https://github.com/GoodForOneFare/esbuild-hashing-test

**Comment by evanw** [comment] 2021-04-11 00:18
Thanks for the test case. It looks like the cause of this is just that the chunk dependency traversal was only following static imports, not dynamic imports. Sorry about that. This will be fixed to follow dynamic imports as well, so they will also be included in the hash in the next release.

**Closed** 2021-04-11 00:22 UTC

**Comment by GoodForOneFare** [comment] 2021-04-11 23:56
Just confirming that the latest version works in our real world app  👍  Thanks for this, and for esbuild in general.
