### ISSUE TITLE
when write is false, the build result contains entry and metafile

### ISSUE THREAD

**Issue by pandagood** [evanw/esbuild#861] opened 2021-02-21 11:26 UTC
Current build result:
```js
{
  warnings: [],
  outputFiles: [
    {
      path: '/Volumes/book/esbuild-react/@modules/react.js',
      contents: [Uint8Array],
      text: [Getter]
    },
    ...
  ]
}
```

Expected build result:
```js
{
  warnings: [],
  outputFiles: [
    {
      entry: "react",
      filepath: '/Volumes/book/esbuild-react/node_modules/react/index.js',   // file path
      path: '/Volumes/book/esbuild-react/@modules/react.js',      // output path
      contents: [Uint8Array],
      text: [Getter]
    },
    metafile:{
      ...
    }
    ...
  ]
}
```

This is convenient when I want to customize the content and structure of the output.

**Comment by evanw** [comment] 2021-02-21 11:33
Yes, I agree. This is a breaking change though so it is being held back until the next breaking change release. Closing as a duplicate of #633.

**Closed by evanw** 2021-02-21 11:33 UTC
