### ISSUE TITLE
Add support tsconfig.json file paths resolving

### ISSUE THREAD

**Issue by MaxmaxmaximusAWS** [evanw/esbuild#1212] opened 2021-04-27 15:56 UTC
"bundle" option is false

tsconfig.json:
```json
{
	"compilerOptions": {
		"target": "es5",
		"lib": [
			"dom",
			"dom.iterable",
			"esnext"
		],
		"allowJs": true,
		"skipLibCheck": true,
		"strict": false,
		"forceConsistentCasingInFileNames": true,
		"noEmit": true,
		"esModuleInterop": true,
		"module": "esnext",
		"moduleResolution": "node",
		"resolveJsonModule": true,
		"isolatedModules": true,
		"jsx": "preserve",
		"baseUrl": ".",
		"paths": {
			"@lib": [
				"src/lib"
			],
			"@lib/*": [
				"src/lib/*"
			],

		}
	},
	"include": [
		"next-env.d.ts",
		"**/*.ts",
		"**/*.tsx"
	],
	"exclude": [
		"node_modules",
		"scripts"
	]
}
```

index.ts:
```typescript
import {lol} from "@lib/lol";
console.log(lol())
```

@lib/lol.ts:
```typescript
export const lol = () => {
	return 'Hello!'
}
```

output file:
```js
import{lol as l}from"@lib/lol";console.log(l());
//# sourceMappingURL=index.js.map
```

but must be:

output file:
```js
import{lol as l}from"./lib/lol";console.log(l());
//# sourceMappingURL=index.js.map
```

**Comment by evanw** [comment] 2021-04-27 19:59
Closing as a duplicate of #394.

**Closed by evanw** 2021-04-27 19:59 UTC
