### ISSUE TITLE
How to transform commonjs to ESM

### ISSUE THREAD

**Issue by bigggge** [evanw/esbuild#768] opened 2021-02-08 03:40 UTC
Before, I did this with Rollup

```  
const bundle = await rollup({
    input,
    plugins: [commonjs({ sourceMap: false })],
  });
  const {
    output: [{ code }],
  } = await bundle.generate({
    exports: "auto",
    format: "es",
  });
```
How can i do the same thing with esbuild?

When i try these code
```
const out = esbuild.buildSync({
    entryPoints: [input],
    format: "esm",
    write: false,
  });
```
but it warning: Converting "require" to "esm" is currently not supported

**Comment by evanw** [comment] 2021-02-08 03:51
Closing as a duplicate of #566. Here is an explanation of why this is not supported: https://github.com/evanw/esbuild/issues/566#issuecomment-735551834. TL;DR it's not always a safe transformation. There is a hack where you can use a plugin to do this transformation in some cases (code is in the linked thread).

**Closed by evanw** 2021-02-08 03:51 UTC
