### ISSUE TITLE
Make peer dependencies external automatically

### ISSUE THREAD

**Issue by raijinsetsu** [evanw/esbuild#727] opened 2021-01-30 16:22 UTC
When listing a dependency as a "peer" in the package.json for module "A", the expectation is that the project/module installing "A" will take care of installing the peers as well.

When using esbuild to bundle module "A", all of the peers are inlined into the output, bloating the NPM module significantly.

We can script a work-around by using the build API but it seems that it would be beneficial for esbuild to automatically "--external" peer dependencies.

**Comment by evanw** [comment] 2021-02-01 03:43
Is there an existing precedent for this? What other bundlers do this?

**Comment by lukeed** [comment] 2021-02-02 15:52
None do this automatically, but the convention is to mark them as externals.

**Comment by raijinsetsu** [comment] 2021-02-02 15:59
Would this be better as a plugin? I haven't looked into what functionality esbuild supports for plugins (or even if it supports them) but it seems like it would be possible so that developers do not need to write this common convention as code each time.

**Comment by lukeed** [comment] 2021-02-02 16:05
This is what I do, since I don't expect any bundler to determine non-native externals for me:

```js
const pkg = require('./package.json');

require('esbuild').buildSync({
  entryPoints: ['input.js'],
  outfile: 'output.js',
  bundle: true,
  external: [
    ...Object.keys(pkg.dependencies),
    ...Object.keys(pkg.peerDependencies || {})
  ],
});
```

**Comment by evanw** [comment] 2021-02-03 12:33
This should be very possible with a plugin. Just use `onResolve` and return `{ path, external: true }` for those dependencies. I'm going to close this since if no bundlers do this automatically, then I don't think esbuild should either. It risks causing confusion due to magic unexpected behavior for people trying out esbuild on existing projects.

**Closed by evanw** 2021-02-03 12:33 UTC

**Comment by adamduncan** [comment] 2021-10-06 17:20
@lukeed Similarly I believe you can use [`esbuild-node-externals`](https://www.npmjs.com/package/esbuild-node-externals) plugin, which will exclude deps from `node_modules`?

```js
require('esbuild').buildSync({
  entryPoints: ['input.js'],
  plugins: [nodeExternalsPlugin()],
  outfile: 'output.js',
  bundle: true,
});
```
