### ISSUE TITLE
Compat babel interop helper code.

### ISSUE THREAD

**Issue by underfin** [evanw/esbuild#1326] opened 2021-05-27 15:49 UTC
# Description

Babel compiled esm code will add  interop module code. This is common usaged at react ecosystem because `create-react-app` use bable compiled code. 
But this interop code will throw error after esbuild bundle. Here is error trace.
```
Uncaught TypeError: Cannot set property default of #<Object> which has only a getter
    at _interopRequireWildcard (Button.js:24)
    at node_modules/primereact/components/button/Button.js (Button.js:8)
    at __require (chunk-GZDVDKT7.js?v=b1e101bf:6)
    at node_modules/primereact/button.js (button.js:3)
    at __require (chunk-GZDVDKT7.js?v=b1e101bf:6)
    at dep:primereact_button:1
```
I tracked this issue found this caused by `__export`, it only add getter for export namespace, here is code.
``` js
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, {get: all[name], enumerable: true});
};
```
Same issue also happend at ts, but https://github.com/microsoft/TypeScript/pull/37236 is fixed this. So i think it should be issue at esbuild.

Original issue: https://github.com/vitejs/vite/issues/3437

## Babel Input
```
import React, { Component } from 'react';
```
## Babel Output
``` ts
var _react = _interopRequireWildcard(require("react"));
function _interopRequireWildcard(obj) {
      if (obj && obj.__esModule) {
        return obj;
      }
      if (obj === null || _typeof(obj) !== "object" && typeof obj !== "function") {
        return {default: obj};
      }
      var cache = _getRequireWildcardCache();
      if (cache && cache.has(obj)) {
        return cache.get(obj);
      }
      var newObj = {};
      var hasPropertyDescriptor = Object.defineProperty && Object.getOwnPropertyDescriptor;
      for (var key in obj) {
        if (Object.prototype.hasOwnProperty.call(obj, key)) {
          var desc = hasPropertyDescriptor ? Object.getOwnPropertyDescriptor(obj, key) : null;
          if (desc && (desc.get || desc.set)) {
            Object.defineProperty(newObj, key, desc);
          } else {
            newObj[key] = obj[key];
          }
        }
      }
     // !! throw error at this line.
      newObj.default = obj;
      if (cache) {
        cache.set(obj, newObj);
      }
      return newObj;
    }
```

**Comment by evanw** [comment] 2021-05-28 00:40
After an initial reading of this code, this seems like a bug in Babel's `_interopRequireWildcard` implementation to me. It seems like the loop should skip copying over the `default` key if it's going to be assigned to after the loop. Otherwise the setter could throw as is the case here.

**Comment by evanw** [comment] 2021-05-28 01:09
Thanks for the link! Ok, I'm going to close this issue as "working as intended" then. This is a Babel bug that has already been fixed, so you need to update your version of Babel.

**Closed by evanw** 2021-05-28 01:09 UTC
