### ISSUE TITLE
Sometimes crashed by goroutine deadlock

### ISSUE THREAD

**Issue by baurine** [evanw/esbuild#1842] opened 2021-12-10 09:24 UTC
Error message:

```
[17:20:33] Starting 'esbuild:build'...
Build started
Build ended: 4858ms
fatal error: all goroutines are asleep - deadlock!
[17:20:42] Finished 'esbuild:build' after 9.27 s
[17:20:42] Finished 'build' after 17 s

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0x0)
        runtime/sema.go:56 +0x25
sync.(*WaitGroup).Wait(0xc0000b8000)
        sync/waitgroup.go:130 +0x71
main.runService(0x1)
        github.com/evanw/esbuild/cmd/esbuild/service.go:138 +0x4cb
main.main()
        github.com/evanw/esbuild/cmd/esbuild/main.go:203 +0x1eb

goroutine 18 [chan receive]:
main.runService.func1()
        github.com/evanw/esbuild/cmd/esbuild/service.go:66 +0x4b
created by main.runService
        github.com/evanw/esbuild/cmd/esbuild/service.go:64 +0x212

goroutine 19 [chan receive]:
main.(*serviceType).sendRequest(0xc0000d2140, {0x80ecc0, 0xc00aea3260})
        github.com/evanw/esbuild/cmd/esbuild/service.go:163 +0xda
main.runService.func2()
        github.com/evanw/esbuild/cmd/esbuild/service.go:92 +0x39
created by main.runService
        github.com/evanw/esbuild/cmd/esbuild/service.go:89 +0x313
Done in 17.36s.
```

It does not always happen, but I met this error several times in 3 weeks.

esbuild version: 0.13.14

**Comment by evanw** [comment] 2021-12-11 19:11
Sorry but there's nothing I can do with this report. You would need to provide a way to reproduce this for me to fix it. Marking as unactionable.

**Comment by baurine** [comment] 2021-12-12 08:37
> Sorry but there's nothing I can do with this report. You would need to provide a way to reproduce this for me to fix it. Marking as unactionable.

understandable.

**Comment by evanw** [comment] 2022-01-06 18:37
I'm going to close this issue since there's nothing I can do here. I'm happy to fix any issues that I can reproduce but I'll need a way to reproduce it.

**Closed by evanw** 2022-01-06 18:37 UTC
Labels: unactionable

**Comment by chrisvariety** [comment] 2022-02-03 04:09
Just ran into this myself. If it's helpful for anyone else, restarting my computer solved it--

**Comment by tanduongfinblox** [comment] 2022-05-20 03:39
I have just run into it. My code run as normal yesterday and today I got this error message:

```
npm run dev

> dev
> concurrently "npm run dev:css" "NODE_ENV=development remix dev"

[0] 
[0] > dev:css
[0] > tailwindcss -w -i ./styles/app.css -o app/styles/app.generated.css
[0] 
[0] 
[0] Rebuilding...
[0] Done in 250ms.
[1] Watching Remix app in development mode...
[1] 💿 Built in 528ms
[1] Remix App Server started at http://localhost:3000 (http://192.168.1.6:3000)
[1] Error: Promise rejected with value: NodeResponse [Response] {
[1]   size: 0,
[1]   [Symbol(Body internals)]: {
[1]     body: null,
[1]     type: null,
[1]     size: 0,
[1]     boundary: null,
[1]     disturbed: false,
[1]     error: null
[1]   },
[1]   [Symbol(Response internals)]: {
[1]     url: undefined,
[1]     status: 302,
[1]     statusText: '',
[1]     headers: {
[1]       location: '/login',
[1]       'set-cookie': '_session=; Path=/; Expires=Thu, 01 Jan 1970 00:00:00 GMT; HttpOnly; SameSite=Lax'
[1]     },
[1]     counter: 0,
[1]     highWaterMark: undefined
[1]   }
[1] }
[1]     at process.<anonymous> (/Users/tanduong/Documents/Code/finblox/monorep/web/app/node_modules/hard-rejection/index.js:15:12)
[1]     at process.emit (node:events:390:28)
[1]     at process.emit (/Users/tanduong/Documents/Code/finblox/monorep/web/app/node_modules/source-map-support/source-map-support.js:516:21)
[1]     at emit (node:internal/process/promises:136:22)
[1]     at processPromiseRejections (node:internal/process/promises:242:25)
[1]     at processTicksAndRejections (node:internal/process/task_queues:97:32)
[1] fatal error: all goroutines are asleep - deadlock!
[1] 
[1] goroutine 1 [semacquire]:
[1] sync.runtime_Semacquire(0x14000113b50)
[1]     runtime/sema.go:56 +0x38
[1] sync.(*WaitGroup).Wait(0x14000113b48)
[1]     sync/waitgroup.go:130 +0xa4
[1] main.runService(0x1)
[1]     github.com/evanw/esbuild/cmd/esbuild/service.go:177 +0x42c
[1] main.main()
[1]     github.com/evanw/esbuild/cmd/esbuild/main.go:207 +0x1f0
[1] 
[1] goroutine 18 [chan receive]:
[1] main.runService.func1(0x14000113b30)
[1]     github.com/evanw/esbuild/cmd/esbuild/service.go:110 +0x58
[1] created by main.runService
[1]     github.com/evanw/esbuild/cmd/esbuild/service.go:108 +0x13c
[1] 
goroutine 19 [chan receive]:
[1] main.(*serviceType).sendRequest(0x14000113b30, {0x104fcd4e0, 0x1400905a330})
[1]     github.com/evanw/esbuild/cmd/esbuild/service.go:203 +0x128
[1] main.runService.func2(0x14000113b30)
[1]     github.com/evanw/esbuild/cmd/esbuild/service.go:132 +0x40
[1] created by main.runService
[1]     github.com/evanw/esbuild/cmd/esbuild/service.go:129 +0x24c
[1] NODE_ENV=development remix dev exited with code 1
```

**Comment by CanRau** [comment] 2022-08-03 22:46
Anyone using Prisma could try `prisma generate` which should fix it according to https://github.com/prisma/prisma/issues/12016

Unfortunately I'm not using Prisma but [better-sqlite3](https://github.com/WiseLibs/better-sqlite3) instead and still run into the exact problem.

It started around a week ago right before vacation and I'm not exactly sure what I did (git won't help much in this case) I've got it temporarily fixed just to crash again and can't get it back working 😰

Sadly it's really hard to tell (for me) from the error what's causing this.
