### ISSUE TITLE
Is it possible to obfuscate the same string with the property when obfuscating the property?

### ISSUE THREAD

**Issue by masx200** [evanw/esbuild#2574] opened 2022-09-27 01:47 UTC
Is it possible to obfuscate the same string with the property when obfuscating the property?

version
0.15.9

```
 npx -y esbuild test.js --mangle-props=_$ --mangle-quoted
```

input 
```js
export default createclass([
    {
        key: "__walk__",
        value: function () {
            console.log(this.__collapse__);
        },
    },
    {
        key: "__collapse__",
        value: function () {
            console.log(this["__walk__"]);
        },
    },
]);
export function createclass(entries) {
    Object.assign(
        constructor.prototype,
        Object.fromEntries(entries.map(({ key, value }) => [key, value]))
    );
    function constructor() {};
   return constructor
}
````
output
```js
export default createclass([
  {
    key: "__walk__",
    value: function() {
      console.log(this.a);
    }
  },
  {
    key: "__collapse__",
    value: function() {
      console.log(this.b);
    }
  }
]);
export function createclass(entries) {
  Object.assign(
    constructor.prototype,
    Object.fromEntries(entries.map(({ key, value }) => [key, value]))
  );
  function constructor() {
  }
  return constructor;
}
```
Expected result
```js
export default createclass([
  {
    key: "l",
    value: function () {
      console.log(this.t);
    },
  },
  {
    key: "t",
    value: function () {
      console.log(this.l);
    },
  },
]);
export function createclass(e) {
  function t() {}
  return (
    Object.assign(
      t.prototype,
      Object.fromEntries(e.map(({ key: e, value: t }) => [e, t]))
    ),
    t
  );
}
```
```

**Comment by evanw** [comment] 2022-09-27 02:13
No, that’s not possible with esbuild.

**Comment by evanw** [comment] 2022-09-29 13:00
Closing as by design. Property mangling in esbuild is a static analysis and requires you to use the properties statically, not dynamically. It's also intentionally designed to work similarly to other tools in the ecosystem.

**Comment by evanw** [comment] 2023-06-05 03:31
I'm reopening this because Terser has since added a way to do this: prefixing a string literal with a `/* @__KEY__ */` comment. More information here: https://github.com/terser/terser/pull/1365. It seems reasonable to do this in esbuild as well.

**Closed** 2023-06-10 15:39 UTC
