### ISSUE TITLE
module resolution fails with pnpm

### ISSUE THREAD

**Issue by hesxenon** [evanw/esbuild#3848] opened 2024-07-26 18:02 UTC
related to #3847 

When trying to solve the above issue with a quick and dirty plugin that just resolves `react-dom` with `node_modules/react-dom/cjs/react-dom.production.min.js` esbuild fails with

```
✘ [ERROR] Could not resolve "scheduler"

    node_modules/react-dom/cjs/react-dom.production.min.js:13:48:
      13 │ 'use strict';var aa=require("react"),ca=require("scheduler");function p(a){for(var b="https://reactjs.org/docs/error-decoder.html?invariant="+a,c=1;c<argume...
         ╵                                                 ~~~~~~~~~~~
```

~~The thing is, that the scheduler package _is_ installed but it's not hoisted since I'm using pnpm. It appears esbuild expects `node_modules/scheduler` but pnpm puts that package in `node_modules/react-dom/node_modules/scheduler`.~~

~~I think the resolution algorithm should start from the file that's trying to import a module, no?~~

**Comment by hesxenon** [comment] 2024-07-26 18:12
I found a solution by resolving to `node_modules/.pnpm/react-dom@18.3.1.../node_modules/react-dom/cjs/react-dom.production.min.js` instead.

I thus think that this issue is just a side-effect of the linked issue since I wouldn't have to do that at all if #3847 wasn't a problem. Feel free to close this if you agree :)

**Comment by evanw** [comment] 2024-07-31 14:33
I'm closing this issue because it doesn't follow the issue reporting instructions. Specifically, it does not provide a way to reproduce the issue.

**Closed by evanw** 2024-07-31 14:33 UTC
