### ISSUE TITLE
Subclass fields being initalized too late

### ISSUE THREAD

**Issue by n3svarbu** [evanw/esbuild#1141] opened 2021-04-12 11:47 UTC
Hello. In this code I'm calling `init()` in a parent constructor that executes it on child as well, but because child constructor was not fully executed, it doesn't have class properties definet yet, and therefore the `SubClass.init()` errors. Shouldn't subclass fields be initialized straight after parent class field are? Not sure if it's expected behaviour, but it works fine building it with babel. I tried using `"useDefineForClassFields": true` in the `tsconfig` but it didn't  seem to help with this matter.

Source:
```typescript
class Test {
	constructor() {
		this.init();
	}

	init() {
		// void or anything
	}
}

class SubTest extends Test {
	some_string : string = 'default_value';
	/*split_string : string[] = [];*/

	init() {
		super.init();
		/*this.split_string = */this.some_string.split('');
	}
}

new SubTest();
```

Generated:
```javascript
  var Test = class {
    constructor() {
      this.init();
    }
    init() {
    }
  };
  var SubTest = class extends Test {
    constructor() {
      super(...arguments);
      this.some_string = "default_value"; // This field is being initialized too late
    }
    init() {
      super.init();
      this.some_string.split(""); // <-- ERRORS HERE
    }
  };
```

I'm aware that by specification we can't user `this` before `super()` in subclasses and that's where this issue comes from. Is there any elegant workaround on this issue?

**Comment by jridgewell** [comment] 2021-04-12 18:42
> Shouldn't subclass fields be initialized straight after parent class field are? Not sure if it's expected behaviour, but it works fine building it with babel.

The transformed code is correct, subclass fields are set _after_ the `super()` constructor call returns. So when the superclass constructor calls `init()` (which is the `SubTest.prototype.init` method), `SubTest`'s fields will not be present yet.

If you evaluate the code without transpiling, you'll see it errors. [Babel also errors](https://babeljs.io/repl/#?browsers=chrome%2070&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAEAqCmEAu0DeAoAkMA9gO2QCcBXYJHQgCgEo0tMkALASwgDpm9mkaBuLAL7osnbjTqZMAeinQAbjmYATaBWhg8ATyacA5oPRD0oSDADKxAEYJk0eAA8k8PEpg2UGTBBwBbeAH0iPWgALmggvF1oAF5oAHIleAAzMGIQJH85MBBieDj-aQAqCAAHEG5ApEJgsIjdAG0AXRjoJt5CqWFMUR5aTy9iEvhCDi5egqKddlLyjLqWjqm2bz9K6sjlsrE4uOoCoSM8eAB3aAtrRHH0IA&debug=false&forceAllTransforms=false&shippedProposals=true&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Ctypescript&prettier=false&targets=&version=7.13.15&externalPlugins=) when transpiling just fields, and when [transpiling everything](https://babeljs.io/repl/#?browsers=chrome%2070&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAEAqCmEAu0DeAoAkMA9gO2QCcBXYJHQgCgEo0tMkALASwgDpm9mkaBuLAL7osnbjTqZMAeinQAbjmYATaBWhg8ATyacA5oPRD0oSDADKxAEYJk0eAA8k8PEpg2UGTBBwBbeAH0iPWgALmggvF1oAF5oAHIleAAzMGIQJH85MBBieDj-aQAqCAAHEG5ApEJgsIjdAG0AXRjoJt5CqWFMUR5aTy9iEvhCDi5egqKddlLyjLqWjqm2bz9K6sjlsrE4uOoCoSM8eAB3aAtrRHH0IA&debug=false&forceAllTransforms=true&shippedProposals=true&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Ctypescript&prettier=false&targets=&version=7.13.15&externalPlugins=).

**Comment by evanw** [comment] 2021-04-12 20:39
The above comment is correct. This is not how JavaScript works. Running the code you provided in node will also crash:

```js
class Test {
  constructor() {
    this.init();
  }

  init() {
    // void or anything
  }
}

class SubTest extends Test {
  some_string = 'default_value';
  /*split_string = [];*/

  init() {
    super.init();
    /*this.split_string = */this.some_string.split('');
  }
}

new SubTest();
```

This crashes with the following error:

```
example.js:17
    /*this.split_string = */this.some_string.split('');
                                             ^

TypeError: Cannot read property 'split' of undefined
```

Closing as working as intended.

**Closed by evanw** 2021-04-12 20:39 UTC

**Comment by n3svarbu** [comment] 2021-04-12 20:40
You are right. I've been working on a project that uses this kind of structure for years and it's compiling fine with babel. I dig deeper and just found that it's the decorators that behave different. [This evaluates fine with legacy decorators](https://babeljs.io/repl/#?browsers=chrome%2070&build=&builtIns=false&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABAJwKYEMAmCA2BPACinWQHNUoAaRMdAW1Ws1QGcJkYAHKOZASkQBvAFCJEzNh268AdAHcOxAEY5UiALyJg6HC1QBuUYmJkKAbVoMAuhvGt2XHshkwwMWDpgAvVMgJ9DMTQoEGQkCQdpZEMAX2FhCBx0FhZEABVWKCFhAEgIBBYoZBBoXn9snJyoAAsYFhc3KH9DHLjc13dykUqAeh7EADc4GExEXkR0MDwa11JcuLbE5NSAZRAlDMLEVAAPKFQwTFTNrO6AATQsXDxEFjgGAH1CjjBSRAAuW6LZ2wByZm0IBwUAeAx0IFQvxaPQAVCxODh3E9vq8Pl8XqQzDZNFj9DCevEch0mgJujkWCBOL4Gp0ArkcrCZvV4YiQc8fpp8UyZHdHuzXjyEZ1fr86a1hG0wKg5Ig1htMs0gA&debug=false&forceAllTransforms=false&shippedProposals=true&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Cstage-1%2Ctypescript&prettier=false&targets=&version=7.13.15&externalPlugins=)

**Comment by evanw** [comment] 2021-04-12 21:02
Is this TypeScript? That code doesn't appear to work [with the TypeScript compiler](https://www.typescriptlang.org/play?emitDecoratorMetadata=false#code/GYVwdgxgLglg9mABAJwKYEMAmCA2BPACinWQHNUoAaRMdAW1Ws1QGcJkYAHKOZASkQBvAFCJEzNh268AdAHcOxAEY5UiALyJg6HC1QBuUYmJkKAbVoMAuhvGt2XHshkwwMWDpgAvVMgJ9DMTQoEGQkCQdpZEMAX2FhCBx0FhZEABVWKCFhAEgIBBYoZBBoXn9snJyoAAsYFhc3KH9DHLjc13dykUqAeh7EADc4GExEXkR0MDwa11JcuLbE5NSAZRAlDMLEVAAPKFQwTFTNrO6AATQsXDxEFjgGAH1CjjBSRAAuW6LZ2wByZm0IBwUAeAx0IFQvxaPQAVCxODh3E9vq8Pl8XqQzDZNFj9DCevEch0mgJujkWCBOL4Gp0ArkcrCZvV4YiQc8fpp8UyZHdHuzXjyEZ1fr86a1hG0wKg5Ig1htMs0gA) either.

**Comment by n3svarbu** [comment] 2021-04-12 21:12
There is a dropdown in Babel REPL to select the Legacy mode for decorators. That's the culprit. Babel sends `descriptor` as a 3rd parameter in the legacy (which I assume is stage 1) decorators. And for TypeScript at stage 2 decorators [here](https://www.typescriptlang.org/docs/handbook/decorators.html#property-decorators) it says they don't pass the descriptor.

> Is this TypeScript? That code doesn't appear to work with the TypeScript compiler either.

Yes, it errors there though because of the `descriptor` arguments.
