### ISSUE TITLE
Error stack trace line/col points to index.js not to original file

### ISSUE THREAD

**Issue by lostsequence** [evanw/esbuild#1673] opened 2021-10-11 10:13 UTC
Stack trace on the screenshot below points to index.js (line: 49354, col: 18 and line: 49329 and col: 11) but not to the original file (ErroBoundary or Loading)

![image](https://user-images.githubusercontent.com/19356669/136771592-62d83f9d-878d-40fe-a8c3-c2e6ed28e3eb.png)

we are using react/typesript
esbuild config:
![image](https://user-images.githubusercontent.com/19356669/136772583-035ac687-1ca4-4755-a22b-373c108fc4f0.png)

**Comment by evanw** [comment] 2021-12-12 14:23
Closing as a duplicate of #708.

**Closed by evanw** 2021-12-12 14:23 UTC
