### ISSUE TITLE
No matching export for types exported via `export { ... }`

### ISSUE THREAD

**Issue by Jakobeha** [evanw/esbuild#1941] opened 2022-01-16 17:47 UTC
See https://github.com/vitejs/vite/issues/2117

Using es-modules, If a dependency exports a type or interface without a corresponding function or namespace, via `export { Type }` and not `export type { Type }`, then you will get "no matching export" errors for said type in esbuild.

I assume because the export gets erased in the JavaScript, but esbuild doesn't realize like it does with `export type`

One possible solution is for the maintainers of the dependency to explicitly use `export type { Type }` when exporting types. `export type = ...` and `export interface ...` also work fine, since TypeScript can infer these are exported types.

But I think esbuild should still not emit errors, because you can't always modify the dependency. At least mention in "no matching export" errors that this could be the reason. There is a matching export, it's just erased during some step in building.

**Comment by hyrious** [comment] 2022-01-16 23:50
I think esbuild has done what you said if you are using the bundle mode ([see it live](https://hyrious.me/esbuild-repl/?version=0.14.11&mode=build&modules=%5B%5B%22main.ts%22%2C%22export+%7B+A+%7D+from+%27.%2Ftypes.ts%27%5Cnexport+let+a+%3D+2%22%2C1%5D%2C%5B%22types.ts%22%2C%22export+type+A+%3D+1%22%2C0%5D%5D&buildOptions=%7B%22bundle%22%3Atrue%2C%22format%22%3A%22esm%22%2C%22splitting%22%3Atrue%7D)).

The real problem here is importing a type from library, which is often no problem because esbuild will know you're not using it by seeing it place in types and erase it:

```ts
import { A } from "lib"
let a: A = 'a' // A is not used and will be erased

export { A } // no, A is used!
```

And leaving a `export { A }` in final js code is not correct, but esbuild can not know whether A is a type by such code to erase it.

But in vue/svelte templates, esbuild cannot erase unused imports because he doesn't know the full component's code, for example the template part is just `import { flip } from 'svelte/animate'` and no script using it. Thus you need the tsconfig's `preserveValueImports` to tell esbuild not erasing it. You can see the point here is 'value import', but only  `import { A }` can not tell us its value or type.

To finaly resolve your problem, you should enable 'isolatedModules' config in ts.

**Comment by evanw** [comment] 2022-01-17 01:15
This is already described in the documentation: https://esbuild.github.io/content-types/#isolated-modules. Files are compiled independently, so esbuild has no way to know that a missing import is supposed to actually be a type. You should enable `isolatedModules` which should prevent you from writing problematic code. You haven't provided enough information so I don't know what's happening but I'm guessing your problem might be that you're writing `import { Type }` instead of `import type { Type }`, which is in your control (not in the dependency).

When bundling, esbuild does actually look across files during the bundling phase so it does a "best effort" approach that attempts to handle problematic code by ignoring missing re-exports in TypeScript files. You only get that when bundling though, and it's also not a fully robust solution. That's why I always recommend enabling `isolatedModules` even if esbuild's bundler happens to be able to handle certain cases without it. And it doesn't sound like you're using esbuild as a bundler, so this doesn't apply to you anyway.

Marking this issue as unactionable because you haven't provided enough information to reproduce this issue. If you do believe this is actually a bug with esbuild (and not just you using esbuild incorrectly), then please provide your input to esbuild (not to another tool like Vite), the esbuild options used, and the desired output.

**Comment by evanw** [comment] 2022-02-02 17:07
Closing for the reason described above.

```ts
import { Test, log } from './app';
export { Test };
```

should instead be written as either

```ts
import { log } from './app';
import type { Test } from './app';
export type { Test };
```

or
```ts
import { type Test, log } from './app';
export { type Test };
```

**Closed by evanw** 2022-02-02 17:07 UTC
Labels: unactionable

**Comment by airtonix** [comment] 2022-04-15 23:18
@evanw the main issue is that the undesirable methods you illustrate are not in our code, but in the code of packages we don't have permission to change.
