### ISSUE TITLE
Why esbuild transform `spread operator` but not transform `nullish coalescing operator`？

### ISSUE THREAD

**Issue by wmzy** [evanw/esbuild#1759] opened 2021-11-09 08:32 UTC
```sh
$ echo 'window ?? { ...{} }' | esbuild --target=chrome80
var __defProp = Object.defineProperty;
var __getOwnPropSymbols = Object.getOwnPropertySymbols;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __propIsEnum = Object.prototype.propertyIsEnumerable;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __spreadValues = (a, b) => {
  for (var prop in b || (b = {}))
    if (__hasOwnProp.call(b, prop))
      __defNormalProp(a, prop, b[prop]);
  if (__getOwnPropSymbols)
    for (var prop of __getOwnPropSymbols(b)) {
      if (__propIsEnum.call(b, prop))
        __defNormalProp(a, prop, b[prop]);
    }
  return a;
};
window ?? __spreadValues({}, {});
```

**Comment by hyrious** [comment] 2021-11-09 08:37
Because spread is faster than `...` in V8.
duplicate of #1583

**Comment by evanw** [comment] 2021-11-10 14:54
Closing as a duplicate of #1583 and #1365. See also #951.

**Closed by evanw** 2021-11-10 14:54 UTC
