### ISSUE TITLE
How about tinygo?

### ISSUE THREAD

**Issue by yisar** [evanw/esbuild#1841] opened 2021-12-09 05:30 UTC
https://github.com/tinygo-org/tinygo

Now build esbuild into wasm, and the final size is 8m, which is still too large in many scenarios.
I don't know whether tinygo is effective for esbuild, but it has played a role in other wasm projects in the past.

**Comment by evanw** [comment] 2021-12-09 05:46
Closing as a duplicate of #1111. TinyGo isn't a real Go compiler. It only works for a subset of Go, and esbuild is not written in that subset, so there's no way this will work. The built-in `recover` function isn't implemented, for example.

**Closed by evanw** 2021-12-09 05:46 UTC
