### ISSUE TITLE
Pure annotation for functions

### ISSUE THREAD

**Issue by skyrpex** [evanw/esbuild#1883] opened 2021-12-23 22:14 UTC
Currently, the `/* @__PURE__ */` annotation must be used individually on every returned value for a given call.

Could it be possible to allow using the annotation on a function, so all its returned values are considered pure? Like in the following.

```ts
/**
 * The function is pure, so if the result is not used, it can be removed.
 * 
 * @__PURE__
 */
function addTwo(number: number) {
    return number + 2;
}

// Will be removed
addTwo(4);

// Will be removed
const x = addTwo(3);

// This will be kept
export const y = addTwo(2);
```

**Comment by evanw** [comment] 2021-12-23 22:55
I understand why you might want it to work this way, but esbuild's implementation is the way `__PURE__` behaves in other tools too, and I think there's value in having this annotation work the same way in all tools instead of having it behave differently depending on the tool. That way people will author packages in a way that works well across tools. There is no formal specification but I believe this convention was originally developed by UglifyJS: https://github.com/mishoo/UglifyJS/pull/1448. So it should work however they have made it work.

I'm mainly building esbuild to follow existing conventions in the community regarding this stuff. I don't want to have esbuild start inventing new connections that will fragment the community. If there is community momentum around a new convention, then it might make sense to add it to esbuild, but I don't think esbuild is the right tool to be innovating on this kind of thing. Other tools are much more widely used, so it makes sense for these discussions to start with those tools first instead of esbuild in my opinion.

**Comment by skyrpex** [comment] 2021-12-23 23:29
Ha! I totally understand your point. Seems like we need a standard JS bundling comitee happening soon 👀 In fact, it doesn't sound like a bad idea, doesn't it? L

Anyway, I'll try to gather attention to some people... Authors and maintainers of Webpack, uglifyjs, what else? Rollup?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by evanw** [comment] 2021-12-24 00:07
I don't think it needs to be super formal. From what I understand, UglifyJS and Terser are the JS minifiers that are used most often. UglifyJS has 10x more downloads than esbuild for example: https://www.npmtrends.com/esbuild-vs-terser-vs-uglify-js. So you could just start there and see if there's any interest. There may also be an existing discussion about this somewhere since there are surely others who want this feature too. If such a discussion exists, it would also be helpful to read for context.

**Comment by evanw** [comment] 2022-01-06 18:25
I'm going to close this since I'm not planning to work on this. If something like this ships in other more widely-used tools and becomes adopted by the community (i.e. is used in a significant number of popular packages), then we can reopen this issue or create a new one.

**Closed by evanw** 2022-01-06 18:25 UTC

**Comment by jfmengels** [comment] 2022-08-10 09:41
I made an other issue for this feature with a more detailed breakdown of motivation and benefits https://github.com/mishoo/UglifyJS/issues/5614.
(I don't think continuing the discussion in a closed issue will lend itself to the feature being re-evaluated)

**Comment by raveclassic** [comment] 2022-08-26 14:49
@bigbanana did you try it? I can't make it work with the latest `esbuild@0.15.5`. 

@evanw I think my case is quite widespread - I'm using https://github.com/colinhacks/zod to build schema validators. Essentially, the library is a bunch of functions which one can use to build module-level constants holding the validators which then can be used on demand. 

The issue is that without this `/* #__PURE__ */` annotations, if I have a shared library with common validators, all of them are bundled, even those that are not used directly in the code. It's quite tedious to add these comments to each constant and very hard to maintain. It would be really really nice if esbuild supported such annotations on function declarations, maybe at least via a plugin. 

Right now I have to add an extra transpilation step with a custom babel plugin that just adds these annotations before each call to zod builder. This makes the bundling slow as hell and ultimately defeats the purpose of having super fast build with esbuild. 

Looking forward to continuing this discussion as it seems the demand is quite high due to how such case is widespread. Essentially, this is a case for any "builder" pattern, whether it's zod, io-ts, injectable-ts, HOF, React HOCs, you name it. It would be _extremely_ handy to have a way to declare _function itself_ as pure. Maybe with annotating function body? 
Example:
```typescript
function buildString() /* #__PURE__ */ {
  // function body
}

// removed by tree-shaking
const fooString = buildString()
// kept by tree-shaking
export const barString = buildString()
```

**Comment by mattfysh** [comment] 2023-03-20 00:55
I suspect many have this issue, as you will tend to declare zod schemas upfront at the top of your module, much like you would a typescript type.

I'm also generating a lot of my zod code using `ts-to-zod`, so I'll need to try and find a way to hook into compiler and add the required annotations. It would be nice though if esbuild could carve out a solution for zod + tree shaking, especially in cases where tree shaking is a priority

**Comment by skyrpex** [comment] 2023-06-02 06:36
Thanks to [this tweet](https://twitter.com/antfu7/status/1664320045797851147) it has come to my attention Google Closure Compiler's [@nosideeffects annotation](https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler#nosideeffects-modifies-thisarguments).

From their docs:

> @nosideeffects indicates that a call to the declared function has no side effects. This annotation allows the compiler to remove calls to the function if the return value is not used. This is not a signal that the function is "pure": it may still read mutable global state.

Much better than the hypotetical "pure" keyword for functions.

**Comment by aleclarson** [comment] 2023-07-18 19:18
Rollup has support for this with `#__NO_SIDE_EFFECTS__` annotation.

https://github.com/rollup/rollup/pull/5024

**Comment by evanw** [comment] 2023-07-18 20:12
Yes. See also #3149, which is already linked above.
