### ISSUE TITLE
side effects are gone when importing in ts files

### ISSUE THREAD

**Issue by kfdf** [evanw/esbuild#1284] opened 2021-05-13 19:22 UTC
This might be something totally obvious that I'm oblivious to, but given two files
```
// a.ts
import { } from './b'
```
and
```
// b.ts
console.log('side effect')
export { }
```
Then the command `npx esbuild a.ts --bundle` yields 
```
(() => {
})();
```
If `a.ts` is renamed to `a.js` or `import { } from './b'` is replaced with `import './b` then I get the expected output:
```
(() => {
  // b.ts
  console.log("side effect");
})();
```
Is it normal? A typescript thing or something?
esbuild version is 0.11.20

**Comment by evanw** [comment] 2021-05-13 22:11
> Is it normal? A typescript thing or something?

Yes. It's unfortunate but is how TypeScript works. You can confirm this for yourself using https://www.typescriptlang.org/play.

If you don't like this behavior you can either use JavaScript, or use TypeScript with `"importsNotUsedAsValues"` configured to something other than `"remove"` in your `tsconfig.json`. See [TypeScript's documentation](https://www.typescriptlang.org/tsconfig#importsNotUsedAsValues) for details.

Closing since this is by design.

**Closed by evanw** 2021-05-13 22:11 UTC
