### ISSUE TITLE
I haven't discovered a method for triggering an event from the esbuild server, similar to the "change" event that esbuild emits.

### ISSUE THREAD

**Issue by hamza761** [evanw/esbuild#3345] opened 2023-08-26 08:27 UTC
As demonstrated in the code snippet below, we can indeed listen for a "change" event:
`new EventSource('/esbuild').addEventListener('change', () => location.reload())`
Now, I wish to introduce a new event, like so:
`new EventSource('/esbuild').addEventListener('error', (err) => someActionOnError(err))`
However, I have been unable to find a means of emitting an event using esbuild's context.serve().

**Comment by zardoy** [comment] 2023-08-27 22:00
As I know (and tested) `esbuild.serve` doesn't serve sse (server sent events) on `/esbuild`, you most probably have this custom logic from https://github.com/evanw/esbuild/issues/802#issuecomment-819578182, you can extend it to send errors as well. Also AFAIK `EventSource` doesn't have `change` event (most probably you wanted to use `message`), `error` fires when you cannot connection to the server (eg process is terminated)

Though I think personally it would be so much better esbuild to provide this feature out of the box, just like the `alias` feature allows us to skip implementing custom functionality via plugins.

**Comment by evanw** [comment] 2023-09-04 11:53
Closing as a duplicate of #2997.

**Closed by evanw** 2023-09-04 11:53 UTC
