### ISSUE TITLE
Invalid define value

### ISSUE THREAD

**Issue by kongyijilafumi** [evanw/esbuild#3600] opened 2024-01-17 10:29 UTC
error: Invalid define value (must be an entity name or valid JSON syntax): `'wss://'+document.domain+'/wss'`
when I use string value define ,The program will not report errors. 
but I use the expression define，The program may encounter exceptions.
so, I want to use the expression define,what should I do?
![image](https://github.com/evanw/esbuild/assets/56569970/6433a0a8-2e30-47fd-9188-d85d51e76272)
![image](https://github.com/evanw/esbuild/assets/56569970/31be13e1-44bd-4c2d-bcd3-0fe05d66e721)

**Comment by hyrious** [comment] 2024-01-17 10:47
The `define` option can only replace JSON literals and a few `a.b` like variables. However, you can use the [inject](https://esbuild.github.io/api/#inject) option to provide variables in a more expressive way. For example:

```js
// create a file named shims.js
export const __WS_URL__ = 'wss://'+document.domain+'/wss'

// then inject it
esbuild.build({
  ...options,
  inject: ['./shims.js']
})
```

**Comment by evanw** [comment] 2024-01-17 22:14
I'm closing this issue because esbuild is working as intended here. I agree that [inject](https://esbuild.github.io/api/#inject) is likely the best fit for your use case. The difference is that `define` inlines compile-time constants while `inject` references (but does not inline) variables from arbitrary code. They are used for different purposes.

**Closed by evanw** 2024-01-17 22:14 UTC

**Comment by kongyijilafumi** [comment] 2024-01-18 09:58
I got it.Thanks for your answer @evanw @hyrious
