### ISSUE TITLE
Jenkins CI: The service was stopped

### ISSUE THREAD

**Issue by sarang5** [evanw/esbuild#3966] opened 2024-11-05 08:43 UTC
I have esbuild, esbuild-loader installed in my application. With the help of webpack optimization, I'm using esbuild-loader to perform minification in production builds. Everything was working fine, and, one day started seeing the issue in my Jenkins CI pipeline where the build was failing with the below error.

```
[00:35:51] HookWebpackError in plugin 'webpackify-client'
14:05:53  Message:
14:05:53      The service was stopped
14:05:53  Details:
14:05:53      details: caused by plugins in Compilation.hooks.processAssets
14:05:53  Error: The service was stopped
14:05:53      at /home/jenkins/agent/workspace/GiSX4Trh4buRbdty9tD0/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:737:38
14:05:53      at responseCallbacks.<computed> (/home/jenkins/agent/workspace/GiSX4Trh4buRbdty9tD0/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:622:9)
14:05:53      at Socket.afterClose (/home/jenkins/agent/workspace/GiSX4Trh4buRbdty9tD0/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:613:28)
14:05:53      at Socket.emit (node:events:529:35)
14:05:53      at Socket.emit (node:domain:552:15)
14:05:53      at endReadableNT (node:internal/streams/readable:1400:12)
14:05:53      at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
14:05:53      module: undefined
14:05:53      loc: undefined
14:05:53      hideStack: true
14:05:53      chunk: undefined
14:05:53      file: undefined
14:05:53      hook: Compilation.hooks.processAssets
14:05:53      error: Error: The service was stopped
14:05:53  [00:35:51] 'build' errored after 6.08 min
14:05:53  "
14:05:53  ✖ Failed step "build" with message "See above"
```

Below is my webpack production minification code.
`
const { EsbuildPlugin } = require('esbuild-loader')
optimization: {
    minimize: true,
    minimizer: [
      new EsbuildPlugin({
        target: 'es2015',
        logLevel: 'debug',
        css: true,  // Apply minification to CSS assets
      })
    ]
  },
`

**Comment by evanw** [comment] 2024-11-05 17:44
A reasonable hypothesis for this is that the Linux OOM killer on your CI machine is killing esbuild because the system doesn’t have enough free memory. Linux has ways to check whether this has happened. If so, one solution could be to give the CI machine more memory.

**Comment by azerbasic** [comment] 2024-11-12 18:29
Did u fix this?

**Comment by azerbasic** [comment] 2024-11-12 18:38
Well I just fixed this problem thanks to @evanw response on this. Im using code pipeline on aws, and increased to 15gb and now working. I had this problem with 10days.

**Comment by evanw** [comment] 2024-11-16 01:21
I'm closing this issue as the service being killed is not a bug with esbuild.

**Closed by evanw** 2024-11-16 01:21 UTC
