### ISSUE TITLE
About minifyWhitespace.

### ISSUE THREAD

**Issue by MooseLeee** [evanw/esbuild#3142] opened 2023-06-02 09:36 UTC
I had use the property "minifyWhitespace" in the config,but it didn't work,how can I to do.
My code just like this:

```
esbuild.context({
  entryPoints: {index: './src/index.tsx'},
  outdir: './dist/',
  bundle: true,
  minify: true,
  minifyWhitespace: true,
  ...
})
```

**Comment by hyrious** [comment] 2023-06-02 09:46
Note that `minify: true` implies `minifyWhitespace: true`, so you cannot turn on whitespace when you have the former.

If you want to only turn on whitespace, you can do this:

```js
minifyIdentifiers: true,
minifySyntax: true,
```

**Comment by MooseLeee** [comment] 2023-06-02 09:48
Now I can only use CSS property: font-size: 0 to made it,but it isn't convinient.

**Comment by MooseLeee** [comment] 2023-06-02 09:57
> Note that `minify: true` implies `minifyWhitespace: true`, so you cannot turn on whitespace when you have the former.
> 
> If you want to only turn on whitespace, you can do this:
> 
> ```js
> minifyIdentifiers: true,
> minifySyntax: true,
> ```

You mean this:
```
esbuild.context({
  entryPoints: {index: './src/index.tsx'},
  outdir: './dist/',
  bundle: true,
  minifyIdentifiers: true,
  minifySyntax: true,
  ...
})
```
But I tried it just now,it didn't work too,sorry that I code in a private network env,I can't provide the code's capture for you.

**Comment by hyrious** [comment] 2023-06-02 10:38
Maybe you can provide a reproduction here: https://esbuild.github.io/try

**Comment by evanw** [comment] 2023-06-04 06:36
I'm marking this as `unactionable` because "it didn't work" is not enough information.

**Closed** 2023-06-09 16:39 UTC
Labels: unactionable
