### ISSUE TITLE
Bundle PnP import

### ISSUE THREAD

**Issue by rtritto** [evanw/esbuild#3690] opened 2024-03-10 03:30 UTC
I'm using `esbuild ./index.ts --bundle --platform=node --outdir=dist` to build this code:
```ts
import { request } from 'undici'
request('URL')
```
e.g. I got:
```js
var require_symbols = __commonJS({
  "../../Users/<USER>/AppData/Local/Yarn/Berry/cache/undici-npm-6.7.1-cc741edc29-10c0.zip/node_modules/undici/lib/core/symbols.js"(exports2, module2) {
    module2.exports = {
      // other code
    }
})
```
In bundle, how can I replace the `zip` import with resolved and used code (only _request_ and not all import of _undici_)?

**Comment by hyrious** [comment] 2024-03-11 03:42
What you're asking for is called [tree-shaking](https://esbuild.github.io/api/#tree-shaking) which in esbuild only works when the imported files are written in ESM format. However `undici` is a [CommonJS only](https://hyrious.me/npm-browser/?q=undici@6.7.1/package/index.js:148) package. So it is impossible to get what you want in esbuild.

**Comment by rtritto** [comment] 2024-03-11 19:19
I'm using [SEA](https://nodejs.org/api/single-executable-applications.html) ([guide](https://dev.to/chad_r_stewart/compile-a-single-executable-from-your-node-app-with-nodejs-20-and-esbuild-210j)) to produce a single file and run it with no other dependencies (without the dependecies of `.zip` files).
To transpile/transform the imported `.zip` (inside _\__commonJS_), should I use an ESBuild plugin (like https://github.com/evanw/esbuild/issues/566#issuecomment-735551834) or a loader (e.g. [esbuild-esm-loader](https://www.npmjs.com/package/esbuild-esm-loader)) or other tools?

**Comment by evanw** [comment] 2024-03-14 19:46
I'm closing this as esbuild seems to be working as intended here.

One way for a package author to make their CommonJS package more friendly to tree-shaking is to allow you to import from a subdirectory of the package to only import that part of the package. If that was the case here (I know nothing about this particular package), you could potentially import from `undici/lib/api/api-request.js` to only import that part of the package instead of importing the whole package from `undici`. That will work if that's how the package author intends for their package to be used, but it may not work if the package author didn't design their package that way. But that's up to the package author, and is not something that esbuild is supposed to solve.

**Closed by evanw** 2024-03-14 19:46 UTC
