### ISSUE TITLE
The `externals` config is not respected when `stdin` is used during on build

### ISSUE THREAD

**Issue by ismail-syed** [evanw/esbuild#694] opened 2021-01-19 06:08 UTC
👋 Thanks for sharing such a great library! 

I think I may have found a bug where the `externals` config is not respected when `stdin` is used. I have an example repository here, https://github.com/ismail-syed/esbuild-stdin-external-bug. 

### BUG

Build config with `stdin` where `external` is not respected

```jsx
  await esbuild.build({
    // This errors, even with external set below
    // ./app.jsx:2:29: error: Could not resolve "react" (mark it as external to exclude it from the bundle)
    // ./app.jsx:3:30: error: Could not resolve "react-dom/server" (mark it as external to exclude it from the bundle)
    stdin: {
      contents: `
      import * as React from "react";
      import * as Server from "react-dom/server";
      let Greet = () => <h1>Hello, world!</h1>;
      console.log(Server.renderToString(<Greet />));
      `,
      sourcefile: "./app.jsx",
      loader: "jsx",
    },

    // I presume this should be respected with stdin like it is with entrypoints
    external: ["react", "react-dom"],
    write: false,
    bundle: true,
  });
```

### Working example

Here's a similar config with a working example

```jsx
await esbuild.build({
    // No errors, see https://github.com/ismail-syed/esbuild-stdin-external-bug/blob/main/app.jsx
    entryPoints: ["./app.jsx"],

    external: ["react", "react-dom"],
    write: false,
    bundle: true,
});
```

**Comment by ismail-syed** [comment] 2021-01-19 06:09
@evanw If this is a legit bug, would love to contribute a fix. Are there any onboarding docs for contributors?

**Comment by evanw** [comment] 2021-02-03 22:56
You need to use `stdin: { resolveDir: '...' }` to tell esbuild what directory to use to resolve these imports. Closing as by design.

**Closed by evanw** 2021-02-03 22:56 UTC
