### ISSUE TITLE
npm install fails behind corporate proxy

### ISSUE THREAD

**Issue by masteph** [evanw/esbuild#319] opened 2020-08-07 09:46 UTC
After upgrading from 0.6.3 to 0.6.17 the install process of npm fails in post install step.
It turned out to be a proxy issue:

> set NODE_DEBUG=net,http,https
> npm install
> [...]
> HTTP 30356: SOCKET ERROR: connect ETIMEDOUT 104.16.18.35:443 Error: connect ETIMEDOUT 104.16.18.35:443
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)
> Trying to download "https://registry.npmjs.org/esbuild-windows-64/-/esbuild-windows-64-0.6.17.tgz"
> Failed to download "https://registry.npmjs.org/esbuild-windows-64/-/esbuild-windows-64-0.6.17.tgz": connect ETIMEDOUT 104.16.18.35:443
> Install unsuccessful
> [...]
> npm ERR! Failed at the esbuild@0.6.17 postinstall script.
> [...]

The reason is that the fetch routine does direct http(s) connections.
https://github.com/evanw/esbuild/blob/master/lib/install.ts#L123

If there would be some way to use npm to download the dependencies that would be great.
Else you should provide a way to respect http_proxy and https_proxy env variables.

Right now I have to find a Windows machine that can do direct downloads and copy the files afterward.

**Comment by evanw** [comment] 2020-08-07 22:14
I just published version 0.6.18, which will fall back to `npm install` if all else fails.

**Comment by danvim** [comment] 2021-08-18 03:56
@evanw I'm getting the same problem on esbuild 0.12.20

It failed to run the following and fell back to try to download the binary from npm directly.


```
PS> npm install --loglevel=error --prefer-offline --no-audit --progress=false esbuild-windows-64@0.12.20
npm ERR! code ETARGET
npm ERR! notarget No matching version found for esbuild-windows-64@0.12.20
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

But if I remove the prefer offline flag, it works fine. What could be the problem? 

When I check the npm cache log, it contains

```
...
27 http fetch GET 200 http://corporate-proxy/esbuild-windows-64 9ms (from cache)
...
36 verbose stack esbuild-windows-64: No match version found for esbuild-windows-64@0.12.20.
...
```

I'm assuming my cache doesn't have the latest version, and so prefer offline doesn't really work.

Then once I've downloaded it once without the prefer offline flag. The package is now cached and `yarn add -D esbuild` now works perfectly fine.

**Comment by evanw** [comment] 2021-08-18 23:11
Just curious: Are you able to install `esbuild-experimental-optdeps@0.12.3` with your corporate proxy? Knowing if that package works for you or not will hopefully help me fix the root cause of these issues.

Context: The `esbuild-experimental-optdeps` package isn't meant to be used for real. Instead it's part of an experiment of mine to use a different package installation strategy that doesn't use an install script. If that strategy works out, I'm planning to remove the install script from the `esbuild` package to hopefully avoid issues like yours. See also issue #789 for more context.

**Comment by danvim** [comment] 2021-08-19 07:48
@evanw Hmm... I'm not sure I can verify quickly. This installation problem only happens if I have cache before a new version of esbuild is released, then it wouldn't be able to find the new version in the local cached manifest and fail. Installation always works for the initial installation, or if I clear my npm cache.

**Comment by Random90** [comment] 2021-08-19 10:19
Hello, I have the same issue as @danvim, being behind corp proxy, but while generating angular 12 library where esbuild is probably dependency of ng-packagr, since that is the only package installed while generating new library.
I don't really have a way to install it manually, since this is a step of schematics workflow process, which just fails:

`UPDATE angular.json (11123 bytes)
UPDATE package.json (2315 bytes)
UPDATE tsconfig.json (960 bytes)
| Installing packages (npm)...
> esbuild@0.12.21 postinstall C:\[...]\node_modules\esbuild
> node install.js

Trying to install "esbuild-windows-64" using npm
Failed to install "esbuild-windows-64" using npm: Command failed: npm install --loglevel=error --prefer-offline --no-audit --progress=false esbuild-windows-64@0.12.21
npm ERR! code ETARGET
npm ERR! notarget No matching version found for esbuild-windows-64@0.12.21.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! A complete log of this run can be found in:
[...]

Trying to download "https://registry.npmjs.org/esbuild-windows-64/-/esbuild-windows-64-0.12.21.tgz"
Failed to download "https://registry.npmjs.org/esbuild-windows-64/-/esbuild-windows-64-0.12.21.tgz": connect ETIMEDOUT 104.16.24.35:443
Install unsuccessful
npm WARN ajv-keywords@3.5.2 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\webpack-dev-server\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! esbuild@0.12.21 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the esbuild@0.12.21 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
[...]
× Package install failed, see above.
The Schematic workflow failed. See above.

`

**Comment by evanw** [comment] 2021-08-21 02:17
I suspect these issues may have been introduced by #551, which landed in [version 0.8.12](https://github.com/evanw/esbuild/releases/tag/v0.8.12) on November 21, 2020. That PR changed the nested `npm` invocation from a subdirectory inside the package to a temporary folder outside the package.

This change was done to fix issues on Windows since deleting a directory on Windows is randomly sometimes impossible, and leaving a nested `node_modules` directory there can sometimes cause problems with tools that scan over `node_modules` directories and expect them to have a specific structure. However, perhaps we could decide we don't care about that case as much as getting this to work.

If my hypothesis is correct, that would mean that installing `0.8.11` behind a corporate proxy should succeed but installing `0.8.12` behind a corporate proxy should fail (assuming installing the latest version of esbuild behind the same proxy also fails). It would be good for someone to verify whether this is the case or not.

In any case, it sounds like I should re-open this issue.

**Comment by danvim** [comment] 2021-08-22 14:58
@evanw I believe in my case, I can install any version as long as they are already in the manifest I've cached locally. If you were to release a newer version tomorrow, I wouldn't be able to install that unless I clear my local cache to remove my local manifest.

**Comment by danvim** [comment] 2021-08-30 08:56
So my computer apparently also fails with create react app with a similar issue. 

https://github.com/facebook/create-react-app/issues/8294

It also worked when I removed the `--offline` flag from the installation command. I think they might be related🤔

**Closed** 2021-09-22 15:21 UTC

**Comment by silverwind** [comment] 2022-11-23 17:01
It seems this issue with ETARGET is not completely fixed, but I can't provice reliable reproduction either. Here's part of the failing log:

```
npm ERR! command sh -c -- node install.js
npm ERR! [esbuild] Failed to find package "esbuild-linux-64" on the file system
npm ERR! [esbuild] Trying to install package "esbuild-linux-64" using npm
npm ERR! [esbuild] Failed to install package "esbuild-linux-64" using npm: Command failed: npm install --loglevel=error --prefer-offline --no-audit --progress=false esbuild-linux-64@0.15.12
npm ERR! npm ERR! code ETARGET
npm ERR! npm ERR! notarget No matching version found for esbuild-linux-64@0.15.12.
npm ERR! npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! npm ERR! notarget a package version that doesn't exist.
npm ERR! [esbuild] Trying to download "https://registry.npmjs.org/esbuild-linux-64/-/esbuild-linux-64-0.15.12.tgz"
npm ERR! [esbuild] Failed to download "https://registry.npmjs.org/esbuild-linux-64/-/esbuild-linux-64-0.15.12.tgz": connect ETIMEDOUT 104.16.18.35:443
```

Running the failing `npm install` command manually works and populates the npm cache so subsequent installs work fine. I have honestly no idea how this ETARGET happens and I suspect a bug in npm itself.
