### ISSUE TITLE
Minify from STDIN to file out

### ISSUE THREAD

**Issue by mangelozzi** [evanw/esbuild#1978] opened 2022-02-01 10:45 UTC
Maybe STDIN to file out is not supported, but I get an error when trying:

```
$ echo "const a = 1" | esbuild --minify --outfile=~/temp.min.js
✘ [ERROR] Invalid transform flag: "--outfile=~/temp.min.js"

1 error
child_process.js:656
    throw err;
    ^

Error: Command failed: /usr/lib/node_modules/esbuild/node_modules/esbuild-linux-64/bin/esbuild --minify --outfile=~/temp.min.js
    at checkExecSyncError (child_process.js:635:11)
    at Object.execFileSync (child_process.js:653:15)
    at Object.<anonymous> (/usr/lib/node_modules/esbuild/bin/esbuild:109:26)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 638159,
  stdout: null,
  stderr: null
}
```

**Comment by hyrious** [comment] 2022-02-01 10:49
This error message says you can not call `esbuild.transform(code, { outfile })`.

Instead, you can redirect stdout:

```bash
echo "const a = 1" | esbuild --minify > ~/temp.min.js
```

**Comment by evanw** [comment] 2022-02-01 17:43
Yes, that's correct. This is documented here: https://esbuild.github.io/api/#transform-api

> In this case the input string comes from stdin and the output string goes to stdout.

Closing as this is by design.

**Closed by evanw** 2022-02-01 17:43 UTC
