### ISSUE TITLE
pnpm install error running postinstall scripts

### ISSUE THREAD

**Issue by GustavoJCL** [evanw/esbuild#3640] opened 2024-02-11 15:21 UTC
Hi, i was creating a project with pnpm, react and vite, but i have this error when i run pnpm install

```
❯ pnpm install
Packages: +211
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 245, reused 159, downloaded 52, added 211, done
node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild: Running postinstall script, failed in 40ms
.../esbuild@0.19.12/node_modules/esbuild postinstall$ node install.js
│ node:internal/child_process:1124
│     result.error = new ErrnoException(result.error, 'spawnSync ' + options.file);
│                    ^
│ <ref *1> Error: spawnSync /media/gus/proyectos/no_country/no_country_front/node_modules/.pnpm/esb…
│     at Object.spawnSync (node:internal/child_process:1124:20)
│     at spawnSync (node:child_process:876:24)
│     at Object.execFileSync (node:child_process:919:15)
│     at validateBinaryVersion (/media/gus/proyectos/no_country/no_country_front/node_modules/.pnpm…
│     at /media/gus/proyectos/no_country/no_country_front/node_modules/.pnpm/esbuild@0.19.12/node_m…
│   errno: -13,
│   code: 'EACCES',
│   syscall: 'spawnSync /media/gus/proyectos/no_country/no_country_front/node_modules/.pnpm/esbuild…
│   path: '/media/gus/proyectos/no_country/no_country_front/node_modules/.pnpm/esbuild@0.19.12/node…
│   spawnargs: [ '--version' ],
│   error: [Circular *1],
│   status: null,
│   signal: null,
│   output: null,
│   pid: 0,
│   stdout: null,
│   stderr: null
│ }
│ Node.js v21.6.1
└─ Failed in 41ms at /media/gus/proyectos/no_country/no_country_front/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild
 ELIFECYCLE  Command failed with exit code 1.
```

my node version is 21.6.1
pnpm version: 8.15.1

steps to reproduce the error:
`pnpm create vite`
Select react with typescript
```
cd project_name
pnpm install

```
![image](https://github.com/evanw/esbuild/assets/93671143/ab70997e-e0e4-4467-9774-62bbbb727c0f)

**Comment by evanw** [comment] 2024-02-11 15:59
I cannot reproduce this:

```console
$ node --version
v21.6.1

$ pnpm --version
8.15.1

$ pnpm create vite
../.pnpm-store/v3/tmp/dlx-7823           |   +1 +
../.pnpm-store/v3/tmp/dlx-7823           | Progress: resolved 1, reused 1, downloaded 0, added 1, done
✔ Project name: … vite-project
✔ Select a framework: › React
✔ Select a variant: › TypeScript

Scaffolding project in /workspaces/codespaces-blank/vite-project...

Done. Now run:

  cd vite-project
  pnpm install
  pnpm run dev

$ cd vite-project

$ pnpm install
Packages: +211
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 245, reused 211, downloaded 0, added 211, done
node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild: Running postinstall script, done in 62ms

dependencies:
+ react 18.2.0
+ react-dom 18.2.0

devDependencies:
+ @types/react 18.2.55
+ @types/react-dom 18.2.19
+ @typescript-eslint/eslint-plugin 6.21.0
+ @typescript-eslint/parser 6.21.0
+ @vitejs/plugin-react 4.2.1
+ eslint 8.56.0
+ eslint-plugin-react-hooks 4.6.0
+ eslint-plugin-react-refresh 0.4.5
+ typescript 5.3.3
+ vite 5.1.1

Done in 4.7s
```

The issue may be a problem on your machine instead of a problem with esbuild. Marking this issue as `unactionable` because there's nothing I can do with it.

**Comment by evanw** [comment] 2024-02-19 01:50
I'm closing this issue because it has been unactionable for a week without further follow-up.

**Closed by evanw** 2024-02-19 01:50 UTC
Labels: unactionable

**Comment by KraXen72** [comment] 2024-06-19 11:20
i had the same issue and solved it by making sure my ntfs partition is mounted with `exec` at the end of fstab options, like so:
```
UUID=xxx                       /media/data   ntfs   uid=1000,gid=1000,rw,user,umask=000,nofail,exec   0 0
UUID=xxx                       /media/win    ntfs   uid=1000,gid=1000,rw,user,umask=000,nofail,exec   0 0
```
if you want to use `users` so anyone can re-mount the partitions, make sure `exec` is defined *after* `users`, because according to `man mount`, `users` implies `noexec` unless **subsequently** overwrritten.
