### ISSUE TITLE
Bundle, fontawesome and memory leaks?

### ISSUE THREAD

**Issue by aolko** [evanw/esbuild#1612] opened 2021-09-16 08:00 UTC
Hi, yesterday i've started having a memory leak problem while using my esbuild bundle and including fontawesome separately as a `<script>`, what follows is:
- fontawesome rendering breaks
- page starts eating up my cpu
- tab crashes
here's [a sandbox](https://codesandbox.io/s/gallant-ardinghelli-w3vzo), preview might die
build src is located in `assets/js/build`.

Also: how do i configure fontawesome in the `main.jsx` directly?

**Comment by aolko** [comment] 2021-09-21 08:02
Please respond

**Comment by evanw** [comment] 2021-09-22 22:02
I looked at the code you linked to but I don't see esbuild being run at all. The only build scripts I see are using parcel, not esbuild. What is the esbuild command that was used here?

**Comment by aolko** [comment] 2021-09-25 08:28
> I looked at the code you linked to but I don't see esbuild being run at all. The only build scripts I see are using parcel, not esbuild. What is the esbuild command that was used here?

` esbuild ./build/main.jsx --bundle --minify --sourcemap --outfile="./bundle.js"`

**Comment by evanw** [comment] 2021-10-17 02:17
I took a look at that link but I don't see anything unusual. There is periodic CPU usage but it looks like it's caused by CodeSandbox, not any esbuild-compiled code. I'm marking this as "unactionable" because it's not clear what's wrong with esbuild here, if anything.

**Comment by evanw** [comment] 2022-01-22 03:05
Closing this because it's unclear what to do here. If a specific problem with esbuild is identified, then we can figure out if it should be fixed and how to fix it.

**Closed by evanw** 2022-01-22 03:05 UTC
Labels: unactionable
