### ISSUE TITLE
[Freature] Add support for remapping external modules

### ISSUE THREAD

**Issue by zaygraveyard** [evanw/esbuild#484] opened 2020-10-22 13:12 UTC
## Setup
```
project
├─ build
|  ├─ module.js
|  └─ out.js
├─ module.js
└─ in.js
```
* `module.js` is the external module, copied as is to the `build` directory as part of the build process
* `in.js` is the input module to be bundled with `esbuild`
* `out.js` the result of the `esbuild` of `in.js`

`in.js`
```js
import './module.js';
// ...
```

## Actual behavior
`out.js`
```js
import '../module.js';
// ...
```

## Requested behavior
`out.js`
```js
import './module.js';
// ...
```

## Description of the problem

Currently the `--external:M` flag, when given an absolute path, will replace all occurrences of imported URLs pointing to `M` in the input with a relative path pointing to `M` from the output.
So in the example above, `out.js` is importing `project/module.js` instead of `project/build/module.js`

## Description of the requested feature

Add a way to let `esbuild` know the new location of `module.js` (ie. `project/build/module.js`).

### Suggestion

Add support for using `--external:M=N` which will map all imports of `M` to `N`

**Comment by zaygraveyard** [comment] 2020-10-22 14:27
Looks like this can be achieved with a plugin similar to https://github.com/evanw/esbuild/issues/111#issuecomment-699593951

**Comment by zaygraveyard** [comment] 2020-10-22 15:02
Looking at the code, if this feature is to be added, this is where the mapping should happen
https://github.com/evanw/esbuild/blob/588fa611406154a901e97ac9bf9328973874444e/internal/resolver/resolver.go#L274

**Comment by zaygraveyard** [comment] 2020-10-22 15:04
Looks like this is a duplicate of #456

**Comment by evanw** [comment] 2020-10-26 03:12
Yes. Closing as a duplicate of #456.

**Closed by evanw** 2020-10-26 03:12 UTC
