### ISSUE TITLE
0.12.4 break build with esnext and subscriptions-transport-ws dependencie

### ISSUE THREAD

**Issue by avallete** [evanw/esbuild#1334] opened 2021-05-31 13:14 UTC
Hi there,

This is probably related to #1332  but the 0.12.4 upgrade break the build on my side because of tsconfig target scoping.

Especially using  `subscriptions-transport-ws` alongside with "esnext" in my project it give me the following error:

```
 > ../../node_modules/subscriptions-transport-ws/node_modules/ws/index.js:3:0: error: Transforming const to the configured target environment ("es5") is not supported yet
    3 │ const WebSocket = require('./lib/websocket');
      ╵ ~~~~~
   ../../node_modules/subscriptions-transport-ws/tsconfig.json:3:14: note: The target environment was set to "es5" here
    3 │     "target": "es5",
      ╵               ~~~~~

 > ../../node_modules/subscriptions-transport-ws/node_modules/ws/lib/sender.js:3:0: error: Transforming const to the configured target environment ("es5") is not supported yet
    3 │ const crypto = require('crypto');
      ╵ ~~~~~
   ../../node_modules/subscriptions-transport-ws/tsconfig.json:3:14: note: The target environment was set to "es5" here
    3 │     "target": "es5",
      ╵               ~~~~~

 > ../../node_modules/subscriptions-transport-ws/node_modules/ws/lib/sender.js:5:0: error: Transforming const to the configured target environment ("es5") is not supported yet
    5 │ const PerMessageDeflate = require('./permessage-deflate');
      ╵ ~~~~~
   ../../node_modules/subscriptions-transport-ws/tsconfig.json:3:14: note: The target environment was set to "es5" here
    3 │     "target": "es5",
      ╵               ~~~~~

 > ../../node_modules/subscriptions-transport-ws/node_modules/ws/lib/sender.js:6:0: error: Transforming const to the configured target environment ("es5") is not supported yet
    6 │ const bufferUtil = require('./buffer-util');
      ╵ ~~~~~
   ../../node_modules/subscriptions-transport-ws/tsconfig.json:3:14: note: The target environment was set to "es5" here
    3 │     "target": "es5",
      ╵               ~~~~~

 > ../../node_modules/subscriptions-transport-ws/node_modules/ws/lib/sender.js:7:0: error: Transforming const to the configured target environment ("es5") is not supported yet
    7 │ const validation = require('./validation');
      ╵ ~~~~~
   ../../node_modules/subscriptions-transport-ws/tsconfig.json:3:14: note: The target environment was set to "es5" here
    3 │     "target": "es5",
      ╵               ~~~~~

 > ../../node_modules/subscriptions-transport-ws/node_modules/ws/lib/sender.js:8:0: error: Transforming const to the configured target environment ("es5") is not supported yet
    8 │ const constants = require('./constants');
      ╵ ~~~~~
   ../../node_modules/subscriptions-transport-ws/tsconfig.json:3:14: note: The target environment was set to "es5" here
    3 │     "target": "es5",
      ╵               ~~~~~

 > ../../node_modules/subscriptions-transport-ws/node_modules/ws/lib/sender.js:13:0: error: Transforming class syntax to the configured target environment ("es5") is not supported yet
    13 │ class Sender {
       ╵ ~~~~~
   ../../node_modules/subscriptions-transport-ws/tsconfig.json:3:14: note: The target environment was set to "es5" here
     3 │     "target": "es5",
       ╵               ~~~~~

 > ../../node_modules/subscriptions-transport-ws/node_modules/ws/lib/sender.js:20:14: error: Transforming object literal extensions to the configured target environment ("es5") is not supported yet
    20 │   constructor (socket, extensions) {
       ╵               ^
   ../../node_modules/subscriptions-transport-ws/tsconfig.json:3:14: note: The target environment was set to "es5" here
     3 │     "target": "es5",
       ╵               ~~~~~

 > ../../node_modules/subscriptions-transport-ws/node_modules/ws/lib/sender.js:45:15: error: Transforming object literal extensions to the configured target environment ("es5") is not supported yet
    45 │   static frame (data, options) {
       ╵                ^
   ../../node_modules/subscriptions-transport-ws/tsconfig.json:3:14: note: The target environment was set to "es5" here
     3 │     "target": "es5",
       ╵               ~~~~~

 > ../../node_modules/subscriptions-transport-ws/node_modules/ws/lib/sender.js:46:4: error: Transforming const to the configured target environment ("es5") is not supported yet
    46 │     const merge = data.length < 1024 || (options.mask && options.rea...
       ╵     ~~~~~
   ../../node_modules/subscriptions-transport-ws/tsconfig.json:3:14: note: The target environment was set to "es5" here
     3 │     "target": "es5",
       ╵               ~~~~~
```

## Workaround

The only fix I found is to rollback to `esbuild@0.12.3`

**Comment by avendiart** [comment] 2021-05-31 23:36
Same issue here, reproducible with the following config and sample code:

```javascript
const path = require('path')

require('esbuild').build({
  platform: 'node',
  entryPoints: [path.resolve(__dirname, '../src/index.ts')],
  outdir: path.resolve(__dirname, '../build'),
  bundle: true,
  metafile: true,
  sourcemap: true,
  treeShaking: true,
  watch: process.env.WATCH === 'true',
})
```

```typescript
import { ApolloServer } from 'apollo-server'

const server = new ApolloServer({
  tracing: true,
  typeDefs: [],
  resolvers: {},
})

server
  .listen()
  .then(({ url }) => {
    console.log(`GraphQL server is ready at ${url}`)
  })
```

Relevant dependencies:
```json
"dependencies": {
  "apollo-server": "2.25.0",
  "graphql": "15.5.0"
},
```

**Comment by evanw** [comment] 2021-06-02 20:48
Closing as a duplicate of #1332.

**Closed by evanw** 2021-06-02 20:48 UTC
