### ISSUE TITLE
Source maps off in the line numbers since 0.8.13 and in the file name since 0.8.25 (regression)

### ISSUE THREAD

**Issue by tskarman** [evanw/esbuild#638] opened 2021-01-03 12:04 UTC
First off, a big thank you for your impressive project.

While evaluating it a few days ago, I noticed that the mapped file names were off in the source maps, so I ran through a few versions after noticing source map work in your release notes. I found out that it's a regression and was introduced in version `0.8.25`.
While going through the preparations for this issue, I noticed that the line numbers were also off by 1-2 lines in my case and could trace it back to version `0.8.13`.

For a start, I just wanted to let you know about this, so I only have screenshots to offer in this first step.

What follows is a series of screenshots of the same call situation across versions `0.8.10` to `0.8.29`. Of interest for this issue are the three top-most stack entries in the respective images:

**esbuild 0.8.10** (file name in source mapping good, line numbers on point)
![esbuild-0 8 10](https://user-images.githubusercontent.com/2319548/103477541-3731c400-4dc0-11eb-9fb2-e449fc972333.png)
**esbuild 0.8.12**  (file name in source mapping good, line numbers on point)
![esbuild-0 8 12](https://user-images.githubusercontent.com/2319548/103477544-3862f100-4dc0-11eb-9d8e-e7e030c0e101.png)
**esbuild 0.8.13** (file name in source mapping good, line numbers off (see above for correct line numbers))
![esbuild-0 8 13](https://user-images.githubusercontent.com/2319548/103477545-39941e00-4dc0-11eb-8951-bce65c452c44.png)
**esbuild 0.8.14** (file name in source mapping good, line numbers off)
![esbuild-0 8 14](https://user-images.githubusercontent.com/2319548/103477546-3b5de180-4dc0-11eb-9fd4-85547775e263.png)
**esbuild 0.8.15** (file name in source mapping good, line numbers off)
![esbuild-0 8 15](https://user-images.githubusercontent.com/2319548/103477548-3dc03b80-4dc0-11eb-9803-7119241cdcb5.png)
**esbuild 0.8.23** (file name in source mapping good, line numbers off)
![esbuild-0 8 23](https://user-images.githubusercontent.com/2319548/103477307-f20c9280-4dbd-11eb-809c-ea5c247595ae.png)
**esbuild 0.8.24** (file name in source mapping good, line numbers off)
![esbuild-0 8 24](https://user-images.githubusercontent.com/2319548/103477308-f46eec80-4dbd-11eb-8928-62cd7f2903be.png)
**esbuild 0.8.25** (file name in source mapping incorrect (should be `shared3.ts` and not `Lifecycle.js`), line numbers off)
![esbuild-0 8 25](https://user-images.githubusercontent.com/2319548/103477309-f5078300-4dbd-11eb-8756-d745f5d3afb3.png)
**esbuild 0.8.26** (file name in source mapping incorrect, line numbers off)
![esbuild-0 8 26](https://user-images.githubusercontent.com/2319548/103477310-f638b000-4dbd-11eb-8d74-2ae613f5fced.png)
**esbuild 0.8.27** (file name in source mapping incorrect, line numbers off)
![esbuild-0 8 27](https://user-images.githubusercontent.com/2319548/103477311-f769dd00-4dbd-11eb-8adf-c78264e3e756.png)
**esbuild 0.8.28** (file name in source mapping incorrect, line numbers off)
![esbuild-0 8 28](https://user-images.githubusercontent.com/2319548/103477312-f89b0a00-4dbd-11eb-9c72-d77be885b41c.png)
**esbuild 0.8.29** (file name in source mapping incorrect, line numbers off)
![esbuild-0 8 29](https://user-images.githubusercontent.com/2319548/103477314-f9cc3700-4dbd-11eb-86c9-bc4583b811ca.png)

### Details
Building/bundling from TypeScript

The `package.json` entry:
```
...
"build:es": "esbuild ./src/index.tsx --log-level=error --minify --target=\"chrome58,firefox57,safari11,edge16\" --define:process.env.NODE_ENV='production' --bundle --sourcemap --outfile=\"./build/bundle.js\"",
...
```

The mismapped source code comes from a separate package and the maps in that package are generated by TypeScript (`tsc`).
That package was static/unmodified through all my test runs here.

The regression introduced in `0.8.13` appears to come from the minification code as the line numbers only come out wrong when I specify `--minify`. Using `--sourcemap=inline` doesn't make a difference. Version `0.8.29` is the same in both regards.

The regression introduced in `0.8.25` shows itself irrespective of `--minify` in all the versions I tried. So the file names always come out wrong. It's the same when specifying `--sourcemap=inline`.

I am sorry for putting the two issues into a single issue. Let me know if you'd like me to create a separate issue for one of the two.

Please also let me know how I can be of further assistance. I can't easily share that particular source code publicly, but maybe I can create a minimal repro given some time.

**Comment by soadzoor** [comment] 2021-01-04 11:18
I'm having similar troubles. Happy to share my source code privately with you @evanw , just like I did a few months ago

**Comment by evanw** [comment] 2021-01-04 21:35
Thank you for the detailed issue, and for the offer to share source code privately. I did a lot of analysis of source maps on various code bases and I think I have experienced the problem myself, so I shouldn't need a code sample. Fixing this is top priority for me and I hope to have a fix soon.

**Comment by evanw** [comment] 2021-01-06 10:36
Ok I think the issues are now fixed. Please try version 0.8.30 and let me know if it works for you or not. I'm leaving this issue open until you can confirm the fix since I don't have a way to reproduce the specific problems you encountered.

I took a little while to fix this because I haven't had a great way of debugging source map problems in the past and I figured it's time to fix that. This issue inspired me to make this: https://evanw.github.io/source-map-visualization/. Now I can actually see what I'm doing so issues like this should be much easier to fix in the future.

I believe there were two source map problems, one regression introduced in version 0.7.18 and one in version 0.8.25 (more details are in [the release notes](https://github.com/evanw/esbuild/blob/18a9d59a4aad7d79a0cbbd9608bbc18e4f0ecfa7/CHANGELOG.md#0830)). I believe that one of the changes introduced in version 0.8.13 caused the earlier regression to start affecting you. I'm guessing it was the change to rewrite `const` to `let` in minified builds. That probably then caused esbuild to try to splice the `let` with a `let` from the previous file. At least that would explain why it would happen in that release. These were the only two problems I was able to find on my own in any case.

**Comment by soadzoor** [comment] 2021-01-06 11:00
@evanw All my sourcemap-related problems seem to be solved with 0.8.30, thank you very much!

Also, the generated sourcemap file is much smaller than before (with 0.8.20). It used to be ~50 MB, now it's only 10MB. But I guess that's a result from 0.8.25. Quoted from the changelog: `...This didn't affect source map correctness but it made source maps unnecessarily large...`

So from my end, everything seems to be fine, thank you again for your fast fixes and your awesome bundler!

**Comment by tskarman** [comment] 2021-01-06 11:23
Yes, everything is coming out correct for me in 0.8.30 - thank you!

The `source-map-visualization` is quite enjoyable

**Comment by evanw** [comment] 2021-01-06 13:02
It’s great to hear that everything is fixed. Sorry for the breakage. Thanks so much for the detailed issue report.

**Closed by evanw** 2021-01-06 13:02 UTC

**Comment by Floffah** [comment] 2021-10-10 15:05
I seem to be getting this issue again in 0.13.4
