### ISSUE TITLE
error with `export type * from`

### ISSUE THREAD

**Issue by stefanprobst** [evanw/esbuild#2329] opened 2022-06-17 20:13 UTC
```bash
echo "export type * from './types'" | npx esbuild --loader=ts
```

results in:

```
✘ [ERROR] Expected identifier but found "*"

    <stdin>:1:12:
      1 │ export type * from './types'
        ╵             ^

1 error
```

**Comment by evanw** [comment] 2022-06-17 21:45
[That's not valid TypeScript.](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcBUcBmUIFs4DkAdAPRIoDOBQA) The TypeScript compiler says this:

```
example.ts:1:1 - error TS1383: Only named exports may use 'export type'.

1 export type * from './types'
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Please check that your code is valid before assuming the problem is with esbuild. Closing this issue as invalid.

**Closed by evanw** 2022-06-17 21:45 UTC

**Comment by stefanprobst** [comment] 2022-06-18 06:35
oh sorry! this was in generated code so i assumed it was valid. sorry for that, should have checked. the upstream issue for this seems to be https://github.com/microsoft/TypeScript/issues/37238 btw.
