### ISSUE TITLE
Package Linking failing after Yarn 3.5.0 installation as deps for `@netlify/plugin-nextjs`

### ISSUE THREAD

**Issue by mnshmnu** [evanw/esbuild#3074] opened 2023-04-20 17:24 UTC
Failed to install `@netlify/plugin-nextjs` package as the build for this package(`@netlify/esbuild@npm:0.14.39`) is failing.

Yarn version: 3.5.0 Berry

Attaching Yarn installation log and the yarn build log

1)
```
$dev❯yarn add @netlify/esbuild@npm:0.14.39
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 250ms
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0007: │ @netlify/esbuild@npm:0.14.39 must be built because it never has been before or the last one failed
➤ YN0009: │ @netlify/esbuild@npm:0.14.39 couldn't be built successfully (exit code 1, logs can be found here: C:\Users\abcd\AppData\Local\Temp\xfs-7b7e0dd7\build.log)
➤ YN0000: └ Completed in 1s 733ms
➤ YN0000: Failed with errors in 2s 150
```

2)

```
# This file contains the result of Yarn building a package (@netlify/esbuild@npm:0.14.39)
# Script name: postinstall

node:internal/errors:867
  const err = new Error(message);
              ^

Error: Command failed: node D:\Files\repo\.yarn\unplugged\@netlify-esbuild-npm-0.14.39-a2f420e29f\node_modules\@netlify\esbuild\bin\esbuild --version
node:fs:2894
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, copyfile 'D:\Files\repo\.yarn\unplugged\@netlify-esbuild-windows-64-npm-0.14.39-e725039b33\node_modules\@netlify\esbuild-windows-64\esbuild.exe' -> 'D:\Files\repo\.yarn\unplugged\esbuild-npm-0.17.17-4c183750d1\node_modules\esbuild\lib\pnpapi-@netlify\esbuild-windows-64-esbuild.exe'
    at Object.copyFileSync (node:fs:2894:3)
    at NodeFS.copyFileSync (D:\Files\repo\.pnp.cjs:8753:24)
    at makeCallSync.subPath (D:\Files\repo\.pnp.cjs:10995:28)
    at ZipOpenFS.makeCallSync (D:\Files\repo\.pnp.cjs:11261:14)
    at makeCallSync.subPath (D:\Files\repo\.pnp.cjs:10994:19)
    at ZipOpenFS.makeCallSync (D:\Files\repo\.pnp.cjs:11261:14)
    at ZipOpenFS.copyFileSync (D:\Files\repo\.pnp.cjs:10993:17)
    at VirtualFS.copyFileSync (D:\Files\repo\.pnp.cjs:10327:24)
    at PosixFS.copyFileSync (D:\Files\repo\.pnp.cjs:10327:24)
    at NodePathFS.copyFileSync (D:\Files\repo\.pnp.cjs:10327:24) {
  errno: -4058,
  syscall: 'copyfile',
  code: 'ENOENT',
  path: 'D:\\Files\\repo\\.yarn\\unplugged\\@netlify-esbuild-windows-64-npm-0.14.39-e725039b33\\node_modules\\@netlify\\esbuild-windows-64\\esbuild.exe',
  dest: 'D:\\Files\\repo\\.yarn\\unplugged\\esbuild-npm-0.17.17-4c183750d1\\node_modules\\esbuild\\lib\\pnpapi-@netlify\\esbuild-windows-64-esbuild.exe'
}

Node.js v18.15.0

    at checkExecSyncError (node:child_process:885:11)
    at Object.execFileSync (node:child_process:921:15)
    at validateBinaryVersion (D:\Files\repo\.yarn\unplugged\@netlify-esbuild-npm-0.14.39-a2f420e29f\node_modules\@netlify\esbuild\install.js:101:32)
    at D:\Files\repo\.yarn\unplugged\@netlify-esbuild-npm-0.14.39-a2f420e29f\node_modules\@netlify\esbuild\install.js:249:5 {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(1827) [Uint8Array] [
      110, 111, 100, 101,  58, 102, 115,  58,  50,  56,  57,  52,
       13,  10,  32,  32, 104,  97, 110, 100, 108, 101,  69, 114,
      114, 111, 114,  70, 114, 111, 109,  66, 105, 110, 100, 105,
      110, 103,  40,  99, 116, 120,  41,  59,  13,  10,  32,  32,
       94,  13,  10,  13,  10,  69, 114, 114, 111, 114,  58,  32,
       69,  78,  79,  69,  78,  84,  58,  32, 110, 111,  32, 115,
      117,  99, 104,  32, 102, 105, 108, 101,  32, 111, 114,  32,
      100, 105, 114, 101,  99, 116, 111, 114, 121,  44,  32,  99,
      111, 112, 121, 102,
      ... 1727 more items
    ]
  ],
  pid: 29544,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(1827) [Uint8Array] [
    110, 111, 100, 101,  58, 102, 115,  58,  50,  56,  57,  52,
     13,  10,  32,  32, 104,  97, 110, 100, 108, 101,  69, 114,
    114, 111, 114,  70, 114, 111, 109,  66, 105, 110, 100, 105,
    110, 103,  40,  99, 116, 120,  41,  59,  13,  10,  32,  32,
     94,  13,  10,  13,  10,  69, 114, 114, 111, 114,  58,  32,
     69,  78,  79,  69,  78,  84,  58,  32, 110, 111,  32, 115,
    117,  99, 104,  32, 102, 105, 108, 101,  32, 111, 114,  32,
    100, 105, 114, 101,  99, 116, 111, 114, 121,  44,  32,  99,
    111, 112, 121, 102,
    ... 1727 more items
  ]
}

Node.js v18.15.0
```

I'm installing `@netlify/plugin-nextjs` version `4.35.0` also tried with `4.34.0`

**Comment by mnshmnu** [comment] 2023-04-20 17:25
Also tried installing `@netlify/esbuild` only. Faced the same issue

**Comment by evanw** [comment] 2023-04-21 16:37
Please provide a self-contained way to reproduce the issue including the necessary steps and any relevant version information (e.g. node, OS, shell).

**Comment by mnshmnu** [comment] 2023-04-23 13:35
> Please provide a self-contained way to reproduce the issue including the necessary steps and any relevant version information (e.g. node, OS, shell).

Attaching a repo with the issue.

[esbuild-test](https://bitbucket.org/Maneesh-Manoj/esbuild-test/src/main/)

This repo contains the bare minimum setup to reproduce the issue

use `yarn install` to install the dependencies and see the result

**Relevant version information**
node-version: v18.15.0
OS: Windows 11, also similar on Linux.
Shell info: 
PSVersion                      5.1.22621.963
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.963
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Happy  to provide any additional information

**Comment by evanw** [comment] 2023-04-23 15:04
I get this when I try that (on Linux):

<pre>
# This file contains the result of Yarn building a package (@netlify/esbuild@npm:0.14.39)
# Script name: postinstall

node:internal/errors:867
  const err = new Error(message);
              ^

Error: Command failed: node /workspaces/codespaces-blank/main/.yarn/unplugged/@netlify-esbuild-npm-0.14.39-a2f420e29f/node_modules/@netlify/esbuild/bin/esbuild --version
/workspaces/codespaces-blank/main/.pnp.cjs:12293
      Error.captureStackTrace(firstError);
            ^

<b>Error: @netlify/esbuild tried to access esbuild, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.</b>

Required package: esbuild
Required by: @netlify/esbuild@npm:0.14.39 (via /workspaces/codespaces-blank/main/.yarn/unplugged/@netlify-esbuild-npm-0.14.39-a2f420e29f/node_modules/@netlify/esbuild/bin/)
</pre>

In any case, the problem is coming from the `@netlify/esbuild` package. It looks like someone has made a package called `@netlify/esbuild` that is a (potentially broken) copy of esbuild's package. This repo has nothing to do with that package, and I cannot provide support for it. You need to track down whoever published that package and ask them to debug your problem instead.

Closing this issue as invalid.

**Closed by evanw** 2023-04-23 15:04 UTC
Labels: unactionable
