### ISSUE TITLE
Debugging breakpoints issue

### ISSUE THREAD

**Issue by arkadiy93** [evanw/esbuild#1256] opened 2021-05-07 05:54 UTC
Sometimes I notice during debugging when having multiple breakpoints it "jumps" over some of them. Could that be that source maps are not ideal?

**Comment by evanw** [comment] 2021-05-07 06:05
It could be. You'll have to provide code and specific instructions to reproduce the issue for it to be something that can be solved here. An alternative if you are unable to provide code or reproduction instructions is for you to inspect the source map using https://evanw.github.io/source-map-visualization/ which could potentially tell you more information.

**Comment by arkadiy93** [comment] 2021-05-07 21:25
Unfortunately the described behaviour is not consistent and can not be reproduced easily.
Thanks for the link, will inspect the source maps when I encounter the bug again.

**Comment by evanw** [comment] 2021-05-08 00:39
Ok. I'm going to close this for now since it's currently unactionable. We can reopen it later if there is more information in the future.

**Closed by evanw** 2021-05-08 00:39 UTC
Labels: unactionable
