### ISSUE TITLE
Bug Report: some packages like `file-saver` build err.

### ISSUE THREAD

**Issue by iam-frankqiu** [evanw/esbuild#652] opened 2021-01-07 08:29 UTC
### To reproduce:

https://github.com/iam-frankqiu/snowpack-react-ts-app/tree/esbuild_file_saver_err

`yarn && yarn esbuild`

The original FileSaver file is: https://github.com/eligrey/FileSaver.js

### Current Behavior:

When I involved `file-saver` to my repository. It turns to the bug. 
Compiled before:
```
import {saveAs} from 'file-saver'
```

Compiled after:
```
import fileSaver from 'file-saver'
console.log(fileSaver.saveAs())
```

### Expected Behavior:
I hope any code compiled can import like before.

**Comment by evanw** [comment] 2021-01-08 09:53
This is expected behavior from what I can tell. You are using esbuild to transform a file in CommonJS format to the ESM format. When that happens, the value of `module.exports` is supposed to be exported as the `default` export.

It behaves this way because this is how node works. You can check this yourself:

```
$ node --input-type=module -e 'import * as all from "./FileSaver.js"; console.log(all)'
[Module] {
  default: <ref *1> [Function: saveAs] { saveAs: [Circular *1] }
}
```

From the above you can see that, just like esbuild, node also exposes the value of `module.exports` as a single `default` export.

**Comment by iam-frankqiu** [comment] 2021-01-09 09:24
> $ node --input-type=module -e 'import * as all from "./FileSaver.js"; console.log(all)'

Thank you. I have got it. But this is a big pain point for me(I believe it's the same for others). Does it exist any ways to solve the problem? Can we add another value to the `format` option or add a special plugin to solve the problem? To solve the problem is really matters to me. I really hope you can provide some ways to solve it. Thank you.

**Comment by evanw** [comment] 2021-01-09 10:29
Unfortunately this is how node has decided that this feature should work, and esbuild follows node's conventions.

Have you considered re-exporting the value yourself? You could create a file that looks like this and bundle that with esbuild instead:

```js
export {default as saveFile} from './FileSaver.js'
```

**Comment by evanw** [comment] 2021-01-14 06:44
Closing this issue since it's working as intended, as described above. Workarounds include rewriting the imports or rewriting the exports.

**Closed by evanw** 2021-01-14 06:44 UTC

**Comment by iam-frankqiu** [comment] 2021-01-21 07:42
> ```js
> ```js
> export {default as saveFile} from './FileSaver.js'
> ```
> 
> 
>       
> ```

Actually. The question is that we use esbuild to compile mounts of packages to ESM format. It's pretty difficult to re-export every package. This is the pain point.  I am also a node.js contributor. Should I create a PR to node to solve this problem?
