### ISSUE TITLE
Escaped double quote in JSX attribute

### ISSUE THREAD

**Issue by aleclarson** [evanw/esbuild#1115] opened 2021-04-06 05:29 UTC
```js
esbuild.transformSync(`<Test json="{ \\"a\\": 1 }" />`, {loader: 'jsx'})
// => error: Expected ">" but found "\\"
```

**Comment by ihupoo** [comment] 2021-04-06 06:45
Also
```
esbuild.transformSync(`<Test json="\s" />`, {loader: 'jsx'})
```
the actual transform result is missing `\`
```
{
  warnings: [],
  code: '/* @__PURE__ */ React.createElement(Test, {\n  json: "s"\n});\n',
  map: ''
}
```

**Comment by evanw** [comment] 2021-04-06 10:44
> ```js
> esbuild.transformSync(`<Test json="{ \\"a\\": 1 }" />`, {loader: 'jsx'})
> // => error: Expected ">" but found "\\"
> ```

JSX is not JS, and strings in JSX do not work like strings in JS. There is nothing in [the JSX specification](https://facebook.github.io/jsx/) that mentions backslash escapes. TypeScript, Babel, and esbuild will all not compile this JSX code because it contains a syntax error. You can escape a quote in JSX using `&quot;` instead of `\"`. See https://github.com/evanw/esbuild/issues/959#issuecomment-797714085 and the rest of that thread for more information.

> ```
> esbuild.transformSync(`<Test json="\s" />`, {loader: 'jsx'})
> ```

Your problem is unrelated to the original post. The `\s` becomes `s` before it even gets to the call to `esbuild.transformSync()`, so this has nothing to do with esbuild. For example, ``console.log(`<Test json="\s" />`)`` will also print `<Test json="s" />`.

Closing because this is working as intended.

**Closed by evanw** 2021-04-06 10:44 UTC
