### ISSUE TITLE
Concatenating multiple entries into one

### ISSUE THREAD

**Issue by fregante** [evanw/esbuild#3362] opened 2023-09-02 06:00 UTC
If I run:

```sh
esbuild --bundle a.js b.js
```

I get:

```
✘ [ERROR] Must use "outdir" when there are multiple input files
```

Any way to have it concatenate/bundle files into a single output instead? This is what browserify used to do for example:

```sh
browserify a.js b.js
```
```js
(function(){function r(e,n,t){function o(i,f){if(!n[i]){if(!e[i]){var c="function"==typeof require&&require;if(!f&&c)return c(i,!0);if(u)return u(i,!0);var a=new Error("Cannot find module '"+i+"'");throw a.code="MODULE_NOT_FOUND",a}var p=n[i]={exports:{}};e[i][0].call(p.exports,function(r){var n=e[i][1][r];return o(n||r)},p,p.exports,r,e,n,t)}return n[i].exports}for(var u="function"==typeof require&&require,i=0;i<t.length;i++)o(t[i]);return o}return r})()({1:[function(require,module,exports){
console.log('a.js loaded')

},{}],2:[function(require,module,exports){
console.log('b.js loaded')

},{}]},{},[1,2]);
```

**Comment by hyrious** [comment] 2023-09-02 06:08
The concated file seems just a result if this module:

```js
require('./a.js')
require('./b.js')
```

So I guess you can just generate contents above and use the [`stdin`](https://esbuild.github.io/api/#stdin) option to do the bundle.

**Comment by fregante** [comment] 2023-09-02 06:18
True, but I'm already using globing from the CLI in order to get a file list, so that becomes impractical

**Comment by evanw** [comment] 2023-09-03 13:08
I'm closing this issue as this is not a bug with esbuild, and is not a feature that I plan to implement. When you tell esbuild to bundle multiple files, it creates a bundle for each one. That's how the API works and is already documented here: https://esbuild.github.io/api/#entry-points. This is because esbuild is a bundler, not a file concatenator. If you want the input to esbuild to be a file concatenation then you can do that yourself first (e.g. with `cat a.js b.js | esbuild --bundle`).

**Closed by evanw** 2023-09-03 13:08 UTC

**Comment by fregante** [comment] 2023-09-03 14:02
Loading javascript files isn't equivalent to just concatenating them, pardon the wrong term. This is an immediate error:

```
// a.js
const foo = 1;
console.log(foo)
```

```
// b.js
const foo = 1;
console.log(foo)
```

> If you want the input to esbuild to be a file concatenation

I don't want esbuild to be a file concatenation, I want it to bundle the files I ask it to bundle, just not separately.

**Comment by evanw** [comment] 2023-09-03 14:07
Ah, I see. In that case you can construct an entry point file with one `import` statement for each file and then pass that to esbuild for bundling. For example `echo "import './a.js'; import './b.js'" | esbuild --bundle`.

**Comment by kapouer** [comment] 2023-10-06 12:34
Same issue here, concatenating using import/require and bundle has side effects with third-party bundled modules (typically, the require/import statements from older bundlers are not ignored, when they should be).

Concatenating manually without bundle works, at the price of losing the source map.

**Comment by kapouer** [comment] 2023-10-23 20:05
Here is an example of the client code workarounds...
https://github.com/kapouer/postinstall-esbuild/blob/b46833e7862bd1b1d55d77defc2b355f06488d31/index.js#L52-L104
