### ISSUE TITLE
Variable names and 'let' keyword separated by newline are incorrectly minified

### ISSUE THREAD

**Issue by haliphax** [evanw/esbuild#411] opened 2020-09-24 13:55 UTC
I've run into a bug minifying my web app's JS resources. I have something like the following in my code:

```javascript
(() => {
    let
        someVariable = some.really.involved.set
            && of.expressions,
        otherVariable = something.else;
    // more code here...
})();
```

In this case, the minified script is output with a comma between `let` and `someVariable`, causing the browser to throw a `SyntaxError` (_Uncaught SyntaxError: let is a reserved identifier_).

I am invoking ESBuild like so, using stdin and stdout rather than directly manipulating files:

`esbuild --bundle --minify --format=esm`

I realize that my choice to put a newline between `let` and the variable name is unnecessary, but I do so in the interest of readability so that the second line of the first assignment (`&& of.expressions,` in the example) is indented further than the beginning of the next assignment (`othervariable = something.else;` in the example).

**Comment by haliphax** [comment] 2020-09-24 14:02
A reproducible case:

__test.js__
```javascript
(() => {
    let
        var1 = true
            && true,
        var2 = 1;
})();
````

`esbuild --bundle test.js --minify --format=esm --outfile=test.min.js`

__test.min.js__
```javascript
(()=>{let,var1=!0,var2=1})();
```

**Comment by evanw** [comment] 2020-09-24 17:03
Thank you for filing this. I'm going to close this because it's a duplicate of #409. It has already been fixed but not yet released. I'll do a release now.

**Closed by evanw** 2020-09-24 17:03 UTC

**Comment by haliphax** [comment] 2020-09-24 17:31
Ah, sorry! I should have looked through closed issues, as well. I only searched through open ones before posting. :+1:
