### ISSUE TITLE
How can I build all imported files in addtion to the entrypoints?

### ISSUE THREAD

**Issue by johann1301s** [evanw/esbuild#3405] opened 2023-09-23 17:37 UTC
The following is my code for building using esbuild.

```js
import * as esbuild from 'esbuild'

esbuild.build({
    entryPoints: ['./src.ts'],
    outdir: 'out'
})
```

The following is `src.ts`.

```js
import { foo } from "./foo";

console.log(foo)
```

And then `foo.ts`.
```js
export const foo = 'bar'
```

How can I configure esbuild to build `foo.ts` in addtion to `src.ts`?

**Comment by evanw** [comment] 2023-09-23 17:41
You don't, sorry. There is currently no easy way to do this with esbuild (although you could probably write some code yourself that uses esbuild to do it with an onResolve plugin that triggers more build calls). Closing as a duplicate of #708.

**Closed by evanw** 2023-09-23 17:41 UTC
