### ISSUE TITLE
File extensions do not change to JS when using "file" loader

### ISSUE THREAD

**Issue by b13nxx** [evanw/esbuild#3371] opened 2023-09-10 00:15 UTC
I was looking at how to handle external files during build in Esbuild and I saw the `file` and `copy` loaders in [this link](https://esbuild.github.io/content-types/#external-file). Which are very good.

For example when I do an import like this (inside index.ts):
```typescript
import xml from '#assets/localizations/english/english.xml'
```

If I understand correctly when using the `file` loader, **it creates a js file** in the destination directory **where the relevant file is located in the source directory** and in that js file it points to **where the actual file is located**:

![image](https://github.com/evanw/esbuild/assets/4191018/98c7b437-9545-44fd-8282-8d04f5de69ac)
![image](https://github.com/evanw/esbuild/assets/4191018/82be1a6c-6137-46cd-b32c-50ead5bd038f)

After building, index.js is created. But it doesn't change **the extension** for imported file. Because while the real extension of the file is XML, **the extension of the file created by esbuild is JS**. So it should have imported it with that. But the result was:
```javascript
var import_english = __toESM(require("#assets/localizations/english/english.xml"));
```

Now isn't there a problem? Because there is no such file in that directory? (There is english.js not english.xml)

### Reproducible Example
[Playground](https://esbuild.github.io/try/#YgAwLjE5LjIALS1sb2FkZXI6LnhtbD1maWxlIC0tb3V0ZGlyPW91dABlAGVudHJ5LmpzAGltcG9ydCB1cmwgZnJvbSAnLi9leGFtcGxlLnhtbCcKCmNvbnNvbGUubG9nKHVybCkAZQBleGFtcGxlLnhtbAB0ZXN0IGNvbnRlbnQ)
It should have imported it through `./out/example.js`, which is clearly visible.

**Comment by evanw** [comment] 2023-09-10 01:41
The `file` loader is intended to be used with bundling: [link](https://esbuild.github.io/try/#YgAwLjE5LjIALS1sb2FkZXI6LnhtbD1maWxlIC0tb3V0ZGlyPW91dCAtLWJ1bmRsZQBlAGVudHJ5LmpzAGltcG9ydCB1cmwgZnJvbSAnLi9leGFtcGxlLnhtbCcKCmNvbnNvbGUubG9nKHVybCkAAGV4YW1wbGUueG1sAHRlc3QgY29udGVudA)

**Comment by b13nxx** [comment] 2023-09-10 13:02
Yeah, I noticed that. So it won't work without using the bundle option, right?

**Comment by evanw** [comment] 2023-09-10 18:43
Yes. Import paths are not rewritten by esbuild when bundling is disabled (which is by design) so what you are trying to do won't work.

**Comment by evanw** [comment] 2023-09-12 19:50
I'm closing this issue as esbuild is working as intended here.

**Closed by evanw** 2023-09-12 19:50 UTC
