### ISSUE TITLE
Since 0.12.17, --watch fail silently when running under lerna

### ISSUE THREAD

**Issue by compulim** [evanw/esbuild#1885] opened 2021-12-24 08:00 UTC
| Versions | |
| - | - |
| First repro | `0.12.17` |
| Also repro | `latest`, `0.13`, `0.12` |
| Not repro | `0.12.16`, `0.12.0`, `0.11` |
| OS | Ubuntu and Windows |
| Node/npm | `14.17.6`/`6.14.15` and `16.13.1`/`8.1.2` |

When using `lerna run <scriptname> --stream` to run `esbuild --watch` with `>= 0.12.17`, it quit silently. I am using `lerna@4.0.0` (latest), it was released about 10 months ago, which is earlier than `0.12.17`.

## 0.12.16

![image](https://user-images.githubusercontent.com/1622400/147332133-70cf42ed-fc0a-4015-83f7-cc957f771194.png)

In the screenshot above, the root package of the monorepo will run `esbuild@0.12.16 --watch`. ESBuild will say "build finished, watching for changes".

## 0.12.17

![image](https://user-images.githubusercontent.com/1622400/147328940-99ffe7e6-de9d-43be-80a2-b5c020a69d25.png)

In the screenshot above, I updated to `esbuild@0.12.17`. When running it through lerna, ESBuild fail silently and quit immediately. There are no output files produced.

However, when running without `--watch` (via `npm run build`), it works without issues, regardless of whether lerna's `--parallel` and `--stream` flag is set or not.

![image](https://user-images.githubusercontent.com/1622400/147332804-37b90076-a2e4-499d-81ee-c8469a67e13b.png)

## Repro

I have prepared a bare minimal repo, https://github.com/compulim/experiment-lerna-esbuild. Please use GitHub Codespaces to try it out on the cloud.

After clone

- Run `npm install` at root to prepare the repository
- `npm start`
   - It should start `esbuild --version && esbuild src/index.js --bundle --outfile=lib/index.js --watch`

ESBuild is located under `packages/app`. To change version of `esbuild`:

- `cd packages/app`
- `npm install esbuild@0.12.6`

By default, GitHub Codespaces use Node 14. You can use `nvm` to change its version.

## Workaround

When running `esbuild`, use `concurrently` to wrap around it. `concurrently` will not close `stdin` on start.

In the bare minimal repo, modify `packages/app/package.json`:

```diff
-    "start": "esbuild --version && esbuild src/index.js --bundle --outfile=lib/index.js --watch"
+    "start": "npx concurrently \"esbuild --version && esbuild src/index.js --bundle --outfile=lib/index.js --watch\""
```

![image](https://user-images.githubusercontent.com/1622400/147336111-f21de115-1247-40f4-b62d-b2be7ad620f8.png)

**Comment by evanw** [comment] 2021-12-24 14:55
Watch mode in esbuild is terminated when stdin is closed. Closing stdin indicates to esbuild that you want to end watch mode.

One way to fix this is to change Lerna itself. The `ignore` here could be changed to `inherit` instead: https://github.com/lerna/lerna/blob/a47fc294393a3e9507a8207a5a2f07648a524722/core/child-process/index.js#L65.

Another way to fix this is to avoid closing stdin:

```diff
diff --git a/packages/app/package.json b/packages/app/package.json
index 5424c2b..2ac3235 100644
--- a/packages/app/package.json
+++ b/packages/app/package.json
@@ -6,7 +6,7 @@
   "main": "lib/index.js",
   "scripts": {
     "build": "esbuild --version && esbuild src/index.js --bundle --outfile=lib/index.js",
-    "start": "esbuild --version && esbuild src/index.js --bundle --outfile=lib/index.js --watch"
+    "start": "esbuild --version && sleep 9999999999 | esbuild src/index.js --bundle --outfile=lib/index.js --watch"
   },
   "author": "",
   "license": "MIT",
```

**Comment by kzc** [comment] 2021-12-24 20:54
Duplicate of #1511

**Comment by luwes** [comment] 2022-01-11 15:27
In case you need a cross-platform solution check out ours above, it uses JS `setInterval` to keep the stdin open until manually stopped.

Changing the stdio in Lerna has some other difficulties seems, comments here:
https://github.com/lerna/lerna/pull/608#pullrequestreview-167946808

**Closed** 2022-09-01 23:46 UTC
