### ISSUE TITLE
[Feature] Output folder without subdirs

### ISSUE THREAD

**Issue by arkadiy93** [evanw/esbuild#748] opened 2021-02-03 20:38 UTC
https://github.com/evanw/esbuild/commit/7a777571c81d8a941b673bc0742f130e0d33fef8

Maybe we can add support to  output folder without subdirs as well? Can be useful for some people imho.

Should not be difficult to implement and support both.

**Comment by evanw** [comment] 2021-02-03 22:04
Closing as a duplicate of #553.

**Closed by evanw** 2021-02-03 22:04 UTC
