### ISSUE TITLE
keep Comments

### ISSUE THREAD

**Issue by fjbalsamo** [evanw/esbuild#3336] opened 2023-08-23 17:38 UTC
Hi, I need keep a Comment. Just one, it this:
`#!/usr/bin/env node`
And, I dont know if it's possible.
Someone help me please

**Comment by evanw** [comment] 2023-08-24 15:22
It looks like this already works: https://esbuild.github.io/try/#dAAwLjE5LjIAACMhL3Vzci9iaW4vZW52IG5vZGUKdGVzdGluZw. I'm closing this issue because it's working as intended (and you didn't follow the instructions to provide information that demonstrates otherwise).

**Closed by evanw** 2023-08-24 15:22 UTC
