### ISSUE TITLE
[bug] Can't work with sql-formatter-plus-plus lib

### ISSUE THREAD

**Issue by baurine** [evanw/esbuild#2181] opened 2022-04-15 07:54 UTC
I use `sql-formatter-plus-plus` npm packages to format my SQL sentence in the frontend. It works fine with cra (create-react-app, wraps webpack). but when I use it with esbuild / vite, it crashes.

Example repo: https://stackblitz.com/edit/vitejs-vite-roxokn?file=src%2Fformat-sql.ts&terminal=dev

Example code:

```js
import { format } from 'sql-formatter-plus-plus'

format('select sleep(1);')
```

It reports the following error message when running:

```
Uncaught Error: Failed to recognize value `undefined` for property `Alphabetic`.
    at getUnicodePropertyValueSet (rewrite-pattern.js:50:9)
    at handleLoneUnicodePropertyNameOrValue (rewrite-pattern.js:68:9)
    at getUnicodePropertyEscapeSet (rewrite-pattern.js:76:9)
    at processCharacterClass (rewrite-pattern.js:160:13)
    at processTerm (rewrite-pattern.js:205:11)
    at rewrite-pattern.js:259:12
    at Array.map (<anonymous>)
    at processTerm (rewrite-pattern.js:258:26)
    at rewrite-pattern.js:259:12
    at Array.map (<anonymous>)
```

**Comment by hyrious** [comment] 2022-04-15 09:17
You can find that error message from the stack trace:

https://github.com/mathiasbynens/regexpu-core/blob/2c9983be22a6117c4fe6af581f3307eacbaf1599/rewrite-pattern.js#L45:

```js
try {
    return require(`regenerate-unicode-properties/${ path }.js`);
} catch (exception) {
    throw new Error(
        `Failed to recognize value \`${ value }\` for property ` +
        `\`${ property }\`.`
    );
}
```

Because esbuild doesn't error out dynamic requires in `try-catch` blocks (since the user has handled this case), this code is just bundled as is without warnings and you will see the error at runtime.

If you want that package work in esbuild and rollup, you have to write a plugin to manually replace the code above to static requires.

**Comment by baurine** [comment] 2022-04-16 00:06
@hyrious  thanks for your help, now I have an idea to make `sql-formatter-plus-plus` work with esbuild, and I tried it really works.

```diff
+ import { format } from 'sql-formatter-plus-plus/dist/sql-formatter'
- import { format } from 'sql-formatter-plus-plus"
```

**Comment by evanw** [comment] 2022-04-17 00:00
Thanks for investigating @hyrious.

I'm closing this issue because this is not a bug in esbuild. Instead it is a known limitation: esbuild does not emulate the file system for you, so things like `require()` with a path that can't be determined at compile time don't work in the browser. This is best fixed by the author of the problematic package. Instead of doing this, which only works with bundlers that support run-time path resolution:

```js
try {
  return require(`regenerate-unicode-properties/${ path }.js`);
} catch (exception) {
  throw new Error(...);
}
```

The package author can do something like this instead, which should work with all bundlers since it only uses compile-time path resolution:

```js
try {
  return {
    'Binary_Property/Dash': () => require(`regenerate-unicode-properties/Binary_Property/Dash.js`),
    'Binary_Property/Case_Ignorable': () => require(`regenerate-unicode-properties/Binary_Property/Case_Ignorable.js`),
    'Binary_Property/ASCII_Hex_Digit': () => require(`regenerate-unicode-properties/Binary_Property/ASCII_Hex_Digit.js`),
    'Binary_Property/Unified_Ideograph': () => require(`regenerate-unicode-properties/Binary_Property/Unified_Ideograph.js`),
    ...
  }[path]();
} catch (exception) {
  throw new Error(...);
}
```

**Closed by evanw** 2022-04-17 00:00 UTC
