### ISSUE TITLE
Incorrectly removes import type asserts when minifying, results in none functional code

### ISSUE THREAD

**Issue by mangelozzi** [evanw/esbuild#3126] opened 2023-05-20 15:25 UTC
Native CSS script modules have landed in Chrome, refer to:
- https://web.dev/css-module-scripts/
- https://github.com/WICG/webcomponents/issues/759

Unforunately esbuild when minifying Javascript will change:
```
import sheet1 from '/static/common/skin/foo.min.css' assert { type: 'css' };
```
to
```
import p from"/static/common/skin/foo.min.css";
```

By dropping the assert file type, it results with the following error when the browser gets the file: 
```
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/css". Strict MIME type checking is enforced for module scripts per HTML spec.
```

The fix I imagine is when miniying a file, only remove the type assert if it is of type JavaScript. JSON and upcomming HTML module imports are examples of other scenarios that would benefit from this change.

**Comment by hyrious** [comment] 2023-05-20 22:33
Import assertions is kept if your `target` is supported (like `--target=chrome91`) or there is `--supported:import-assertions=true`.

**Comment by evanw** [comment] 2023-05-20 23:18
I'm guessing this is because you have a `target` set to a browser that doesn't support import assertions (as stated in the previous comment). When you do this, esbuild has to remove the import assertions. Otherwise that browser would consider those import assertions a syntax error and would fail to even parse your code.

You can see this for yourself by trying your code both [without a target](https://esbuild.github.io/try/#dAAwLjE3LjE5AABpbXBvcnQgc2hlZXQxIGZyb20gJy9zdGF0aWMvY29tbW9uL3NraW4vZm9vLm1pbi5jc3MnIGFzc2VydCB7IHR5cGU6ICdjc3MnIH07) and [with a target](https://esbuild.github.io/try/#dAAwLjE3LjE5AC0tdGFyZ2V0PWNocm9tZTkwAGltcG9ydCBzaGVldDEgZnJvbSAnL3N0YXRpYy9jb21tb24vc2tpbi9mb28ubWluLmNzcycgYXNzZXJ0IHsgdHlwZTogJ2NzcycgfTs). So I'm closing this issue as "working as intended". If you still believe this to be a bug in esbuild, please provide a way to reproduce the issue.

**Closed by evanw** 2023-05-20 23:18 UTC

**Comment by mangelozzi** [comment] 2023-05-21 09:22
Apologies, I did spend quite a bit of time reading the documentation trying to figure out if it supports its. I mostly just read about not native css imports. Thanks for clearing this issue up. Hopefully this issue may help others with the same problem as CSS script imports become more popular.
