### ISSUE TITLE
Ability to get `esbuild` output in scripts without reading from FS

### ISSUE THREAD

**Issue by timocov** [evanw/esbuild#220] opened 2020-07-04 17:24 UTC
`esbuild` is awesome and ultra fast tool to bundle JS code, but currently it doesn't do some minifications other tools like terser do (see #218).

`esbuild` has JS API so we can write simple script to run `esbuild` and then provide output to `terser` (for instance), but it seems that there is no option to run `esbuild` and get output from it without reading outfile manually, so you have to run `esbuild` first, then read out file and pass it to `terser`.

It would be nice to return the output from `esbuild` as returned value (even without writing the result on the disk totally) so we don't need to read it again from FS.

**Comment by evanw** [comment] 2020-07-04 20:23
I agree that this would be useful. It would also bring the JavaScript API up to parity with the Go API, which can already do this. This is already an existing feature request though, so I'm going to close this as a duplicate of #139.

**Closed by evanw** 2020-07-04 20:23 UTC
