### ISSUE TITLE
Since v0.19.4 esbuild erroneously transforms RegExp based on target array

### ISSUE THREAD

**Issue by AlexJeffcott** [evanw/esbuild#3471] opened 2023-11-03 10:10 UTC
Since version 0.19.4 esbuild is incorrectly transforming some language features which I believe are actually compatible with the targets array.

https://esbuild.github.io/try/#dAAwLjE5LjQALS10YXJnZXQ9Y2hyb21lMTAwAGNvbnN0IG1hdGNoID0gc3RyLm1hdGNoKC9ccHtFbW9qaX0vdSk

**Incorrectly transforms in `0.19.4` and `0.19.5`**
target=chrome115
`const match = str.match(/\p{Emoji}/u)` => `const match = str.match(new RegExp("\\p{Emoji}", "u"));`

target=chrome63
`const match = str.match(/\p{Emoji}/u)` => `const match = str.match(new RegExp("\\p{Emoji}", "u"));`

target=safari12
`const match = str.match(/\p{Emoji}/u)` => `const match = str.match(new RegExp("\\p{Emoji}", "u"));`

target=safari11
`const match = str.match(/\p{Emoji}/u)` => `const match = str.match(new RegExp("\\p{Emoji}", "u"));`

target=es2018
`const match = str.match(/\p{Emoji}/u)` => `const match = str.match(/\p{Emoji}/u);`

**Correctly transforms in `0.19.3`**
target=chrome115
`const match = str.match(/\p{Emoji}/u)` => `const match = str.match(/\p{Emoji}/u);`

target=chrome63
`const match = str.match(/\p{Emoji}/u)` => `const match = str.match(new RegExp("\\p{Emoji}", "u"));`

target=safari12
`const match = str.match(/\p{Emoji}/u)` => `const match = str.match(/\p{Emoji}/u);`

target=safari11
`const match = str.match(/\p{Emoji}/u)` => `const match = str.match(new RegExp("\\p{Emoji}", "u"));`

target=es2018
`const match = str.match(/\p{Emoji}/u)` => `const match = str.match(/\p{Emoji}/u);`

**Comment by evanw** [comment] 2023-11-04 04:32
I believe this happened because Unicode 15.1 came out, the compatibility tests that esbuild uses were updated for Unicode 15.1, and all of a sudden all existing browser versions were considered to not support these features. You can see the resulting test failures listed in esbuild's compiled internal compatibility table [here](https://github.com/evanw/esbuild/blob/4e11b50fe3178ed0a78c077df78788d66304d379/internal/compat/js_table.go#L784-L797).

I'm not totally sure what to do with this. You could argue that esbuild shouldn't do this transformation because the same syntax is supported both with and without Unicode 15.1 support. But you could also argue that esbuild should do this transformation because the meaning of that syntax has changed.

For example, Unicode 15.1 adds the `ID_Compat_Math_Start` property, which I think might mean that `/\p{ID_Compat_Math_Start}/u.test('∇')` should return true? But right now existing browsers consider it a syntax error. So esbuild's transformation to use `new RegExp` means it's doing the correct thing: transforming valid JS syntax from the future to avoid syntax errors in older browsers. This transformation also lets you provide your own polyfill for `RegExp` that implements missing features.

In another example, Unicode 15.1 adds U+30FB KATAKANA MIDDLE DOT to `ID_Continue`, which did not previously contain that character. I think that means `/\p{ID_Continue}/u.test('・')` previously returned false but should now return true. If esbuild passed through that syntax unmodified without transforming to use `new RegExp`, then it would be impossible for you to provide your own polyfill for `RegExp` to make your regular expressions conform to Unicode 15.1.

So esbuild's transformation here is sort of necessary, and seems like the correct thing to do.

**Comment by AlexJeffcott** [comment] 2023-11-07 12:02
Apologies for the late reply. I wanted to speak to some colleagues to see what they thought about this interesting problem.

Firstly, I think that you are right that this behaviour is, in fact, correct.

Two things, though:

1. if one wanted to use the raw syntax, what would be the best way to do that?
2. if this is the correct behaviour, the warning does seem a little alarming.

**Comment by evanw** [comment] 2023-11-09 20:02
> 1. if one wanted to use the raw syntax, what would be the best way to do that?

You can use the [`supported`](https://esbuild.github.io/api/#supported) feature to override `target` on a feature-by-feature basis. For example:

https://esbuild.github.io/try/#dAAwLjE5LjUALS10YXJnZXQ9Y2hyb21lMzAKLS1zdXBwb3J0ZWQ6cmVnZXhwLXVuaWNvZGUtcHJvcGVydHktZXNjYXBlcz10cnVlCi0tc3VwcG9ydGVkOnJlZ2V4cC1zdGlja3ktYW5kLXVuaWNvZGUtZmxhZ3M9dHJ1ZQB4PS9ccHtFbW9qaX0vdQ

> 2. if this is the correct behaviour, the warning does seem a little alarming.

What warning are you talking about? AFAIK esbuild doesn't emit warnings when doing this.

**Comment by AlexJeffcott** [comment] 2023-11-13 10:29
1. 👍 

2. Ah, sorry I misspoke when I said ‘warnings’. They are debug messages:

```sh
● [DEBUG] Unicode property escapes in regular expressions are not available in the configured target environment ("chrome79", "firefox106", "safari13") [unsupported-regexp]

  This regular expression literal has been converted to a "new RegExp()" constructor to avoid generating code with a syntax error. However, you will need to include a polyfill for “RegExp" for your code to have the correct behavior at run-time.
```

**Comment by evanw** [comment] 2023-11-18 21:05
I see. Debug messages are intended to be used like this. The warning log level is for things that are very likely a real problem with your code. The debug log level is for things that could be a problem with your code. Debug messages are deliberately not shown by default because they can be false positives. The debug log level is intended to be temporarily enabled when your code isn't working to show you possible reasons why your code may not be working. As you can see here, this is a way for esbuild to tell you about what it's doing with your regular expressions in case you weren't aware of it or were wondering why it's happening, as well as for esbuild to tell you that you'll need to provide your own shim for the regular expression you have provided to work correctly in the environment you have specified. It's not expected for the debug log level to be enabled all the time without any debug messages being present.

I'm closing this issue because esbuild appears to be working as intended here.

**Closed by evanw** 2023-11-18 21:05 UTC
