### ISSUE TITLE
ERROR: Expected "*/" to terminate multi-line comment

### ISSUE THREAD

**Issue by noelpuig** [evanw/esbuild#3715] opened 2024-04-02 22:58 UTC
When trying to build my application, I get this error, and I can't figure out what it is... I went and removed all comments from the main.js file, and it still complains. Furthermore, I also attempted to revert to an older version, but I still get this.

I'm not sure if this is my fault or not, but I checked and don't have any mulit-line comments in my project. Any help is appreciated, thanks.

```[vite:css-post] [esbuild css minify] Transform failed with 1 error:
<stdin>:931:1: ERROR: Expected "*/" to terminate multi-line comment

X [ERROR] Expected "*/" to terminate multi-line comment

    <stdin>:931:1:
      931 │ }
          ╵  ^

  The multi-line comment starts here:

    <stdin>:595:0:
      595 │ /*
          ╵ ~~


✓ built in 1.56s
error during build:
Error: [esbuild css minify] Transform failed with 1 error:
<stdin>:931:1: ERROR: Expected "*/" to terminate multi-line comment
    at failureErrorWithLog (C:\Users\noelp\Desktop\Folders\PolyNotes\node_modules\vite\node_modules\esbuild\lib\main.js:1649:15)
    at C:\Users\noelp\Desktop\Folders\PolyNotes\node_modules\vite\node_modules\esbuild\lib\main.js:847:29
    at responseCallbacks.<computed> (C:\Users\noelp\Desktop\Folders\PolyNotes\node_modules\vite\node_modules\esbuild\lib\main.js:703:9)   
    at handleIncomingPacket (C:\Users\noelp\Desktop\Folders\PolyNotes\node_modules\vite\node_modules\esbuild\lib\main.js:762:9)
    at Socket.readFromStdout (C:\Users\noelp\Desktop\Folders\PolyNotes\node_modules\vite\node_modules\esbuild\lib\main.js:679:7)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)```

**Comment by evanw** [comment] 2024-04-02 23:01
You didn't follow the issue reporting instructions because there's no way for me to reproduce this. Marking as `unactionable`. This will be closed soon if a reproduction is not provided.

**Closed** 2024-04-03 23:14 UTC
Labels: unactionable
