### ISSUE TITLE
Props mangling breaks enums

### ISSUE THREAD

**Issue by JakubekWeg** [evanw/esbuild#2101] opened 2022-03-13 15:31 UTC
Having this typescript code inside `app.ts`:
```ts
const enum Foo { One }

console['log'](Foo.One)
```
I expect it to print `0`.
By using the command:
`esbuild app.ts --tree-shaking=true --minify`
the output is 
```js
console.log(0);
```
which is fine, but when I enable props mangling:
`esbuild app.ts --tree-shaking=true --minify --mangle-props=.`
the output is 
```js
var Foo=(n=>(n[n.One=0]="One",n))(Foo||{});console.log(Foo.n);
```
which prints `undefined`

I suppose this is not generally intended behavior and can be considered a bug.

**Comment by evanw** [comment] 2022-03-13 15:39
Yes, enabling prop mangling breaks many things. This is why the docs recommend using a special pattern such as a trailing underscore to be able to control which names this applies to: https://esbuild.github.io/api/#mangle-props. That's the way this feature is intended to be used. Using `--mangle-props=.` is a bad idea.

It's worth noting that what you describe also happens with the output from the official TypeScript compiler. The output of `tsc -isolatedModules` is this:

```js
var Foo;
(function (Foo) {
    Foo[Foo["One"] = 0] = "One";
})(Foo || (Foo = {}));
console['log'](Foo.One);
```

Building that with `esbuild --tree-shaking=true --minify --mangle-props=.` gives this:

```js
var Foo;(function(n){n[n.One=0]="One"})(Foo||(Foo={}));console.log(Foo.n);
```

Which also prints `undefined` just like esbuild.

**Comment by JakubekWeg** [comment] 2022-03-15 07:47
That's very unfortunate it's not going to be fixed, because it's great feature.
However I managed to obfuscate and minify my entire project by using esbuild command twice and adding almost 200 props mangling exclusions for browser api. 
For anyone wondering how: execute commands this way:
```
esbuild app.ts --tree-shaking=true | esbuild --minify --mangle-props=.
```
then file app.ts
```ts
const enum Foo { One }
console['log']({bar: 1, 'bar2': 2}, Foo.One)
```
gets transpiled into
```
console.log({o:1,bar2:2},0);
```
Which is exactly what I needed.

**Comment by evanw** [comment] 2022-03-15 12:05
It looks like you can get this to work using `Foo['One']` instead of `Foo.One` without needing to build twice (assuming you aren't using `--mangle-quoted`) or you can use `--reserve-props=One`.

What esbuild is doing here is the same thing that you'd get with TypeScript+Terser, so I'm going to close this as expected behavior.

**Closed by evanw** 2022-03-15 12:05 UTC
