### ISSUE TITLE
Duplicated identifier with react as external 

### ISSUE THREAD

**Issue by zmitry** [evanw/esbuild#405] opened 2020-09-21 16:07 UTC
[meta.out.txt](https://github.com/evanw/esbuild/files/5257725/meta.out.txt)
here is what I've got
![image](https://user-images.githubusercontent.com/14317641/93791965-8ef75580-fc3d-11ea-8da8-d62197c8a212.png)
and here is my config 
```
const { build } = require("esbuild");

build({
  entryPoints: ["./src/index.js"],
  minify: false,
  define: {
    "process.env.NODE_ENV": '"development"'
  },
  outfile: "./out.js",
  bundle: true,
  target: "es2017",
  format: "esm",
  sourcemap: "external",
  external: ["assets/icons", "assets/images", "assets/styles", "react", "react-dom"],
}).then(console.log, console.error);

```

**Comment by zmitry** [comment] 2020-09-21 16:33
Let me know what info you need to debug this.

**Comment by zmitry** [comment] 2020-09-21 20:13
I suppose this is related to my local setup, I had inconsistent versions between react and react-is

**Comment by zmitry** [comment] 2020-09-21 21:47
Okay, I've solved my issue with resolutions, I'm not quite sure if it was my issue or not. But i'm pretty satisfied with results, I set up two pass build with esbuild and then webpack as post processor and here is my result with 40k LoC typescript codebase 
![image](https://user-images.githubusercontent.com/14317641/93825009-190ae280-fc6d-11ea-91a6-ce8589b77f2d.png)
The only one issue that left is to somehow replace emotion plugin with custom pragma implementation but it seems to be tricky

**Comment by zmitry** [comment] 2020-09-21 21:48
@evanw How would you recommend to migrate from styled-components/emotion stuff to esbuild.

**Comment by evanw** [comment] 2020-09-22 05:07
Did you close this because it’s not a bug with esbuild? If you bundle something with esbuild and the resulting code has a syntax error, then that is a bug in esbuild and we should fix it.

**Comment by zmitry** [comment] 2020-09-22 11:27
@evanw It might be a bug with my setup, I've solved this issue with setting up `resolutions` in my package.json.  I don't want to bother ui with that bug because I have two pass setup with webpack and a lot of weird things might happen and the might not be related to esbuild.

**Comment by zmitry** [comment] 2020-09-23 19:35
So, I did a bit of debugging, I can confirm, this is an esbuild issue. 
This issue is reproducible for me on this conditions. 
You have to use splitting: false, you have to mark react as external.  Maybe you might need to use import() but I'm not sure about that. With this conditions esbuild creates duplicated import statements which is not valid react syntax. 
@evanw

**Comment by evanw** [comment] 2020-09-24 06:23
I’m unable to reproduce that with a simple example of a react code base with those build options. Is there a way you can provide a code sample that reproduces the problem?

**Comment by zmitry** [comment] 2020-09-24 08:46
@evanw That might require some time to debug minimal example which I can shere. I will do that over weekends.

**Comment by evanw** [comment] 2020-10-20 19:41
Is this still happening? If not, I'd like to close this issue.

**Comment by zmitry** [comment] 2020-10-21 22:57
@evanw sorry, I did not use esbuild in production. So I didn't get a change to reproduce it.

**Closed** 2020-10-21 22:56 UTC
