### ISSUE TITLE
Problem bundling Typescript NodeJS project

### ISSUE THREAD

**Issue by ziggy6792** [evanw/esbuild#1736] opened 2021-11-02 04:46 UTC
### My Setup

Typescript NodeJS project bundled with `esbuild`
I have provided a sample (to showcase my issue) from a larger monorepo to be deployed to AWS lambda
I would like to bundle so that each of my lambdas have everything they need and so that I can keep the deployment packages small (AWS sets 250MB limit)

### Sample Here
https://github.com/ziggy6792/bundling-issue

### My Problem

When I build with `tsc` and then run `yarn build && yarn start:build` it works fine
When I build with `esbuild` and then run `yarn esbuild && yarn start:build` I get the following error

```
 throw new Error('Virtual path "' + name + '" conflicts with a real path in the schema');
        ^

Error: Virtual path "_id" conflicts with a real path in the schema
    at Schema.virtual (/Users/sive/Documents/workspace/bundling-issue/dist/index.js:36802:15)
    at Schema.<anonymous> (/Users/sive/Documents/workspace/bundling-issue/dist/index.js:36880:16)
    at Array.forEach (<anonymous>)
    at Schema.loadClass (/Users/sive/Documents/workspace/bundling-issue/dist/index.js:36866:51)
    at _buildSchema (/Users/sive/Documents/workspace/bundling-issue/dist/index.js:60882:11)
    at buildSchema (/Users/sive/Documents/workspace/bundling-issue/dist/index.js:61292:39)
    at processProp (/Users/sive/Documents/workspace/bundling-issue/dist/index.js:60625:37)
    at _buildSchema (/Users/sive/Documents/workspace/bundling-issue/dist/index.js:60870:41)
    at buildSchema (/Users/sive/Documents/workspace/bundling-issue/dist/index.js:61292:39)
    at getModelForClass (/Users/sive/Documents/workspace/bundling-issue/dist/index.js:61262:41)
 ```

### Troubleshooting

- I assume this issue is caused somehow by how `esbuild` is bundling/tree shaking and I do not believe this error has anything to do with how I am using mongo db (as the error only occurs when I bundle with `esbuild`) 
- I therefore assume there is some solution around adding some config to `esbuild.config.js` to tell `esbuild` how to correctly resolve some dependency or something
- I do not get this error when I do not bundle the node externals (see `esbuild.config.js` line 16) 
- I have a branch `working-lock-file` which actually works fine. But if I delete that lock file and `yarn install` again the error comes back. I need to be able to find a proper fix for this so I can bring the fix back into my original mono-repo. 

Any help would be greatly appreciated
Thanks a lot,

**Comment by evanw** [comment] 2021-11-09 06:05
I can reproduce this issue myself using https://gitpod.io/#https://github.com/ziggy6792/bundling-issue. However, this is a lot of unfamiliar code to go through and debugging this issue through all of that code could easily take an hour or more, so I'm not going to debug this issue for you. But I'm happy to fix the issue if the issue can be identified. Marking this as unactionable until more information is provided.

**Comment by evanw** [comment] 2022-01-22 02:25
Closing due to age and lack of information.

**Closed by evanw** 2022-01-22 02:25 UTC
Labels: unactionable
