### ISSUE TITLE
how to change default interpret result in onLoad callbacks ? 

### ISSUE THREAD

**Issue by yangdm2015** [evanw/esbuild#1720] opened 2021-10-27 10:32 UTC
Thanks for this wonderful tool!!

When build a plugin，I've noticed that the callback added by onLoad can only get the path part of any import statements, but not the whole statement. 

Also，what we can do is changing things before esbuild interpret it. if its possible to change interpret result ? 
like:
```javascript
//a.js
module.exports = { name: 1 };
// b.js
import * as a from './a.js'
console.log('a=',a)
```
if I write a plugin like this
```javascript
let passPlugin = {
  name: "pass",
  //enforce: 'post',  wish to have something like this that can config to run this plugin after esbuild build
  setup(build) {
    build.onLoad({ filter: /.*js/ }, async (args) => {
    //  Currently, plugins  always run  before esbuild interpret  code.
	// wish to run this plugin after esbuild interpreted 
	//get  the result from [args.contents]，get the whole  import part from [args.statement]
	// like this:
	// const {contents,statement } =args
	// if(statement.includes('import * as ') ){
	//     delete contents.defalut
	//}
	// return {contents}
      const source = await fs.promises.readFile(args.path, "utf8");
      return { contents: source };
    });
  },
};
```
I hope to get what esbuild original interpreted and change to something other .
Is any current apis allow me to do  this ?

**Comment by evanw** [comment] 2022-01-06 18:23
Sorry, you'll have to figure out how to do that yourself. You can do this with an esbuild `onLoad` plugin that substitutes alternate file content, and you can transform the content however you see fit with whatever tools you choose. I'm going to close this issue since it's not a bug with esbuild.

Keep in mind that what you're asking for is still not well defined because `import * as x from 'y'; console.log(x.default)` and `import x from 'y'; console.log(x)` are equivalent syntax. Note that esbuild's behavior changed recently with #1849 to be more Webpack-like. Specifically esbuild now uses node's way of handling `default` in `.mjs` files and files in packages tagged with `"type": "module"` in the `package.json` file. I'm mentioning that in case that fixes your problem.

**Comment by yangdm2015** [comment] 2022-01-06 18:23
您发给我的信件已经收到，非常感谢！--------------------------------------------Yang shan   祝您愉快！

**Closed by evanw** 2022-01-06 18:23 UTC
