### ISSUE TITLE
TypeScript class static blocks transpilation broken in latest release 

### ISSUE THREAD

**Issue by philkunz** [evanw/esbuild#2219] opened 2022-05-02 16:29 UTC
It looks like class static blocks are not transpiled properly from TypeScript input in the latest version.

This causes decorators in TypeScript to not work propery anymore.

**Comment by evanw** [comment] 2022-05-07 19:13
I'm marking this issue as `unactionable` because there isn't enough information here to reproduce the issue.

**Comment by evanw** [comment] 2022-05-16 12:52
Closing due to lack of a response. I can’t fix the problem if  you don’t show what the problem is. We can reopen this if the problem is demonstrated.

**Closed by evanw** 2022-05-16 12:52 UTC
Labels: unactionable
