### ISSUE TITLE
Falsy success compilation

### ISSUE THREAD

**Issue by ryabv** [evanw/esbuild#2491] opened 2022-08-23 12:27 UTC
There is a strange behavior, when the input string does not contain any punctuation symbols.

You can try it with this command:
```
echo 'justastring' | esbuild --loader=jsx
```

The output will be the same line with semicolon in the end:
```
justastring;
```

But if you will add a comma in the end of input, it will break the output:
```
echo 'justastring,' | esbuild --loader=jsx
```

```
✘ [ERROR] Unexpected end of file

    <stdin>:2:0:
      2 │ 
        ╵ ^

1 error
```

But in fact the first input is wrong as well, because it is not a valid js code. I think it may relate to the old interpretation of code, when we were able to write `a = 10`, and it would be okay in old version of JS. So maybe it is interpreted like `const justastring = undefined;`. But anyway, it looks like a bug for modern JS.

**Comment by evanw** [comment] 2022-08-23 12:36
The first code is valid JavaScript and the second is a syntax error. This is not strange. JavaScript is very well specified: https://tc39.es/ecma262/. You are welcome to read the specification yourself to learn about how JavaScript works. Perhaps you don’t yet know about automatic semicolon insertion? Anyway, this is not a bug so I’m closing this issue.

**Closed by evanw** 2022-08-23 12:36 UTC

**Comment by hyrious** [comment] 2022-08-23 13:05
Syntax Error &NotEqual; Runtime Error. Syntax error means it cannot form a valid AST so we call the code 'invalid', the code will stop work at the very beginning. While runtime error won't happen unless you execute it. Bundlers are not smart enough to find runtime errors only by statically analyze it -- which equals to [halting problem](https://en.wikipedia.org/wiki/Halting_problem).

An example of syntax error that 'not run':

```js
// we don't call f(), but it errors out
function f() { justastring, }
```

An example or runtime error that don't show until you execute it:

```js
function f() { justastring }
// no error unless you call f()
```
