### ISSUE TITLE
Can I build index.ts to single html file?

### ISSUE THREAD

**Issue by humbleCoder1990** [evanw/esbuild#1800] opened 2021-11-24 03:49 UTC
This is my "index.html" 

```
<html>
  <head>
    <link rel="stylesheet" href="index.css">
    <script type="module" src="index.js"></script>
  </head>
  <body>
    <div id="root"></div>
  </body>
</html>
```

Then I want to use this command.
"esbuild index.html --bundle --outfile=dist/index.html --minify"

Then, Can I have the index.html (build version) like this?

```
<html>
  <head>

    <style>

        /* My css codes inside index.css */

    </style>
    
  </head>
  <body>
    <div id="root"></div>
    <script>

        /* My Typescript codes... inside index.ts */

    </script>
  </body>
</html>

```

**Comment by evanw** [comment] 2021-11-24 04:28
No. HTML is not one of the supported languages. See https://esbuild.github.io/content-types/ for the set of supported languages. You will have to write some post-build code to assemble the HTML file yourself, which shouldn't be too hard. Closing as a duplicate of #31.

**Closed by evanw** 2021-11-24 04:28 UTC
